Repository ynput/OpenPype, pull requests merged in 2020-12, with the labels that each got.

#727 Hiero: effects workflow
  pype/plugins/global/publish/collect_resources_path.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/hiero/_publish/collect_assetbuilds.py
  pype/plugins/hiero/_publish/collect_colorspace.py
  pype/plugins/hiero/_publish/extract_effects.py
  pype/plugins/hiero/publish/collect_assetbuilds.py
  pype/plugins/hiero/publish/collect_clip_effects.py
  pype/plugins/hiero/publish/collect_frame_ranges.py
  pype/plugins/hiero/publish/collect_instances.py
  pype/plugins/hiero/publish/collect_workfile.py
  pype/plugins/hiero/publish/extract_clip_effects.py
  pype/plugins/hiero/publish/extract_effects.py
  pype/plugins/nuke/load/load_effect.py
  pype/plugins/nuke/load/load_effect_ip.py
Labels: 2x-dev, enhancement, host: Hiero

#762 Settings modifiable dictionary with top labels
  pype/settings/defaults/project_anatomy/imageio.json
  pype/settings/defaults/project_settings/standalonepublisher.json
  pype/settings/lib.py
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_standalonepublisher.json
  pype/tools/settings/settings/style/style.css
  pype/tools/settings/settings/widgets/anatomy_types.py
  pype/tools/settings/settings/widgets/base.py
  pype/tools/settings/settings/widgets/item_types.py
  pype/tools/settings/settings/widgets/lib.py
  pype/tools/settings/settings/widgets/widgets.py
Labels: enhancement

#767 Collapsible wrapper in settings
  pype/tools/settings/settings/README.md
  pype/tools/settings/settings/gui_schemas/system_schema/example_schema.json
  pype/tools/settings/settings/widgets/item_types.py
Labels: enhancement

#768 Harmony: template extraction and palettes thumbnails on mac
  pype/hosts/harmony/js/PypeHarmony.js
  pype/plugins/harmony/publish/extract_palette.py
  pype/plugins/harmony/publish/extract_template.py
Labels: bug, host: Harmony, hotfix

#766 TVPaint store context to workfile metadata (764)
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/validate_workfile_project_name.py
Labels: bug

#769 TVPaint store members key
  pype/plugins/tvpaint/load/load_reference_image.py
Labels: backend

#770 Settings required keys in modifiable dict
  pype/tools/settings/settings/README.md
  pype/tools/settings/settings/widgets/item_types.py
Labels: enhancement

#763 Extract review audio cut fix
  pype/plugins/global/publish/extract_review.py
Labels: bug

#746 Unreal: add 4.26 support
  pype/hosts/unreal/lib.py
  pype/lib/hooks.py
Labels: enhancement, host: UE

#771 Anatomy with dynamic schemas
  pype/tools/settings/settings/widgets/anatomy_types.py
Labels: enhancement

#772 Unified settings category widget
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_main.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_main.json
  pype/tools/settings/settings/widgets/base.py
Labels: enhancement

#774 Feature AE load background
  pype/lib/abstract_collect_render.py
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/load/load_background.py
  pype/plugins/aftereffects/load/load_file.py
  pype/plugins/aftereffects/publish/collect_render.py
  pype/plugins/lib.py
Labels: enhancement, host: After Effects

#773 Maya: Look - respect original texture colorspace when not using maketx
  pype/plugins/maya/publish/extract_look.py
Labels: bug, host: Maya

#776 Clear metadata from loaded settings
  pype/settings/lib.py
Labels: enhancement

#783 settings GUI styles
  pype/tools/settings/settings/style/style.css
  pype/tools/settings/settings/widgets/base.py
Labels: enhancement

#788 Maya plugins use settings
  pype/plugins/ftrack/publish/validate_custom_ftrack_attributes.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/create/create_rendersetup.py
  pype/plugins/maya/publish/extract_camera_mayaScene.py
  pype/plugins/maya/publish/extract_maya_scene_raw.py
  pype/plugins/maya/publish/extract_model.py
  pype/plugins/maya/publish/extract_playblast.py
  pype/plugins/maya/publish/extract_rig.py
  pype/plugins/maya/publish/extract_thumbnail.py
  pype/plugins/maya/publish/extract_yeti_rig.py
  pype/plugins/maya/publish/submit_maya_muster.py
  pype/plugins/maya/publish/validate_attributes.py
  pype/plugins/maya/publish/validate_muster_connection.py
  pype/settings/defaults/project_settings/ftrack.json
  pype/settings/defaults/project_settings/global.json
  pype/settings/defaults/project_settings/maya.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_tools.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_capture.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_publish.json
Labels: backend

#781 AE - fix publish after background load
  pype/lib/__init__.py
  pype/lib/plugin_tools.py
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/create/create_render.py
  pype/plugins/aftereffects/load/load_background.py
  pype/plugins/aftereffects/load/load_file.py
  pype/plugins/aftereffects/publish/collect_render.py
  pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
  pype/plugins/lib.py
Labels: host: After Effects

#794 Rmove previous implementation of hooks
  pype/hooks/celaction/prelaunch.py
  pype/hooks/fusion/prelaunch.py
  pype/hooks/photoshop/prelaunch.py
  pype/hooks/premiere/prelaunch.py
  pype/hooks/resolve/prelaunch.py
  pype/hooks/tvpaint/prelaunch.py
  pype/hooks/unreal/unreal_prelaunch.py
  pype/lib/__init__.py
  pype/lib/hooks.py
Labels: backend

#797 Python 2: make user settings compatible with python 2 hosts
  pype.py
  pype/hosts/maya/menu.py
  pype/lib/user_settings.py
  requirements.txt
Labels: bug

#800 Avalon context lib fix
  pype/lib/avalon_context.py
Labels: bug

#798 Launcher actions update
  pype/tools/launcher/models.py
  pype/tools/launcher/window.py
Labels: bug

#805 add settings, tray and mongo launcher
  dev_mongo.ps1
  dev_settings.ps1
  dev_tray.ps1
Labels: backend

#807 Feature/push hier value to nonhier action
  pype/modules/ftrack/events/action_push_frame_values_to_task.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
Labels: bug

#806 Harmony: fix palette and image sequence loader
  pype/hosts/harmony/js/PypeHarmony.js
  pype/hosts/harmony/js/loaders/ImageSequenceLoader.js
  pype/plugins/harmony/load/load_palette.py
Labels: bug, client, host: Harmony

#809 TVPaint repair invalid metadata
  pype/plugins/tvpaint/publish/collect_workfile_data.py
Labels: bug

#811 Settings store in mongo
  pype.py
  pype/lib/__init__.py
  pype/lib/mongo.py
  pype/settings/constants.py
  pype/settings/handlers.py
  pype/settings/lib.py
  pype/tools/settings/settings/widgets/base.py
  pype/tools/settings/settings/widgets/lib.py
Labels: enhancement

#813 Services menu do not popup on tray start
  pype/modules/base.py
Labels: bug

#814 Standalone publisher fix in 3.0
  pype/tools/standalonepublish/app.py
  pype/tools/standalonepublish/widgets/widget_asset.py
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: bug

#815 Modules keys in settings
  pype/modules/avalon_apps/avalon_app.py
  pype/modules/base.py
  pype/modules/clockify/clockify_module.py
  pype/modules/ftrack/ftrack_module.py
  pype/modules/idle_manager/idle_manager.py
  pype/modules/logging/logging_module.py
  pype/modules/rest_api/rest_api.py
  pype/modules/standalonepublish/standalonepublish_module.py
  pype/modules/timers_manager/timers_manager.py
  pype/modules/user/user_module.py
  pype/settings/defaults/system_settings/modules.json
  pype/tools/settings/settings/gui_schemas/system_schema/module_settings/schema_ftrack.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_modules.json
Labels: backend

#810 Bugfix: Supercritical fix for Pype
  pype.py
  pype/lib/splash.txt
  pype/lib/terminal.py
  pype/lib/terminal_splash.py
  requirements.txt
Labels: HIGH, bug

#821 Version to task with right settings
  pype/modules/ftrack/events/event_version_to_task_statuses.py
  pype/modules/ftrack/ftrack_server/event_server_cli.py
  pype/modules/ftrack/ftrack_server/ftrack_server.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
  pype/pype_commands.py
  pype/settings/defaults/project_settings/ftrack.json
  pype/settings/defaults/project_settings/global.json
  pype/settings/defaults/project_settings/maya.json
  pype/settings/defaults/project_settings/nuke.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
Labels: enhancement

#820 Prettier Jsons
  .prettierrc
  pype/hosts/hiero/tags.json
  pype/hosts/maya/menu.json
  pype/hosts/maya/menu_backup.json
  pype/hosts/premiere/extensions/com.pype/jsx/jsconfig.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_main.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_plugins.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_celaction.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_global.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_harmony.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_hiero.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_maya.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_nuke.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_resolve.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_standalonepublisher.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_unreal.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_anatomy_attributes.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_anatomy_imageio.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_anatomy_templates.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_publish.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_tools.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_capture.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_load.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_maya_publish.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_publish_gui_filter.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_workfile_build.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/template_color.json
  pype/tools/settings/settings/gui_schemas/system_schema/example_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/example_template.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_aftereffects.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_blender.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_celaction.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_djv.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_fusion.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_harmony.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_houdini.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_maya.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_mayabatch.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_photoshop.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_resolve.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_shell.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_tvpaint.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_unreal.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/template_host_unchangables.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/template_nuke.json
  pype/tools/settings/settings/gui_schemas/system_schema/module_settings/schema_ftrack.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_applications.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_general.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_main.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_modules.json
  pype/tools/settings/settings/gui_schemas/system_schema/tool_settings/schema_arnold.json
  pype/tools/settings/settings/gui_schemas/system_schema/tool_settings/schema_vray.json
  pype/tools/settings/settings/gui_schemas/system_schema/tool_settings/schema_yeti.json
Labels: backend

#826 Removed start timer action
  pype/hooks/global/post_ftrack_changes.py
  pype/modules/ftrack/actions/action_start_timer.py
Labels: enhancement

#827 Reset to pype default action show properly
  pype/tools/settings/settings/widgets/item_types.py
Labels: bug

#829 Ftrack module use modules manager for ftrack paths
  pype/modules/clockify/ftrack/server/action_clockify_sync_server.py
  pype/modules/clockify/ftrack/user/action_clockify_sync_local.py
  pype/modules/ftrack/actions/action_delivery.py
  pype/modules/ftrack/actions/action_store_thumbnails_to_avalon.py
  pype/modules/ftrack/events/event_sync_to_avalon.py
  pype/modules/ftrack/ftrack_module.py
  pype/modules/ftrack/ftrack_server/sub_event_processor.py
  pype/modules/ftrack/ftrack_server/sub_legacy_server.py
  pype/modules/ftrack/ftrack_server/sub_user_server.py
  pype/modules/ftrack/lib/__init__.py
  pype/modules/ftrack/lib/settings.py
Labels: enhancement

#796 3.0.fix sync server settings
  pype/modules/__init__.py
  pype/modules/sync_server/README.md
  pype/modules/sync_server/__init__.py
  pype/modules/sync_server/providers/gdrive.py
  pype/modules/sync_server/providers/lib.py
  pype/modules/sync_server/sync_server.py
  pype/plugins/global/publish/integrate_new.py
  pype/settings/defaults/project_settings/global.json
  pype/settings/defaults/system_settings/general.json
  pype/settings/defaults/system_settings/modules.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_global.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_syncserver.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_modules.json
Labels: bug

#822 Maya: Take into account vray master AOV switch
  pype/hosts/maya/expected_files.py
Labels: bug, host: Maya

#823 respecting space in path
  setup/nuke/nuke_path/write_to_read.py
Labels: host: Nuke, hotfix

#831 Maya: Deadline submitter - shared data access violation
  pype/plugins/global/publish/extract_scanline_exr.py
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: MEDIUM, bug, host: Maya

#795 DWAA/DWAB support on windows
  pype/lib/__init__.py
  pype/lib/plugin_tools.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_jpeg.py
  pype/plugins/global/publish/extract_review.py
Labels: enhancement

#812 Tray action interface
  pype/lib/python_module_tools.py
  pype/modules/README.md
  pype/modules/__init__.py
  pype/modules/avalon_apps/avalon_app.py
  pype/modules/base.py
  pype/modules/launcher_action.py
  pype/modules/settings_action.py
  pype/modules/standalonepublish/__init__.py
  pype/modules/standalonepublish_action.py
  pype/tools/launcher/actions.py
Labels: enhancement

#824 Maya: handle referenced AOVs for Vray
  pype/hosts/maya/expected_files.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/publish/collect_render.py
  pype/plugins/maya/publish/validate_vray_referenced_aovs.py
Labels: enhancement, host: Maya

#837 Fix - AE - added explicit cast to int
  pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
Labels: hotfix

#839 terminal.py crash on import
  pype/lib/terminal.py
Labels: bug

#844 List item with wrapper
  pype/tools/settings/settings/README.md
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_main.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_global.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_anatomy_imageio.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schemas/schema_global_tools.json
  pype/tools/settings/settings/widgets/item_types.py
Labels: enhancement

#840 Optionally hide image planes from reviews.
  pype/plugins/maya/create/create_review.py
  pype/plugins/maya/publish/extract_playblast.py
Labels: enhancement, host: Maya

#848 Ftrack actions with settings
  pype/modules/ftrack/actions/action_clean_hierarchical_attributes.py
  pype/modules/ftrack/actions/action_create_cust_attrs.py
  pype/modules/ftrack/actions/action_delete_asset.py
  pype/modules/ftrack/actions/action_delete_old_versions.py
  pype/modules/ftrack/actions/action_delivery.py
  pype/modules/ftrack/actions/action_job_killer.py
  pype/modules/ftrack/actions/action_prepare_project.py
  pype/modules/ftrack/actions/action_seed.py
  pype/modules/ftrack/actions/action_store_thumbnails_to_avalon.py
  pype/modules/ftrack/actions/action_sync_to_avalon.py
  pype/modules/ftrack/actions/action_thumbnail_to_childern.py
  pype/modules/ftrack/events/event_task_to_parent_status.py
  pype/modules/ftrack/events/event_task_to_version_status.py
  pype/modules/ftrack/events/event_thumbnail_updates.py
  pype/modules/ftrack/events/event_version_to_task_statuses.py
  pype/modules/ftrack/lib/ftrack_action_handler.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
  pype/modules/ftrack/lib/ftrack_event_handler.py
  pype/settings/defaults/project_settings/ftrack.json
Labels: enhancement

#856 Ftrack project entity is not stored to event data
  pype/modules/ftrack/events/event_task_to_parent_status.py
  pype/modules/ftrack/events/event_task_to_version_status.py
  pype/modules/ftrack/events/event_thumbnail_updates.py
  pype/modules/ftrack/events/event_version_to_task_statuses.py
  pype/modules/ftrack/lib/ftrack_action_handler.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
  pype/modules/ftrack/lib/ftrack_event_handler.py
Labels: bug, ftrack

#846 Thread safe Terminal
  pype/lib/terminal.py
Labels: backend, enhancement
