Repository ynput/OpenPype, pull requests merged in 2020-10, with the labels that each got.

#584 Harmony: fix clashing namespace of called js functions
  pype/hosts/harmony/__init__.py
Labels: HIGH, bug, host: Harmony

#580 Standalone publisher editorial plugins interfering
  pype/plugins/global/publish/extract_hierarchy_avalon.py
  pype/plugins/standalonepublisher/publish/collect_clip_instances.py
  pype/plugins/standalonepublisher/publish/collect_instance_data.py
  pype/plugins/standalonepublisher/publish/extract_shot_data.py
  pype/plugins/standalonepublisher/publish/extract_thumbnail.py
  pype/plugins/standalonepublisher/publish/validate_editorial_resources.py
  pype/scripts/otio_burnin.py
  pype/tools/standalonepublish/widgets/widget_drop_frame.py
Labels: hotfix

#569 Maya: fix maya scene type preset exception
  pype/plugins/maya/publish/extract_camera_mayaScene.py
  pype/plugins/maya/publish/extract_maya_scene_raw.py
  pype/plugins/maya/publish/extract_model.py
  pype/plugins/maya/publish/extract_yeti_rig.py
Labels: affects: USER, bug, host: Maya

#560 Anatomy instance data collection is substantially faster for many instances
  pype/plugins/global/publish/collect_anatomy_instance_data.py
Labels: enhancement

#587 NKS small fixes
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
  pype/plugins/nukestudio/publish/extract_review_cutup_video.py
Labels: HIGH, hotfix

#577 Ftrack module without Qt
  pype/modules/ftrack/__init__.py
  pype/modules/ftrack/ftrack_server/__init__.py
  pype/modules/ftrack/ftrack_server/custom_db_connector.py
  pype/modules/ftrack/ftrack_server/lib.py
  pype/modules/ftrack/ftrack_server/sub_event_storer.py
  pype/modules/ftrack/lib/avalon_sync.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
  pype/modules/ftrack/tray/login_dialog.py
  pype/modules/ftrack/tray/login_tools.py
Labels: backend

#581 Avalon module without Qt
  pype/modules/avalon_apps/avalon_app.py
Labels: backend

#588 Environments in settings GUI
  pype/settings/lib.py
  pype/tools/settings/settings/gui_schemas/system_schema/1_examples.json
  pype/tools/settings/settings/widgets/base.py
  pype/tools/settings/settings/widgets/item_types.py
  pype/tools/settings/settings/widgets/lib.py
Labels: backend

#590 Hiero integration added
  pype/resources/app_icons/hiero.png
Labels: enhancement

#572 Feature/180 store task types
  pype/hosts/nukestudio/tags.py
  pype/modules/clockify/launcher_actions/ClockifySync.py
  pype/modules/ftrack/lib/avalon_sync.py
  pype/plugins/global/publish/extract_hierarchy_avalon.py
  pype/plugins/maya/publish/collect_yeti_cache.py
  pype/plugins/nukestudio/publish/collect_shots.py
  schema/config-1.1.json
  schema/inventory-1.1.json
  schema/project-2.1.json
Labels: backend, enhancement

#573 Maya: add look assigner to pype menu even if scriptsmenu is not available
  pype/hosts/maya/menu.py
Labels: affects: USER, enhancement, host: Maya

#591 Maya: Deadline - make use of asset dependencies optional
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: affects: CORE, host: Maya

#514 Maya: Updating a look where the shader name changed, leaves the geo without a shader
  pype/plugins/maya/load/load_look.py
  pype/widgets/message_window.py
Labels: bug, host: Maya

#589 Host settings in GUI
  pype/settings/defaults/environments/global.json
  pype/settings/defaults/system_settings/global/applications.json
  pype/settings/defaults/system_settings/global/hosts.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_applications_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_blender_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_celaction_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_djv_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_fusion_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_harmony_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_host_template.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_houdini_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_maya_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_nuke_template.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_photoshop_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_resolve_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_shell_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/system_unreal_schema.json
Labels: backend

#598 convert remaining environments
  pype/settings/defaults/system_settings/global/general.json
  pype/settings/defaults/system_settings/global/modules.json
  pype/tools/settings/settings/gui_schemas/system_schema/0_system_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_general_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_intents_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_modules_gui_schema.json
Labels: backend

#550 Settings GUI - Item type value type validation
  pype/tools/settings/settings/widgets/item_types.py
Labels: backend

#599 Settings GUI has nice checkbox
  pype/tools/settings/settings/widgets/item_types.py
  pype/tools/settings/settings/widgets/widgets.py
Labels: affects: USER, enhancement

#600 Settings GUI environments and discard changes
  pype/tools/settings/settings/widgets/item_types.py
Labels: backend

#562 Intent publish setting wasn't working with default value
  pype/plugins/global/publish/extract_burnin.py
  pype/tools/pyblish_pype/window.py
Labels: bug

#575 Nuke: Publishing, loading and updating alembic cameras
  pype/plugins/nuke/create/create_camera
  pype/plugins/nuke/create/create_camera.py
  pype/plugins/nuke/load/load_backdrop.py
  pype/plugins/nuke/load/load_camera_abc.py
  pype/plugins/nuke/publish/collect_instances.py
  pype/plugins/nuke/publish/extract_camera.py
Labels: enhancement

#609 Harmony: function signature
  pype/hosts/harmony/__init__.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/load/load_audio.py
  pype/plugins/harmony/load/load_background.py
  pype/plugins/harmony/load/load_imagesequence.py
  pype/plugins/harmony/load/load_template_workfile.py
  pype/plugins/harmony/publish/collect_current_file.py
  pype/plugins/harmony/publish/collect_palettes.py
  pype/plugins/harmony/publish/extract_palette.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/harmony/publish/extract_template.py
  pype/plugins/harmony/publish/extract_workfile.py
  pype/plugins/harmony/publish/validate_audio.py
  pype/plugins/harmony/publish/validate_scene_settings.py
Labels: bug, host: Harmony

#606 Standalone publisher now has icon
  pype/tools/standalonepublish/__main__.py
Labels: enhancement

#614 Audio file existence check
  pype/plugins/harmony/publish/extract_render.py
Labels: hotfix

#607 Deadline user defaults to pype username if present
  pype/plugins/global/publish/collect_current_pype_user.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: enhancement

#452 Fusion basic integration
  pype/hooks/fusion/prelaunch.py
  pype/hosts/fusion/__init__.py
  pype/hosts/fusion/menu.py
  pype/hosts/fusion/menu_style.qss
  pype/hosts/fusion/pipeline.py
  pype/hosts/fusion/scripts/duplicate_with_inputs.py
  pype/hosts/fusion/scripts/fusion_switch_shot.py
  pype/hosts/fusion/scripts/publish_filesequence.py
  pype/hosts/fusion/scripts/set_rendermode.py
  pype/hosts/fusion/utility_scripts/32bit/backgrounds_selected_to32bit.py
  pype/hosts/fusion/utility_scripts/32bit/backgrounds_to32bit.py
  pype/hosts/fusion/utility_scripts/32bit/loaders_selected_to32bit.py
  pype/hosts/fusion/utility_scripts/32bit/loaders_to32bit.py
  pype/hosts/fusion/utility_scripts/Pype_menu.py
  pype/hosts/fusion/utility_scripts/switch_ui.py
  pype/hosts/fusion/utility_scripts/update_loader_ranges.py
  pype/hosts/fusion/utils.py
  pype/plugins/fusion/create/create_exr_saver.py
  pype/plugins/fusion/load/load_sequence.py
  pype/plugins/fusion/publish/collect_instances.py
  pype/plugins/fusion/publish/collect_render_target.py
  pype/plugins/fusion/publish/increment_current_file_deadline.py
  pype/plugins/fusion/publish/publish_image_sequences.py
  pype/plugins/fusion/publish/render_local.py
  pype/plugins/fusion/publish/save_scene.py
  pype/plugins/fusion/publish/submit_deadline.py
  pype/plugins/fusion/publish/validate_background_depth.py
  pype/plugins/fusion/publish/validate_comp_saved.py
  pype/plugins/fusion/publish/validate_create_folder_checked.py
  pype/plugins/fusion/publish/validate_filename_has_extension.py
  pype/plugins/fusion/publish/validate_saver_has_input.py
  pype/plugins/fusion/publish/validate_saver_passthrough.py
  pype/plugins/fusion/publish/validate_unique_subsets.py
  pype/plugins/global/publish/collect_avalon_entities.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_jpeg.py
  pype/plugins/global/publish/extract_review.py
  pype/resources/app_icons/fusion.png
Labels: enhancement, host:Fusion

#512 Maya: Tiled EXRs to scanline EXRs render option
  pype/plugins/global/publish/extract_scanline_exr.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/publish/collect_render.py
Labels: affects: CORE, host: Maya

#618 Maya: allow renders to have version synced with workfile
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/collect_render.py
Labels: enhancement

#620 nks: broken order on plugins
  pype/hosts/nuke/lib.py
  pype/plugins/nukestudio/publish/collect_hierarchy_context.py
Labels: HIGH, host: Hiero, host: Nuke, hotfix

#619 Bugfix/605 sync to avalon doesn t remove renamed task
  pype/modules/ftrack/events/action_sync_to_avalon.py
  pype/modules/ftrack/events/event_sync_to_avalon.py
  pype/modules/ftrack/lib/avalon_sync.py
Labels: bug

#608 Ftrack server action improvement
  pype/modules/ftrack/__init__.py
  pype/modules/ftrack/events/action_push_frame_values_to_task.py
  pype/modules/ftrack/events/action_sync_to_avalon.py
  pype/modules/ftrack/lib/__init__.py
  pype/modules/ftrack/lib/ftrack_action_handler.py
  pype/modules/ftrack/lib/ftrack_base_handler.py
Labels: backend

#622 nks little bits
  pype/plugins/nukestudio/publish/collect_hierarchy_context.py
  pype/plugins/nukestudio/publish/collect_plates.py
  pype/plugins/nukestudio/publish/collect_reviews.py
  pype/plugins/nukestudio/publish/extract_review_cutup_video.py
Labels: HIGH, host: Hiero, hotfix

#624 fps(nks): fps collecting into clip instances
  pype/plugins/nukestudio/publish/collect_clips.py
  pype/plugins/nukestudio/publish/collect_framerate.py
Labels: HIGH, host: Hiero, hotfix

#627 fix(hiero): fps order of clip instance data collecting
  pype/plugins/hiero/publish/collect_clips.py
  pype/plugins/hiero/publish/collect_framerate.py
Labels: 2x-dev, bug, host: Hiero

#623 Task processing in event sync
  pype/modules/ftrack/events/event_sync_to_avalon.py
Labels: bug

#625 Add source for review instances.
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
Labels: bug, ftrack

#628 Add mp4 support for RV action.
  pype/modules/ftrack/actions/action_rv.py
Labels: enhancement

#603 Nuke render write targeting knob improvement
  pype/hosts/nuke/lib.py
  pype/plugins/nuke/publish/collect_instances.py
  pype/plugins/nuke/publish/collect_legacy_write.py
  pype/plugins/nuke/publish/validate_write_legacy.py
Labels: 2x-dev, enhancement

#631 Launch TvPaint shot work file from within Ftrack
  pype/hooks/tvpaint/prelaunch.py
  pype/hosts/tvpaint/__init__.py
  pype/hosts/tvpaint/template.tvpp
  pype/resources/app_icons/tvpaint.png
Labels: 2x-dev, enhancement

#615 Harmony: More efficient publishing
  pype/plugins/harmony/publish/collect_scene.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/harmony/publish/extract_template.py
  pype/plugins/harmony/publish/extract_workfile.py
  pype/plugins/harmony/publish/validate_audio.py
  pype/plugins/harmony/publish/validate_scene_settings.py
Labels: 2x-dev, affects: CORE, host: Harmony

#639 Missing audio on farm submission.
  pype/plugins/global/publish/submit_publish_job.py
Labels: bug, host: Nuke

#638 Improved publishing of multiple representation from SP
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
  pype/plugins/global/publish/cleanup.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_review.py
  pype/plugins/standalonepublisher/publish/collect_representation_names.py
  pype/plugins/standalonepublisher/publish/extract_thumbnail.py
Labels: HIGH, enhancement

#644 Nuke: prevent crash if we only have single frame in sequence
  pype/plugins/nuke/load/load_sequence.py
Labels: bug, host: Nuke

#641 Burnin script logs better output
  pype/lib.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_review.py
  pype/scripts/otio_burnin.py
Labels: backend, enhancement

#645 Lib subprocess without logger
  pype/lib.py
Labels: bug

#633 review from imagesequence error
  pype/plugins/hiero/publish/collect_clips.py
  pype/plugins/hiero/publish/collect_review.py
  pype/plugins/hiero/publish/extract_review_cutup.py
  pype/plugins/hiero/publish/extract_review_cutup_video.py
Labels: bug, host: Hiero

#646 Pyblish-pype spacer in terminal wasn't transparent
  pype/tools/pyblish_pype/widgets.py
Labels: bug

#642 Get latest version in lib
  pype/hosts/harmony/__init__.py
  pype/lib.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/nuke/publish/collect_review.py
Labels: backend, enhancement

#601 Settings function moved out of tool
  pype/settings/lib.py
  pype/tools/settings/settings/widgets/base.py
Labels: backend

#635 Extract review small enhancement
  pype/plugins/global/publish/extract_review.py
Labels: backend, enhancement

#657 Photoshop: Fix Layer name was not propagating correctly
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
  pype/plugins/photoshop/load/load_image.py
Labels: 2x-dev, bug, host: Photoshop

#658 Launcher has unified group identifier
  pype/tools/launcher/delegates.py
Labels: enhancement

#665 Nuke: wrong conditions when fixing legacy write nodes
  pype/plugins/nuke/publish/validate_write_legacy.py
Labels: bug, host: Nuke, hotfix

#668 TVPaint integration
  pype/hooks/tvpaint/prelaunch.py
  pype/hosts/tvpaint/__init__.py
  pype/hosts/tvpaint/avalon.loc
  pype/plugins/tvpaint/load/load_image.py
Labels: enhancement

#672 Pyblish pype animation switch and other bugs
  pype/tools/pyblish_pype/app.py
  pype/tools/pyblish_pype/compat.py
  pype/tools/pyblish_pype/control.py
  pype/tools/pyblish_pype/settings.py
  pype/tools/pyblish_pype/util.py
  pype/tools/pyblish_pype/view.py
  pype/tools/pyblish_pype/window.py
Labels: 2x-dev, bug
