Repository ynput/OpenPype, pull requests merged in 2020-09, with the labels that each got.

#501 Remove extra dash
  pype/scripts/otio_burnin.py
Labels: bug

#499 feat(nuke): adding image loader
  pype/plugins/nuke/load/load_image.py
  pype/plugins/nuke/load/load_sequence.py
Labels: HIGH, host: Nuke

#511 Maya: Fix tile order for Draft Tile Assembler
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: affects: USER, bug, host: Maya

#508 NukeStudio: Fix comment tag collection and integration.
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
  pype/plugins/nukestudio/publish/collect_hierarchy_context.py
  pype/plugins/nukestudio/publish/collect_shots.py
  pype/plugins/nukestudio/publish/collect_tag_comments.py
Labels: bug, host: NukeStudio

#455 Fix alembic settings being reset when updating reference.
  pype/hosts/maya/plugin.py
Labels: bug, host: Maya

#518 388 Extract review a representation name with `*_burnin`
  pype/plugins/global/publish/extract_burnin.py
Labels: bug

#470 Update subset families on integration
  pype/plugins/global/publish/integrate_new.py
Labels: bug

#474 Fix optional skip reviews on renders.
  pype/plugins/global/publish/submit_publish_job.py
Labels: bug, host: Maya

#456 photoshop with websocket
  pype/modules/websocket_server/hosts/photoshop.py
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
  pype/modules/websocket_server/websocket_server.py
  pype/plugins/photoshop/create/create_image.py
  pype/plugins/photoshop/load/load_image.py
  pype/plugins/photoshop/publish/collect_current_file.py
  pype/plugins/photoshop/publish/collect_instances.py
  pype/plugins/photoshop/publish/extract_image.py
  pype/plugins/photoshop/publish/extract_review.py
  pype/plugins/photoshop/publish/extract_save_scene.py
  pype/plugins/photoshop/publish/increment_workfile.py
  pype/plugins/photoshop/publish/validate_instance_asset.py
  pype/plugins/photoshop/publish/validate_naming.py
Labels: enhancement

#510 Maya: Image plane cache and PNG reprensentations.
  pype/plugins/maya/load/load_image_plane.py
Labels: enhancement, host: Maya

#483 Optional camera creation on image plane loading.
  pype/plugins/maya/load/load_image_plane.py
Labels: enhancement, host: Maya

#527 ListWidgetItem has fixed move buttons
  pype/tools/settings/settings/widgets/item_types.py
Labels: bug

#534 Converting tray modules and their settings to GUI
  pype/settings/defaults/system_settings/global/applications.json
  pype/settings/defaults/system_settings/global/general.json
  pype/settings/defaults/system_settings/global/modules.json
  pype/settings/defaults/system_settings/global/tools.json
  pype/settings/defaults/system_settings/global/tray_modules.json
  pype/tools/settings/settings/gui_schemas/system_schema/0_system_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_intents_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_modules_gui_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/1_tray_items.json
Labels: enhancement

#540 Copy file and file path are working in Maya 2020
  pype/plugins/global/load/copy_file.py
  pype/plugins/global/load/copy_file_path.py
Labels: bug

#520 Extract review a representation name with `*_burnin`
  pype/plugins/global/publish/extract_burnin.py
Labels: bug

#551 Hierarchy data was not considering active isntances
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
  pype/plugins/global/publish/extract_hierarchy_avalon.py
  pype/plugins/standalonepublisher/publish/collect_editorial.py
Labels: bug

#544 Maya: Fix missing frame range update on audio.
  pype/plugins/maya/load/load_audio.py
Labels: bug, host: Maya

#545 Maya: Fix missing update of frame range on image plane.
  pype/plugins/maya/load/load_image_plane.py
Labels: bug, host: Maya

#556 Fix of raw json item
  pype/tools/settings/settings/widgets/item_types.py
Labels: bug

#543 Refresh Ftrack locations on session rollback
  pype/plugins/ftrack/publish/integrate_ftrack_api.py
  pype/plugins/ftrack/publish/integrate_ftrack_note.py
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
Labels: bug

#557 Path widget fix
  pype/tools/settings/settings/style/style.css
  pype/tools/settings/settings/widgets/item_types.py
Labels: bug

#537 Settings: Maya plugins and capture settings
  pype/settings/defaults/project_settings/plugins/maya/maya/maya_capture.json
  pype/settings/defaults/project_settings/plugins/maya/maya/publish.json
  pype/settings/defaults/project_settings/plugins/maya/maya/workfile_build.json
  pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json
  pype/tools/settings/settings/gui_schemas/projects_schema/2_maya_capture.json
  pype/tools/settings/settings/gui_schemas/projects_schema/2_maya_plugins.json
  pype/tools/settings/settings/gui_schemas/projects_schema/2_maya_workfiles.json
  pype/tools/settings/settings/widgets/lib.py
Labels: affects: CORE, enhancement

#563 RestApi module without Qt
  pype/modules/rest_api/rest_api.py
Labels: enhancement

#561 Setting tool: Remove spacer after refresh
  pype/tools/settings/settings/widgets/base.py
Labels: bug
