Repository ynput/OpenPype, pull requests merged in 2020-11, with the labels that each got.

#669 Hook and plugin filter extracted from lib.py
  pype/lib/__init__.py
  pype/lib/deprecated.py
  pype/lib/hooks.py
  pype/lib/lib_old.py
  pype/lib/plugin_tools.py
Labels: backend

#680 Fix ffmpeg executable path with spaces
  pype/lib.py
  pype/plugins/global/publish/extract_jpeg.py
  pype/plugins/global/publish/extract_review.py
  pype/plugins/global/publish/extract_review_slate.py
  pype/plugins/global/publish/validate_ffmpeg_installed.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/hiero/publish/extract_review_cutup.py
  pype/plugins/photoshop/publish/extract_review.py
  pype/plugins/standalonepublisher/publish/extract_shot_data.py
  pype/plugins/standalonepublisher/publish/extract_thumbnail.py
  pype/scripts/otio_burnin.py
  pype/tools/standalonepublish/widgets/widget_drop_frame.py
Labels: bug, hotfix

#679 Hotfix: Added default version number
  pype/plugins/global/publish/submit_publish_job.py
Labels: HIGH, bug, hotfix

#677 Order workfile build as presets.
  pype/lib.py
Labels: enhancement

#681 Lib from illicit part 1
  pype/api.py
  pype/hosts/hiero/lib.py
  pype/hosts/maya/lib.py
  pype/hosts/nuke/lib.py
  pype/lib/__init__.py
  pype/lib/applications.py
  pype/lib/deprecated.py
  pype/lib/lib_old.py
Labels: backend

#685 Nuke Favorite directories "shot dir" "project dir" - not working #684
  pype/hosts/nuke/lib.py
Labels: host: Nuke, hotfix

#675 TVPaint image loader with options
  pype/plugins/tvpaint/load/load_image.py
Labels: 2x-dev, enhancement

#674 Camera name in burnins
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/maya/publish/extract_playblast.py
Labels: 2x-dev, enhancement

#692 #688 - Fix publishing hidden layers
  pype/plugins/photoshop/publish/extract_image.py
  pype/plugins/photoshop/publish/extract_review.py
Labels: bug, host: Photoshop, hotfix

#678 Ask user to select non-default camera from scene or create a new.
  pype/plugins/maya/load/load_image_plane.py
Labels: enhancement

#682 Maya: Vray expected file fixes
  pype/hosts/maya/expected_files.py
Labels: bug, host: Maya

#667 Feature/663 aftereffects integration with websocket
  pype/hosts/aftereffects/__init__.py
  pype/modules/websocket_server/hosts/aftereffects.py
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/create/create_render.py
  pype/plugins/aftereffects/load/load_file.py
  pype/plugins/lib.py
  pype/resources/app_icons/aftereffects.png
Labels: 2x-dev, enhancement

#703 Hotfix/thumbnail and review standalone publish
  pype/plugins/standalonepublisher/publish/collect_instance_data.py
  pype/plugins/standalonepublisher/publish/extract_thumbnail.py
Labels: bug

#701 Fix: Burnin data pass and FFmpeg tool check
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/validate_ffmpeg_installed.py
  pype/plugins/photoshop/publish/extract_review.py
  pype/scripts/otio_burnin.py
Labels: HIGH, bug

#706 Feature #664 3.0 lib refactor
  docs/source/pype.aport.rst
  docs/source/pype.rst
  pype/api.py
  pype/hosts/fusion/lib.py
  pype/hosts/fusion/scripts/fusion_switch_shot.py
  pype/hosts/hiero/lib.py
  pype/hosts/maya/lib.py
  pype/hosts/nuke/lib.py
  pype/lib.py
  pype/lib/__init__.py
  pype/lib/applications.py
  pype/lib/avalon_context.py
  pype/lib/deprecated.py
  pype/lib/ffmpeg_utils.py
  pype/lib/hooks.py
  pype/lib/path_tools.py
  pype/lib/plugin_tools.py
  pype/plugins/celaction/publish/collect_audio.py
  pype/plugins/launcher/actions/Aport.py
  pype/plugins/launcher/actions/unused/PremierePro.py
  pype/plugins/maya/publish/collect_yeti_rig.py
  pype/plugins/maya/publish/extract_camera_mayaScene.py
  pype/scripts/fusion_switch_shot.py
  pype/tests/README.md
  pype/tests/test_lib_restructuralization.py
Labels: backend

#709 Nuke: load sequence with correct frame start
  pype/plugins/nuke/load/load_sequence.py
Labels: HIGH, host: Nuke, hotfix

#710 Maya: Fix for publishing multiple cameras with review from the same scene
  pype/plugins/maya/publish/collect_ftrack_family.py
  pype/plugins/maya/publish/collect_remove_marked.py
  pype/plugins/maya/publish/collect_review.py
  pype/plugins/maya/publish/extract_camera_alembic.py
  pype/plugins/maya/publish/extract_camera_mayaScene.py
Labels: bug, host: Maya, hotfix

#711 Maya workfile version wasn't syncing with renders properly
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/collect_render.py
  pype/plugins/photoshop/load/load_image.py
Labels: bug

#715 Maya: disable legacy override check for cameras
  pype/hosts/maya/expected_files.py
Labels: bug, host: Maya

#717 Removed artist view from pyblish gui
  pype/tools/pyblish_pype/app.css
  pype/tools/pyblish_pype/delegate.py
  pype/tools/pyblish_pype/img/tab-home.png
  pype/tools/pyblish_pype/model.py
  pype/tools/pyblish_pype/settings.py
  pype/tools/pyblish_pype/view.py
  pype/tools/pyblish_pype/window.py
Labels: 2x-dev, enhancement

#716 Synchronize ftrack hierarchical and shot attributes
  pype/modules/ftrack/events/event_push_frame_values_to_task.py
Labels: enhancement

#693 TV Paint: initial implementation with loaders, creators and local rendering
  pype/hosts/tvpaint/__init__.py
  pype/plugins/global/publish/extract_review.py
  pype/plugins/tvpaint/create/create_render_layer.py
  pype/plugins/tvpaint/create/create_render_pass.py
  pype/plugins/tvpaint/create/create_review.py
  pype/plugins/tvpaint/load/load_image.py
  pype/plugins/tvpaint/load/load_reference_image.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/extract_sequence.py
  pype/plugins/tvpaint/publish/validate_frame_range.py
Labels: enhancement

#719 Sort instances by label in pyblish gui
  pype/tools/pyblish_pype/model.py
  pype/tools/pyblish_pype/view.py
  pype/tools/pyblish_pype/window.py
Labels: enhancement

#721 Maya: add camera rig publishing option
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/maya/create/create_camera.py
  pype/plugins/maya/load/load_reference.py
  pype/plugins/maya/publish/extract_maya_scene_raw.py
Labels: enhancement

#722 Maya: vray proxy was no loading at all
  pype/plugins/maya/load/load_vrayproxy.py
Labels: bug

#726 Asset fetch second fix
  pype/tools/launcher/widgets.py
  pype/tools/launcher/window.py
Labels: HIGH, bug

#729 fix(SP): getting fps from context instead of nonexistent entity
  pype/plugins/standalonepublisher/publish/collect_instance_data.py
Labels: HIGH, host: Standalone, hotfix

#699 686 standalonepublisher editorial from image sequences
  pype/plugins/standalonepublisher/publish/collect_clear_instances.py
  pype/plugins/standalonepublisher/publish/collect_editorial.py
  pype/plugins/standalonepublisher/publish/collect_hierarchy.py
  pype/plugins/standalonepublisher/publish/collect_instance_data.py
  pype/plugins/standalonepublisher/publish/collect_instance_resources.py
  pype/plugins/standalonepublisher/publish/collect_instances.py
  pype/plugins/standalonepublisher/publish/extract_shot_data.py
  pype/plugins/standalonepublisher/publish/extract_thumbnail.py
  pype/plugins/standalonepublisher/publish/extract_trim_video_audio.py
  pype/plugins/standalonepublisher/publish/validate_editorial_resources.py
Labels: 2x-dev, enhancement, host: Standalone

#720 Hiero collecting and processing review
  pype/hosts/hiero/__init__.py
  pype/hosts/hiero/lib.py
  pype/hosts/hiero/menu.py
  pype/hosts/hiero/plugin.py
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/hiero/_publish/collect_review.py
  pype/plugins/hiero/create/create_shot_clip.py
  pype/plugins/hiero/publish/collect_assetbuilds.py
  pype/plugins/hiero/publish/collect_frame_ranges.py
  pype/plugins/hiero/publish/collect_instances.py
  pype/plugins/hiero/publish/collect_review.py
  pype/plugins/hiero/publish/collect_workfile.py
  pype/plugins/hiero/publish/extract_effects.py
  pype/plugins/hiero/publish/extract_review_cutup.py
Labels: 2x-dev, enhancement, host: Hiero

#738 #735 - fixes for After Effects
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/create/create_render.py
  pype/plugins/aftereffects/publish/collect_render.py
  pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
  pype/plugins/global/publish/submit_publish_job.py
Labels: bug, host: After Effects

#740 TVPaint extract review fix
  pype/plugins/global/publish/extract_review.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/extract_sequence.py
Labels: bug

#744 Hotfix: Maya: multiple renderable cameras in layer
  pype/hosts/maya/expected_files.py
Labels: HIGH, bug, host: Maya, hotfix

#742 Ftrack integrate custom attributes fix
  pype/plugins/ftrack/publish/collect_ftrack_api.py
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
Labels: HIGH, bug, hotfix

#750 Dict invisible and dict merge
  pype/tools/settings/settings/README.md
  pype/tools/settings/settings/gui_schemas/projects_schema/0_project_gui_schema.json
  pype/tools/settings/settings/gui_schemas/projects_schema/1_plugins_gui_schema.json
  pype/tools/settings/settings/gui_schemas/projects_schema/2_maya_capture.json
  pype/tools/settings/settings/gui_schemas/system_schema/example_schema.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_blender.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_celaction.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_djv.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_fusion.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_harmony.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_houdini.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_maya.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_mayabatch.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_photoshop.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_resolve.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_shell.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/schema_unreal.json
  pype/tools/settings/settings/gui_schemas/system_schema/host_settings/template_nuke.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_main.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_modules.json
  pype/tools/settings/settings/gui_schemas/system_schema/schema_tools.json
  pype/tools/settings/settings/widgets/item_types.py
Labels: enhancement

#757 Ftrack plugins cleanup
  pype/modules/ftrack/actions/action_delivery.py
  pype/plugins/ftrack/publish/validate_custom_ftrack_attributes.py
Labels: backend

#751 Raw json environment discard fix
  pype/tools/settings/settings/widgets/item_types.py
Labels: bug

#758 Settings cherry pick develop changes to 2.x/develop
  pype/settings/lib.py
  pype/tools/settings/settings/widgets/base.py
Labels: backend

#754 fix(hiero): trimming review with clip event number
  pype/plugins/hiero/publish/extract_review_cutup.py
Labels: host: Hiero, hotfix

#761 Extract review may not add audio to output
  pype/plugins/global/publish/extract_review.py
Labels: enhancement

#748 Maya: Vray handling of default aov
  pype/hosts/maya/expected_files.py
  pype/plugins/maya/publish/extract_look.py
Labels: bug, host: Maya

#760 After Effects fixes
  pype/lib/abstract_submit_deadline.py
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/publish/collect_audio.py
  pype/plugins/aftereffects/publish/collect_render.py
  pype/plugins/aftereffects/publish/extract_save_scene.py
  pype/plugins/aftereffects/publish/submit_aftereffects_deadline.py
  pype/plugins/global/publish/submit_publish_job.py
Labels: host: After Effects
