Repository ynput/OpenPype, pull requests merged in 2020-05, with the labels that each got.

#94 Feature/ftrack first step cleanup
  pype/ftrack/actions/action_delete_asset.py
  pype/ftrack/actions/action_store_thumbnails_to_avalon.py
  pype/ftrack/lib/__init__.py
  pype/ftrack/lib/ftrack_action_handler.py
  pype/ftrack/lib/ftrack_app_handler.py
  pype/ftrack/lib/ftrack_base_handler.py
  pype/ftrack/lib/ftrack_event_handler.py
  pype/ftrack/lib/lib.py
Labels: enhancement, ftrack

#120 passing PYPE_PYTHON_EXE to farm jobs
  pype/plugins/global/publish/submit_publish_job.py
Labels: affects: CORE, enhancement

#121 Integrate: handle errors during file copy
  pype/plugins/global/publish/integrate_new.py
Labels: affects: CORE, enhancement

#38 Feature/PYPE-762 multi root
  docs/source/conf.py
  make_docs.bat
  pype/__init__.py
  pype/clockify/widget_settings.py
  pype/ftrack/actions/action_create_folders.py
  pype/ftrack/actions/action_create_project_structure.py
  pype/ftrack/actions/action_delete_old_versions.py
  pype/ftrack/actions/action_delivery.py
  pype/ftrack/actions/action_prepare_project.py
  pype/ftrack/actions/action_store_thumbnails_to_avalon.py
  pype/ftrack/events/event_user_assigment.py
  pype/ftrack/lib/avalon_sync.py
  pype/ftrack/lib/ftrack_app_handler.py
  pype/ftrack/tray/login_dialog.py
  pype/lib.py
  pype/logging/gui/widgets.py
  pype/muster/widget_login.py
  pype/nuke/lib.py
  pype/plugins/global/publish/collect_anatomy_context_data.py
  pype/plugins/global/publish/collect_anatomy_instance_data.py
  pype/plugins/global/publish/collect_anatomy_object.py
  pype/plugins/global/publish/collect_avalon_entities.py
  pype/plugins/global/publish/collect_rendered_files.py
  pype/plugins/global/publish/integrate_master_version.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/submit_maya_deadline.py
  pype/plugins/maya/publish/submit_maya_muster.py
  pype/plugins/nuke/publish/submit_nuke_deadline.py
  pype/scripts/publish_deadline.py
  pype/scripts/publish_filesequence.py
  pype/tools/texture_copy/app.py
  schema/config-1.0.json
Labels: enhancement

#118 Feature/117 ftrack mongo id custom attribute
  pype/ftrack/actions/action_create_cust_attrs.py
  pype/ftrack/events/event_sync_to_avalon.py
  pype/ftrack/lib/avalon_sync.py
Labels: affects: CORE, enhancement

#119 Expose write node frame range and limit checkbox.
  pype/nuke/lib.py
Labels: enhancement

#133 Bugfix/premiere cleanup
  pype/avalon_apps/rest_api.py
  pype/services/rest_api/lib/handler.py
Labels: affects: CORE, bug

#138 bugfix/collect reviews variable fix
  pype/plugins/nukestudio/publish/collect_reviews.py
Labels: affects: CORE, bug

#141 Feature/pype 785 osx compatibility
  pype/ftrack/lib/ftrack_app_handler.py
Labels: MEDIUM, affects: CORE, enhancement

#114 Feature/93 flexible template assignment
  pype/nuke/lib.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/extract_yeti_cache.py
  pype/plugins/maya/publish/extract_yeti_rig.py
  pype/plugins/nuke/publish/collect_writes.py
  pype/plugins/nuke/publish/extract_render_local.py
  pype/plugins/nuke/publish/extract_thumbnail.py
  pype/plugins/standalonepublisher/publish/collect_context.py
Labels: affects: CORE, enhancement

#146 some minor fixes for new premiere integration
  pype/services/adobe_communicator/lib/publish.py
Labels: HIGH, affects: CORE, bug

#149 add timeout on request to deadline
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/publish/submit_maya_deadline.py
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: MEDIUM, affects: USER, enhancement

#151 removing unused collect deadline user plugin
  pype/plugins/global/publish/collect_deadline_user.py
Labels: bug

#154 pass PYPE_DEV to deadline job
  pype/plugins/maya/publish/submit_maya_deadline.py
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: affects: CORE, enhancement

#155 fixed condition for multipartExr
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_jpeg.py
  pype/plugins/global/publish/extract_review.py
Labels: HIGH, affects: USER, bug

#23 nks cut reference videos
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_review.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/nukestudio/_unused/collect_timecodes.py
  pype/plugins/nukestudio/publish/collect_clip_resolution.py
  pype/plugins/nukestudio/publish/collect_clips.py
  pype/plugins/nukestudio/publish/collect_frame_ranges.py
  pype/plugins/nukestudio/publish/collect_framerate.py
  pype/plugins/nukestudio/publish/collect_hierarchy_context.py
  pype/plugins/nukestudio/publish/collect_plates.py
  pype/plugins/nukestudio/publish/collect_reviews.py
  pype/plugins/nukestudio/publish/extract_review_cutup_video.py
Labels: enhancement

#130 fix(nks): duplicity in hierarchy tag and not matching names clips
  pype/plugins/nukestudio/publish/collect_clips.py
  pype/plugins/nukestudio/publish/collect_hierarchy_context.py
Labels: affects: USER, bug

#161 nuke family `render2d` if published from imgsequence
  pype/plugins/nuke/publish/collect_writes.py
Labels: HIGH

#103 Feature/pype 754 review burnin filtering
  pype/lib.py
  pype/nuke/lib.py
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_review.py
  pype/plugins/global/publish/extract_review_slate.py
  pype/plugins/global/publish/integrate_new.py
  pype/scripts/otio_burnin.py
Labels: affects: CORE, enhancement
