Repository ynput/OpenPype, pull requests merged in 2021-03, with the labels that each got.

#1062 Multiselect combobox works
  pype/tools/settings/settings/widgets/item_widgets.py
  pype/tools/settings/settings/widgets/multiselection_combobox.py
Labels: bug

#1039 Publish command in Pype cli
  pype/cli.py
  pype/pype_commands.py
Labels: enhancement

#1072 Optionally add task to subset name
  pype/api.py
  pype/hosts/blender/plugin.py
  pype/hosts/harmony/plugin.py
  pype/hosts/houdini/plugin.py
  pype/hosts/maya/plugin.py
  pype/hosts/nuke/plugin.py
  pype/hosts/resolve/plugin.py
  pype/hosts/tvpaint/plugin.py
  pype/lib/__init__.py
  pype/lib/profiles_filtering.py
  pype/plugin.py
  pype/plugins/aftereffects/create/create_render.py
  pype/plugins/blender/create/create_action.py
  pype/plugins/blender/create/create_animation.py
  pype/plugins/blender/create/create_camera.py
  pype/plugins/blender/create/create_layout.py
  pype/plugins/blender/create/create_model.py
  pype/plugins/blender/create/create_rig.py
  pype/plugins/blender/create/create_setdress.py
  pype/plugins/harmony/create/create_farm_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/create/create_template.py
  pype/plugins/houdini/create/create_alembic_camera.py
  pype/plugins/houdini/create/create_pointcache.py
  pype/plugins/houdini/create/create_vbd_cache.py
  pype/plugins/maya/create/create_animation.py
  pype/plugins/maya/create/create_ass.py
  pype/plugins/maya/create/create_assembly.py
  pype/plugins/maya/create/create_camera.py
  pype/plugins/maya/create/create_layout.py
  pype/plugins/maya/create/create_look.py
  pype/plugins/maya/create/create_mayaascii.py
  pype/plugins/maya/create/create_model.py
  pype/plugins/maya/create/create_pointcache.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/create/create_rendersetup.py
  pype/plugins/maya/create/create_review.py
  pype/plugins/maya/create/create_rig.py
  pype/plugins/maya/create/create_setdress.py
  pype/plugins/maya/create/create_unreal_staticmesh.py
  pype/plugins/maya/create/create_vrayproxy.py
  pype/plugins/maya/create/create_vrayscene.py
  pype/plugins/maya/create/create_yeti_cache.py
  pype/plugins/maya/create/create_yeti_rig.py
  pype/plugins/nuke/create/create_backdrop.py
  pype/plugins/nuke/create/create_camera.py
  pype/plugins/nuke/create/create_gizmo.py
  pype/plugins/nuke/create/create_read.py
  pype/plugins/photoshop/create/create_image.py
  pype/plugins/tvpaint/create/create_render_layer.py
  pype/plugins/tvpaint/create/create_render_pass.py
  pype/plugins/tvpaint/create/create_review.py
  pype/tools/standalonepublish/__init__.py
  pype/tools/standalonepublish/__main__.py
  pype/tools/standalonepublish/app.py
  pype/tools/standalonepublish/widgets/constants.py
  pype/tools/standalonepublish/widgets/widget_asset.py
  pype/tools/standalonepublish/widgets/widget_components.py
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: 2x-dev, enhancement

#1082 Collect instance data fix subset query
  pype/plugins/global/publish/collect_anatomy_instance_data.py
Labels: 2x-dev, bug

#1083 Collect instance data fix subset query
  pype/plugins/publish/collect_anatomy_instance_data.py
Labels: bug

#1081 Removed usage of AVALON_MONGO from settings
  pype/tools/settings/settings/widgets/categories.py
  pype/tools/settings/settings/widgets/widgets.py
Labels: bug

#1079 PS - added .psb support
  pype/hosts/photoshop/plugins/publish/collect_workfile.py
  pype/hosts/photoshop/plugins/publish/increment_workfile.py
Labels: enhancement

#1078 PS - added support for .psb in workfiles
  pype/plugins/photoshop/publish/collect_workfile.py
  pype/plugins/photoshop/publish/increment_workfile.py
Labels: 2x-dev, enhancement, host: Photoshop

#1090 Fix versions variable usage in standalone publisher
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: 2x-dev, bug

#1091 Fix versions variable usage in standalone publisher
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: bug

#1085 Ftrack integrate hierarchy fix
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack_SP.py
Labels: 2x-dev, bug

#1086 Ftrack integrate hierarchy fix
  pype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  pype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack_SP.py
Labels: bug

#1080 TVPaint extractor enhancement
  pype/hosts/tvpaint/lib.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/extract_sequence.py
  pype/plugins/tvpaint/publish/validate_layers_visibility.py
Labels: 2x-dev, enhancement

#1084 TVPaint extractor enhancement
  pype/hosts/tvpaint/api/lib.py
  pype/hosts/tvpaint/plugins/publish/collect_instances.py
  pype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  pype/hosts/tvpaint/plugins/publish/extract_sequence.py
  pype/hosts/tvpaint/plugins/publish/validate_layers_visibility.py
Labels: enhancement

#1098 Default settings cleanup
  pype/hosts/maya/api/action.py
  pype/hosts/maya/api/lib.py
  pype/hosts/maya/plugins/publish/extract_playblast.py
  pype/hosts/maya/plugins/publish/extract_thumbnail.py
  pype/hosts/nuke/plugins/load/load_mov.py
  pype/settings/defaults/project_settings/maya.json
  pype/settings/defaults/project_settings/nuke.json
  pype/settings/defaults/project_settings/standalonepublisher.json
  pype/settings/entities/schemas/projects_schema/schema_project_maya.json
  pype/settings/entities/schemas/projects_schema/schema_project_nuke.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_nuke_load.json
  pype/settings/entities/schemas/projects_schema/schemas/template_maya_capture.json
Labels: bug

#1093 Feature/643 mark publishable instances in photoshop
  pype/hooks/aftereffects/prelaunch.py
  pype/hooks/photoshop/prelaunch.py
  pype/modules/websocket_server/hosts/photoshop.py
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
  pype/plugins/photoshop/create/create_image.py
  pype/plugins/photoshop/publish/collect_instances.py
  pype/plugins/photoshop/publish/validate_naming.py
  pype/plugins/photoshop/publish/validate_unique_subsets.py
Labels: 2x-dev

#1095 Feature/643 mark publishable instances in photoshop
  pype/hosts/photoshop/plugins/create/create_image.py
  pype/hosts/photoshop/plugins/publish/collect_instances.py
  pype/hosts/photoshop/plugins/publish/validate_naming.py
  pype/hosts/photoshop/plugins/publish/validate_unique_subsets.py
  pype/modules/websocket_server/hosts/photoshop.py
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
Labels: enhancement

#1106 Reset loader's asset selection on context change
  pype/hosts/maya/__init__.py
Labels: 2x-dev, enhancement

#1107 Reset loader's asset selection on context change
  pype/hosts/maya/api/__init__.py
  pype/hosts/maya/api/lib.py
Labels: enhancement

#1096 Show diagnostic info when clicking on version in pype tray
  pype/lib/pype_info.py
  pype/modules/base.py
  pype/resources/icons/working.svg
  pype/tools/tray/pype_info_widget.py
  pype/tools/tray/pype_tray.py
Labels: enhancement

#1111 Missing gobal environments
  pype/settings/defaults/system_settings/general.json
  start.py
Labels: bug

#1112 TVPaint prelaunch hook fix
  pype/hosts/tvpaint/hooks/pre_launch_args.py
Labels: bug

#1113 Parse global environments
  start.py
Labels: bug

#1117 Sites local settings by site name
  pype/settings/lib.py
  pype/tools/settings/local_settings/projects_widget.py
  pype/tools/settings/local_settings/widgets.py
Labels: enhancement

#1119 Remove Rest Api module
  pype/hosts/maya/plugins/create/create_render.py
  pype/hosts/maya/plugins/create/create_vrayscene.py
  pype/hosts/maya/plugins/publish/validate_muster_connection.py
  pype/hosts/premiere/lib.py
  pype/hosts/premiere/ppro/js/pype_restapi_client.js
  pype/modules/__init__.py
  pype/modules/avalon_apps/avalon_app.py
  pype/modules/avalon_apps/rest_api.py
  pype/modules/muster/muster.py
  pype/modules/muster/rest_api.py
  pype/modules/rest_api/__init__.py
  pype/modules/rest_api/base_class.py
  pype/modules/rest_api/lib/__init__.py
  pype/modules/rest_api/lib/exceptions.py
  pype/modules/rest_api/lib/factory.py
  pype/modules/rest_api/lib/handler.py
  pype/modules/rest_api/lib/lib.py
  pype/modules/rest_api/rest_api.py
  pype/modules/user/rest_api.py
  pype/modules/user/user_module.py
  pype/modules/webserver/__init__.py
  pype/modules/webserver/base_routes.py
  pype/modules/webserver/server.py
  pype/modules/webserver/webserver_module.py
  pype/settings/defaults/system_settings/modules.json
  pype/settings/entities/schemas/system_schema/schema_modules.json
Labels: deprecated, enhancement

#1125 Avoid dot in repre extension
  pype/plugins/global/publish/integrate_new.py
Labels: 2x-dev, bug

#1114 1089 Nuke: AvalonTab as default for write node
  pype/hosts/nuke/lib.py
Labels: 2x-dev, bug, host: Nuke

#1124 1070 Nuke: workfile template
  pype/hosts/nuke/__init__.py
Labels: 2x-dev, enhancement, host: Nuke

#1127 1071 Nuke: shortcuts for Pype menu
  pype/hosts/nuke/menu.py
Labels: 2x-dev, enhancement, host: Nuke

#1132 Fix inheritance of CreateBackdrop creator
  pype/hosts/nuke/plugins/create/create_backdrop.py
Labels: bug

#1129 Settings schemas cleanup
  pype/settings/defaults/project_settings/ftrack.json
  pype/settings/entities/dict_immutable_keys_entity.py
  pype/settings/entities/item_entities.py
  pype/settings/entities/schemas/README.md
  pype/settings/entities/schemas/projects_schema/schema_main.json
  pype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  pype/settings/entities/schemas/system_schema/example_schema.json
  pype/settings/entities/schemas/system_schema/example_template.json
  pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  pype/settings/entities/schemas/system_schema/schema_general.json
  pype/settings/entities/schemas/system_schema/schema_modules.json
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: enhancement

#1138 #21 - Change timers after task change
  pype/__init__.py
  pype/lib/__init__.py
  pype/lib/avalon_context.py
  pype/modules/timers_manager/rest_api.py
  pype/modules/timers_manager/timers_manager.py
Labels: enhancement

#1136 Maya copy mel
  pype/hosts/maya/api/__init__.py
  pype/hosts/maya/hooks/pre_copy_mel.py
  pype/hosts/maya/lib.py
  pype/tools/workfiles/app.py
Labels: bug

#1137 Remove TVPaint's pywin installer
  pype/hosts/tvpaint/hooks/pre_install_pywin.py
Labels: backend, enhancement

#1142 nuke deadline submit with environ var from presets overrides
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: 2x-dev, enhancement, host: Nuke

#1008 Only extend clip range when collecting.
  pype/plugins/hiero/publish/collect_clips.py
Labels: 2x-dev, enhancement

#1143 Animated launch in launcher tool
  pype/tools/launcher/constants.py
  pype/tools/launcher/delegates.py
  pype/tools/launcher/models.py
  pype/tools/launcher/widgets.py
Labels: enhancement

#1101 Bulk mov render publishing
  pype/plugins/ftrack/publish/collect_ftrack_api.py
  pype/plugins/ftrack/publish/integrate_ftrack_api.py
  pype/plugins/global/publish/cleanup.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/standalonepublisher/publish/collect_batch_instances.py
  pype/plugins/standalonepublisher/publish/collect_context.py
  pype/plugins/standalonepublisher/publish/collect_matching_asset.py
Labels: 2x-dev, enhancement

#1108 Bulk mov render publishing
  pype/hosts/standalonepublisher/plugins/publish/collect_batch_instances.py
  pype/hosts/standalonepublisher/plugins/publish/collect_context.py
  pype/hosts/standalonepublisher/plugins/publish/collect_matching_asset.py
  pype/modules/ftrack/plugins/publish/collect_ftrack_api.py
  pype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  pype/plugins/publish/cleanup.py
  pype/plugins/publish/integrate_new.py
Labels: enhancement

#1146 Nuke: adding preset for a Read node name to all img and mov Loaders
  .gitignore
  pype/plugins/nuke/load/load_image.py
  pype/plugins/nuke/load/load_mov.py
  pype/plugins/nuke/load/load_sequence.py
Labels: 2x-dev, client, enhancement, host: Nuke

#1148 Nuke: shortcuts for Pype menu
  pype/hosts/nuke/api/menu.py
  pype/settings/defaults/project_settings/nuke.json
  pype/settings/entities/schemas/projects_schema/schema_project_nuke.json
Labels: client, enhancement, host: Nuke

#1144 Application executable check is less strict
  pype/lib/applications.py
Labels: backend, bug

#1145 Anatomy schema modifications 1st step
  pype/lib/anatomy.py
  pype/settings/defaults/project_anatomy/attributes.json
  pype/settings/defaults/project_anatomy/tasks.json
  pype/settings/defaults/project_anatomy/templates.json
  pype/settings/entities/__init__.py
  pype/settings/entities/base_entity.py
  pype/settings/entities/enum_entity.py
  pype/settings/entities/input_entities.py
  pype/settings/entities/item_entities.py
  pype/settings/entities/lib.py
  pype/settings/entities/root_entities.py
  pype/settings/entities/schemas/projects_schema/schema_main.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_templates.json
Labels: backend

#1149 Harmony missing module
  setup.py
Labels: bug, host: Harmony

#1150 bug: pype root determination when running from sources
  README.md
  start.py
  test_localsystem.txt
Labels: bug

#1157 Ftrack module refactor
  pype/lib/applications.py
  pype/lib/mongo.py
  pype/lib/python_module_tools.py
  pype/modules/ftrack/__init__.py
  pype/modules/ftrack/event_handlers_server/action_clone_review_session.py
  pype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py
  pype/modules/ftrack/event_handlers_server/action_sync_to_avalon.py
  pype/modules/ftrack/event_handlers_server/event_del_avalon_id_from_new.py
  pype/modules/ftrack/event_handlers_server/event_first_version_status.py
  pype/modules/ftrack/event_handlers_server/event_next_task_update.py
  pype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
  pype/modules/ftrack/event_handlers_server/event_radio_buttons.py
  pype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  pype/modules/ftrack/event_handlers_server/event_task_to_parent_status.py
  pype/modules/ftrack/event_handlers_server/event_task_to_version_status.py
  pype/modules/ftrack/event_handlers_server/event_thumbnail_updates.py
  pype/modules/ftrack/event_handlers_server/event_user_assigment.py
  pype/modules/ftrack/event_handlers_server/event_version_to_task_statuses.py
  pype/modules/ftrack/event_handlers_user/action_applications.py
  pype/modules/ftrack/event_handlers_user/action_batch_task_creation.py
  pype/modules/ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
  pype/modules/ftrack/event_handlers_user/action_client_review_sort.py
  pype/modules/ftrack/event_handlers_user/action_component_open.py
  pype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  pype/modules/ftrack/event_handlers_user/action_create_folders.py
  pype/modules/ftrack/event_handlers_user/action_create_project_structure.py
  pype/modules/ftrack/event_handlers_user/action_delete_asset.py
  pype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
  pype/modules/ftrack/event_handlers_user/action_delivery.py
  pype/modules/ftrack/event_handlers_user/action_djvview.py
  pype/modules/ftrack/event_handlers_user/action_job_killer.py
  pype/modules/ftrack/event_handlers_user/action_multiple_notes.py
  pype/modules/ftrack/event_handlers_user/action_prepare_project.py
  pype/modules/ftrack/event_handlers_user/action_rv.py
  pype/modules/ftrack/event_handlers_user/action_seed.py
  pype/modules/ftrack/event_handlers_user/action_store_thumbnails_to_avalon.py
  pype/modules/ftrack/event_handlers_user/action_sync_to_avalon.py
  pype/modules/ftrack/event_handlers_user/action_test.py
  pype/modules/ftrack/event_handlers_user/action_thumbnail_to_childern.py
  pype/modules/ftrack/event_handlers_user/action_thumbnail_to_parent.py
  pype/modules/ftrack/event_handlers_user/action_where_run_ask.py
  pype/modules/ftrack/event_handlers_user/action_where_run_show.py
  pype/modules/ftrack/events/event_test.py
  pype/modules/ftrack/ftrack_module.py
  pype/modules/ftrack/ftrack_server/custom_db_connector.py
  pype/modules/ftrack/ftrack_server/event_server_cli.py
  pype/modules/ftrack/ftrack_server/ftrack_server.py
  pype/modules/ftrack/ftrack_server/lib.py
  pype/modules/ftrack/lib/avalon_sync.py
  pype/modules/ftrack/lib/settings.py
  pype/modules/ftrack/scripts/sub_event_processor.py
  pype/modules/ftrack/scripts/sub_event_status.py
  pype/modules/ftrack/scripts/sub_event_storer.py
  pype/modules/ftrack/scripts/sub_legacy_server.py
  pype/modules/ftrack/scripts/sub_user_server.py
  pype/modules/ftrack/tray/ftrack_tray.py
Labels: backend, enhancement

#1158 Temporary fix of short names from settings
  pype/modules/ftrack/lib/avalon_sync.py
Labels: bug

#1152 Maya: fixes for Redshift support
  pype/hosts/maya/expected_files.py
Labels: 2x-dev, bug, client, enhancement, host: Maya

#1156 Maya: support for Deadline Group and Limit Groups - backport 2.x
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: 2x-dev, client, enhancement, host: Maya

#1155 Maya: support for Deadline Group and Limit Groups
  pype/modules/deadline/plugins/publish/submit_maya_deadline.py
  pype/settings/defaults/project_settings/deadline.json
  pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: client, enhancement, host: Maya

#1163 Maya: Submit to Deadline - fix typo in condition
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: 2x-dev, bug

#1166 Maya: Bugfix: superclass for CreateCameraRig
  pype/plugins/maya/create/create_camera.py
Labels: 2x-dev, HIGH, bug, host: Maya

#1067 Fix getting the camera name.
  pype/plugins/maya/publish/extract_playblast.py
Labels: 2x-dev, bug, host: Maya

#1064 Ensure "NUKE_TEMP_DIR" is not part of the Deadline job environment.
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: 2x-dev

#1151 Modifiable dict with required keys
  pype/settings/entities/dict_mutable_keys_entity.py
  pype/settings/entities/exceptions.py
  pype/settings/entities/schemas/system_schema/example_schema.json
  pype/tools/settings/settings/widgets/dict_mutable_widget.py
Labels: enhancement

#1169 Settings raw-json value type
  pype/settings/entities/input_entities.py
  pype/settings/entities/schemas/README.md
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: enhancement

#1170 Application executables and arguments separated
  pype/hooks/pre_python2_vendor.py
  pype/lib/applications.py
  pype/settings/defaults/system_settings/applications.json
  pype/settings/entities/input_entities.py
  pype/settings/entities/item_entities.py
  pype/settings/entities/root_entities.py
  pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  pype/tools/settings/local_settings/apps_widget.py
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: backend, enhancement

#1168 Anatomy data on project document
  pype/modules/__init__.py
  pype/modules/base.py
  pype/modules/ftrack/ftrack_module.py
  pype/modules/ftrack/lib/avalon_sync.py
  pype/modules/settings_action.py
  pype/settings/defaults/project_anatomy/attributes.json
  pype/settings/entities/__init__.py
  pype/settings/entities/anatomy_entities.py
  pype/settings/entities/base_entity.py
  pype/settings/entities/dict_immutable_keys_entity.py
  pype/settings/entities/dict_mutable_keys_entity.py
  pype/settings/entities/enum_entity.py
  pype/settings/entities/input_entities.py
  pype/settings/entities/item_entities.py
  pype/settings/entities/list_entity.py
  pype/settings/entities/root_entities.py
  pype/settings/entities/schemas/projects_schema/schema_main.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_templates.json
  pype/settings/handlers.py
  pype/settings/lib.py
Labels: enhancement

#1167 Nuke: deadline submit limiting group filter
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: 2x-dev, client, host: Nuke

#1073 Collect audio for farm reviews.
  pype/plugins/global/publish/collect_audio.py
Labels: 2x-dev

#1174 Fix path spaces in jpeg extractor
  pype/plugins/global/publish/extract_jpeg.py
Labels: bug

#1182 Fix TVPaints usage of pywin
  setup.py
Labels: bug

#1178 fix(nuke): reverse search to make it more versatile
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: hotfix

#1183 Enum super call fix
  pype/settings/entities/enum_entity.py
Labels: bug

#1185 Settings UI error catch
  pype/settings/entities/__init__.py
  pype/settings/handlers.py
  pype/tools/settings/settings/widgets/categories.py
Labels: enhancement

#1186 Active key for optional plugins
  pype/settings/defaults/project_settings/maya.json
  pype/settings/defaults/project_settings/nuke.json
  pype/settings/entities/schemas/projects_schema/schemas/template_publish_plugin.json
Labels: enhancement

#1187 Settings handler properties fix
  pype/settings/handlers.py
Labels: bug

#1184 Feature/rename master to hero version
  pype/lib/avalon_context.py
  pype/modules/sync_server/tray/app.py
  pype/plugins/publish/integrate_master_version.py
  pype/settings/defaults/project_anatomy/templates.json
  pype/settings/defaults/project_settings/global.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_templates.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  schema/hero_version-1.0.json
Labels: deprecated, enhancement

#1195 update houdini menu
  pype/hosts/houdini/startup/MainMenuCommon.XML
  pype/hosts/houdini/startup/scripts/123.py
  pype/settings/defaults/system_settings/applications.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
Labels: bug

#1189 Remaining active key for optional plugins
  pype/settings/defaults/project_settings/deadline.json
  pype/settings/defaults/project_settings/maya.json
  pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: enhancement

#1192 Extract review with resolution
  pype/plugins/publish/extract_review.py
  pype/settings/defaults/project_settings/global.json
  pype/settings/entities/input_entities.py
  pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: enhancement

#1193 Project plugin paths and envs
  pype/__init__.py
  pype/hosts/celaction/api/cli.py
  pype/lib/__init__.py
  pype/lib/applications.py
  pype/settings/defaults/project_settings/global.json
  pype/settings/defaults/system_settings/general.json
  pype/settings/entities/schemas/projects_schema/schema_project_global.json
  pype/settings/entities/schemas/system_schema/schema_general.json
  pype/tools/standalonepublish/publish.py
  pype/tools/standalonepublish/widgets/widget_components.py
Labels: enhancement

#1204 Bulk mov strict task
  pype/lib/__init__.py
  pype/lib/plugin_tools.py
  pype/plugin.py
  pype/plugins/standalonepublisher/publish/collect_batch_instances.py
  pype/plugins/standalonepublisher/publish/collect_bulk_mov_instances.py
  pype/plugins/standalonepublisher/publish/validate_task_existence.py
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: 2x-dev

#1202 Update custom ftrack session attributes
  pype/modules/ftrack/ftrack_server/lib.py
Labels: 2x-dev, bug

#1206 Error message in pyblish UI
  pype/tools/pyblish_pype/model.py
Labels: 2x-dev

#1197 Forwards compatible config
  pype/modules/ftrack/actions/action_create_cust_attrs.py
Labels: 2x-dev

#1205 Error message in pyblish UI
  pype/tools/pyblish_pype/model.py
Labels: backend, enhancement

#1209 Remove ftrack mongo settings
  pype/modules/ftrack/lib/settings.py
  pype/settings/defaults/system_settings/modules.json
  pype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
Labels: enhancement

#1217 Fix - modified path of plugin loads for Harmony and TVPaint
  pype/plugins/harmony/create/create_farm_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/create/create_template.py
  pype/plugins/tvpaint/create/create_render_layer.py
  pype/plugins/tvpaint/create/create_render_pass.py
  pype/plugins/tvpaint/create/create_review.py
Labels: 2x-dev, bug

#1214 Fix regex checks in profiles filtering
  pype/lib/profiles_filtering.py
Labels: 2x-dev, bug

#1198 Blender auto PySide2 install hook
  pype/hosts/blender/hooks/pre_pyside_install.py
Labels: enhancement

#1199 Nuke: write node colorspace ignore `default()` label
  pype/plugins/nuke/publish/collect_writes.py
Labels: client, host: Nuke, hotfix

#1201 Nuke: adding preset for a Read node name to all img and mov Loaders
  pype/hosts/nuke/plugins/load/load_image.py
  pype/hosts/nuke/plugins/load/load_mov.py
  pype/hosts/nuke/plugins/load/load_sequence.py
  pype/settings/defaults/project_settings/nuke.json
  pype/settings/entities/schemas/projects_schema/schemas/template_loader_plugin.json
Labels: enhancement, host: Nuke

#1203 Nuke: AvalonTab as default for write node
  pype/hosts/nuke/api/lib.py
Labels: bug, client, host: Nuke

#1194 Nuke: deadline submission with search replaced env values from preset
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: client, host: Nuke, hotfix

#1213 Fix regex checks in profiles filtering
  pype/lib/profiles_filtering.py
Labels: bug

#1219 Pype's workfiles tool in nuke
  pype/hosts/nuke/api/__init__.py
  pype/hosts/nuke/api/menu.py
Labels: bug

#1234 AE - added SubsetManager
  pype/modules/websocket_server/hosts/aftereffects.py
  pype/modules/websocket_server/stubs/aftereffects_server_stub.py
  pype/plugins/aftereffects/create/create_render.py
  pype/plugins/aftereffects/load/load_background.py
  pype/plugins/aftereffects/load/load_file.py
Labels: 2x-dev, enhancement, host: After Effects

#1221 Settings in mongo as dict
  pype/settings/handlers.py
Labels: HIGH, enhancement

#1228 Removed environment metadata from apps and hosts
  pype/hooks/pre_global_host_data.py
  pype/lib/applications.py
  pype/modules/ftrack/event_handlers_user/action_applications.py
  pype/settings/defaults/system_settings/applications.json
  pype/settings/entities/enum_entity.py
  pype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_celaction.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_fusion.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_mayabatch.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_photoshop.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_resolve.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  pype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
  pype/tools/launcher/models.py
Labels: HIGH, backend, enhancement

#1226 Fix - handle duplication of Task name
  pype/plugins/harmony/publish/collect_farm_render.py
Labels: 2x-dev, bug

#1232 Remove settings file handler
  pype/settings/handlers.py
Labels: backend

#1233 Hide expand button if content does not contain any widget
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: enhancement

#1207 Nuke: deadline submit limit group filter
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  pype/settings/defaults/project_settings/deadline.json
  pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: enhancement, host: Nuke
