Repository ynput/OpenPype, pull requests merged in 2021-05, with the labels that each got.

#1446 Faster settings actions
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/list_entity.py
Labels: enhancement

#1445 Keep metadata on remove overrides
  openpype/settings/entities/dict_mutable_keys_entity.py
Labels: bug

#1404 Extract review first documentation
  website/docs/admin_settings_project.md
  website/docs/project_settings/assets/global_extract_review_letter_box.png
  website/docs/project_settings/assets/global_extract_review_letter_box_settings.png
  website/docs/project_settings/assets/global_extract_review_output_defs.png
  website/docs/project_settings/assets/global_extract_review_profiles.png
  website/docs/project_settings/settings_project_global.md
  website/sidebars.js
Labels: documentation, enhancement

#1403 Blender PySide2 install guide
  website/docs/admin_hosts_blender.md
  website/sidebars.js
Labels: documentation, enhancement

#1349 Igniter: Reverse item filter for OpenPype version
  igniter/bootstrap_repos.py
  openpype/cli.py
  openpype/pype_commands.py
  tools/create_zip.ps1
  tools/create_zip.py
  tools/create_zip.sh
Labels: backend, enhancement

#1447 Global settings save/load out of system settings
  openpype/settings/handlers.py
Labels: backend, bug

#1305 TVPaint documentation
  tools/run_documentation.ps1
  website/docs/artist_hosts_tvpaint.md
  website/docs/assets/tvp_asset_loader_actions.png
  website/docs/assets/tvp_asset_loader_version.png
  website/docs/assets/tvp_color_groups.png
  website/docs/assets/tvp_color_groups2.png
  website/docs/assets/tvp_create_layer.png
  website/docs/assets/tvp_create_pass.png
  website/docs/assets/tvp_create_review.png
  website/docs/assets/tvp_hidden_window.gif
  website/docs/assets/tvp_library.gif
  website/docs/assets/tvp_loader.gif
  website/docs/assets/tvp_openpype_menu.png
  website/docs/assets/tvp_permission.png
  website/docs/assets/tvp_permission2.png
  website/docs/assets/tvp_pyblish.png
  website/docs/assets/tvp_pyblish_render.png
  website/docs/assets/tvp_render_pass.png
  website/docs/assets/tvp_scene_inventory.png
  website/docs/assets/tvp_subset_manager.png
  website/docs/assets/tvp_timeline_color.png
  website/docs/assets/tvp_timeline_color2.png
  website/docs/assets/tvp_write_file.png
  website/sidebars.js
Labels: documentation, host: TV Paint

#1456 Add to overrides actions fix
  openpype/settings/entities/dict_immutable_keys_entity.py
Labels: bug

#1457 Settings actions process fix
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
  openpype/tools/settings/settings/widgets/base.py
Labels: bug

#1458 Ftrack specific settings save warning messages
  openpype/modules/ftrack/ftrack_module.py
Labels: enhancement

#1462 Validation of dynamic items in settings
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/list_entity.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_publish_gui_filter.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
Labels: backend, bug

#1444 Feature/sync server priority
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/sync_server/tray/app.py
  openpype/modules/sync_server/tray/delegates.py
  openpype/modules/sync_server/tray/lib.py
  openpype/modules/sync_server/tray/models.py
  openpype/modules/sync_server/tray/widgets.py
Labels: enhancement, module: Sitesync

#1464 Various typos and smaller fixes
  openpype/hosts/maya/plugins/publish/collect_remove_marked.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_clear_instances.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
  openpype/plugins/publish/collect_current_pype_user.py
  openpype/plugins/publish/collect_scene_version.py
Labels: bug

#1463 Forward/Backward compatible apps and tools with OpenPype 3
  pype/modules/ftrack/actions/action_create_cust_attrs.py
  pype/modules/ftrack/lib/avalon_sync.py
Labels: 2x-dev, backend, enhancement

#1468 Fix groups check in Python 2
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
Labels: HIGH, bug

#1466 Extract burnins with color setting
  openpype/plugins/publish/extract_burnin.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: enhancement

#1467 Extract burnins with sequences
  openpype/plugins/publish/extract_burnin.py
  openpype/scripts/otio_burnin.py
Labels: enhancement

#1449 Poetry: Move to OpenPype
  .gitignore
  tools/build.ps1
  tools/build.sh
  tools/create_env.ps1
  tools/create_env.sh
  tools/create_zip.ps1
  tools/create_zip.sh
  tools/fetch_thirdparty_libs.ps1
  tools/fetch_thirdparty_libs.sh
  tools/make_docs.ps1
  tools/make_docs.sh
  tools/run_settings.ps1
  tools/run_settings.sh
  tools/run_tests.ps1
  tools/run_tests.sh
  tools/run_tray.ps1
  tools/run_tray.sh
Labels: backend, enhancement

#1472 Burnin custom font filepath
  openpype/plugins/publish/extract_burnin.py
  openpype/scripts/otio_burnin.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_representation_tags.json
Labels: backend, bug, enhancement

#1474 Igniter buttons enable/disable fix
  igniter/install_dialog.py
Labels: bug

#1475 Fix SyncServer get_enabled_projects should handle global state
  openpype/modules/sync_server/sync_server_module.py
Labels: bug

#1473 Path entity with placeholder
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json
  openpype/tools/settings/settings/widgets/item_widgets.py
Labels: enhancement

#1443 Maya: Support for looks on VRay Proxies
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/load/load_look.py
  openpype/hosts/maya/plugins/load/load_vrayproxy.py
  openpype/hosts/maya/plugins/publish/collect_vrayproxy.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
  openpype/tools/mayalookassigner/app.py
  openpype/tools/mayalookassigner/commands.py
  openpype/tools/mayalookassigner/vray_proxies.py
  openpype/tools/mayalookassigner/widgets.py
  website/docs/artist_hosts_maya.md
  website/docs/assets/maya-vray_proxy-loader.jpg
  website/docs/assets/maya-vray_proxy.jpg
Labels: host: Maya, renderer:Vray

#1479 Nuke: workfile version synced to db version always
  pype/plugins/nuke/publish/collect_workfile.py
Labels: client, host: Nuke, hotfix

#1477 Settings tool cleanup
  openpype/tools/settings/__init__.py
  openpype/tools/settings/lib.py
  openpype/tools/settings/local_settings/apps_widget.py
  openpype/tools/settings/local_settings/constants.py
  openpype/tools/settings/local_settings/widgets.py
  openpype/tools/settings/local_settings/window.py
  openpype/tools/settings/settings/__init__.py
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/dict_mutable_widget.py
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/list_item_widget.py
  openpype/tools/settings/settings/list_strict_widget.py
  openpype/tools/settings/settings/multiselection_combobox.py
  openpype/tools/settings/settings/tests.py
  openpype/tools/settings/settings/widgets.py
  openpype/tools/settings/settings/widgets/__init__.py
  openpype/tools/settings/settings/widgets/lib.py
  openpype/tools/settings/settings/window.py
  openpype/tools/settings/settings/wrapper_widgets.py
Labels: backend, enhancement

#1476 Sorted Applications and Tools in Custom attribute
  openpype/modules/ftrack/lib/custom_attributes.py
  openpype/settings/defaults/system_settings/tools.json
Labels: enhancement

#1482 List entity catch add/remove item changes properly
  openpype/settings/entities/list_entity.py
Labels: backend, bug

#1416 PS - group all published instances
  openpype/lib/__init__.py
  openpype/lib/plugin_tools.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: client, enhancement, host: Photoshop

#1481 Resolve: additional fixes of publishing workflow
  openpype/hosts/resolve/api/lib.py
  openpype/hosts/resolve/api/plugin.py
  openpype/hosts/resolve/plugins/publish/precollect_instances.py
  openpype/plugins/publish/collect_otio_review.py
  openpype/settings/defaults/project_settings/global.json
Labels: bug, host: Resolve

#1485 Undefined constant in subprocess module
  openpype/lib/__init__.py
  openpype/lib/execute.py
  openpype/plugins/publish/extract_burnin.py
Labels: bug

#1492 Codec determination in extract burnin
  openpype/scripts/otio_burnin.py
Labels: bug

#1495 nuke: space in node name breaking process
  openpype/hosts/nuke/api/lib.py
Labels: bug, host: Nuke

#1498 Various smaller fixes
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
  openpype/plugins/load/delete_old_versions.py
  openpype/plugins/publish/integrate_hero_version.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: bug

#1489 TVPaint: Increment workfile version on successfull publish.
  pype/plugins/tvpaint/publish/increment_workfile_version.py
Labels: 2x-dev, host: TV Paint

#1499 Use instance frame start instead of timeline
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: bug

#1486 Use instance frame start instead of timeline.
  pype/plugins/maya/publish/extract_thumbnail.py
Labels: 2x-dev, bug, host: Maya

#1484 Use SubsetLoader and multiple contexts for delete_old_versions
  pype/plugins/global/load/delete_old_versions.py
Labels: 2x-dev, enhancement

#1502 Existing subsets hints in creator
  pype/tools/standalonepublish/widgets/widget_family.py
Labels: 2x-dev, backend, bug

#1503 Existing subsets hints in creator
  openpype/tools/standalonepublish/widgets/widget_family.py
Labels: backend, bug

#1483 Maya: Use of multiple deadline servers
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/publish/collect_render.py
  pype/plugins/maya/publish/submit_maya_deadline.py
  pype/plugins/maya/publish/validate_deadline_connection.py
Labels: 2x-dev, MEDIUM, client, host: Maya

#1504 Store data from modifiable dict as list
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
  openpype/tools/settings/settings/dict_mutable_widget.py
Labels: enhancement

#1289 OpenPype: Support for Docker
  .dockerignore
  Dockerfile
  pyproject.toml
  tools/build.ps1
  tools/build.sh
  tools/create_env.ps1
  tools/create_env.sh
  tools/create_zip.ps1
  tools/create_zip.sh
  tools/docker_build.sh
  tools/fetch_thirdparty_libs.sh
  tools/make_docs.ps1
  tools/make_docs.sh
  tools/run_mongo.ps1
  tools/run_mongo.sh
  tools/run_settings.sh
  tools/run_tests.ps1
  tools/run_tests.sh
  tools/run_tray.sh
  tools/update_submodules.ps1
  tools/update_submodules.sh
  website/docs/dev_build.md
Labels: enhancement

#1480 Maya: Redshift - set proper start frame on proxy
  pype/plugins/maya/publish/extract_redshift_proxy.py
Labels: 2x-dev, bug, hotfix, renderer:Redshift

#1508 Tests: fix pype -> openpype to make tests work again
  tests/igniter/test_bootstrap_repos.py
  tests/openpype/lib/test_user_settings.py
  tools/run_tests.sh
Labels: backend, bug

#1510 Feature Aftereffects setting cleanup documentation
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
  openpype/settings/defaults/project_settings/aftereffects.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
  website/docs/admin_hosts_aftereffects.md
  website/docs/assets/admin_hosts_aftereffects_settings.png
  website/sidebars.js
Labels: documentation, enhancement, host: After Effects

#1506 Feature Harmony setting cleanup documentation
  openpype/hosts/harmony/api/__init__.py
  openpype/hosts/harmony/plugins/publish/validate_scene_settings.py
  openpype/settings/defaults/project_settings/harmony.json
  openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
  website/docs/admin_hosts_harmony.md
  website/docs/assets/admin_hosts_harmony_settings.png
  website/sidebars.js
Labels: documentation, host: Harmony

#1501 Feature Sync server settings enhancement
  openpype/modules/sync_server/providers/abstract_provider.py
  openpype/modules/sync_server/providers/gdrive.py
  openpype/modules/sync_server/providers/lib.py
  openpype/modules/sync_server/providers/local_drive.py
  openpype/modules/sync_server/sync_server.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/sync_server/tray/lib.py
  openpype/modules/sync_server/tray/widgets.py
  openpype/modules/sync_server/utils.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/__init__.py
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
Labels: enhancement, module: Sitesync

#1517 Maya: wrong collection of playblasted frames
  pype/plugins/global/publish/extract_review.py
  pype/plugins/maya/publish/extract_playblast.py
Labels: HIGH, bug, client

#1515 Maya: wrong collection of playblasted frames
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/plugins/publish/extract_review.py
Labels: HIGH, bug

#1507 nuke: fixing start_at with option gui
  pype/plugins/nuke/load/load_mov.py
  pype/plugins/nuke/load/load_sequence.py
Labels: 2x-dev, host: Nuke, hotfix

#1509 3.0 | nuke: fixing start_at with option gui
  openpype/hosts/nuke/plugins/load/load_mov.py
  openpype/hosts/nuke/plugins/load/load_sequence.py
Labels: bug, host: Nuke

#1520 Store as list dictionary check initial value with right type
  openpype/settings/entities/dict_mutable_keys_entity.py
Labels: backend, bug

#1513 OpenPype: use `semver` module for version resolution
  igniter/bootstrap_repos.py
  poetry.lock
  pyproject.toml
  start.py
  tests/igniter/test_bootstrap_repos.py
  tools/build.ps1
Labels: backend, enhancement

#1471 Sync Server beginning of documentation
  website/README.md
  website/docs/artist_tools.md
  website/docs/assets/site_sync_gdrive_user.png
  website/docs/assets/site_sync_loader.png
  website/docs/assets/site_sync_local_setting.png
  website/docs/assets/site_sync_project_settings.png
  website/docs/assets/site_sync_sync_queue.png
  website/docs/assets/site_sync_system.png
  website/docs/module_site_sync.md
Labels: documentation

#1524 OpenPype: Build - Add progress bars
  tools/build.ps1
  tools/build_dependencies.py
Labels: backend, enhancement

#1526 Maya: fix look assignment
  openpype/tools/mayalookassigner/app.py
Labels: HIGH, bug, host: Maya

#1525 OpenPype: disable submodule update with `--no-submodule-update`
  tools/build.ps1
  tools/build.sh
Labels: backend

#1523 Bugfix Sync server local site issues
  openpype/modules/sync_server/providers/local_drive.py
  openpype/modules/sync_server/sync_server_module.py
Labels: bug, module: Sitesync

#1396 Project manager
  openpype/cli.py
  openpype/lib/__init__.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/ftrack/lib/avalon_sync.py
  openpype/pype_commands.py
  openpype/tools/project_manager/__init__.py
  openpype/tools/project_manager/__main__.py
  openpype/tools/project_manager/project_manager/__init__.py
  openpype/tools/project_manager/project_manager/constants.py
  openpype/tools/project_manager/project_manager/delegates.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/project_manager/project_manager/multiselection_combobox.py
  openpype/tools/project_manager/project_manager/style/__init__.py
  openpype/tools/project_manager/project_manager/style/images/combobox_arrow.png
  openpype/tools/project_manager/project_manager/style/images/combobox_arrow_disabled.png
  openpype/tools/project_manager/project_manager/style/pyqt5_resources.py
  openpype/tools/project_manager/project_manager/style/pyside2_resources.py
  openpype/tools/project_manager/project_manager/style/qrc_resources.py
  openpype/tools/project_manager/project_manager/style/resources.qrc
  openpype/tools/project_manager/project_manager/style/style.css
  openpype/tools/project_manager/project_manager/view.py
  openpype/tools/project_manager/project_manager/widgets.py
  openpype/tools/project_manager/project_manager/window.py
  tools/run_project_manager.ps1
Labels: enhancement

#1535 Host name collecting fix
  openpype/plugins/publish/collect_anatomy_context_data.py
Labels: backend, bug

#1536 OpenPype: Powershell scripts polishing
  tools/build.ps1
  tools/build_win_installer.ps1
  tools/create_env.ps1
  tools/create_zip.ps1
  tools/make_docs.ps1
  tools/run_documentation.ps1
  tools/run_mongo.ps1
  tools/run_project_manager.ps1
  tools/run_tests.ps1
Labels: backend, bug

#1541 Bugfix PS subset and quick review
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/photoshop/plugins/publish/extract_image.py
  openpype/hosts/photoshop/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Labels: bug, host: Photoshop

#1530 TVPaint loader settings
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: enhancement

#1531 Handle duplicated task names in project manager
  openpype/tools/project_manager/project_manager/model.py
Labels: backend, bug

#1532 User installation documentation
  website/docs/artist_install.md
  website/docs/assets/artist_systray.png
  website/docs/assets/install_01.png
  website/docs/assets/install_02.png
  website/docs/assets/install_03.png
  website/docs/assets/install_04.png
  website/docs/assets/install_05.png
  website/sidebars.js
Labels: documentation

#1533 celaction: app not starting
  pype/lib/applications.py
Labels: 2x-dev, HIGH, bug, client, hotfix

#1528 Blender can initialize differente user script paths
  openpype/hosts/blender/__init__.py
  openpype/hosts/blender/api/__init__.py
  openpype/hosts/blender/api/lib.py
Labels: backend, bug, enhancement

#1549 Feature Delivery in library loader
  pype/lib/delivery.py
  pype/plugins/global/load/delivery.py
Labels: 2x-dev, client, enhancement

#1542 Color entity
  openpype/settings/entities/__init__.py
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/color_entity.py
  openpype/settings/entities/exceptions.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/system_schema/example_schema.json
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/color_widget.py
  openpype/widgets/color_widgets/__init__.py
  openpype/widgets/color_widgets/color_inputs.py
  openpype/widgets/color_widgets/color_picker_widget.py
  openpype/widgets/color_widgets/color_screen_pick.py
  openpype/widgets/color_widgets/color_triangle.py
  openpype/widgets/color_widgets/color_view.py
  openpype/widgets/color_widgets/eyedropper.png
Labels: enhancement

#1539 Celaction publishing
  pype/hosts/celaction/cli.py
  pype/plugins/celaction/publish/collect_celaction_instances.py
Labels: 2x-dev, HIGH, bug, client, hotfix

#1566 Fix Maya playblast.
  pype/plugins/maya/publish/extract_playblast.py
Labels: bug, host: Maya

#1557 Tools: launcher scripts for project manager
  tools/run_project_manager.ps1
  tools/run_projectmanager.sh
Labels: enhancement

#1554 More failsafes prevent errored runs.
  pype/plugins/global/load/delete_old_versions.py
Labels: 2x-dev, bug, convert to 3.0

#1578 Hiero: publishing issues
  openpype/plugins/publish/extract_otio_audio_tracks.py
  openpype/plugins/publish/extract_otio_review.py
Labels: HIGH, client, host: Hiero, hotfix

#1581 Ftrack delete action cause circular error
  pype/modules/ftrack/actions/action_delete_asset.py
Labels: 2x-dev, backend, bug

#1579 Ftrack delete action cause circular error
  openpype/modules/ftrack/event_handlers_user/action_delete_asset.py
Labels: backend, bug

#1546 Feature Delivery in library loader
  openpype/lib/delivery.py
  openpype/modules/ftrack/event_handlers_user/action_delivery.py
  openpype/plugins/load/delivery.py
  website/docs/artist_tools.md
  website/docs/assets/tools/tools_delivery_loader.png
Labels: client, enhancement

#1590 Delivery in LibraryLoader - fixed sequence issue
  pype/lib/delivery.py
  pype/plugins/global/load/delivery.py
Labels: 2x-dev, bug

#1555 Simple tvpaint publish
  openpype/hosts/tvpaint/api/__init__.py
  openpype/hosts/tvpaint/plugins/create/create_review.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
Labels: backend, enhancement

#1534 Extract review bg color
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/template_rgba_color.json
Labels: enhancement

#1582 Sync to avalon do not store hierarchy key
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/ftrack/lib/avalon_sync.py
Labels: backend, enhancement

#1543 Documentation: Dev and system build documentation
  website/docs/admin_distribute.md
  website/docs/admin_openpype_commands.md
  website/docs/admin_use.md
  website/docs/dev_build.md
  website/package.json
  website/yarn.lock
Labels: documentation, enhancement

#1592 Build: stop cleaning of pyc files in build directory
  tools/build.ps1
  tools/build.sh
  tools/create_env.ps1
  tools/create_env.sh
  tools/create_zip.ps1
  tools/create_zip.sh
  tools/run_tests.ps1
  tools/run_tests.sh
Labels: backend, bug

#1595 Ftrack event server launch variable fix
  openpype/cli.py
  openpype/modules/ftrack/ftrack_server/event_server_cli.py
Labels: backend, bug

#1599 List append fix in mutable dict settings
  openpype/settings/entities/dict_mutable_keys_entity.py
Labels: backend, bug

#1569 Crop overscan in Extract Review
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  website/docs/project_settings/assets/global_extract_review_letter_box.png
  website/docs/project_settings/assets/global_extract_review_letter_box_settings.png
  website/docs/project_settings/assets/global_extract_review_output_defs.png
  website/docs/project_settings/settings_project_global.md
Labels: enhancement

#1598 Documentation: Maya: fix review
  website/docs/artist_hosts_maya.md
  website/docs/assets/maya-model_review_setup.jpg
Labels: bug, documentation

#1553 Maya Hardware support
  pype/hosts/maya/expected_files.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/publish/collect_render.py
  pype/plugins/maya/publish/validate_render_single_camera.py
  pype/plugins/maya/publish/validate_rendersettings.py
Labels: 2x-dev, convert to 3.0, host: Maya

#1172 Hiero: Initial frame publish support.
  pype/hosts/hiero/tags.json
  pype/plugins/hiero/publish/collect_frame_ranges.py
  pype/plugins/hiero/publish/collect_frames.py
  pype/plugins/hiero/publish/collect_hierarchy_context.py
  pype/plugins/hiero/publish/collect_tag_handles.py
  pype/plugins/hiero/publish/extract_frames.py
Labels: 2x-dev, convert to 3.0, enhancement

#1588 FFmpeg filters in quote marks
  pype/plugins/global/publish/extract_review.py
Labels: 2x-dev, backend, bug

#1607 Maya: Render workflow fixes
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: host: Maya

#1609 Maya: Render workflow fixes - 2.0 backport
  pype/plugins/global/publish/submit_publish_job.py
Labels: 2x-dev, host: Maya
