Repository ynput/OpenPype, pull requests merged in 2021-08, with the labels that each got.

#1891 Settings: Conditional dict enum positioning
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/system_schema/example_schema.json
  openpype/tools/settings/settings/dict_conditional.py
Labels: backend, enhancement

#1889 publisher: editorial plugins fixes
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_hierarchy.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py
  openpype/settings/defaults/project_settings/standalonepublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json
Labels: bug

#1892 Settings: global validators with options
  openpype/plugins/publish/validate_editorial_asset_name.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: enhancement

#1890 global: integrate name missing default template
  openpype/plugins/publish/integrate_new.py
Labels: bug

#1817 Maya: expected files -> render products ⚙️ overhaul - Pype 2.x backport
  pype/hosts/maya/expected_files.py
  pype/hosts/maya/lib.py
  pype/hosts/maya/lib_renderproducts.py
  pype/hosts/maya/lib_rendersetup.py
  pype/plugins/maya/publish/collect_render.py
Labels: 2x-dev, host: Maya

#1762 Maya: Shader name validation
  openpype/hosts/maya/api/commands.py
  openpype/hosts/maya/api/menu.py
  openpype/hosts/maya/api/shader_definition_editor.py
  openpype/hosts/maya/plugins/publish/validate_model_name.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schema_project_maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_scriptsmenu.json
  openpype/vendor/python/common/scriptsmenu/__init__.py
  openpype/vendor/python/common/scriptsmenu/action.py
  openpype/vendor/python/common/scriptsmenu/launchformari.py
  openpype/vendor/python/common/scriptsmenu/launchformaya.py
  openpype/vendor/python/common/scriptsmenu/launchfornuke.py
  openpype/vendor/python/common/scriptsmenu/scriptsmenu.py
  openpype/vendor/python/common/scriptsmenu/vendor/Qt.py
  openpype/vendor/python/common/scriptsmenu/vendor/__init__.py
  openpype/vendor/python/common/scriptsmenu/version.py
  website/docs/admin_hosts_maya.md
  website/docs/assets/maya-admin_model_name_validator.png
  website/docs/assets/maya-admin_scriptsmenu.png
Labels: MEDIUM, client, enhancement, host: Maya

#1893 Bug: fixed python detection
  tools/build.ps1
  tools/create_env.ps1
Labels: backend, bug

#1885 TVPaint: Increment workfile
  openpype/hosts/tvpaint/plugins/publish/increment_workfile_version.py
Labels: enhancement, host: TV Paint

#1863 Maya: add support for `RedshiftNormalMap` node, fix `tx` linear space 🚀
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: MEDIUM, host: Maya, renderer:Redshift

#1898 Support nested studio plugins paths.
  openpype/__init__.py
Labels: enhancement

#1902 Burnins: Use input's bitrate in h624
  openpype/scripts/otio_burnin.py
Labels: backend, bug

#1903 Pyblish UI: Fix collecting stage processing
  openpype/tools/pyblish_pype/control.py
  openpype/tools/pyblish_pype/model.py
Labels: backend, bug

#1900 Ftrack: Where I run action enhancement
  openpype/modules/ftrack/event_handlers_user/action_where_run_ask.py
  openpype/modules/ftrack/event_handlers_user/action_where_run_show.py
Labels: backend, enhancement, module: Ftrack

#1899 Ftrack: Private project server actions
  openpype/modules/ftrack/event_handlers_server/action_private_project_detection.py
  openpype/modules/ftrack/lib/ftrack_base_handler.py
Labels: enhancement, module: Ftrack, backend

#1901 Feature AE local render
  openpype/hosts/aftereffects/plugins/create/create_local_render.py
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/aftereffects/plugins/publish/extract_local_render.py
  openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  website/docs/artist_hosts_aftereffects.md
Labels: enhancement, client, documentation, host: After Effects

#1906 Settings UI: List order works as expected
  openpype/tools/settings/settings/list_item_widget.py
Labels: bug, backend

#1815 Settings list can use template or schema as object type
  openpype/settings/entities/lib.py
  openpype/settings/entities/list_entity.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/system_schema/example_infinite_hierarchy.json
  openpype/settings/entities/schemas/system_schema/example_schema.json
Labels: enhancement, backend

#1914 Fix - texture validators for workfiles triggers only for textures workfiles
  openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py
  openpype/hosts/standalonepublisher/plugins/publish/validate_texture_batch.py
  openpype/hosts/standalonepublisher/plugins/publish/validate_texture_name.py
  openpype/hosts/standalonepublisher/plugins/publish/validate_texture_workfiles.py
Labels: bug, host: Standalone

#1904 Hiero: loaded clip was not set colorspace from version data
  openpype/hosts/hiero/plugins/load/load_clip.py
  openpype/hosts/hiero/plugins/publish/precollect_instances.py
Labels: bug

#1913 Fix - validators for textures workfiles trigger only for textures workfiles
  pype/plugins/standalonepublisher/publish/collect_texture.py
  pype/plugins/standalonepublisher/publish/validate_texture_batch.py
  pype/plugins/standalonepublisher/publish/validate_texture_name.py
  pype/plugins/standalonepublisher/publish/validate_texture_workfiles.py
Labels: bug, host: Standalone, 2x-dev

#1916 Nuke: update video file crassing
  openpype/hosts/nuke/plugins/load/load_mov.py
Labels: bug

#1917 standalone: validator asset parents
  openpype/plugins/publish/validate_editorial_asset_name.py
Labels: bug

#1922 Fix - validate takes repre["files"] as list all the time
  openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
Labels: bug, module: Deadline

#1927 Global: Updated logos and Default settings
  openpype/settings/defaults/project_settings/unreal.json
  website/static/img/logos/pypeclub_black.svg
  website/static/img/logos/pypeclub_color_white.svg
  website/static/img/logos/pypeclub_white.svg
Labels: enhancement

#1924 Duplicate family name.
  pype/plugins/photoshop/create/create_image.py
Labels: bug, host: Photoshop

#1919 Settings UI: Modifiable dict view enhance
  openpype/tools/settings/settings/dict_mutable_widget.py
Labels: enhancement

#1926 Nuke: submit to farm failed due `ftrack` family remove
  openpype/hosts/nuke/plugins/publish/extract_review_data_lut.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
Labels: bug, host: Nuke

#1923 Maya: Scene patching 🩹on submission to Deadline
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
  website/docs/admin_hosts_maya.md
  website/docs/assets/maya-admin_submit_maya_job_to_deadline.png
Labels: enhancement, host: Maya, documentation, module: Deadline

#1925 Check for missing ✨ Python when using `pyenv`
  README.md
  tools/create_env.ps1
Labels: enhancement, backend

#1920 Settings: Default values for enum
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/README.md
Labels: enhancement, backend

#1930 Fix - Deadline publish on Linux started Tray instead of headless publishing
  vendor/deadline/custom/plugins/GlobalJobPreLoad.py
Labels: bug, module: Deadline

#1935 Fix - ftrack family was added incorrectly in some cases
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
Labels: bug

#1932 Settings UI: Breadcrumbs in settings
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
  openpype/settings/entities/root_entities.py
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/breadcrumbs_widget.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/dict_conditional.py
  openpype/tools/settings/settings/dict_mutable_widget.py
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/list_item_widget.py
  openpype/tools/settings/settings/list_strict_widget.py
  openpype/tools/settings/settings/multiselection_combobox.py
  openpype/tools/settings/settings/style/style.css
  openpype/tools/settings/settings/widgets.py
  openpype/tools/settings/settings/wrapper_widgets.py
Labels: feature

#1937 Fix - make AE workfile publish to Ftrack configurable
  openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
  openpype/settings/defaults/project_settings/ftrack.json
Labels: client, module: Ftrack

#1940 Python console interpreter
  openpype/lib/log.py
  openpype/modules/__init__.py
  openpype/modules/python_console_interpreter/__init__.py
  openpype/modules/python_console_interpreter/module.py
  openpype/modules/python_console_interpreter/window/__init__.py
  openpype/modules/python_console_interpreter/window/widgets.py
  openpype/style/__init__.py
  openpype/style/fonts/RobotoMono/LICENSE.txt
  openpype/style/fonts/RobotoMono/README.txt
  openpype/style/fonts/RobotoMono/RobotoMono-Italic-VariableFont_wght.ttf
  openpype/style/fonts/RobotoMono/RobotoMono-VariableFont_wght.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Bold.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-BoldItalic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-ExtraLight.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-ExtraLightItalic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Italic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Light.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-LightItalic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Medium.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-MediumItalic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Regular.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-SemiBold.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-SemiBoldItalic.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-Thin.ttf
  openpype/style/fonts/RobotoMono/static/RobotoMono-ThinItalic.ttf
  openpype/style/style.css
Labels: enhancement

#1812 Maya: expected files -> render products ⚙️ overhaul
  openpype/hosts/maya/api/expected_files.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/api/lib_rendersetup.py
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: host: Maya

#1941 standalone: editorial shared object problem
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
Labels: bug, host: Standalone

#1928 Bugfix nuke deadline app name
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
Labels: bug, module: Deadline

#1945 Maya: Menu actions fix
  openpype/hosts/maya/api/menu.py
Labels: bug, host: Maya

#1946 TVPaint: Fixed rendered frame indexes
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
Labels: bug, host: TV Paint

#1947 Maya: Add Xgen family support
  openpype/hosts/maya/plugins/create/create_xgen.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
  openpype/hosts/maya/plugins/publish/extract_xgen_cache.py
  openpype/plugins/publish/integrate_new.py
  website/docs/artist_hosts_maya.md
Labels: client, feature

#1942 Add face sets to exported alembics
  openpype/hosts/maya/plugins/create/create_animation.py
  openpype/hosts/maya/plugins/create/create_model.py
  openpype/hosts/maya/plugins/create/create_pointcache.py
  openpype/hosts/maya/plugins/publish/extract_animation.py
  openpype/hosts/maya/plugins/publish/extract_model.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
Labels: enhancement, host: Maya

#1910 Environments: Tool environments in alphabetical order
  openpype/lib/applications.py
Labels: enhancement, backend

#1960 Resolve path when adding to zip
  igniter/bootstrap_repos.py
Labels: type: bug

#1948 Global: Define hosts in CollectSceneVersion
  openpype/plugins/publish/collect_scene_version.py
Labels: type: enhancement

#1915 #1894 - adds host to template_name_profiles for filtering
  openpype/plugins/publish/integrate_new.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: type: enhancement

#1888 Disregard publishing time.
  openpype/plugins/publish/start_timer.py
  openpype/plugins/publish/stop_timer.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
Labels: type: feature

#1972 Ftrack: Fix hosts attribute in collect ftrack username
  openpype/modules/default_modules/ftrack/plugins/publish/collect_username.py
Labels: type: bug

#1970 Deadline: Houdini plugins in different hierarchy
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_render_deadline.py
Labels: type: bug, host: Houdini, module: Deadline

#1954 CI: change release numbering triggers
  .github/workflows/prerelease.yml
  tools/ci_tools.py
Labels: backend

#1655 Maya: Deadline custom settings - Pype 2 backport
  pype/plugins/maya/publish/submit_maya_deadline.py
Labels: host: Maya, client, 2x-dev, convert to 3.0

#1961 Global: ExtractJpeg can handle filepaths with spaces
  openpype/plugins/publish/extract_jpeg_exr.py
Labels: type: bug

#1974 Ftrack: arrow submodule has https url source
  .gitmodules
Labels: backend
