Repository ynput/OpenPype, pull requests merged in 2021-12, with the labels that each got.

#2349 Local settings: Copyable studio paths
  openpype/style/style.css
  openpype/tools/settings/local_settings/apps_widget.py
Labels: type: enhancement

#2315 General: Multilayer EXRs support
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/lib/__init__.py
  openpype/lib/plugin_tools.py
  openpype/lib/transcoding.py
  openpype/lib/vendor_bin_utils.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_jpeg_exr.py
  openpype/plugins/publish/extract_review.py
Labels: type: enhancement

#2342 Remove wrongly used host for hook
  openpype/hooks/pre_foundry_apps.py
Labels: type: bug

#2355 Launcher: Minimize button on MacOs
  openpype/tools/launcher/window.py
Labels: type: bug

#2347 Adobe products show issue
  openpype/hooks/pre_non_python_host_launch.py
  openpype/hosts/webpublisher/plugins/publish/validate_tvpaint_workfile_data.py
Labels: type: bug, host: Photoshop, host: After Effects

#2362 JobQueue: Fix loading of settings
  openpype/modules/default_modules/job_queue/module.py
Labels: type: bug

#2361 Burnins: Be able recognize mxf OPAtom format
  openpype/scripts/otio_burnin.py
Labels: type: enhancement

#2359 Tools: Placeholder color
  openpype/tools/loader/app.py
  openpype/tools/project_manager/project_manager/widgets.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
  openpype/tools/settings/local_settings/apps_widget.py
  openpype/tools/settings/local_settings/general_widget.py
  openpype/tools/settings/local_settings/mongo_widget.py
  openpype/tools/settings/local_settings/projects_widget.py
  openpype/tools/settings/settings/widgets.py
  openpype/tools/standalonepublish/widgets/widget_asset.py
  openpype/tools/subsetmanager/window.py
  openpype/tools/utils/__init__.py
  openpype/tools/workfiles/app.py
Labels: type: bug

#2339 Flame: Fix default argument value in custom dictionary
  openpype/hosts/flame/api/lib.py
Labels: type: bug

#2367 Settings: Webpublisher in hosts enum
  openpype/settings/entities/enum_entity.py
Labels: type: enhancement

#2373 Webpublisher: Fix assignment of families of TVpaint instances
  openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_instances.py
Labels: type: bug

#2374 Nuke: fixing menu re-drawing during context change
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/menu.py
Labels: type: bug

#2369 Nuke: fixing node name based on switched asset name
  openpype/hosts/nuke/plugins/load/load_clip.py
Labels: type: bug

#2365 Hiero: python3 compatibility
  openpype/hosts/hiero/__init__.py
  openpype/hosts/hiero/api/__init__.py
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/hiero/api/otio/__init__.py
  openpype/hosts/hiero/api/otio/hiero_export.py
  openpype/hosts/hiero/api/otio/hiero_import.py
  openpype/hosts/hiero/api/otio/utils.py
  openpype/hosts/hiero/api/plugin.py
  openpype/hosts/hiero/api/startup/HieroPlayer/PlayerPresets.hrox
  openpype/hosts/hiero/api/startup/Icons/1_add_handles_end.png
  openpype/hosts/hiero/api/startup/Icons/2_add_handles.png
  openpype/hosts/hiero/api/startup/Icons/3D.png
  openpype/hosts/hiero/api/startup/Icons/3_add_handles_start.png
  openpype/hosts/hiero/api/startup/Icons/4_2D.png
  openpype/hosts/hiero/api/startup/Icons/edit.png
  openpype/hosts/hiero/api/startup/Icons/fusion.png
  openpype/hosts/hiero/api/startup/Icons/hierarchy.png
  openpype/hosts/hiero/api/startup/Icons/houdini.png
  openpype/hosts/hiero/api/startup/Icons/layers.psd
  openpype/hosts/hiero/api/startup/Icons/lense.png
  openpype/hosts/hiero/api/startup/Icons/lense1.png
  openpype/hosts/hiero/api/startup/Icons/maya.png
  openpype/hosts/hiero/api/startup/Icons/nuke.png
  openpype/hosts/hiero/api/startup/Icons/pype_icon.png
  openpype/hosts/hiero/api/startup/Icons/resolution.png
  openpype/hosts/hiero/api/startup/Icons/resolution.psd
  openpype/hosts/hiero/api/startup/Icons/retiming.png
  openpype/hosts/hiero/api/startup/Icons/retiming.psd
  openpype/hosts/hiero/api/startup/Icons/review.png
  openpype/hosts/hiero/api/startup/Icons/review.psd
  openpype/hosts/hiero/api/startup/Icons/volume.png
  openpype/hosts/hiero/api/startup/Icons/z_layer_bg.png
  openpype/hosts/hiero/api/startup/Icons/z_layer_fg.png
  openpype/hosts/hiero/api/startup/Icons/z_layer_main.png
  openpype/hosts/hiero/api/startup/Python/Startup/SpreadsheetExport.py
  openpype/hosts/hiero/api/startup/Python/Startup/Startup.py
  openpype/hosts/hiero/api/startup/Python/Startup/otioexporter/OTIOExportTask.py
  openpype/hosts/hiero/api/startup/Python/Startup/otioexporter/OTIOExportUI.py
  openpype/hosts/hiero/api/startup/Python/Startup/otioexporter/__init__.py
  openpype/hosts/hiero/api/startup/Python/Startup/project_helpers.py
  openpype/hosts/hiero/api/startup/Python/Startup/selection_tracker.py
  openpype/hosts/hiero/api/startup/Python/Startup/setFrameRate.py
  openpype/hosts/hiero/api/startup/Python/Startup/version_everywhere.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/PimpMySpreadsheet.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/Purge.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/nukeStyleKeyboardShortcuts.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/otioimporter/OTIOImport.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/otioimporter/__init__.py
  openpype/hosts/hiero/api/startup/Python/StartupUI/setPosterFrame.py
  openpype/hosts/hiero/api/startup/TaskPresets/10.5/Processors/hiero.exporters.FnShotProcessor.ShotProcessor/pipeline.xml
  openpype/hosts/hiero/api/startup/TaskPresets/11.1/Processors/hiero.exporters.FnShotProcessor.ShotProcessor/pipeline.xml
  openpype/hosts/hiero/api/startup/TaskPresets/11.2/hiero.exporters.FnShotProcessor.ShotProcessor/pipeline.xml
  openpype/hosts/hiero/plugins/publish/precollect_instances.py
  openpype/hosts/hiero/plugins/publish/precollect_workfile.py
  openpype/hosts/hiero/plugins/publish_old_workflow/precollect_retime.py
  openpype/hosts/hiero/startup/Python/Startup/otioexporter/__init__.py
  openpype/hosts/hiero/startup/Python/Startup/selection_tracker.py
  openpype/plugins/publish/collect_otio_subset_resources.py
  openpype/settings/defaults/system_settings/applications.json
Labels: type: enhancement

#2378 hiero: fix workio and flatten
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/hiero/api/otio/hiero_export.py
  openpype/hosts/hiero/api/workio.py
Labels: type: bug

#2379 hiero: solve custom ocio path
  openpype/hosts/hiero/api/lib.py
Labels: type: bug

#2291 Royal Render: Fix plugin order and OpenPype auto-detection
  openpype/modules/default_modules/royal_render/plugins/publish/collect_default_rr_path.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_rr_path_from_instance.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_sequences_from_job.py
  openpype/modules/default_modules/royal_render/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
  poetry.lock
  pyproject.toml
Labels: type: bug, module: RoyalRender

#2381 Flame: fix ftrack publisher
  openpype/hosts/flame/hooks/pre_flame_setup.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/export_preset/openpype_seg_thumbnails_jpg.xml
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/export_preset/openpype_seg_video_h264.xml
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/modules/__init__.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/modules/app_utils.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/modules/ftrack_lib.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/modules/panel_app.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/modules/uiwidgets.py
  openpype/hosts/flame/utility_scripts/openpype_flame_to_ftrack/openpype_flame_to_ftrack.py
  openpype/settings/defaults/system_settings/applications.json
Labels: type: bug

#2357 Linux : flip updating submodules logic
  tools/build.sh
Labels: backend

#2396 Settings: Fix state change of wrapper label
  openpype/style/style.css
Labels: type: bug

#2385 Flame: moving `utility_scripts` to api folder also with `scripts`
  openpype/hosts/flame/api/scripts/wiretap_com.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/export_preset/openpype_seg_thumbnails_jpg.xml
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/export_preset/openpype_seg_video_h264.xml
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/modules/__init__.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/modules/app_utils.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/modules/ftrack_lib.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/modules/panel_app.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/modules/uiwidgets.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/openpype_flame_to_ftrack.py
  openpype/hosts/flame/api/utility_scripts/openpype_in_flame.py
  openpype/hosts/flame/api/utils.py
  openpype/hosts/flame/hooks/pre_flame_setup.py
Labels: type: enhancement

#2186 OpenPypeV3: Add key parent asset to path templating construction
  openpype/lib/avalon_context.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/tools/workfiles/app.py
  website/docs/admin_settings_project_anatomy.md
Labels: type: enhancement

#2384 Centos 7 dependency compatibility
  Dockerfile.centos7
Labels: type: enhancement, backend

#2394 [Fix][MAYA] Handle message type attribute within CollectLook
  openpype/hosts/maya/plugins/publish/collect_look.py
Labels: host: Maya

#2356 Maya: Add is_static_image_plane and is_in_all_views option in imagePlaneLoader
  openpype/hosts/maya/plugins/load/load_image_plane.py
Labels: type: enhancement, host: Maya

#2403 General: Fix access to environments from default settings
  openpype/settings/lib.py
Labels: type: bug

#2382 Enhancement: Settings: Use project settings values from another project
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/widgets.py
Labels: type: enhancement

#2377 Blender 3: Support auto install for new blender version
  openpype/hosts/blender/hooks/pre_pyside_install.py
Labels: type: enhancement, host: Blender

#2399 Fix: Placeholder Input color set fix
  openpype/tools/utils/widgets.py
Labels: type: bug

#2404 Ftrack: Check existence of object type on recreation
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Labels: type: enhancement, module: Ftrack

#2412 AfterEffects: Variant 2022 is in defaults but missing in schemas
  openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
Labels: type: bug

#2416 Settings UI: Breadcrumbs path does not create new entities
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
  openpype/settings/entities/root_entities.py
  openpype/tools/settings/settings/breadcrumbs_widget.py
Labels: type: bug

#2417 PS: Introduced settings for invalid characters to use in ValidateNaming plugin
  openpype/hosts/photoshop/plugins/publish/validate_naming.py
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Labels: type: bug, host: Photoshop

#2419 Modules: JobQueue module moved one hierarchy level higher
  openpype/modules/base.py
  openpype/modules/job_queue/__init__.py
  openpype/modules/job_queue/job_server/__init__.py
  openpype/modules/job_queue/job_server/job_queue_route.py
  openpype/modules/job_queue/job_server/jobs.py
  openpype/modules/job_queue/job_server/server.py
  openpype/modules/job_queue/job_server/utils.py
  openpype/modules/job_queue/job_server/workers.py
  openpype/modules/job_queue/job_server/workers_rpc_route.py
  openpype/modules/job_queue/job_workers/__init__.py
  openpype/modules/job_queue/job_workers/base_worker.py
  openpype/modules/job_queue/module.py
Labels: type: enhancement

#2420 Settings UI: Hyperlinks to settings
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/window.py
Labels: type: enhancement

#2406 Nuke: baking representations was not additive
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
Labels: type: bug, host: Nuke

#2418 TimersManager: Start timer post launch hook
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/modules/default_modules/ftrack/launch_hooks/post_ftrack_changes.py
  openpype/modules/default_modules/timers_manager/exceptions.py
  openpype/modules/default_modules/timers_manager/launch_hooks/post_start_timer.py
  openpype/modules/default_modules/timers_manager/rest_api.py
  openpype/modules/default_modules/timers_manager/timers_manager.py
Labels: type: enhancement

#2424 General: Environment variables groups
  openpype/cli.py
  openpype/hooks/pre_global_host_data.py
  openpype/lib/applications.py
  openpype/pype_commands.py
  vendor/deadline/custom/plugins/GlobalJobPreLoad.py
Labels: type: enhancement, backend

#2401 General: MongoDB ability to specify replica set groups
  openpype/api.py
  openpype/lib/__init__.py
  openpype/lib/log.py
  openpype/lib/mongo.py
  start.py
Labels: type: enhancement

#2429 Photoshop: New style validations for New publisher
  openpype/hosts/photoshop/plugins/publish/help/validate_instance_asset.xml
  openpype/hosts/photoshop/plugins/publish/help/validate_naming.xml
  openpype/hosts/photoshop/plugins/publish/help/validate_unique_subsets.xml
  openpype/hosts/photoshop/plugins/publish/validate_instance_asset.py
  openpype/hosts/photoshop/plugins/publish/validate_naming.py
  openpype/hosts/photoshop/plugins/publish/validate_unique_subsets.py
  openpype/pipeline/__init__.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/lib.py
  openpype/pipeline/publish/publish_plugins.py
Labels: type: enhancement, host: Photoshop

#2432 Forced cx_freeze to include sqlite3 into build
  setup.py
Labels: backend

#2428 Short Pyblish plugin path
  openpype/lib/plugin_tools.py
Labels: type: bug, backend

#2402 Enhancement: Global cleanup plugin that explicitly remove paths from context
  openpype/plugins/publish/cleanup.py
  openpype/plugins/publish/cleanup_explicit.py
Labels: type: enhancement

#2405 Maya: Replaced PATH usage with vendored oiio path for maketx utility
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: host: Maya

#2434 Harmony: Added new style validations for New Publisher
  openpype/hosts/harmony/plugins/publish/help/validate_audio.xml
  openpype/hosts/harmony/plugins/publish/help/validate_instances.xml
  openpype/hosts/harmony/plugins/publish/help/validate_scene_settings.xml
  openpype/hosts/harmony/plugins/publish/validate_audio.py
  openpype/hosts/harmony/plugins/publish/validate_instances.py
  openpype/hosts/harmony/plugins/publish/validate_scene_settings.py
Labels: type: enhancement, host: Harmony
