Repository ynput/OpenPype, pull requests merged in 2021-04, with the labels that each got.

#1239 Minor settings changes
  pype/settings/entities/dict_mutable_keys_entity.py
  pype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: bug

#1237 Pype global settings
  igniter/tools.py
  pype/settings/constants.py
  pype/settings/defaults/system_settings/general.json
  pype/settings/entities/schemas/system_schema/schema_general.json
  pype/settings/handlers.py
Labels: enhancement

#1208 Pype 3: modules path unification in zips/dirs
  igniter/bootstrap_repos.py
  igniter/tools.py
  start.py
  tests/igniter/test_bootstrap_repos.py
  tests/igniter/test_tools.py
  tools/run_mongo.ps1
Labels: MEDIUM, backend

#1262 Remove unused deprecated environment variables
  openpype/hosts/celaction/api/cli.py
  openpype/tools/standalonepublish/widgets/widget_components.py
Labels: backend

#1255 Create test_build.yml
  .circleci/config.yml
  .github/workflows/test_build.yml
  tools/build.ps1
  tools/create_env.sh
Labels: backend

#1259 Ignore Ftrack url slash
  openpype/modules/ftrack/ftrack_module.py
Labels: backend, bug

#1266 Fix rebranding in Harmony
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/settings/defaults/project_settings/harmony.json
Labels: bug

#1229 Forward compatible app names handling
  pype/lib/profiles_filtering.py
  pype/modules/ftrack/lib/ftrack_app_handler.py
  pype/plugins/harmony/create/create_farm_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/create/create_template.py
  pype/plugins/nuke/publish/collect_writes.py
  pype/plugins/tvpaint/create/create_render_layer.py
  pype/plugins/tvpaint/create/create_render_pass.py
  pype/plugins/tvpaint/create/create_review.py
  pype/tools/launcher/lib.py
Labels: 2x-dev

#1218 Apps tools prep action
  pype/modules/ftrack/actions/action_apps_tools_conversion.py
Labels: 2x-dev

#1242 Avalon schema names
  pype/plugins/global/publish/extract_hierarchy_avalon.py
  pype/tools/assetcreator/app.py
Labels: 2x-dev

#1243 Forward compatible ftrack group
  pype/modules/ftrack/lib/avalon_sync.py
  pype/plugins/ftrack/publish/integrate_hierarchy_ftrack.py
Labels: 2x-dev

#1165 Nuke: workfile template
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/lib.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schema_project_nuke.json
Labels: client, enhancement, host: Nuke

#1268 Igniter qt import
  igniter/__init__.py
Labels: HIGH, backend, bug

#1238 App group in application full name
  openpype/hosts/celaction/api/cli.py
  openpype/lib/applications.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_celaction.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_fusion.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_mayabatch.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_photoshop.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_resolve.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
  openpype/tools/launcher/window.py
Labels: backend

#1269 Documentation for Deadline
  website/docs/assets/deadline_configure_event.png
  website/docs/assets/deadline_configure_plugin.png
  website/docs/assets/deadline_fail.png
  website/docs/assets/ffmpeg_path.png
  website/docs/module_deadline.md
Labels: documentation

#1261 Modifiable dict offset in UI
  openpype/tools/settings/settings/widgets/dict_mutable_widget.py
Labels: enhancement

#1258 Repository: Switch from ssh to https for submodules
  .gitmodules
Labels: backend, bug

#1278 Fix root return in Anatomy
  openpype/lib/anatomy.py
Labels: bug

#1277 Dynamic app variants
  openpype/lib/applications.py
  openpype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_mayabatch.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
  openpype/settings/entities/schemas/system_schema/schema_applications.json
  openpype/settings/lib.py
  openpype/tools/settings/local_settings/apps_widget.py
  openpype/tools/settings/settings/widgets/dict_mutable_widget.py
Labels: enhancement

#1274 AE remove orphaned instance from workfile
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
Labels: bug, host: After Effects

#1275 Fix AE remove orphaned instances
  pype/plugins/aftereffects/publish/collect_render.py
Labels: 2x-dev, bug

#1283 remains of unrenamed pype. namespace
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/fusion/plugins/publish/collect_render_target.py
  openpype/hosts/fusion/scripts/set_rendermode.py
  openpype/hosts/hiero/startup/Python/Startup/Startup.py
  openpype/hosts/photoshop/api/__init__.py
  openpype/hosts/resolve/api/pipeline.py
  openpype/hosts/resolve/hooks/pre_resolve_setup.py
  openpype/scripts/export_maya_ass_job.py
Labels: bug

#1257 Shell prelaunch hook fix
  openpype/hooks/pre_with_windows_shell.py
  openpype/lib/applications.py
Labels: backend

#1286 Fix executables from local settings
  openpype/settings/lib.py
Labels: backend, bug

#1287 Docs: Update Linux build environment
  README.md
  website/docs/dev_build.md
Labels: documentation

#1251 Ftrack api connection fix
  openpype/modules/ftrack/ftrack_server/ftrack_server.py
  openpype/modules/ftrack/ftrack_server/lib.py
Labels: bug

#1282 AE remove orphaned instance from workfile - fix self.stub
  pype/plugins/aftereffects/publish/collect_render.py
Labels: 2x-dev, bug

#1270 Fix clean up of composition must propagate to instance
  openpype/hosts/aftereffects/plugins/publish/remove_publish_highlight.py
Labels: bug, host: After Effects

#1285 OpenPype settings registry
  igniter/bootstrap_repos.py
  igniter/install_dialog.py
  igniter/install_thread.py
  igniter/user_settings.py
  openpype/lib/__init__.py
  openpype/lib/local_settings.py
  start.py
  tests/igniter/test_bootstrap_repos.py
  tests/pype/lib/test_user_settings.py
Labels: HIGH, backend, bug

#1271 add openpype_root to pythonpath
  .github/workflows/test_build.yml
  start.py
Labels: bug

#1279 Fix for the workflow between Blender and Unreal for OpenPype 3.0
  openpype/hooks/pre_python2_vendor.py
  openpype/hosts/blender/api/__init__.py
  openpype/hosts/blender/plugins/load/load_layout.py
  openpype/hosts/unreal/__init__.py
  openpype/hosts/unreal/hooks/pre_workfile_preparation.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/launch_hooks/pre_python2_vendor.py
Labels: bug

#1267 add ftrack documentation
  website/docs/artist_ftrack.md
  website/docs/assets/ftrack/ftrack-api.gif
  website/docs/assets/ftrack/ftrack-api.png
  website/docs/assets/ftrack/ftrack-api2.png
  website/docs/assets/ftrack/ftrack-api3.png
  website/docs/assets/ftrack/ftrack-api4.png
  website/docs/assets/ftrack/ftrack-delivery-icon.png
  website/docs/assets/ftrack/ftrack-login-api.png
  website/docs/assets/ftrack/ftrack-login_1.png
  website/docs/assets/ftrack/ftrack-login_50.png
  website/docs/assets/ftrack/ftrack-login_81.png
  website/docs/assets/ftrack/ftrack_logout.gif
  website/docs/manager_ftrack.md
  website/docs/manager_ftrack_actions.md
  website/docs/module_ftrack.md
Labels: documentation

#1295 Modules using keyring to store credentials
  openpype/modules/clockify/clockify_api.py
  openpype/modules/clockify/constants.py
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/ftrack/lib/credentials.py
  openpype/modules/ftrack/tray/ftrack_tray.py
  openpype/modules/ftrack/tray/login_dialog.py
Labels: backend

#1313 Ftrack custom attributes in bulks
  openpype/modules/ftrack/lib/avalon_sync.py
Labels: bug, module: Ftrack

#1312 Ftrack custom attributes in bulks
  pype/modules/ftrack/lib/avalon_sync.py
Labels: 2x-dev, bug, module: Ftrack

#1318 Blender: Load Scene Settings from Ftrack and New Validator for Object Mode
  openpype/hosts/blender/api/__init__.py
  openpype/hosts/blender/plugins/publish/validate_object_mode.py
Labels: enhancement, host: Blender

#1320 Validate project settings
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/hosts/tvpaint/plugins/publish/validate_project_settings.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: enhancement, host: TV Paint

#1297 Validate project settings
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/validate_project_settings.py
Labels: 2x-dev, enhancement, host: TV Paint

#1307 Blender: Added documentation
  website/docs/artist_hosts_blender.md
  website/docs/assets/blender-model_create_instance.jpg
  website/docs/assets/blender-model_error_details.jpg
  website/docs/assets/blender-model_example.jpg
  website/docs/assets/blender-model_pre_publish.jpg
  website/docs/assets/blender-model_publish_error.jpg
  website/docs/assets/blender-rig_create.jpg
  website/docs/assets/blender-rig_hierarchy_before_publish.jpg
  website/docs/assets/blender-rig_hierarchy_example.jpg
  website/docs/assets/blender-rig_model_setup.jpg
  website/docs/assets/blender-save_modelling_file.jpg
  website/sidebars.js
Labels: documentation, host: Blender

#1325 Set initial project settings
  openpype/hosts/tvpaint/api/__init__.py
  openpype/hosts/tvpaint/api/lib.py
Labels: enhancement, host: TV Paint

#1327 Fix default application names
  openpype/settings/defaults/project_anatomy/attributes.json
Labels: bug

#1299 TV Paint: Set initial project settings.
  pype/hooks/tvpaint/prelaunch.py
  pype/hosts/tvpaint/__init__.py
  pype/hosts/tvpaint/lib.py
Labels: 2x-dev, enhancement, host: TV Paint

#1328 Maya: Make tx option configurable with presets
  pype/plugins/maya/create/create_look.py
Labels: 2x-dev, enhancement, host: Maya

#1332 Maya: Make tx option configurable with presets - OpenPype 3
  openpype/hosts/maya/plugins/create/create_look.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
Labels: enhancement, host: Maya

#1298 TV Paint: Validate mark in and out.
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/validate_marks.py
  pype/plugins/tvpaint/publish/validate_project_settings.py
Labels: 2x-dev, enhancement, host: TV Paint

#1334 TV Paint: Validate mark in and out.
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/hosts/tvpaint/plugins/publish/validate_marks.py
  openpype/hosts/tvpaint/plugins/publish/validate_project_settings.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: enhancement, host: TV Paint

#1302 TVPaint asset name validation
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/validate_asset_name.py
  pype/plugins/tvpaint/publish/validate_workfile_project_name.py
Labels: 2x-dev, enhancement, host: TV Paint

#1329 Pype info window scrollable
  openpype/tools/tray/pype_info_widget.py
Labels: LOW, enhancement

#1340 Fill default values of CreateLook
  openpype/settings/defaults/project_settings/maya.json
Labels: backend, bug

#1341 Add Maya 2022 and Nuke 13 for testing
  openpype/settings/defaults/project_anatomy/attributes.json
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
Labels: backend

#1338 Plugin settings and extract review
  openpype/lib/plugin_tools.py
  openpype/plugins/publish/extract_review.py
Labels: backend, bug

#1350 Mutliselection size calculation fix
  openpype/tools/settings/settings/widgets/multiselection_combobox.py
Labels: backend, bug

#1308 Nuke: freschdesk tickets
  pype/hosts/nuke/lib.py
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/nuke/publish/collect_instances.py
  pype/plugins/nuke/publish/collect_writes.py
  pype/plugins/nuke/publish/validate_rendered_frames.py
Labels: 2x-dev, host: Nuke, hotfix

#1309 Nuke: freschdesk tickets
  openpype/hosts/nuke/api/lib.py
Labels: bug, host: Nuke

#1344 Nuke: freschdesk ticket v2
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/hosts/nuke/plugins/publish/precollect_writes.py
  openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
Labels: bug, host: Nuke

#1354 Remove Python 2 prelaunch hook
  openpype/hooks/pre_python2_vendor.py
  openpype/lib/__init__.py
Labels: bug

#1319 TVPaint asset name validation
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/hosts/tvpaint/plugins/publish/validate_asset_name.py
  openpype/hosts/tvpaint/plugins/publish/validate_workfile_project_name.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: enhancement, host: TV Paint

#1200 Maya: Support for Redshift nodes in looks
  openpype/hosts/maya/plugins/load/load_look.py
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/extract_look.py
  openpype/hosts/maya/plugins/publish/validate_look_sets.py
Labels: MEDIUM, host: Maya, renderer:Redshift

#1367 Ftrack URL cleanup
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/ftrack/lib/credentials.py
  openpype/modules/ftrack/tray/ftrack_tray.py
  openpype/modules/ftrack/tray/login_dialog.py
Labels: enhancement

#1366 Temporary fix of Idle manager on MacOs
  openpype/modules/idle_manager/idle_module.py
Labels: bug

#1368 update cx_freeze
  poetry.lock
  pyproject.toml
Labels: backend

#1372 Maya import bugs
  openpype/hosts/maya/plugins/publish/extract_vrayscene.py
  openpype/hosts/maya/plugins/publish/validate_unreal_mesh_triangulated.py
Labels: bug

#1362 Hiero: fixing source frame from correct object
  pype/plugins/hiero/publish/collect_calculate_retime.py
  pype/plugins/hiero/publish/collect_clips.py
  pype/plugins/hiero/publish/collect_frame_ranges.py
  pype/plugins/hiero/publish/collect_plates.py
  pype/plugins/hiero/publish/collect_review.py
  pype/plugins/hiero/publish/collect_tag_framestart.py
Labels: 2x-dev, bug, host: Hiero

#1369 Python 2 definition in settings
  openpype/hooks/pre_python_2_prelaunch.py
  openpype/lib/applications.py
  openpype/modules/ftrack/launch_hooks/pre_python2_vendor.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json
Labels: enhancement

#1360 Maya: Support for Redshift proxies - backport of #1358 for Pype 2
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/maya/create/create_redshift_proxy.py
  pype/plugins/maya/load/load_redshift_proxy.py
  pype/plugins/maya/publish/extract_redshift_proxy.py
Labels: 2x-dev, host: Maya, renderer:Redshift

#1364 AE added scene duration validation
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
Labels: enhancement, host: After Effects

#1388 Cleanup launcher actions
  openpype/launcher_actions.py
  openpype/modules/launcher_action.py
  openpype/tools/launcher/actions.py
Labels: backend

#1381 Remove OpenPype User Module
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/local_settings.py
  openpype/modules/__init__.py
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/user/__init__.py
  openpype/modules/user/rest_api.py
  openpype/modules/user/user_module.py
  openpype/modules/user/widget_user.py
  openpype/plugins/publish/collect_current_pype_user.py
  openpype/settings/__init__.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
  openpype/tools/settings/local_settings/general_widget.py
  openpype/tools/settings/local_settings/window.py
Labels: enhancement

#1390 Maya: Redshift proxy - fix first frame for sequence
  openpype/hosts/maya/plugins/publish/extract_redshift_proxy.py
Labels: host: Maya, hotfix, renderer:Redshift

#1384 Unreal miss default settings
  openpype/settings/defaults/system_settings/applications.json
Labels: HIGH, bug

#1387 Ftrack handling of save settings
  openpype/lib/applications.py
  openpype/lib/log.py
  openpype/modules/ftrack/event_handlers_server/action_prepare_project.py
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
  openpype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/ftrack/lib/__init__.py
  openpype/modules/ftrack/lib/avalon_sync.py
  openpype/modules/ftrack/lib/constants.py
  openpype/modules/ftrack/lib/custom_attributes.py
  openpype/modules/settings_action.py
  openpype/settings/__init__.py
  openpype/settings/entities/root_entities.py
  openpype/settings/exceptions.py
  openpype/settings/lib.py
  openpype/tools/settings/settings/widgets/categories.py
Labels: enhancement

#1389 Sync Queue GUI filtering
  openpype/modules/sync_server/tray/lib.py
  openpype/modules/sync_server/tray/models.py
  openpype/modules/sync_server/tray/widgets.py
Labels: module: Sitesync

#1399 Maya: Vray - problem getting all file nodes for look publishing
  pype/plugins/maya/publish/collect_look.py
Labels: 2x-dev, host: Maya, hotfix, renderer:Vray

#1383 Add task name to context pop up.
  pype/hosts/maya/__init__.py
Labels: 2x-dev, host: Maya

#1371 Enhance review letterbox feature.
  pype/plugins/global/publish/extract_review.py
Labels: 2x-dev, enhancement

#1363 Feature AE add duration validation
  pype/hosts/aftereffects/__init__.py
  pype/plugins/aftereffects/publish/collect_render.py
  pype/plugins/aftereffects/publish/validate_scene_settings.py
Labels: 2x-dev, client, enhancement, host: After Effects

#1382 FFmpeg gamma argument
  openpype/settings/defaults/project_settings/global.json
Labels: backend, bug

#1400 Enhance review letterbox feature
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/template_rgba_color.json
Labels: enhancement

#1414 Nuke: deadline submission with gpu
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: 2x-dev, enhancement, host: Nuke

#1417 Houdini menu filename
  setup/houdini/MainMenuCommon.xml
Labels: 2x-dev, bug

#1380 MacOs build and install issues
  igniter/bootstrap_repos.py
  igniter/openpype.icns
  igniter/tools.py
  pyproject.toml
  setup.py
  start.py
  tools/build.ps1
  tools/build.sh
  tools/build_dependencies.py
  tools/create_env.ps1
  tools/create_env.sh
  tools/run_mongo.sh
Labels: bug

#1415 PS - group all published instances
  pype/plugins/photoshop/publish/collect_instances.py
Labels: 2x-dev, client, host: Photoshop

#1433 Nuke: fixing undo for loaded mov and sequence
  pype/plugins/nuke/load/load_mov.py
  pype/plugins/nuke/load/load_sequence.py
Labels: 2x-dev, bug, client

#1431 ExtractReview skip empty strings from settings
  openpype/plugins/publish/extract_review.py
Labels: bug

#1432 Nuke: fixing undo for loaded mov and sequence
  openpype/hosts/nuke/plugins/load/load_mov.py
  openpype/hosts/nuke/plugins/load/load_sequence.py
Labels: bug, client

#1426 AE - validation for duration was 1 frame shorter
  pype/hosts/aftereffects/__init__.py
Labels: 2x-dev, bug, host: After Effects

#1430 Bugfix Sync server tweaks
  openpype/modules/sync_server/providers/gdrive.py
  openpype/modules/sync_server/providers/lib.py
  openpype/modules/sync_server/sync_server.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/sync_server/tray/app.py
  openpype/modules/sync_server/tray/models.py
  openpype/modules/sync_server/tray/widgets.py
  openpype/modules/sync_server/utils.py
Labels: bug, module: Sitesync

#1427 AE - validation for duration was 1 frame shorter
  openpype/hosts/aftereffects/api/__init__.py
Labels: bug, host: After Effects

#1424 TVPaint frame range definition
  pype/hosts/tvpaint/lib.py
  pype/plugins/tvpaint/publish/collect_instance_frames.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/extract_sequence.py
  pype/plugins/tvpaint/publish/validate_marks.py
Labels: enhancement

#1428 Bugfix Maya in deadline for OpenPype
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/startup/userSetup.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  vendor/deadline/custom/plugins/GlobalJobPreLoad.py
Labels: bug, host: Maya

#1441 Igniter re-write
  igniter/Poppins/OFL.txt
  igniter/Poppins/Poppins-Black.ttf
  igniter/Poppins/Poppins-BlackItalic.ttf
  igniter/Poppins/Poppins-Bold.ttf
  igniter/Poppins/Poppins-BoldItalic.ttf
  igniter/Poppins/Poppins-ExtraBold.ttf
  igniter/Poppins/Poppins-ExtraBoldItalic.ttf
  igniter/Poppins/Poppins-ExtraLight.ttf
  igniter/Poppins/Poppins-ExtraLightItalic.ttf
  igniter/Poppins/Poppins-Italic.ttf
  igniter/Poppins/Poppins-Light.ttf
  igniter/Poppins/Poppins-LightItalic.ttf
  igniter/Poppins/Poppins-Medium.ttf
  igniter/Poppins/Poppins-MediumItalic.ttf
  igniter/Poppins/Poppins-Regular.ttf
  igniter/Poppins/Poppins-SemiBold.ttf
  igniter/Poppins/Poppins-SemiBoldItalic.ttf
  igniter/Poppins/Poppins-Thin.ttf
  igniter/Poppins/Poppins-ThinItalic.ttf
  igniter/__init__.py
  igniter/install_dialog.py
  igniter/install_thread.py
  igniter/stylesheet.css
  igniter/tools.py
  start.py
Labels: enhancement

#1413 Fix Avalon plugins attribute overrides
  openpype/__init__.py
  openpype/lib/__init__.py
  openpype/lib/plugin_tools.py
Labels: bug

#1442 Faster settings UI loading
  openpype/tools/settings/settings/widgets/dict_mutable_widget.py
Labels: enhancement
