Repository ynput/OpenPype, pull requests merged in 2021-09, with the labels that each got.

#1977 Collectors order
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/plugins/publish/collect_host_name.py
Labels: type: bug

#1939 OpenPype: Add version validation and `--headless` mode and update progress 🔄
  .gitmodules
  igniter/__init__.py
  igniter/bootstrap_repos.py
  igniter/install_dialog.py
  igniter/nice_progress_bar.py
  igniter/tools.py
  igniter/update_thread.py
  igniter/update_window.py
  openpype/cli.py
  start.py
  website/docs/admin_openpype_commands.md
  website/docs/admin_use.md
Labels: type: enhancement, type: documentation, backend

#1981 Last workfile with multiple work templates
  openpype/lib/applications.py
  openpype/tools/workfiles/app.py
Labels: type: bug

#1982 Standalone Publisher: Extract harmony zip handle workfile template
  openpype/hosts/standalonepublisher/plugins/publish/extract_harmony_zip.py
Labels: host: Harmony, host: Standalone

#1959 Global: Settings defined by Addons/Modules
  openpype/modules/__init__.py
  openpype/modules/base.py
  openpype/settings/__init__.py
  openpype/settings/constants.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/lib.py
  openpype/settings/entities/root_entities.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
  openpype/settings/lib.py
Labels: type: enhancement, backend

#1978 Settings UI: Number sliders
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/system_schema/example_schema.json
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/style/style.css
  openpype/widgets/sliders.py
Labels: type: enhancement

#1975 Stop timer was within validator order range.
  openpype/plugins/publish/stop_timer.py
Labels: type: bug

#1992 Nuke thumbnails generated from middle of the sequence
  openpype/hosts/nuke/plugins/publish/extract_thumbnail.py
Labels: type: bug, host: Nuke

#1990 Nuke: last version from path gets correct version
  openpype/lib/path_tools.py
Labels: type: bug, host: Nuke

#2001 Settings UI: Number with configurable steps
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/system_schema/schema_modules.json
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/widgets.py
Labels: type: enhancement

#1996 Moving project folder structure creation out of ftrack module #1989
  openpype/api.py
  openpype/lib/__init__.py
  openpype/lib/path_tools.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_create_project_structure.py
  openpype/settings/__init__.py
Labels: type: enhancement

#1986 Global: Example addons
  openpype/modules/README.md
  openpype/modules/base.py
  openpype/modules/example_addons/example_addon/__init__.py
  openpype/modules/example_addons/example_addon/addon.py
  openpype/modules/example_addons/example_addon/interfaces.py
  openpype/modules/example_addons/example_addon/plugins/publish/example_plugin.py
  openpype/modules/example_addons/example_addon/settings/defaults/project_settings.json
  openpype/modules/example_addons/example_addon/settings/defaults/system_settings.json
  openpype/modules/example_addons/example_addon/settings/dynamic_schemas/project_dynamic_schemas.json
  openpype/modules/example_addons/example_addon/settings/dynamic_schemas/system_dynamic_schemas.json
  openpype/modules/example_addons/example_addon/settings/schemas/project_schemas/main.json
  openpype/modules/example_addons/example_addon/settings/schemas/project_schemas/the_template.json
  openpype/modules/example_addons/example_addon/settings/schemas/system_schemas/main.json
  openpype/modules/example_addons/example_addon/widgets.py
  openpype/modules/example_addons/tiny_addon.py
  openpype/settings/entities/lib.py
  openpype/settings/entities/schemas/system_schema/schema_modules.json
Labels: type: enhancement

#1984 nuke, resolve, hiero: precollector order lest then 0.5
  openpype/hosts/hiero/plugins/publish/precollect_clip_effects.py
  openpype/hosts/hiero/plugins/publish/precollect_instances.py
  openpype/hosts/hiero/plugins/publish/precollect_workfile.py
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/hosts/nuke/plugins/publish/precollect_workfile.py
  openpype/hosts/nuke/plugins/publish/precollect_writes.py
  openpype/hosts/resolve/plugins/publish/precollect_instances.py
  openpype/hosts/resolve/plugins/publish/precollect_workfile.py
Labels: type: bug, host: Nuke, host: Resolve, host: Hiero

#2019 Ftrack: Show OpenPype versions in event server status
  openpype/lib/__init__.py
  openpype/lib/pype_info.py
  openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py
  openpype/modules/default_modules/ftrack/scripts/sub_event_processor.py
  openpype/modules/default_modules/ftrack/scripts/sub_event_status.py
  openpype/modules/default_modules/ftrack/scripts/sub_event_storer.py
Labels: type: enhancement, module: Ftrack

#2016 General: Fix Python 2 breaking line
  openpype/lib/path_tools.py
Labels: type: bug

#2014 Documentation: Ftrack launch argsuments update
  website/docs/admin_openpype_commands.md
  website/docs/module_ftrack.md
Labels: module: Ftrack, type: documentation

#2015 Ftrack: Sync to avalon actions have jobs
  openpype/modules/default_modules/ftrack/event_handlers_server/action_sync_to_avalon.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_sync_to_avalon.py
  openpype/modules/default_modules/ftrack/lib/ftrack_base_handler.py
Labels: type: enhancement, module: Ftrack

#2003 Nuke: Compatibility with Nuke 13
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/publish/extract_ouput_node.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_lut.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
  openpype/hosts/nuke/plugins/publish/extract_thumbnail.py
  openpype/hosts/nuke/plugins/publish/precollect_workfile.py
  openpype/hosts/nuke/startup/write_to_read.py
  openpype/settings/defaults/system_settings/applications.json
Labels: type: enhancement, host: Nuke

#1952 Nuke Quick Start / Tutorial
  website/docs/artist_hosts_nuke_tut.md
  website/docs/assets/nuke_tut/nuke_AnatomyAppsVersions.png
  website/docs/assets/nuke_tut/nuke_AssetLoadOutOfDate.png
  website/docs/assets/nuke_tut/nuke_AssetLoader.png
  website/docs/assets/nuke_tut/nuke_Context.png
  website/docs/assets/nuke_tut/nuke_Create.png
  website/docs/assets/nuke_tut/nuke_Creator.png
  website/docs/assets/nuke_tut/nuke_Load.png
  website/docs/assets/nuke_tut/nuke_ManageVersion.png
  website/docs/assets/nuke_tut/nuke_NukeColor.png
  website/docs/assets/nuke_tut/nuke_Publish.png
  website/docs/assets/nuke_tut/nuke_PyblishCheckBox.png
  website/docs/assets/nuke_tut/nuke_PyblishDialogNuke.png
  website/docs/assets/nuke_tut/nuke_PyblishDialogNukeNoteIntent.png
  website/docs/assets/nuke_tut/nuke_RenderLocalFarm.png
  website/docs/assets/nuke_tut/nuke_RunNukeFtrackAction.png
  website/docs/assets/nuke_tut/nuke_RunNukeFtrackAction_p3.png
  website/docs/assets/nuke_tut/nuke_RunNukeLauncher.png
  website/docs/assets/nuke_tut/nuke_RunNukeLauncher_p2.png
  website/docs/assets/nuke_tut/nuke_ValidateContainers.png
  website/docs/assets/nuke_tut/nuke_WorkFileNamingAnatomy.png
  website/docs/assets/nuke_tut/nuke_WorkFileSaveAs.png
  website/docs/assets/nuke_tut/nuke_WorkfileOnStartup.png
  website/docs/assets/nuke_tut/nuke_WriteNode.png
  website/docs/assets/nuke_tut/nuke_WriteNodeCreated.png
  website/docs/assets/nuke_tut/nuke_WriteNodeReview.png
  website/docs/assets/nuke_tut/nuke_WriteSettings.png
  website/docs/assets/nuke_tut/nuke_versionless.png
  website/sidebars.js
Labels: type: documentation

#2022 Console interpreter: Handle invalid sizes on initialization
  openpype/modules/default_modules/python_console_interpreter/window/widgets.py
Labels: type: enhancement

#2033 PYPE-1892_tag-fix
  openpype/hosts/hiero/api/tags.py
Labels: type: bug

#2017 General: Staging icon
  openpype/hosts/maya/api/shader_definition_editor.py
  openpype/lib/pype_info.py
  openpype/modules/default_modules/avalon_apps/avalon_app.py
  openpype/modules/default_modules/clockify/widgets.py
  openpype/modules/default_modules/ftrack/tray/login_dialog.py
  openpype/modules/default_modules/muster/widget_login.py
  openpype/modules/default_modules/python_console_interpreter/window/widgets.py
  openpype/modules/default_modules/sync_server/tray/app.py
  openpype/modules/default_modules/timers_manager/widget_user_idle.py
  openpype/plugins/load/delivery.py
  openpype/resources/__init__.py
  openpype/style/__init__.py
  openpype/tools/launcher/actions.py
  openpype/tools/launcher/window.py
  openpype/tools/project_manager/project_manager/window.py
  openpype/tools/settings/settings/style/__init__.py
  openpype/tools/standalonepublish/app.py
  openpype/tools/tray/pype_info_widget.py
  openpype/tools/tray/pype_tray.py
Labels: type: enhancement

#2009 Modules: Connect method is not required
  openpype/modules/base.py
  openpype/modules/default_modules/avalon_apps/avalon_app.py
  openpype/modules/default_modules/clockify/clockify_module.py
  openpype/modules/default_modules/deadline/deadline_module.py
  openpype/modules/default_modules/log_viewer/log_view_module.py
  openpype/modules/default_modules/muster/muster.py
  openpype/modules/default_modules/project_manager_action.py
  openpype/modules/default_modules/python_console_interpreter/module.py
  openpype/modules/default_modules/settings_module/settings_action.py
  openpype/modules/default_modules/slack/slack_module.py
  openpype/modules/default_modules/sync_server/sync_server_module.py
Labels: type: enhancement

#2040 Workfiles tool: Task selection
  openpype/lib/pype_info.py
  openpype/tools/workfiles/app.py
Labels: type: bug

#2037 Ftrack: Delete old versions missing settings key
  openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_old_versions.py
Labels: type: bug, module: Ftrack

#2034 PYPE-1835_Create-Read-From-Rendered---Typo
  openpype/hosts/nuke/api/lib.py
Labels: type: bug

#2041 Added possibility to configure of synchronization of workfile version…
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement, host: Nuke

#2036 General: Task types in profiles
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/lib/plugin_tools.py
  openpype/lib/profiles_filtering.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/defaults/project_settings/slack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_workfile_build.json
  openpype/settings/entities/schemas/projects_schema/schemas/template_workfile_options.json
Labels: type: enhancement

#2006 Bugfix/webpublisher task type
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
Labels: type: bug

#2032 FFmpeg: Subprocess arguments as list
  openpype/hosts/harmony/plugins/publish/extract_render.py
  openpype/hosts/photoshop/plugins/publish/extract_review.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py
  openpype/lib/__init__.py
  openpype/lib/execute.py
  openpype/plugins/publish/extract_jpeg_exr.py
  openpype/plugins/publish/extract_otio_audio_tracks.py
  openpype/plugins/publish/extract_otio_review.py
  openpype/plugins/publish/extract_otio_trimming_video.py
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/extract_review_slate.py
Labels: type: bug

#2038 Loader & Library loader: Use tools from OpenPype
  openpype/hosts/fusion/api/menu.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/hiero/api/menu.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/houdini/startup/MainMenuCommon.xml
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/customize.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/resolve/api/menu.py
  openpype/hosts/resolve/api/pipeline.py
  openpype/modules/default_modules/avalon_apps/avalon_app.py
  openpype/modules/default_modules/sync_server/tray/models.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
  openpype/tools/libraryloader/__init__.py
  openpype/tools/libraryloader/__main__.py
  openpype/tools/libraryloader/app.py
  openpype/tools/libraryloader/lib.py
  openpype/tools/libraryloader/widgets.py
  openpype/tools/loader/__init__.py
  openpype/tools/loader/__main__.py
  openpype/tools/loader/app.py
  openpype/tools/loader/images/default_thumbnail.png
  openpype/tools/loader/lib.py
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/delegates.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/models.py
  openpype/tools/utils/views.py
  openpype/tools/utils/widgets.py
Labels: type: enhancement

#2044 Settings UI: Deffered set value on entity
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/dict_mutable_widget.py
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/lib.py
Labels: type: enhancement

#2042 Settings UI: Project view enhancements
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/style/style.css
Labels: type: enhancement

#2028 WebserverModule: Removed interface of webserver module
  openpype/modules/default_modules/avalon_apps/avalon_app.py
  openpype/modules/default_modules/muster/muster.py
  openpype/modules/default_modules/timers_manager/timers_manager.py
  openpype/modules/default_modules/webserver/interfaces.py
  openpype/modules/default_modules/webserver/webserver_module.py
Labels: type: enhancement

#2024 TimersManager: Removed interface of timers manager
  openpype/modules/default_modules/clockify/clockify_module.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/timers_manager/interfaces.py
  openpype/modules/default_modules/timers_manager/timers_manager.py
Labels: type: enhancement

#2045 Removed shell flag in subprocess call
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py
  openpype/plugins/publish/extract_jpeg_exr.py
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/extract_review_slate.py
Labels: type: bug

#2046 FFmpeg: Split command to list does not work
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
  openpype/lib/__init__.py
  openpype/lib/execute.py
  openpype/plugins/publish/extract_jpeg_exr.py
  openpype/plugins/publish/extract_otio_audio_tracks.py
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/extract_review_slate.py
Labels: type: bug, severity: HIGH

#2052 Nuke: proxy mode validator
  openpype/hosts/nuke/plugins/publish/validate_proxy_mode.py
Labels: type: enhancement

#2043 Loader: Families filtering
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
  openpype/settings/entities/schemas/projects_schema/schemas/template_publish_families.json
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/app.py
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2056 Differentiate jpg sequences from thumbnail
  openpype/hosts/nuke/plugins/load/load_sequence.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
Labels: type: bug

#2057 Hiero: Editorial fixes
  openpype/hosts/hiero/otio/hiero_export.py
  openpype/hosts/hiero/plugins/publish/precollect_instances.py
  openpype/hosts/hiero/plugins/publish/precollect_workfile.py
  openpype/plugins/publish/collect_hierarchy.py
  openpype/plugins/publish/collect_otio_frame_ranges.py
  openpype/plugins/publish/collect_otio_review.py
  openpype/plugins/publish/collect_otio_subset_resources.py
Labels: type: bug, severity: HIGH

#2039 Settings for Nuke IncrementScriptVersion
  openpype/hosts/nuke/plugins/publish/increment_script_version.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement, host: Nuke

#2049 Ftrack: Removed ftrack interface
  openpype/modules/default_modules/clockify/clockify_module.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/ftrack/interfaces.py
  openpype/modules/default_modules/ftrack/lib/__init__.py
  openpype/modules/default_modules/ftrack/lib/settings.py
Labels: type: enhancement, module: Ftrack

#2030 Adding predefined project folders creation in PM
  openpype/tools/project_manager/project_manager/window.py
Labels: type: enhancement

#2058 Timers manger: Typo fix
  openpype/modules/default_modules/timers_manager/timers_manager.py
Labels: type: bug

#2054 General: Startup validations
  openpype/plugins/publish/validate_ffmpeg_installed.py
  start.py
Labels: type: enhancement, backend

#2008 Settings: Flag project as deactivated and hide from tools' view
  openpype/modules/default_modules/sync_server/sync_server_module.py
  openpype/modules/default_modules/sync_server/tray/app.py
  openpype/modules/default_modules/sync_server/tray/models.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
  openpype/settings/defaults/project_anatomy/attributes.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json
  openpype/tools/launcher/models.py
  openpype/tools/launcher/window.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/settings/local_settings/projects_widget.py
  openpype/tools/settings/settings/widgets.py
  openpype/tools/standalonepublish/widgets/widget_asset.py
Labels: type: enhancement, type: feature

#2063 Fix Sync Queue when project disabled
  openpype/modules/default_modules/sync_server/tray/app.py
  openpype/modules/default_modules/sync_server/tray/models.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
Labels: type: bug, module: Sitesync

#2051 Tools: add support for pyenv on windows
  tools/build_win_installer.ps1
Labels: type: enhancement, backend

#2068 Maya: Validate setdress top group
  openpype/hosts/maya/plugins/create/create_setdress.py
  openpype/hosts/maya/plugins/publish/validate_setdress_root.py
Labels: type: enhancement, host: Maya, client, type: feature

#1955 Maya: Enable publishing render attrib sets (e.g. V-Ray Displacement) with model
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/plugins/inventory/import_modelrender.py
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: host: Maya, client, type: feature

#2069 Project manager: Filter first item after selection of project
  openpype/tools/project_manager/project_manager/__init__.py
  openpype/tools/project_manager/project_manager/constants.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/project_manager/project_manager/window.py
Labels: type: enhancement, severity: LOW

#2077 Nuke UI scaling
  openpype/hosts/nuke/__init__.py
  openpype/lib/applications.py
Labels: host: Nuke

#1979 SyncServer: Dropbox Provider
  openpype/modules/default_modules/sync_server/providers/abstract_provider.py
  openpype/modules/default_modules/sync_server/providers/dropbox.py
  openpype/modules/default_modules/sync_server/providers/gdrive.py
  openpype/modules/default_modules/sync_server/providers/lib.py
  openpype/modules/default_modules/sync_server/providers/resources/dropbox.png
  openpype/modules/default_modules/sync_server/sync_server.py
  openpype/modules/default_modules/sync_server/utils.py
  openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
  poetry.lock
  pyproject.toml
Labels: type: enhancement, module: Sitesync

#2085 Blender: fix texture missing when publishing blend files
  openpype/hosts/blender/plugins/publish/extract_blend.py
Labels: type: bug

#2081 Blender: fixed Curves with modifiers in Rigs
  openpype/hosts/blender/plugins/load/load_rig.py
Labels: type: bug

#2083 General: Startup validations oiio tool path fix on linux
  start.py
Labels: type: bug

#2080 Tray UI: Message box about missing settings defaults
  openpype/settings/__init__.py
  openpype/tools/tray/pype_tray.py
Labels: type: enhancement

#2088 Added choosing different dirmap mapping if workfile synched locally
  openpype/hosts/maya/api/__init__.py
  openpype/modules/default_modules/sync_server/sync_server_module.py
Labels: type: enhancement, host: Maya, module: Sitesync

#2084 General: Remove IdleManager module
  openpype/modules/default_modules/idle_manager/__init__.py
  openpype/modules/default_modules/idle_manager/idle_module.py
  openpype/modules/default_modules/idle_manager/idle_threads.py
  openpype/modules/default_modules/idle_manager/interfaces.py
  openpype/modules/default_modules/timers_manager/idle_threads.py
  openpype/modules/default_modules/timers_manager/timers_manager.py
  openpype/modules/default_modules/timers_manager/widget_user_idle.py
Labels: type: enhancement

#2079 Tray UI: Show menu where first click happened
  openpype/tools/tray/pype_tray.py
Labels: type: enhancement

#2091 Added running configurable disk mapping command before start of OP
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/settings/handlers.py
  start.py
  website/docs/admin_settings_system.md
  website/docs/assets/settings/settings_system_general.png
Labels: type: feature
