Repository ynput/OpenPype, pull requests merged in 2021-10, with the labels that each got.

#2064 Nuke: Adding `still` image family workflow
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/create/create_write_still.py
  openpype/hosts/nuke/plugins/load/load_image.py
  openpype/hosts/nuke/plugins/publish/extract_render_local.py
  openpype/hosts/nuke/plugins/publish/precollect_writes.py
  openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/defaults/project_settings/nuke.json
Labels: type: enhancement

#2070 Use CRF for burnin when available
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_review.py
  openpype/scripts/otio_burnin.py
Labels: type: enhancement

#1965 Use crf for quality in burnin
  pype/plugins/global/publish/extract_burnin.py
  pype/plugins/global/publish/extract_review.py
  pype/scripts/otio_burnin.py
Labels: type: enhancement, 2x-dev

#2062 Maya: validate authorized loaded plugins
  openpype/hosts/maya/plugins/publish/validate_loaded_plugin.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement, host: Maya

#2078 Global: add global validators to settings
  openpype/hosts/maya/plugins/publish/validate_instance_in_context.py
  openpype/hosts/nuke/plugins/publish/validate_instance_in_context.py
  openpype/plugins/publish/collect_avalon_entities.py
  openpype/plugins/publish/start_timer.py
  openpype/plugins/publish/stop_timer.py
  openpype/plugins/publish/validate_containers.py
  openpype/plugins/publish/validate_intent.py
  openpype/plugins/publish/validate_version.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement

#2073 SFTP provider
  openpype/modules/default_modules/sync_server/providers/abstract_provider.py
  openpype/modules/default_modules/sync_server/providers/lib.py
  openpype/modules/default_modules/sync_server/providers/resources/sftp.png
  openpype/modules/default_modules/sync_server/providers/sftp.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
  poetry.lock
  pyproject.toml
  website/docs/assets/site_sync_project_sftp_settings.png
  website/docs/assets/site_sync_sftp_project_setting_not_forced.png
  website/docs/assets/site_sync_sftp_settings_local.png
  website/docs/assets/site_sync_sftp_system.png
  website/docs/module_site_sync.md
Labels: module: Sitesync, type: feature

#2095 General: Cloud mongo ca certificate issue
  igniter/tools.py
  openpype/lib/mongo.py
  openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py
  start.py
Labels: type: bug, severity: HIGH

#2087 TVPaint: Creator use context from workfile
  openpype/hosts/tvpaint/api/plugin.py
Labels: type: bug, host: TV Paint

#2103 Ftrack: Project settings save custom attributes skip unknown attributes
  openpype/modules/default_modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/ftrack/lib/__init__.py
  openpype/modules/default_modules/ftrack/lib/constants.py
Labels: type: bug, module: Ftrack

#2104 Settings UI: Project model refreshing and sorting
  openpype/tools/settings/settings/constants.py
  openpype/tools/settings/settings/widgets.py
Labels: type: enhancement

#2100 Fix broken import in sftp provider
  openpype/modules/default_modules/sync_server/providers/sftp.py
Labels: type: bug

#2096 Delivery Action Files Sequence fix
  openpype/lib/delivery.py
Labels: host: Nuke

#2109 TVPaint: Behavior name of loop also accept repeat
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
Labels: type: bug, host: TV Paint

#2110 Add startup script for Houdini Core.
  openpype/hosts/houdini/startup/scripts/houdinicore.py
Labels: type: bug

#1625 Maya: Set the pixel aspect on new launch.
  pype/hosts/maya/lib.py
Labels: type: bug, host: Maya, 2x-dev, convert to 3.0

#1552 Customizable subset name for workfiles.
  pype/lib/plugin_tools.py
  pype/plugins/aftereffects/publish/collect_workfile.py
  pype/plugins/harmony/publish/collect_workfile.py
  pype/plugins/maya/publish/collect_scene.py
  pype/plugins/nuke/publish/collect_workfile.py
  pype/plugins/photoshop/publish/collect_workfile.py
Labels: type: enhancement, host: Nuke, host: Maya, host: Harmony, host: Photoshop, 2x-dev, host: After Effects, convert to 3.0

#2191 Project Manager: Fix copying of tasks
  openpype/tools/project_manager/project_manager/model.py
Labels: type: bug
