Repository ynput/OpenPype, pull requests merged in 2021-11, with the labels that each got.

#2072 Houdini: simple HDA workflow
  openpype/hosts/houdini/api/plugin.py
  openpype/hosts/houdini/plugins/create/create_hda.py
  openpype/hosts/houdini/plugins/load/load_hda.py
  openpype/hosts/houdini/plugins/publish/collect_active_state.py
  openpype/hosts/houdini/plugins/publish/collect_instances.py
  openpype/hosts/houdini/plugins/publish/extract_hda.py
  openpype/hosts/houdini/plugins/publish/validate_bypass.py
  openpype/plugins/publish/integrate_new.py
  website/docs/artist_hosts_houdini.md
Labels: host: Houdini, type: feature

#2185 Usage of tools code
  openpype/hosts/houdini/api/usd.py
  openpype/hosts/maya/api/__init__.py
  openpype/plugins/publish/validate_containers.py
  openpype/tools/launcher/window.py
  openpype/tools/pyblish_pype/control.py
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2184 Settings: Dictionary based on project roots
  openpype/settings/entities/__init__.py
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/color_entity.py
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
  openpype/settings/entities/root_entities.py
  openpype/settings/entities/schemas/README.md
Labels: type: enhancement

#2179 Subset name: Be able to pass asset document to get subset name
  openpype/hosts/standalonepublisher/plugins/publish/collect_bulk_mov_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile.py
  openpype/lib/__init__.py
  openpype/lib/plugin_tools.py
Labels: type: enhancement

#2196 Delivery: Check 'frame' key in template for sequence delivery
  openpype/lib/delivery.py
Labels: type: enhancement

#2170 Maya : Colorspace configuration
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/menu.py
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Labels: host: Maya, type: feature

#2174 Maya: Aspect ratio
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/menu.py
Labels: type: bug, host: Maya

#2204 Ftrack: Replace Queue with deque in event handlers logic
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_asset.py
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Labels: type: enhancement, module: Ftrack

#2203 Ftrack: Fill missing ftrack id on mongo project
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Labels: type: bug, module: Ftrack

#2199 Maya : Validate mesh ngons
  openpype/hosts/maya/plugins/publish/validate_mesh_ngons.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement

#2205 Tools: Workfiles tool don't use avalon widgets
  openpype/tools/mayalookassigner/app.py
  openpype/tools/utils/lib.py
  openpype/tools/workfiles/app.py
Labels: type: bug

#2176 Add validate active site button to sync queue on a project
  openpype/modules/default_modules/sync_server/providers/abstract_provider.py
  openpype/modules/default_modules/sync_server/resources/refresh.png
  openpype/modules/default_modules/sync_server/sync_server.py
  openpype/modules/default_modules/sync_server/sync_server_module.py
  openpype/modules/default_modules/sync_server/tray/models.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
  openpype/tests/mongo_performance.py
  website/docs/artist_tools.md
Labels: module: Sitesync

#2183 Blender: Fix trying to pack an image when the shader node has no texture
  openpype/hosts/blender/plugins/publish/extract_blend.py
Labels: type: bug, host: Blender

#2168 Blender: Added support for audio
  openpype/hosts/blender/plugins/load/load_audio.py
Labels: host: Blender, type: feature

#2193 Settings: Site sync project settings improvement
  openpype/modules/default_modules/sync_server/providers/dropbox.py
  openpype/modules/default_modules/sync_server/providers/gdrive.py
  openpype/modules/default_modules/sync_server/providers/local_drive.py
  openpype/modules/default_modules/sync_server/providers/sftp.py
  openpype/settings/entities/__init__.py
  openpype/settings/entities/dict_immutable_keys_entity.py
Labels: backend, module: Sitesync

#2200 Tools: New select context dialog
  openpype/cli.py
  openpype/pype_commands.py
  openpype/tools/context_dialog/__init__.py
  openpype/tools/context_dialog/window.py
  openpype/tools/utils/constants.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/models.py
  openpype/tools/workfiles/app.py
  openpype/tools/workfiles/model.py
Labels: type: enhancement

#2207 Fix - different command used for Linux and Mac OS
  start.py
Labels: type: bug

#2210 Maya : multiple subsets review broken
  openpype/hosts/maya/api/lib.py
Labels: type: bug, host: Maya

#2211 Maya : validate unique names
  openpype/plugins/publish/validate_unique_names.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement

#2208 Tools: OpenPype stylesheet in workfiles tool
  openpype/style/data.json
  openpype/style/images/checkbox_checked.png
  openpype/style/images/checkbox_checked_disabled.png
  openpype/style/images/checkbox_checked_focus.png
  openpype/style/images/checkbox_checked_hover.png
  openpype/style/images/checkbox_indeterminate.png
  openpype/style/images/checkbox_indeterminate_disabled.png
  openpype/style/images/checkbox_indeterminate_focus.png
  openpype/style/images/checkbox_indeterminate_hover.png
  openpype/style/images/checkbox_unchecked.png
  openpype/style/images/checkbox_unchecked_disabled.png
  openpype/style/images/checkbox_unchecked_focus.png
  openpype/style/images/checkbox_unchecked_hover.png
  openpype/style/pyqt5_resources.py
  openpype/style/pyside2_resources.py
  openpype/style/resources.qrc
  openpype/style/style.css
  openpype/tools/utils/host_tools.py
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2219 Tools: Center loader and library loader on show
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/app.py
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2212 Maya : Validate shape zero
  openpype/hosts/maya/plugins/publish/validate_shape_zero.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement

#2220 Add both side availability on Site Sync sites to Loader
  openpype/modules/default_modules/sync_server/tray/delegates.py
  openpype/modules/default_modules/sync_server/tray/lib.py
  openpype/modules/default_modules/sync_server/tray/models.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/constants.py
Labels: type: enhancement, module: Sitesync

#2177 Maya: review viewport settings
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
  openpype/plugins/publish/extract_review.py
  openpype/vendor/python/common/capture.py
Labels: type: bug, host: Maya

#2198 Dirmap in Nuke
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/startup/menu.py
  openpype/lib/path_tools.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schema_project_nuke.json
Labels: type: enhancement, host: Nuke

#2232 Pyblish Tool: Fix targets handling
  openpype/tools/pyblish_pype/control.py
Labels: type: bug

#2235 Style: Fix transparent image in style
  openpype/style/images/transparent.png
  openpype/style/pyqt5_resources.py
  openpype/style/pyside2_resources.py
Labels: type: enhancement

#2239 General: Skip module directories without init file
  openpype/modules/base.py
Labels: type: enhancement

#2234 Fix - enum for color coding in PS
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Labels: type: bug, host: Photoshop

#2236 Python 2: Unicode to string conversion
  openpype/lib/python_module_tools.py
Labels: type: bug

#2238 General: Static interfaces
  openpype/modules/base.py
  openpype/modules/default_modules/settings_module/interfaces.py
  openpype/modules/default_modules/timers_manager/timers_manager.py
  openpype/modules/example_addons/example_addon/addon.py
  openpype/modules/example_addons/example_addon/interfaces.py
  openpype/modules/example_addons/example_addon/widgets.py
  openpype/modules/interfaces.py
Labels: type: enhancement

#2224 Modules: Module can add cli commands
  openpype/cli.py
  openpype/modules/README.md
  openpype/modules/base.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/example_addons/example_addon/addon.py
  openpype/pype_commands.py
Labels: type: enhancement

#2237 Added queue for studio processing in PS
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver_cli.py
  openpype/settings/defaults/project_settings/photoshop.json
Labels: type: bug, host: Photoshop

#2225 Add a "following workfile versioning" option on publish
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/validate_version.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: type: enhancement

#2188 Add command line way of running site sync server
  openpype/cli.py
  openpype/lib/local_settings.py
  openpype/modules/default_modules/sync_server/providers/local_drive.py
  openpype/modules/default_modules/sync_server/sync_server.py
  openpype/modules/default_modules/sync_server/sync_server_module.py
  openpype/modules/default_modules/sync_server/tray/widgets.py
  openpype/plugins/publish/integrate_new.py
  openpype/pype_commands.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schema_project_syncserver.json
  website/docs/assets/site_sync_always_on.png
  website/docs/module_site_sync.md
Labels: type: documentation, module: Sitesync

#2214 Ftrack: Base event fix of 'get_project_from_entity' method
  openpype/modules/default_modules/ftrack/lib/ftrack_base_handler.py
Labels: type: bug, module: Ftrack

#2061 Basic Royal Render Integration ✨
  openpype/cli.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/ftrack/plugins/publish/collect_local_ftrack_creds.py
  openpype/modules/default_modules/royal_render/__init__.py
  openpype/modules/default_modules/royal_render/api.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_default_rr_path.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_rr_path_from_instance.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_sequences_from_job.py
  openpype/modules/default_modules/royal_render/royal_render_module.py
  openpype/modules/default_modules/royal_render/rr_job.py
  openpype/modules/default_modules/royal_render/rr_root/README.md
  openpype/modules/default_modules/royal_render/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
  openpype/pype_commands.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
  poetry.lock
  tests/openpype/modules/default_modules/royal_render/test_rr_job.py
Labels: module: RoyalRender, type: feature

#2243 Tools: Subset manager in OpenPype
  openpype/style/style.css
  openpype/tools/subsetmanager/README.md
  openpype/tools/subsetmanager/__init__.py
  openpype/tools/subsetmanager/model.py
  openpype/tools/subsetmanager/widgets.py
  openpype/tools/subsetmanager/window.py
  openpype/tools/utils/host_tools.py
Labels: type: enhancement

#2245 Ftrack: Session creation and Prepare project
  openpype/modules/default_modules/ftrack/ftrack_module.py
Labels: type: bug, module: Ftrack

#2250 Ftrack: Sync project ftrack id cache issue
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Labels: type: bug, module: Ftrack

#2254 Loader load version issue
  openpype/tools/loader/model.py
Labels: type: bug

#2221 Added endpoint for configured extensions
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver_cli.py
Labels: type: enhancement, backend

#2247 Burnins: Support mxf metadata
  openpype/scripts/otio_burnin.py
Labels: type: bug

#2251 Tools: Tasks widget
  openpype/tools/context_dialog/window.py
  openpype/tools/launcher/models.py
  openpype/tools/launcher/widgets.py
  openpype/tools/launcher/window.py
  openpype/tools/utils/constants.py
  openpype/tools/utils/tasks_widget.py
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2255 Tools: SceneInventory in OpenPype
  openpype/tools/sceneinventory/__init__.py
  openpype/tools/sceneinventory/lib.py
  openpype/tools/sceneinventory/model.py
  openpype/tools/sceneinventory/switch_dialog.py
  openpype/tools/sceneinventory/view.py
  openpype/tools/sceneinventory/widgets.py
  openpype/tools/sceneinventory/window.py
  openpype/tools/utils/host_tools.py
Labels: type: enhancement

#2261 Tools: Select Context dialog attribute fix
  openpype/tools/context_dialog/window.py
  openpype/tools/workfiles/app.py
Labels: type: bug

#2259 LookAssigner: Fix tool reopen
  openpype/tools/mayalookassigner/app.py
Labels: type: bug, host: Maya

#2195 Maya: texture colorspace modes in looks
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/extract_look.py
  openpype/settings/defaults/project_settings/standalonepublisher.json
Labels: type: bug, host: Maya

#2260 Maya: Render publishing fails on linux
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: type: bug

#2264 limiting validator to specific editorial hosts
  openpype/plugins/publish/validate_editorial_asset_name.py
Labels: type: bug

#2197 Maya: Support for configurable AOV separator characters
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
  tools/run_mongo.ps1
Labels: type: bug, host: Maya

#2265 Tools: Assets widget
  openpype/tools/context_dialog/window.py
  openpype/tools/launcher/window.py
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/app.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/assets_widget.py
  openpype/tools/utils/host_tools.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/tasks_widget.py
  openpype/tools/utils/widgets.py
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2262 SceneInventory: Choose loader in asset switcher
  openpype/style/style.css
  openpype/tools/sceneinventory/switch_dialog.py
  openpype/tools/sceneinventory/widgets.py
Labels: type: enhancement

#2258 Standalone: editorial not publishing thumbnails on all subsets
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_resources.py
Labels: type: bug

#2244 Tools: Creator in OpenPype
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/constants.py
  openpype/style/style.css
  openpype/tools/creator/__init__.py
  openpype/tools/creator/constants.py
  openpype/tools/creator/model.py
  openpype/tools/creator/widgets.py
  openpype/tools/creator/window.py
  openpype/tools/publisher/constants.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/utils/host_tools.py
Labels: type: enhancement

#2266 Tools: Parenting of tools in Nuke and Hiero
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/hiero/api/menu.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/menu.py
Labels: type: bug, host: Nuke, host: Hiero

#2269 Ftrack: Remove unused clean component plugin
  openpype/modules/default_modules/ftrack/plugins/publish/integrate_remove_components.py
Labels: type: enhancement, module: Ftrack

#2157 OpenPypeV3: add key task type, task shortname and user to path templating construction
  openpype/hosts/harmony/plugins/publish/collect_farm_render.py
  openpype/hosts/harmony/plugins/publish/collect_palettes.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_harmony_scenes.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_harmony_zips.py
  openpype/hosts/standalonepublisher/plugins/publish/extract_harmony_zip.py
  openpype/lib/anatomy.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_anatomy/templates.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_templates.json
  openpype/settings/lib.py
  openpype/tools/workfiles/app.py
  website/docs/admin_settings_project_anatomy.md
Labels: type: feature

#2272 Version handling fixes
  igniter/bootstrap_repos.py
  openpype/cli.py
  openpype/pype_commands.py
  openpype/tools/repack_version.py
  tests/unit/igniter/test_bootstrap_repos.py
  website/docs/admin_openpype_commands.md
Labels: type: bug, backend

#2274 Bug: fix variable name _asset_id in workfiles application
  openpype/tools/workfiles/app.py
Labels: type: bug

#2267 Houdini: Add experimental tools action
  openpype/hosts/houdini/startup/MainMenuCommon.xml
Labels: type: enhancement, host: Houdini

#2278 Nuke: Anatomy fill data use task as dictionary
  openpype/api.py
  openpype/hosts/nuke/api/lib.py
  openpype/lib/avalon_context.py
Labels: type: bug, host: Nuke

#2280 Deadline: Fix publish targets
  openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: bug

#2268 Royal Render: Support for rr channels in separate dirs
  openpype/modules/default_modules/royal_render/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
Labels: type: enhancement, module: RoyalRender

#2277 StandalonePublisher: Remove unused plugin ExtractHarmonyZip
  openpype/hosts/standalonepublisher/plugins/publish/extract_harmony_zip.py
Labels: type: enhancement, host: Standalone

#1980 TVPaint: Load workfile from published.
  openpype/hosts/tvpaint/plugins/load/load_workfile.py
Labels: host: TV Paint, type: feature

#2281 FFmpeg: Execute ffprobe using list of arguments instead of string command
  openpype/lib/vendor_bin_utils.py
Labels: type: bug

#2285 New Publisher: Fix mapping of indexes
  openpype/tools/publisher/widgets/list_view_widgets.py
Labels: type: bug

#2071 Ftrack: Sync incoming links to inputs.
  pype/modules/ftrack/events/event_sync_to_avalon.py
  pype/modules/ftrack/lib/__init__.py
  pype/modules/ftrack/lib/avalon_sync.py
  pype/modules/ftrack/lib/custom_attributes.py
Labels: type: enhancement, 2x-dev

#2287 Ftrack: Synchronize input links
  openpype/lib/avalon_context.py
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Labels: type: enhancement, module: Ftrack

#2284 Alternate site for site sync doesnt work for sequences
  openpype/modules/default_modules/sync_server/providers/sftp.py
  openpype/modules/default_modules/sync_server/sync_server_module.py
Labels: type: bug, module: Sitesync

#2294 Nuke: inventory update removes all loaded read nodes
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/hosts/nuke/plugins/load/load_image.py
  openpype/hosts/nuke/plugins/load/load_script_precomp.py
Labels: type: bug

#2295 Maya: Deadline - fix limit groups
  openpype/modules/default_modules/deadline/plugins/publish/submit_maya_deadline.py
Labels: type: bug, host: Maya, module: Deadline

#2209 TVPaint: Workers rendering
  openpype/hosts/tvpaint/lib.py
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
  openpype/hosts/tvpaint/worker/__init__.py
  openpype/hosts/tvpaint/worker/worker.py
  openpype/hosts/tvpaint/worker/worker_job.py
  openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_instances.py
  openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_workfile_data.py
  openpype/hosts/webpublisher/plugins/publish/extract_tvpaint_workfile.py
  openpype/hosts/webpublisher/plugins/publish/others_cleanup_job_root.py
  openpype/hosts/webpublisher/plugins/publish/validate_tvpaint_workfile_data.py
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/modules/default_modules/ftrack/plugins/publish/collect_username.py
  openpype/modules/default_modules/job_queue/__init__.py
  openpype/modules/default_modules/job_queue/job_server/__init__.py
  openpype/modules/default_modules/job_queue/job_server/job_queue_route.py
  openpype/modules/default_modules/job_queue/job_server/jobs.py
  openpype/modules/default_modules/job_queue/job_server/server.py
  openpype/modules/default_modules/job_queue/job_server/utils.py
  openpype/modules/default_modules/job_queue/job_server/workers.py
  openpype/modules/default_modules/job_queue/job_server/workers_rpc_route.py
  openpype/modules/default_modules/job_queue/job_workers/__init__.py
  openpype/modules/default_modules/job_queue/job_workers/base_worker.py
  openpype/modules/default_modules/job_queue/module.py
  openpype/plugins/publish/collect_modules.py
  openpype/settings/defaults/project_settings/webpublisher.json
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
Labels: type: enhancement, host: TV Paint

#2298 Project Manager: Added ability to delete project
  openpype/tools/project_manager/project_manager/images/bin.png
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/project_manager/project_manager/style.py
  openpype/tools/project_manager/project_manager/widgets.py
  openpype/tools/project_manager/project_manager/window.py
Labels: type: enhancement

#2192 Store typed version dependencies for workfiles
  openpype/plugins/publish/collect_scene_loaded_versions.py
  openpype/plugins/publish/collect_scene_version.py
  openpype/plugins/publish/integrate_inputlinks.py
  openpype/tools/assetlinks/__init__.py
  openpype/tools/assetlinks/widgets.py
  openpype/tools/loader/widgets.py
Labels: type: feature

#2306 Workfiles tool: Fix task formatting
  openpype/tools/workfiles/app.py
Labels: type: bug

#2304 Tools: Cleanup of unused classes
  openpype/hosts/houdini/api/usd.py
  openpype/tools/assetcreator/app.py
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/app.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/assets_widget.py
  openpype/tools/utils/constants.py
  openpype/tools/utils/delegates.py
  openpype/tools/utils/models.py
  openpype/tools/utils/tasks_widget.py
  openpype/tools/utils/views.py
  openpype/tools/utils/widgets.py
Labels: type: enhancement

#2311 nuke: do not multiply representation on class method
  openpype/hosts/nuke/api/plugin.py
Labels: type: bug

#2309 General: Run process log stderr as info log level
  openpype/lib/execute.py
Labels: type: enhancement

#2312 Deadline timeout and logging
  igniter/tools.py
  vendor/deadline/custom/plugins/GlobalJobPreLoad.py
Labels: type: bug, module: Deadline

#2314 InputLinks: Typo in "inputLinks" key
  openpype/lib/avalon_context.py
Labels: type: bug

#2302 Delivery: Fix delivery paths created on windows
  openpype/lib/delivery.py
Labels: type: bug

#2324 docs[website]: Add Ellipse Studio (logo) as an OpenPype contributor
  website/src/css/custom.css
  website/src/pages/index.js
  website/static/img/ellipse-studio.png
Labels: type: documentation

#2323 Hiero: Add experimental tools action
  openpype/hosts/hiero/api/menu.py
Labels: type: enhancement, host: Hiero

#2326 Fix - provider icons are pulled from a folder
  openpype/modules/default_modules/sync_server/README.md
  openpype/tools/utils/lib.py
Labels: type: bug, module: Sitesync

#2322 Input links: Cleanup and unification of differences
  openpype/lib/avalon_context.py
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
  openpype/plugins/publish/integrate_inputlinks.py
  openpype/tools/assetlinks/widgets.py
Labels: type: enhancement, severity: HIGH

#2317 General: Don't validate vendor bin with executing them
  start.py
Labels: type: enhancement, severity: HIGH

#2330 Hiero: fixing multiple templates at a hierarchy parent
  openpype/hosts/hiero/api/plugin.py
Labels: type: bug

#2331 nuke: bake preset single input exception
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
Labels: type: bug

#2140 Nuke: Alembic model workflow
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/plugins/create/create_model.py
  openpype/hosts/nuke/plugins/load/load_model.py
  openpype/hosts/nuke/plugins/publish/collect_model.py
  openpype/hosts/nuke/plugins/publish/extract_model.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: feature

#2305 General: Reduce vendor imports
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/fusion/api/lib.py
  openpype/hosts/fusion/plugins/inventory/set_tool_color.py
  openpype/hosts/fusion/scripts/set_rendermode.py
  openpype/hosts/fusion/utility_scripts/switch_ui.py
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/load/actions.py
  openpype/hosts/maya/plugins/publish/collect_yeti_rig.py
  openpype/hosts/maya/plugins/publish/submit_maya_muster.py
  openpype/hosts/maya/plugins/publish/validate_assembly_transforms.py
  openpype/hosts/maya/plugins/publish/validate_muster_connection.py
  openpype/hosts/photoshop/api/__init__.py
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/default_modules/deadline/plugins/publish/validate_deadline_connection.py
  openpype/modules/default_modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
  openpype/modules/default_modules/royal_render/plugins/publish/collect_sequences_from_job.py
  openpype/plugins/load/copy_file.py
  openpype/plugins/load/copy_file_path.py
  openpype/plugins/load/delete_old_versions.py
  openpype/plugins/load/open_djv.py
  openpype/plugins/load/open_file.py
  openpype/tools/assetcreator/model.py
  openpype/widgets/message_window.py
  openpype/widgets/popup.py
  openpype/widgets/project_settings.py
Labels: type: enhancement

#2328 General: FFprobe error exception contain original error message
  openpype/plugins/publish/extract_review.py
Labels: type: enhancement

#2334 Timers Manager: Disable auto stop timer on linux platform
  openpype/modules/default_modules/timers_manager/timers_manager.py
Labels: type: bug

#1374 Support multiple Ftrack reviews.
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
Labels: type: enhancement, module: Ftrack, 2x-dev, convert to 3.0

#2094 Tvpaint: Deadline
  pype/plugins/tvpaint/publish/collect_deadline_submission.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_json_data.py
  pype/plugins/tvpaint/publish/collect_layer_behaviors.py
  pype/plugins/tvpaint/publish/collect_tvpaint_info.py
  pype/plugins/tvpaint/publish/collect_workfile.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/extract_deadline_submission.py
  pype/plugins/tvpaint/publish/extract_layer_exposure_frames.py
  pype/plugins/tvpaint/publish/extract_sequence.py
  pype/plugins/tvpaint/publish/submit_tvpaint_deadline.py
Labels: 2x-dev

#2296 Settings UI use OpenPype styles
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/settings/__init__.py
  openpype/tools/settings/local_settings/apps_widget.py
  openpype/tools/settings/local_settings/projects_widget.py
  openpype/tools/settings/local_settings/widgets.py
  openpype/tools/settings/local_settings/window.py
  openpype/tools/settings/settings/__init__.py
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/dict_conditional.py
  openpype/tools/settings/settings/dict_mutable_widget.py
  openpype/tools/settings/settings/images/__init__.py
  openpype/tools/settings/settings/images/add.png
  openpype/tools/settings/settings/images/confirm.png
  openpype/tools/settings/settings/images/down.png
  openpype/tools/settings/settings/images/mask.png
  openpype/tools/settings/settings/images/remove.png
  openpype/tools/settings/settings/images/up.png
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/lib.py
  openpype/tools/settings/settings/list_item_widget.py
  openpype/tools/settings/settings/style/__init__.py
  openpype/tools/settings/settings/style/style.css
  openpype/tools/settings/settings/widgets.py
  openpype/tools/settings/settings/window.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/widgets.py
  openpype/widgets/nice_checkbox.py
Labels: type: feature

#2321 Maya: configurable model top level validation
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/validate_model_content.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: host: Maya

#2320 Maya: configurable model top level validation
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/validate_model_content.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: host: Maya

#2338 General: OpenPype default modules hierarchy
  openpype/modules/base.py
  openpype/modules/default_modules/settings_module/__init__.py
  openpype/modules/launcher_action.py
  openpype/modules/project_manager_action.py
  openpype/modules/settings_action.py
  openpype/modules/standalonepublish_action.py
Labels: type: enhancement

#2345 Assets Widget: Clear model on project change
  openpype/tools/utils/assets_widget.py
Labels: type: enhancement

#2343 Maya Look Assigner: Fix Python 3 compatibility
  openpype/tools/mayalookassigner/models.py
Labels: type: bug, host: Maya

#2340 Tools: Use Qt context on tools show
  openpype/tools/utils/host_tools.py
Labels: type: bug
