Repository ynput/OpenPype, pull requests merged in 2021-06, with the labels that each got.

#1616 MacOs Fix launch of standalone publisher
  openpype/modules/standalonepublish_action.py
Labels: backend, bug

#1614 Maya capture 'isolate_view' fix + minor corrections
  pype/hosts/maya/lib.py
  pype/plugins/maya/publish/extract_playblast.py
  pype/plugins/maya/publish/extract_thumbnail.py
  pype/vendor/capture_gui/__init__.py
  pype/vendor/capture_gui/accordion.py
  pype/vendor/capture_gui/app.py
  pype/vendor/capture_gui/colorpicker.py
  pype/vendor/capture_gui/lib.py
  pype/vendor/capture_gui/plugin.py
  pype/vendor/capture_gui/plugins/cameraplugin.py
  pype/vendor/capture_gui/plugins/codecplugin.py
  pype/vendor/capture_gui/plugins/defaultoptionsplugin.py
  pype/vendor/capture_gui/plugins/displayplugin.py
  pype/vendor/capture_gui/plugins/genericplugin.py
  pype/vendor/capture_gui/plugins/ioplugin.py
  pype/vendor/capture_gui/plugins/panzoomplugin.py
  pype/vendor/capture_gui/plugins/rendererplugin.py
  pype/vendor/capture_gui/plugins/resolutionplugin.py
  pype/vendor/capture_gui/plugins/timeplugin.py
  pype/vendor/capture_gui/plugins/viewportplugin.py
  pype/vendor/capture_gui/presets.py
  pype/vendor/capture_gui/resources/config.png
  pype/vendor/capture_gui/resources/import.png
  pype/vendor/capture_gui/resources/reset.png
  pype/vendor/capture_gui/resources/save.png
  pype/vendor/capture_gui/tokens.py
  pype/vendor/capture_gui/vendor/Qt.py
  pype/vendor/capture_gui/vendor/__init__.py
  pype/vendor/capture_gui/version.py
Labels: bug

#1612 'Delivery action' report fix + typos
  openpype/lib/delivery.py
  openpype/modules/ftrack/event_handlers_user/action_delivery.py
  openpype/plugins/load/delivery.py
Labels: bug

#1613 'Delivery action' report fix +typos
  pype/modules/ftrack/actions/action_delivery.py
Labels: bug

#1618 Settings template skip paths support wrappers
  openpype/settings/entities/lib.py
Labels: backend, bug

#1619 Bug: Initialize blessed term only in console mode
  start.py
Labels: HIGH, bug

#1621 Sync server Qt layout fix
  openpype/modules/sync_server/tray/app.py
  openpype/modules/sync_server/tray/widgets.py
Labels: backend, bug

#1620 Console Listener on Python 2 fix
  openpype/modules/webserver/host_console_listener.py
  openpype/modules/webserver/webserver_module.py
Labels: backend, bug

#1622 Tray style
  openpype/style/style.css
  openpype/tools/tray/pype_info_widget.py
  openpype/tools/tray/pype_tray.py
Labels: enhancement

#1623 Loader and Library loader enhancements
  openpype/tools/workfiles/app.py
Labels: enhancement

#1624 Launcher tool style
  openpype/style/style.css
  openpype/tools/launcher/actions.py
  openpype/tools/launcher/widgets.py
  openpype/tools/launcher/window.py
Labels: enhancement

#1627 Faster hierarchical values push
  openpype/modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py
Labels: backend, enhancement, module: Ftrack

#1626 Faster hierarchical values push
  pype/modules/ftrack/events/action_push_frame_values_to_task.py
Labels: 2x-dev, backend, enhancement, module: Ftrack

#1630 Standalone style
  openpype/style/style.css
  openpype/tools/standalonepublish/app.py
  openpype/tools/standalonepublish/widgets/widget_component_item.py
  openpype/tools/standalonepublish/widgets/widget_components_list.py
  openpype/tools/standalonepublish/widgets/widget_drop_empty.py
  openpype/tools/standalonepublish/widgets/widget_family.py
Labels: enhancement

#1284 3.0.0 - curated changelog
  CHANGELOG.md
Labels: documentation

#1631 Settings permissions
  openpype/cli.py
  openpype/modules/settings_action.py
  openpype/pype_commands.py
  openpype/tools/settings/__init__.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/window.py
Labels: backend, enhancement

#1632 Admin menu and project manager
  openpype/lib/__init__.py
  openpype/lib/local_settings.py
  openpype/modules/__init__.py
  openpype/modules/avalon_apps/avalon_app.py
  openpype/modules/base.py
  openpype/modules/project_manager_action.py
  openpype/modules/settings_action.py
  openpype/resources/icons/eye.png
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/schema_modules.json
  openpype/style/style.css
  openpype/tools/project_manager/project_manager/window.py
  openpype/tools/settings/__init__.py
  openpype/tools/settings/lib.py
  openpype/tools/settings/local_settings/general_widget.py
  openpype/tools/settings/settings/window.py
  openpype/tools/tray/pype_tray.py
  openpype/widgets/__init__.py
  openpype/widgets/password_dialog.py
Labels: enhancement

#1634 Tray doubleclick
  openpype/modules/base.py
  openpype/modules/launcher_action.py
  openpype/tools/tray/pype_tray.py
Labels: enhancement

#1636 Use poetry to build / publish OpenPype wheel
  .gitignore
  pyproject.toml
  setup.py
  tools/build_dependencies.py
Labels: backend

#1637 Duplicated ftrack session in collector
  openpype/modules/ftrack/plugins/publish/collect_ftrack_api.py
Labels: HIGH, backend, bug

#1602 OpenPype CI releases
  .github/workflows/nightly_merge.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  pyproject.toml
  tools/ci_tools.py
Labels: backend

#1652 Fix missing dbm python module
  setup.py
Labels: HIGH, backend, bug

#1646 Add asset on task item
  openpype/tools/project_manager/project_manager/model.py
Labels: backend, bug

#1645 Project manager save and queue
  openpype/tools/project_manager/project_manager/model.py
Labels: backend, bug

#1644 New project anatomy values
  openpype/settings/handlers.py
Labels: backend, bug

#1648 Transparent branches in view on Mac
  openpype/style/style.css
Labels: bug

#1649 #1333 - added tooltip hints to Pyblish buttons
  openpype/tools/pyblish_pype/window.py
Labels: enhancement

#1660 Mac launch arguments fix
  openpype/hooks/pre_mac_launch.py
  openpype/modules/standalonepublish_action.py
Labels: backend, bug

#1650 StandalonePublisher: adding exception for adding `delete` tag to repre
  pype/plugins/standalonepublisher/publish/collect_instance_resources.py
Labels: 2x-dev, HIGH, client, convert to 3.0, enhancement, hotfix

#1671 Settings list race condifiton and mutable dict list conversion
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/tools/settings/settings/list_item_widget.py
Labels: HIGH, backend, bug

#1683 #683 - Validate Frame Range in Standalone Publisher
  openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py
  openpype/settings/defaults/project_settings/standalonepublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json
Labels: client, enhancement, host: Standalone

#1669 Project Manger: Default name column width
  openpype/tools/project_manager/project_manager/view.py
Labels: LOW, enhancement

#1680 #683 - Validate frame range in Standalone Publisher
  pype/plugins/standalonepublisher/publish/validate_frame_ranges.py
Labels: 2x-dev, client, host: Standalone

#1664 Remove publish highlight icon in AE
  pype/plugins/aftereffects/create/create_render.py
Labels: 2x-dev, bug, convert to 3.0, host: After Effects

#1667 Remove outline in stylesheet
  openpype/style/style.css
Labels: LOW, enhancement

#1662 TVPaint custom subset template
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
  openpype/hosts/tvpaint/plugins/create/create_render_pass.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile.py
  openpype/lib/plugin_tools.py
  openpype/plugin.py
  openpype/settings/defaults/project_settings/global.json
Labels: backend, bug, enhancement, host: TV Paint

#1668 StandalonePublisher: instance data attribute `keepSequence`
  pype/plugins/standalonepublisher/publish/collect_instance_resources.py
Labels: bug, client, convert to 3.0, hotfix

#1556 Add docstrings to Project manager tool
  openpype/tools/project_manager/__init__.py
  openpype/tools/project_manager/project_manager/constants.py
  openpype/tools/project_manager/project_manager/delegates.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/project_manager/project_manager/window.py
Labels: backend

#1689 Sort applications and tools alphabetically in Settings UI
  openpype/settings/entities/enum_entity.py
Labels: LOW, enhancement

#1675 Ftrack subprocess handle of stdout/stderr
  openpype/modules/ftrack/ftrack_server/socket_thread.py
Labels: HIGH, backend, bug

#1694 OpenPype style in modules
  openpype/modules/clockify/clockify_api.py
  openpype/modules/clockify/widgets.py
  openpype/modules/ftrack/tray/login_dialog.py
  openpype/modules/muster/widget_login.py
  openpype/modules/timers_manager/widget_user_idle.py
Labels: enhancement

#1697 update dependencies
  .gitignore
  poetry.lock
  pyproject.toml
Labels: MEDIUM, backend

#1703 Log Viewer with OpenPype style
  openpype/modules/log_viewer/tray/app.py
  openpype/modules/log_viewer/tray/widgets.py
  openpype/style/style.css
Labels: LOW, enhancement

#1702 Scrolling in OpenPype info widget
  openpype/tools/tray/pype_info_widget.py
Labels: LOW, enhancement

#1705 Standalone publisher Thumbnail export args
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
  openpype/settings/defaults/project_settings/standalonepublisher.json
Labels: backend, bug, host: Standalone

#1707 Nuke: broken publishing rendered frames
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
Labels: HIGH, bug, client, host: Nuke

#1714 Maya: Extract review hotfix
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: HIGH, bug, host: Maya, hotfix

#1713 Maya: Extract review hotfix - 2.x backport
  pype/plugins/maya/publish/extract_playblast.py
  pype/plugins/maya/publish/extract_thumbnail.py
Labels: HIGH, bug, host: Maya, hotfix

#1711 Settings: Imageio improving granularity
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Labels: bug, client, host: Nuke

#1715 Sync main 2.x back to 2.x develop
  CHANGELOG.md
  pype/plugins/maya/publish/extract_playblast.py
  pype/plugins/maya/publish/extract_thumbnail.py
  pype/plugins/standalonepublisher/publish/collect_instance_resources.py
Labels: 2x-dev

#1654 Maya: Split model content validator
  pype/plugins/maya/publish/validate_model_content.py
  pype/plugins/maya/publish/validate_model_top_group.py
Labels: 2x-dev, MEDIUM, client, convert to 3.0, host: Maya

#1716 Default subset template for TVPaint review and workfile families
  openpype/settings/defaults/project_settings/global.json
Labels: backend, bug, host: TV Paint

#1709 1698 Nuke: Prerender Frame Range by default
  pype/hosts/nuke/lib.py
  pype/plugins/nuke/create/create_write_prerender.py
  pype/plugins/nuke/publish/collect_instances.py
  pype/plugins/nuke/publish/collect_writes.py
  pype/plugins/nuke/publish/validate_rendered_frames.py
Labels: 2x-dev, client, host: Nuke, hotfix

#1695 Smoother edges of color triangle
  openpype/widgets/color_widgets/color_inputs.py
  openpype/widgets/color_widgets/color_triangle.py
Labels: LOW, enhancement

#1710 global: removing obsolete ftrack validator plugin
  pype/plugins/global/publish/validate_custom_ftrack_attributes.py
Labels: 2x-dev, hotfix, module: Ftrack

#1717 Subset template and TVPaint subset template docs
  website/docs/admin_hosts_tvpaint.md
  website/docs/artist_hosts_tvpaint.md
  website/docs/assets/tvp_create_review.png
  website/docs/project_settings/assets/global_tools_creator_subset_template.png
  website/docs/project_settings/settings_project_global.md
  website/sidebars.js
Labels: documentation, enhancement

#1724 TVPaint use layer name for default variant
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
Labels: backend, bug, host: TV Paint

#1725 Autoupdate launcher
  openpype/tools/launcher/models.py
  openpype/tools/launcher/widgets.py
  openpype/tools/launcher/window.py
Labels: backend, enhancement

#1727 Tools names forwards compatibility
  pype/lib/applications.py
Labels: 2x-dev, HIGH, backend, bug

#1732 Ftrack sync status
  openpype/modules/ftrack/event_handlers_server/event_version_to_task_statuses.py
Labels: backend, bug, module: Ftrack

#1733 Launcher project changes
  openpype/tools/launcher/lib.py
  openpype/tools/launcher/widgets.py
  openpype/tools/launcher/window.py
Labels: backend, bug

#1734 Ftrack missing custom attribute message
  openpype/modules/ftrack/lib/avalon_sync.py
Labels: backend, bug, module: Ftrack

#1737 Local settings UI crash on missing defaults
  openpype/modules/settings_action.py
  openpype/tools/settings/local_settings/window.py
Labels: backend, bug

#1736 Validate containers settings
  openpype/settings/defaults/project_settings/harmony.json
  openpype/settings/defaults/project_settings/houdini.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
  openpype/settings/entities/schemas/projects_schema/schema_project_houdini.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: backend, enhancement

#1679 Application without executables
  openpype/lib/applications.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant_items.json
  openpype/settings/lib.py
  openpype/tools/settings/local_settings/apps_widget.py
Labels: backend, bug, host: UE

#1735 TVPaint white background on thumbnail
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: bug, host: TV Paint

#1708 Toggle Ftrack upload in StandalonePublisher
  openpype/hosts/standalonepublisher/plugins/publish/collect_context.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_instances.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_matchmove.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/standalonepublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  website/docs/admin_hosts_aftereffects.md
  website/docs/assets/ftrack/ftrack-collect-advanced.png
  website/docs/assets/ftrack/ftrack-collect-main.png
  website/docs/module_ftrack.md
Labels: client, enhancement, host: Standalone, module: Ftrack

#1726 PS - added loader from sequence
  openpype/hosts/photoshop/plugins/lib.py
  openpype/hosts/photoshop/plugins/load/load_image.py
  openpype/hosts/photoshop/plugins/load/load_image_from_sequence.py
Labels: client, enhancement, host: Photoshop

#1739 Settings Hosts enum
  openpype/settings/entities/__init__.py
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_unchangables.json
Labels: backend, enhancement

#1745 Backend acre module commit update
  poetry.lock
Labels: backend, bug

#1741 Nuke: fixing render creator for no selection format failing
  openpype/hosts/nuke/plugins/create/create_write_prerender.py
  openpype/hosts/nuke/plugins/create/create_write_render.py
Labels: HIGH, bug, host: Nuke

#1750 celaciton: audio subset changed data structure
  pype/plugins/celaction/publish/collect_audio.py
Labels: HIGH, client, hotfix

#1754 celaction fixes
  pype/plugins/celaction/publish/collect_celaction_instances.py
  pype/plugins/celaction/publish/submit_celaction_deadline.py
Labels: HIGH, client, hotfix

#1755 TVPaint ftrack family
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
Labels: backend, host: TV Paint, module: Ftrack

#1757 Application executables with environment variables
  openpype/lib/applications.py
Labels: backend, enhancement

#1759 Added AE explicitly to ValidateVersion
  pype/plugins/global/publish/validate_version.py
Labels: 2x-dev, bug, client

#1761 Standalone publisher thumbnail extractor fix
  openpype/hosts/standalonepublisher/plugins/publish/extract_thumbnail.py
Labels: HIGH, backend, bug, host: Standalone

#1766 Workfile tool widths
  openpype/tools/workfiles/app.py
Labels: LOW, enhancement

#1764 Settings UI with refresh button
  openpype/tools/settings/settings/categories.py
Labels: backend, bug

#1767 Project specific environments
  openpype/lib/applications.py
Labels: HIGH, backend, bug

#1769 Settings UI copy/paste
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/root_entities.py
  openpype/tools/settings/settings/base.py
Labels: backend, enhancement

#1765 Push hierarchical attributes care about task parent changes
  pype/modules/ftrack/events/event_push_frame_values_to_task.py
Labels: 2x-dev, backend, enhancement, module: Ftrack

#1763 Push hierarchical attributes care about task parent changes
  openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
  openpype/modules/ftrack/lib/__init__.py
  openpype/modules/ftrack/lib/custom_attributes.py
Labels: backend, enhancement, module: Ftrack

#1758 Anatomy others templates don't cause crash
  openpype/lib/anatomy.py
Labels: backend, bug

#1776 Settings application use python 2 only where needed
  openpype/lib/applications.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/lib.py
  openpype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_photoshop.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  openpype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
Labels: backend, enhancement

#1775 FFprobe streams order
  openpype/lib/vendor_bin_utils.py
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/extract_review_slate.py
Labels: HIGH, backend, bug

#1753 Settings schema without prefill
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/lib.py
  openpype/settings/entities/root_entities.py
Labels: backend, enhancement

#1772 Fix - single file files are str only, cast it to list to count properly
  openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py
Labels: bug
