Repository ynput/OpenPype, pull requests merged in 2021-01, with the labels that each got.

#851 Deadline as Pype Module
  pype/modules/__init__.py
  pype/modules/deadline/deadline_module.py
  pype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  pype/modules/deadline/plugins/publish/submit_maya_deadline.py
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  pype/modules/deadline/plugins/publish/submit_publish_job.py
  pype/modules/deadline/plugins/publish/validate_deadline_connection.py
  pype/plugins/maya/create/create_render.py
  requirements.txt
Labels: backend

#859 Remove presets getter
  pype/lib/__init__.py
  pype/lib/anatomy.py
  pype/lib/config.py
Labels: backend

#847 Next task update with settings
  pype/modules/ftrack/events/event_next_task_update.py
  pype/modules/ftrack/events/event_version_to_task_statuses.py
  pype/settings/defaults/project_settings/ftrack.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
Labels: enhancement

#870 Extension key in templates
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/global/publish/integrate_thumbnail.py
  pype/plugins/houdini/publish/extract_alembic.py
  pype/plugins/houdini/publish/extract_vdb_cache.py
  pype/plugins/standalonepublisher/publish/collect_context.py
  pype/settings/defaults/project_anatomy/templates.json
Labels: backend

#872 Remove get_application usage
  pype/hosts/maya/__init__.py
  pype/hosts/nuke/lib.py
Labels: backend

#737 Hiero publish Audio refactory
  pype/hosts/hiero/__init__.py
  pype/hosts/hiero/lib.py
  pype/hosts/hiero/plugin.py
  pype/plugins/hiero/publish/collect_instances.py
  pype/plugins/hiero/publish/collect_review.py
  pype/plugins/hiero/publish/extract_audio.py
  pype/plugins/hiero/publish/validate_audio.py
Labels: 2x-dev, enhancement, host: Hiero

#883 Pype: add vendor folder
  vendor/README.md
Labels: backend

#885 fix(nuke): improving of hashing path
  pype/plugins/nuke/load/load_sequence.py
Labels: HIGH, bug, hotfix

#892 Hiero: cut videos with correct secons
  pype/plugins/hiero/publish/extract_review_cutup.py
Labels: hotfix

#894 fix(photoshop): missing template.psd and prelaunch hook
  pype/hooks/photoshop/prelaunch.py
  pype/hosts/photoshop/template.psd
Labels: enhancement, hotfix

#876 Feature #817 syncserver gui
  pype/modules/sync_server/providers/gdrive.py
  pype/modules/sync_server/providers/resources/gdrive.png
  pype/modules/sync_server/providers/resources/studio.png
  pype/modules/sync_server/sync_server.py
  pype/modules/sync_server/tray/app.py
  pype/plugins/global/publish/integrate_new.py
  pype/tools/settings/settings/style/style.css
Labels: enhancement

#889 Get the correct file path for the updated mov.
  pype/plugins/nuke/load/load_mov.py
Labels: bug

#884 Packaging Task for outsorcing
  pype/hosts/nuke/__init__.py
  pype/hosts/nuke/lib.py
  pype/lib/__init__.py
  pype/lib/packaging.py
  pype/modules/ftrack/events/action_pack_workfiles.py
  setup/nuke/nuke_path/init.py
  setup/nuke/nuke_path/menu.py
Labels: 2x-dev, enhancement

#898 Launcher fix actions discover
  pype/tools/launcher/models.py
  pype/tools/launcher/widgets.py
  pype/tools/launcher/window.py
Labels: bug

#896 Launcher fix actions discover
  pype/tools/launcher/models.py
  pype/tools/launcher/widgets.py
  pype/tools/launcher/window.py
Labels: 2x-dev, bug

#893 TVPaint audio/sound loader
  pype/plugins/tvpaint/load/load_sound.py
Labels: 2x-dev

#903 TVPaint without layer ids
  pype/plugins/tvpaint/create/create_render_pass.py
  pype/plugins/tvpaint/load/load_reference_image.py
  pype/plugins/tvpaint/publish/collect_instances.py
  pype/plugins/tvpaint/publish/collect_workfile_data.py
  pype/plugins/tvpaint/publish/extract_sequence.py
  pype/plugins/tvpaint/publish/validate_duplicated_layer_names.py
  pype/plugins/tvpaint/publish/validate_missing_layer_names.py
  pype/plugins/tvpaint/publish/validate_render_pass_group.py
Labels: 2x-dev

#904 TVPaint without layer ids
  pype/hosts/tvpaint/plugins/create/create_render_pass.py
  pype/hosts/tvpaint/plugins/load/load_reference_image.py
  pype/hosts/tvpaint/plugins/publish/collect_instances.py
  pype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  pype/hosts/tvpaint/plugins/publish/extract_sequence.py
  pype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
  pype/hosts/tvpaint/plugins/publish/validate_missing_layer_names.py
  pype/hosts/tvpaint/plugins/publish/validate_render_pass_group.py
Labels: enhancement

#899 Anatomy updates from pype setup
  pype/lib/anatomy.py
Labels: enhancement

#891 Clone review session with children.
  pype/modules/ftrack/actions/action_clone_review_session.py
Labels: 2x-dev, enhancement, ftrack

#908 Clone review session with children.
  pype/modules/ftrack/events/action_clone_review_session.py
  pype/settings/defaults/project_settings/ftrack.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_ftrack.json
Labels: enhancement

#881 Harmony deadline submission
  pype/hosts/harmony/__init__.py
  pype/hosts/harmony/js/PypeHarmony.js
  pype/hosts/harmony/js/publish/CollectFarmRender.js
  pype/plugins/global/publish/submit_publish_job.py
  pype/plugins/harmony/create/create_farm_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/publish/collect_audio.py
  pype/plugins/harmony/publish/collect_farm_render.py
  pype/plugins/harmony/publish/collect_instances.py
  pype/plugins/harmony/publish/collect_palettes.py
  pype/plugins/harmony/publish/collect_scene.py
  pype/plugins/harmony/publish/collect_workfile.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/harmony/publish/extract_workfile.py
  pype/plugins/harmony/publish/submit_harmony_deadline..py
  pype/plugins/harmony/publish/validate_scene_settings.py
Labels: 2x-dev, enhancement, host: Harmony

#911 Harmony deadline submission
  pype/hooks/harmony/pre_launch_args.py
  pype/hosts/harmony/__init__.py
  pype/hosts/harmony/js/PypeHarmony.js
  pype/hosts/harmony/js/publish/CollectFarmRender.js
  pype/modules/deadline/plugins/publish/submit_publish_job.py
  pype/plugins/harmony/create/create_farm_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/publish/collect_audio.py
  pype/plugins/harmony/publish/collect_farm_render.py
  pype/plugins/harmony/publish/collect_instances.py
  pype/plugins/harmony/publish/collect_palettes.py
  pype/plugins/harmony/publish/collect_scene.py
  pype/plugins/harmony/publish/collect_workfile.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/harmony/publish/extract_workfile.py
  pype/plugins/harmony/publish/submit_harmony_deadline..py
  pype/plugins/harmony/publish/validate_scene_settings.py
  pype/settings/defaults/project_settings/harmony.json
  pype/tools/settings/settings/gui_schemas/projects_schema/schema_project_harmony.json
Labels: enhancement

#909 Nuke: baking mov with correct colorspace inherited from write
  pype/hosts/nuke/lib.py
Labels: 2x-dev, host: Nuke, hotfix

#913 nuke: bake writes colorspace
  pype/hosts/nuke/api/lib.py
Labels: bug, host: Nuke

#920 Fix PS - Create from single layer
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
Labels: 2x-dev

#921 Photoshop fix - create called on single layer
  pype/modules/websocket_server/stubs/photoshop_server_stub.py
Labels: bug

#933 nuke: missing `file` knob update
  pype/plugins/nuke/load/load_image.py
Labels: bug, host: Nuke, hotfix

#935 nuke: missing `file` knob update
  pype/hosts/nuke/plugins/load/load_image.py
Labels: bug, host: Nuke

#940 escape executables in pre launch hooks
  pype/hooks/aftereffects/pre_launch_args.py
  pype/hooks/harmony/pre_launch_args.py
  pype/hooks/photoshop/pre_launch_args.py
  pype/hooks/photoshop/prelaunch.py
Labels: bug
