Repository ynput/OpenPype, pull requests merged in 2021-02, with the labels that each got.

#944 AE - added prelaunch hook for opening last or workfile from template
  pype/hooks/aftereffects/prelaunch.py
  pype/hosts/aftereffects/template.aep
Labels: 2x-dev, host: After Effects

#941 PS - safer handling of loading of workfile
  pype/hooks/photoshop/prelaunch.py
Labels: 2x-dev

#938 Maya: Handling Arnold referenced AOVs
  pype/hosts/maya/expected_files.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/publish/collect_render.py
Labels: 2x-dev, host: Maya

#945 AE - added prelaunch hook for opening last or workfile from template
  pype/hooks/aftereffects/pre_launch_args.py
  pype/hosts/aftereffects/template.aep
Labels: enhancement

#954 DJV new version arguments
  pype/modules/ftrack/actions/action_djvview.py
  pype/plugins/global/load/open_djv.py
Labels: 2x-dev, bug

#955 DJV new version arguments
  pype/modules/ftrack/actions/action_djvview.py
  pype/plugins/global/load/open_djv.py
Labels: bug

#953 Fix single frame Sequence in TVPaint
  pype/plugins/tvpaint/publish/extract_sequence.py
Labels: bug

#952 Fix single frame Sequence in TVPaint
  pype/hosts/tvpaint/plugins/publish/extract_sequence.py
Labels: 2x-dev, bug

#956 Subset family is now stored in subset document
  pype/plugins/global/publish/integrate_new.py
Labels: 2x-dev, bug

#957 Subset family is now stored in subset document
  pype/plugins/global/publish/integrate_new.py
Labels: bug

#951 Maya: Handling Arnold referenced AOVs - Pype 3
  pype/hosts/maya/api/expected_files.py
  pype/hosts/maya/plugins/create/create_render.py
  pype/hosts/maya/plugins/publish/collect_render.py
Labels: enhancement, host: Maya

#960 Prores ks in burnin script
  pype/scripts/otio_burnin.py
Labels: bug

#959 Prores ks in burnin script
  pype/scripts/otio_burnin.py
Labels: bug

#934 Refactor blender to 3.0 format
  pype/hosts/blender/api/__init__.py
  pype/hosts/blender/api/action.py
  pype/hosts/blender/api/plugin.py
  pype/hosts/blender/plugins/__init__.py
  pype/hosts/blender/plugins/create/__init__.py
  pype/hosts/blender/plugins/create/create_action.py
  pype/hosts/blender/plugins/create/create_animation.py
  pype/hosts/blender/plugins/create/create_camera.py
  pype/hosts/blender/plugins/create/create_layout.py
  pype/hosts/blender/plugins/create/create_model.py
  pype/hosts/blender/plugins/create/create_rig.py
  pype/hosts/blender/plugins/create/create_setdress.py
  pype/hosts/blender/plugins/load/__init__.py
  pype/hosts/blender/plugins/load/load_action.py
  pype/hosts/blender/plugins/load/load_animation.py
  pype/hosts/blender/plugins/load/load_camera.py
  pype/hosts/blender/plugins/load/load_layout.py
  pype/hosts/blender/plugins/load/load_model.py
  pype/hosts/blender/plugins/load/load_rig.py
  pype/hosts/blender/plugins/publish/__init__.py
  pype/hosts/blender/plugins/publish/collect_current_file.py
  pype/hosts/blender/plugins/publish/collect_instances.py
  pype/hosts/blender/plugins/publish/extract_abc.py
  pype/hosts/blender/plugins/publish/extract_animation_collection.py
  pype/hosts/blender/plugins/publish/extract_blend.py
  pype/hosts/blender/plugins/publish/extract_fbx.py
  pype/hosts/blender/plugins/publish/extract_fbx_animation.py
  pype/hosts/blender/plugins/publish/increment_workfile_version.py
  pype/hosts/blender/plugins/publish/integrate_animation.py
  pype/hosts/blender/plugins/publish/validate_mesh_has_uv.py
  pype/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py
  pype/hosts/blender/startup/init.py
  pype/plugins/blender/publish/extract_blend.py
  pype/settings/defaults/system_settings/applications.json
  pype/setup/blender/init.py
  pype/tools/pyblish_pype/app.py
Labels: backend, host: Blender

#961 Refactor Unreal to 3.0 structure
  pype/hosts/celaction/hooks/pre_celaction_registers.py
  pype/hosts/unreal/api/__init__.py
  pype/hosts/unreal/api/lib.py
  pype/hosts/unreal/api/plugin.py
  pype/hosts/unreal/hooks/pre_workfile_preparation.py
  pype/hosts/unreal/plugins/__init__.py
  pype/hosts/unreal/plugins/create/create_layout.py
  pype/hosts/unreal/plugins/create/create_staticmeshfbx.py
  pype/hosts/unreal/plugins/load/load_animation.py
  pype/hosts/unreal/plugins/load/load_rig.py
  pype/hosts/unreal/plugins/load/load_setdress.py
  pype/hosts/unreal/plugins/load/load_staticmeshfbx.py
  pype/hosts/unreal/plugins/publish/collect_current_file.py
  pype/hosts/unreal/plugins/publish/collect_instances.py
  pype/hosts/unreal/plugins/publish/extract_layout.py
Labels: backend

#962 Refactor houdini to 3.0 structure
  pype/hosts/houdini/__init__.py
  pype/hosts/houdini/api/__init__.py
  pype/hosts/houdini/api/lib.py
  pype/hosts/houdini/plugins/create/create_alembic_camera.py
  pype/hosts/houdini/plugins/create/create_pointcache.py
  pype/hosts/houdini/plugins/create/create_vbd_cache.py
  pype/hosts/houdini/plugins/load/load_alembic.py
  pype/hosts/houdini/plugins/load/load_camera.py
  pype/hosts/houdini/plugins/publish/collect_current_file.py
  pype/hosts/houdini/plugins/publish/collect_frames.py
  pype/hosts/houdini/plugins/publish/collect_instances.py
  pype/hosts/houdini/plugins/publish/collect_output_node.py
  pype/hosts/houdini/plugins/publish/collect_workscene_fps.py
  pype/hosts/houdini/plugins/publish/extract_alembic.py
  pype/hosts/houdini/plugins/publish/extract_vdb_cache.py
  pype/hosts/houdini/plugins/publish/valiate_vdb_input_node.py
  pype/hosts/houdini/plugins/publish/validate_alembic_input_node.py
  pype/hosts/houdini/plugins/publish/validate_animation_settings.py
  pype/hosts/houdini/plugins/publish/validate_bypass.py
  pype/hosts/houdini/plugins/publish/validate_camera_rop.py
  pype/hosts/houdini/plugins/publish/validate_mkpaths_toggled.py
  pype/hosts/houdini/plugins/publish/validate_outnode_exists.py
  pype/hosts/houdini/plugins/publish/validate_output_node.py
  pype/hosts/houdini/plugins/publish/validate_primitive_hierarchy_paths.py
  pype/hosts/houdini/plugins/publish/validate_vdb_input_node.py
  pype/hosts/houdini/startup/MainMenuCommon.XML
  pype/hosts/houdini/startup/scripts/123.py
  pype/hosts/unreal/plugins/create/create_layout.py
  pype/settings/defaults/system_settings/applications.json
Labels: backend

#964 PS - remove pywin installation from hook
  pype/hooks/photoshop/prelaunch.py
Labels: 2x-dev, bug, host: Photoshop

#965 PSD Bulk export of ANIM group
  pype/plugins/standalonepublisher/publish/extract_bg_main_groups.py
Labels: 2x-dev, enhancement

#967 Create project structure action fix multiroot
  pype/modules/ftrack/actions/action_create_project_structure.py
Labels: 2x-dev, bug

#971 fix(nuke): frame offset mov loader
  pype/plugins/nuke/load/load_mov.py
Labels: bug, release

#972 Fix update of project's tasks on Ftrack sync
  pype/modules/ftrack/lib/avalon_sync.py
Labels: bug

#973 Fix update of project's tasks on Ftrack sync
  pype/modules/ftrack/lib/avalon_sync.py
Labels: bug

#968 Create project structure action fix multiroot
  pype/modules/ftrack/actions/action_create_project_structure.py
Labels: bug

#974 Ftrack plugins in ftrack module
  pype/modules/ftrack/ftrack_module.py
  pype/modules/ftrack/plugins/_unused_publish/integrate_ftrack_comments.py
  pype/modules/ftrack/plugins/publish/collect_ftrack_api.py
  pype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  pype/modules/ftrack/plugins/publish/integrate_ftrack_component_overwrite.py
  pype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  pype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
  pype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  pype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack_SP.py
  pype/modules/ftrack/plugins/publish/integrate_remove_components.py
  pype/modules/ftrack/plugins/publish/validate_custom_ftrack_attributes.py
Labels: enhancement

#979 Get creator by name fix
  pype/lib/__init__.py
  pype/lib/avalon_context.py
  pype/plugins/blender/load/load_layout.py
  pype/plugins/maya/load/load_reference.py
Labels: 2x-dev, bug

#980 Get creator by name fix
  pype/hosts/blender/plugins/load/load_layout.py
  pype/hosts/maya/plugins/load/load_reference.py
  pype/lib/__init__.py
  pype/lib/avalon_context.py
Labels: bug

#982 Fix Ftrack custom attribute update
  pype/modules/ftrack/events/event_sync_to_avalon.py
Labels: 2x-dev, bug

#983 Fix Ftrack custom attribute update
  pype/modules/ftrack/events/event_sync_to_avalon.py
Labels: bug

#984 fix(nuke): missing preset's variable
  pype/plugins/nuke/publish/extract_thumbnail.py
Labels: 2x-dev, bug, host: Nuke

#985 fix(nuke): missing preset's variable
  pype/hosts/nuke/plugins/publish/extract_thumbnail.py
Labels: bug, host: Nuke

#986 Maya: Alembic only set attributes that exists.
  pype/hosts/maya/plugin.py
Labels: enhancement

#987 Maya: Alembic only set attributes that exists
  pype/hosts/maya/api/plugin.py
Labels: enhancement

#975 nuke: wrong frame offset in mov loader
  pype/hosts/nuke/plugins/load/load_mov.py
Labels: bug, enhancement, host: Nuke

#988 Nuke: add nuke related env var to sumbission
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: 2x-dev, host: Nuke, release

#993 Nuke deadline presets
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: bug, enhancement, host: Nuke, release

#990 Extract review handle bizzar pixel aspect ratio
  pype/plugins/global/publish/extract_review.py
Labels: 2x-dev, bug

#995 Maya: Looks - disable hardlinks
  pype/plugins/maya/publish/extract_look.py
Labels: bug, host: Maya

#981 Harmony: render local and handle fixes
  pype/hosts/harmony/__init__.py
  pype/hosts/harmony/js/PypeHarmony.js
  pype/hosts/harmony/js/creators/CreateRender.js
  pype/hosts/harmony/js/loaders/ImageSequenceLoader.js
  pype/hosts/harmony/js/loaders/TemplateLoader.js
  pype/hosts/harmony/js/publish/CollectCurrentFile.js
  pype/hosts/harmony/js/publish/CollectFarmRender.js
  pype/hosts/harmony/js/publish/CollectPalettes.js
  pype/hosts/harmony/js/publish/ExtractPalette.js
  pype/hosts/harmony/js/publish/ExtractTemplate.js
  pype/lib/abstract_collect_render.py
  pype/plugins/harmony/create/create_render.py
  pype/plugins/harmony/load/load_imagesequence.py
  pype/plugins/harmony/publish/collect_audio.py
  pype/plugins/harmony/publish/collect_farm_render.py
  pype/plugins/harmony/publish/collect_instances.py
  pype/plugins/harmony/publish/collect_palettes.py
  pype/plugins/harmony/publish/collect_scene.py
  pype/plugins/harmony/publish/extract_render.py
  pype/plugins/harmony/publish/submit_harmony_deadline..py
  pype/plugins/harmony/publish/validate_scene_settings.py
Labels: 2x-dev, host: Harmony

#994 Nuke deadline presets
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
Labels: bug, enhancement, host: Nuke

#1001 Settings as entities
  pype/api.py
  pype/settings/__init__.py
  pype/settings/constants.py
  pype/settings/entities/__init__.py
  pype/settings/entities/base_entity.py
  pype/settings/entities/dict_immutable_keys_entity.py
  pype/settings/entities/dict_mutable_keys_entity.py
  pype/settings/entities/exceptions.py
  pype/settings/entities/input_entities.py
  pype/settings/entities/item_entities.py
  pype/settings/entities/lib.py
  pype/settings/entities/list_entity.py
  pype/settings/entities/root_entities.py
  pype/settings/entities/schemas/system_schema/example_schema.json
  pype/settings/entities/schemas/system_schema/example_template.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_aftereffects.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_blender.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_celaction.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_djv.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_fusion.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_harmony.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_houdini.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_maya.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_mayabatch.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_photoshop.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_resolve.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_tvpaint.json
  pype/settings/entities/schemas/system_schema/host_settings/schema_unreal.json
  pype/settings/entities/schemas/system_schema/host_settings/template_host_unchangables.json
  pype/settings/entities/schemas/system_schema/host_settings/template_host_variant.json
  pype/settings/entities/schemas/system_schema/host_settings/template_nuke.json
  pype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
  pype/settings/entities/schemas/system_schema/module_settings/template_custom_attribute.json
  pype/settings/entities/schemas/system_schema/schema_applications.json
  pype/settings/entities/schemas/system_schema/schema_general.json
  pype/settings/entities/schemas/system_schema/schema_main.json
  pype/settings/entities/schemas/system_schema/schema_modules.json
  pype/settings/entities/schemas/system_schema/schema_tools.json
  pype/settings/entities/schemas/system_schema/tool_settings/schema_arnold.json
  pype/settings/entities/schemas/system_schema/tool_settings/schema_vray.json
  pype/settings/entities/schemas/system_schema/tool_settings/schema_yeti.json
  pype/settings/entities/schemas/system_schema/tool_settings/template_tool_variant.json
  pype/settings/lib.py
  pype/tools/settings/settings/widgets/base.py
  pype/tools/settings/settings/widgets/categories.py
  pype/tools/settings/settings/widgets/dict_mutable_widget.py
  pype/tools/settings/settings/widgets/item_types.py
  pype/tools/settings/settings/widgets/item_widgets.py
  pype/tools/settings/settings/widgets/lib.py
  pype/tools/settings/settings/widgets/list_item_widget.py
  pype/tools/settings/settings/widgets/widgets.py
  pype/tools/settings/settings/widgets/window.py
  pype/tools/settings/settings/widgets/wrapper_widgets.py
Labels: backend, enhancement

#989 fix(nuke): add nuke related env var to sumbission
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
Labels: bug, host: Nuke

#1006 PS - remove obsolete functions from pywin32
  pype/plugins/photoshop/publish/collect_instances.py
  pype/plugins/photoshop/publish/collect_review.py
Labels: 2x-dev, host: Photoshop, hotfix

#1007 PS fix - removed unwanted functions from pywin32
  pype/plugins/photoshop/publish/collect_instances.py
  pype/plugins/photoshop/publish/collect_review.py
Labels: bug, host: Photoshop

#922 Clone description of review session objects.
  pype/modules/ftrack/actions/action_clone_review_session.py
Labels: bug

#445 Delete old versions
  pype/plugins/global/load/delete_old_versions.py
Labels: enhancement

#1011 Delete version as loader action
  pype/plugins/global/load/delete_old_versions.py
Labels: 2x-dev

#1012 Delete version as loader action
  pype/plugins/global/load/delete_old_versions.py
Labels: enhancement

#1018 Removed Python 3 syntax from settings entities
  pype/settings/entities/exceptions.py
  pype/settings/entities/lib.py
Labels: bug

#1014 Unify the use of single and multi root templates
  pype/settings/defaults/project_anatomy/roots.json
  pype/settings/defaults/project_anatomy/templates.json
  pype/settings/lib.py
  pype/tools/settings/settings/widgets/anatomy_types.py
Labels: deprecated, enhancement

#1016 Launch script for non python hosts
  pype/hooks/aftereffects/pre_launch_args.py
  pype/hooks/global/pre_non_python_host_launch.py
  pype/hooks/harmony/pre_launch_args.py
  pype/hooks/photoshop/pre_launch_args.py
  pype/scripts/non_python_host_launch.py
Labels: enhancement

#966 PSD Bulk export of ANIM group
  pype/plugins/standalonepublisher/publish/collect_context.py
  pype/plugins/standalonepublisher/publish/extract_bg_for_compositing.py
  pype/plugins/standalonepublisher/publish/extract_bg_main_groups.py
  pype/plugins/standalonepublisher/publish/extract_images_from_psd.py
Labels: enhancement

#1025 Plugins settings are not loaded correctly
  pype/lib/plugin_tools.py
  pype/plugin.py
Labels: bug

#1024 Get global environments
  pype/api.py
  pype/lib/__init__.py
  pype/lib/deprecated.py
  pype/lib/env_tools.py
  pype/modules/avalon_apps/avalon_app.py
Labels: backend, enhancement

#1026 Fusion refactor to pype 3.0
  pype/hosts/fusion/__init__.py
  pype/hosts/fusion/api/__init__.py
  pype/hosts/fusion/api/lib.py
  pype/hosts/fusion/api/menu.py
  pype/hosts/fusion/api/menu_style.qss
  pype/hosts/fusion/api/pipeline.py
  pype/hosts/fusion/api/utils.py
  pype/hosts/fusion/hooks/pre_fusion_setup.py
  pype/hosts/fusion/plugins/create/create_exr_saver.py
  pype/hosts/fusion/plugins/inventory/select_containers.py
  pype/hosts/fusion/plugins/inventory/set_tool_color.py
  pype/hosts/fusion/plugins/load/actions.py
  pype/hosts/fusion/plugins/load/load_sequence.py
  pype/hosts/fusion/plugins/publish/collect_comp.py
  pype/hosts/fusion/plugins/publish/collect_fusion_version.py
  pype/hosts/fusion/plugins/publish/collect_instances.py
  pype/hosts/fusion/plugins/publish/collect_render_target.py
  pype/hosts/fusion/plugins/publish/increment_current_file_deadline.py
  pype/hosts/fusion/plugins/publish/render_local.py
  pype/hosts/fusion/plugins/publish/save_scene.py
  pype/hosts/fusion/plugins/publish/submit_deadline.py
  pype/hosts/fusion/plugins/publish/validate_background_depth.py
  pype/hosts/fusion/plugins/publish/validate_comp_saved.py
  pype/hosts/fusion/plugins/publish/validate_create_folder_checked.py
  pype/hosts/fusion/plugins/publish/validate_filename_has_extension.py
  pype/hosts/fusion/plugins/publish/validate_saver_has_input.py
  pype/hosts/fusion/plugins/publish/validate_saver_passthrough.py
  pype/hosts/fusion/plugins/publish/validate_unique_subsets.py
  pype/hosts/fusion/scripts/fusion_switch_shot.py
  pype/hosts/fusion/utility_scripts/Pype_menu.py
  pype/setup/fusion/scripts/Comp/colorbleed/32bit/backgrounds_selected_to32bit.py
  pype/setup/fusion/scripts/Comp/colorbleed/32bit/backgrounds_to32bit.py
  pype/setup/fusion/scripts/Comp/colorbleed/32bit/loaders_selected_to32bit.py
  pype/setup/fusion/scripts/Comp/colorbleed/32bit/loaders_to32bit.py
  pype/setup/fusion/scripts/Comp/colorbleed/duplicate_with_input_connections.py
  pype/setup/fusion/scripts/Comp/colorbleed/set_rendermode.py
  pype/setup/fusion/scripts/Comp/colorbleed/switch_ui.py
  pype/setup/fusion/scripts/Comp/colorbleed/update_selected_loader_ranges.py
  test_localsystem.txt
Labels: backend

#932 Resolve - loading and updating clips
  pype/hosts/resolve/README.markdown
  pype/hosts/resolve/RESOLVE_API_README_v16.2.0_down.txt
  pype/hosts/resolve/RESOLVE_API_README_v16.2.0_up.txt
  pype/hosts/resolve/__init__.py
  pype/hosts/resolve/api/__init__.py
  pype/hosts/resolve/api/action.py
  pype/hosts/resolve/api/lib.py
  pype/hosts/resolve/api/menu.py
  pype/hosts/resolve/api/menu_style.qss
  pype/hosts/resolve/api/pipeline.py
  pype/hosts/resolve/api/plugin.py
  pype/hosts/resolve/api/preload_console.py
  pype/hosts/resolve/api/testing_utils.py
  pype/hosts/resolve/api/todo-rendering.py
  pype/hosts/resolve/api/utils.py
  pype/hosts/resolve/api/workio.py
  pype/hosts/resolve/hooks/pre_resolve_setup.py
  pype/hosts/resolve/otio/utils.py
  pype/hosts/resolve/plugins/create/create_shot_clip.py
  pype/hosts/resolve/plugins/load/load_clip.py
  pype/hosts/resolve/plugins/publish/collect_instances.py
  pype/hosts/resolve/plugins/publish/collect_workfile.py
  pype/hosts/resolve/plugins/publish/extract_workfile.py
  pype/hosts/resolve/utility_scripts/resolve_dev_scriping.py
  pype/hosts/resolve/utility_scripts/test.py
  pype/hosts/resolve/utility_scripts/tests/test_otio_as_edl.py
  pype/hosts/resolve/utility_scripts/tests/testing_create_timeline_item_from_path.py
  pype/plugins/resolve/_publish/collect_clip_resolution.py
  pype/plugins/resolve/_publish/collect_clips.py
Labels: enhancement, host: Resolve

#1013 Maya: Vray scene publishing
  pype/hosts/maya/lib.py
  pype/hosts/maya/render_setup_tools.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/maya/create/create_render.py
  pype/plugins/maya/create/create_vrayscene.py
  pype/plugins/maya/load/load_vrayscene.py
  pype/plugins/maya/publish/collect_render.py
  pype/plugins/maya/publish/collect_renderable_camera.py
  pype/plugins/maya/publish/collect_vrayscene.py
  pype/plugins/maya/publish/extract_vrayscene.py
  pype/plugins/maya/publish/validate_vray_translator_settings.py
Labels: enhancement, host: Maya

#1029 Maya: Vray scene publishing for Pype 3
  pype/hosts/maya/api/lib.py
  pype/hosts/maya/api/render_setup_tools.py
  pype/hosts/maya/plugins/create/create_render.py
  pype/hosts/maya/plugins/create/create_vrayscene.py
  pype/hosts/maya/plugins/load/load_vrayscene.py
  pype/hosts/maya/plugins/publish/collect_render.py
  pype/hosts/maya/plugins/publish/collect_renderable_camera.py
  pype/hosts/maya/plugins/publish/collect_vrayscene.py
  pype/hosts/maya/plugins/publish/extract_vrayscene.py
  pype/hosts/maya/plugins/publish/validate_vray_translator_settings.py
  pype/plugins/publish/integrate_new.py
Labels: enhancement, host: Maya

#1033 Tools miss env groups in schema
  pype/settings/defaults/system_settings/tools.json
  pype/settings/entities/root_entities.py
  pype/settings/entities/schemas/system_schema/tool_settings/schema_vray.json
  pype/settings/entities/schemas/system_schema/tool_settings/schema_yeti.json
Labels: bug

#1036 smaller nuke fixes from production
  pype/hosts/nuke/lib.py
  pype/plugins/nuke/publish/collect_instances.py
  pype/plugins/nuke/publish/submit_nuke_deadline.py
Labels: bug

#1038 Nuke small fixes
  pype/hosts/nuke/api/lib.py
  pype/hosts/nuke/plugins/publish/precollect_instances.py
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
Labels: bug

#1031 TVPaint thumbnail extract fix
  pype/plugins/tvpaint/publish/extract_sequence.py
Labels: bug

#1037 TVPaint thumbnail extract fix
  pype/hosts/tvpaint/plugins/publish/extract_sequence.py
Labels: bug

#1041 Fix entity move under project
  pype/modules/ftrack/events/event_sync_to_avalon.py
Labels: bug

#1040 Fix entity move under project
  pype/modules/ftrack/events/event_sync_to_avalon.py
Labels: 2x-dev, bug

#1035 Environments for context command
  pype/cli.py
  pype/pype_commands.py
Labels: enhancement

#1045 Auto fix unicode strings
  pype/hosts/maya/plugins/publish/validate_unicode_strings.py
  pype/lib/execute.py
  pype/plugins/publish/repair_unicode_strings.py
Labels: bug

#1046 Auto fix unicode strings
  pype/lib/applications.py
  pype/plugins/global/publish/repair_unicode_strings.py
  pype/plugins/maya/publish/validate_unicode_strings.py
Labels: bug

#1047 Harmony - add regex search to filter allowed task names for collectin…
  pype/plugins/harmony/publish/collect_palettes.py
Labels: 2x-dev, host: Harmony

#1052 Fix order of wrappers in settings gui
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: bug

#1053 Maya: speedup renderable camera collection
  pype/hosts/maya/attributes.py
  pype/plugins/maya/publish/collect_renderable_camera.py
Labels: 2x-dev, host: Maya

#1054 Maya: Pype 3 implementation of #1053
  pype/hosts/maya/api/attributes.py
  pype/hosts/maya/plugins/publish/collect_renderable_camera.py
Labels: enhancement, host: Maya

#1051 Populate plugins settings
  pype/hosts/maya/plugins/publish/validate_model_name.py
  pype/hosts/maya/plugins/publish/validate_rig_joints_hidden.py
  pype/hosts/maya/plugins/publish/validate_shader_name.py
  pype/hosts/maya/plugins/publish/validate_transform_naming_suffix.py
  pype/hosts/nuke/plugins/publish/validate_knobs.py
  pype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  pype/settings/defaults/project_settings/deadline.json
  pype/settings/defaults/project_settings/harmony.json
  pype/settings/defaults/project_settings/maya.json
  pype/settings/defaults/project_settings/nuke.json
  pype/settings/entities/dict_immutable_keys_entity.py
  pype/settings/entities/schemas/projects_schema/schema_main.json
  pype/settings/entities/schemas/projects_schema/schema_plugins.json
  pype/settings/entities/schemas/projects_schema/schema_project_deadline.json
  pype/settings/entities/schemas/projects_schema/schema_project_global.json
  pype/settings/entities/schemas/projects_schema/schema_project_harmony.json
  pype/settings/entities/schemas/projects_schema/schema_project_maya.json
  pype/settings/entities/schemas/projects_schema/schema_project_nuke.json
  pype/settings/entities/schemas/projects_schema/schema_project_standalonepublisher.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_load.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
  pype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
  pype/settings/entities/schemas/projects_schema/schemas/template_create_plugin.json
  pype/settings/entities/schemas/projects_schema/schemas/template_loader_plugin.json
  pype/settings/entities/schemas/projects_schema/schemas/template_publish_plugin.json
Labels: enhancement

#1055 Label wrap for all entities
  pype/settings/entities/base_entity.py
  pype/settings/entities/dict_immutable_keys_entity.py
  pype/settings/entities/dict_mutable_keys_entity.py
  pype/settings/entities/list_entity.py
  pype/settings/entities/schemas/projects_schema/schema_project_global.json
  pype/tools/settings/settings/widgets/base.py
  pype/tools/settings/settings/widgets/item_widgets.py
Labels: enhancement

#1059 Explicit subset filter in anatomy instance data
  pype/plugins/global/publish/collect_anatomy_instance_data.py
Labels: 2x-dev, bug

#1061 Explicit subset filter in anatomy instance data
  pype/plugins/publish/collect_anatomy_instance_data.py
Labels: bug

#1057 TVPaint frame offset
  pype/plugins/tvpaint/publish/extract_sequence.py
Labels: 2x-dev, bug

#1060 TVPaint frame offset
  pype/hosts/tvpaint/plugins/publish/extract_sequence.py
Labels: bug
