Repository ynput/OpenPype, pull requests merged in 2022-02, with the labels that each got.

#2618 hotfix: OIIO tool path - add extension on windows
  openpype/lib/vendor_bin_utils.py
Labels: type: bug

#2619 Release/3.8.0
  openpype/lib/vendor_bin_utils.py
Labels: type: bug

#2613 Fix - safer pulling of task name for webpublishing from PS
  openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py
Labels: host: Photoshop

#2590 Global: fix broken otio review extractor
  openpype/plugins/publish/extract_otio_review.py
Labels: type: bug

#2617 Cosmetics: Fix common typos in openpype/website
  website/docs/admin_distribute.md
  website/docs/admin_hosts_resolve.md
  website/docs/admin_hosts_tvpaint.md
  website/docs/admin_openpype_commands.md
  website/docs/admin_settings.md
  website/docs/admin_settings_project_anatomy.md
  website/docs/admin_settings_system.md
  website/docs/admin_webserver_for_webpublisher.md
  website/docs/artist_concepts.md
  website/docs/artist_getting_started.md
  website/docs/artist_hosts_aftereffects.md
  website/docs/artist_hosts_hiero.md
  website/docs/artist_hosts_maya.md
  website/docs/artist_hosts_nuke_tut.md
  website/docs/artist_hosts_photoshop.md
  website/docs/artist_hosts_resolve.md
  website/docs/artist_hosts_unreal.md
  website/docs/artist_publish.md
  website/docs/artist_tools.md
  website/docs/changelog.md
  website/docs/dev_build.md
  website/docs/dev_contribute.md
  website/docs/features.md
  website/docs/module_ftrack.md
  website/docs/module_site_sync.md
  website/docs/project_settings/settings_project_global.md
  website/docs/project_settings/settings_project_nuke.md
  website/docs/project_settings/settings_project_standalone.md
  website/docs/pype2/admin_anatomy.md
  website/docs/pype2/admin_config.md
  website/docs/pype2/admin_ftrack.md
  website/docs/pype2/admin_install.md
  website/docs/pype2/admin_introduction.md
  website/docs/pype2/admin_presets_ftrack.md
  website/docs/pype2/admin_presets_nukestudio.md
  website/docs/pype2/admin_presets_plugins.md
  website/docs/pype2/admin_presets_tools.md
  website/docs/pype2/admin_pype_commands.md
  website/docs/pype2/admin_setup_troubleshooting.md
  website/docs/upgrade_notes.md
  website/docusaurus.config.js
Labels: type: documentation

#2602 Ftrack: Family to Asset type mapping is in settings
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#2627 nuke: adding clear button to write nodes
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/startup/clear_rendered.py
Labels: type: enhancement

#2638 TVPaint: Image loaders also work on review family
  openpype/hosts/tvpaint/plugins/load/load_image.py
  openpype/hosts/tvpaint/plugins/load/load_reference_image.py
Labels: type: enhancement, host: TV Paint

#2629 General: Project backup tools
  openpype/cli.py
  openpype/lib/project_backpack.py
  openpype/pype_commands.py
Labels: type: enhancement

#2641 WebPublisher: fix instance duplicates
  openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py
  openpype/hosts/photoshop/plugins/publish/validate_unique_subsets.py
  openpype/lib/remote_publish.py
  openpype/pype_commands.py
Labels: host: Photoshop

#2647 Docker: enhance dockerfiles with metadata, fix pyenv initialization
  Dockerfile
  Dockerfile.centos7
  tools/docker_build.sh
Labels: backend

#2576 Nuke: load color space from representation data
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/utils.py
  openpype/hosts/nuke/plugins/load/load_clip.py
Labels: type: enhancement

#2556 New Publisher: New features and preparations for new standalone publisher
  openpype/hosts/testhost/plugins/create/auto_creator.py
  openpype/hosts/testhost/plugins/create/test_creator_1.py
  openpype/hosts/testhost/plugins/create/test_creator_2.py
  openpype/hosts/testhost/plugins/publish/collect_context.py
  openpype/hosts/testhost/plugins/publish/collect_instance_1.py
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/lib/__init__.py
  openpype/pipeline/lib/attribute_definitions.py
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/publisher/control.py
  openpype/tools/publisher/widgets/__init__.py
  openpype/tools/publisher/widgets/assets_widget.py
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/precreate_widget.py
  openpype/tools/publisher/widgets/tasks_widget.py
  openpype/tools/publisher/widgets/validations_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
  openpype/tools/resources/__init__.py
  openpype/tools/resources/images/delete.png
  openpype/tools/resources/images/file.png
  openpype/tools/resources/images/files.png
  openpype/tools/resources/images/folder.png
  openpype/tools/utils/__init__.py
  openpype/tools/utils/assets_widget.py
  openpype/tools/utils/models.py
  openpype/tools/utils/tasks_widget.py
  openpype/tools/utils/widgets.py
  openpype/widgets/attribute_defs/files_widget.py
  openpype/widgets/attribute_defs/widgets.py
Labels: type: enhancement

#2658 Houdini: Moved to OpenPype
  openpype/hosts/houdini/api/__init__.py
  openpype/hosts/houdini/api/lib.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/houdini/api/plugin.py
  openpype/hosts/houdini/api/workio.py
  openpype/hosts/houdini/plugins/create/create_hda.py
  openpype/hosts/houdini/plugins/load/load_alembic.py
  openpype/hosts/houdini/plugins/load/load_camera.py
  openpype/hosts/houdini/plugins/load/load_hda.py
  openpype/hosts/houdini/plugins/load/load_image.py
  openpype/hosts/houdini/plugins/load/load_usd_layer.py
  openpype/hosts/houdini/plugins/load/load_usd_reference.py
  openpype/hosts/houdini/plugins/load/load_vdb.py
  openpype/hosts/houdini/plugins/publish/collect_instances.py
  openpype/hosts/houdini/plugins/publish/collect_instances_usd_layered.py
  openpype/hosts/houdini/plugins/publish/collect_remote_publish.py
  openpype/hosts/houdini/startup/MainMenuCommon.xml
  openpype/hosts/houdini/startup/scripts/123.py
  openpype/hosts/houdini/startup/scripts/houdinicore.py
Labels: type: enhancement, host: Houdini

#2649 Maya: Move implementation to OpenPype
  openpype/hosts/maya/__init__.py
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/action.py
  openpype/hosts/maya/api/commands.py
  openpype/hosts/maya/api/customize.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/menu.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/api/setdress.py
  openpype/hosts/maya/api/workio.py
  openpype/hosts/maya/plugins/inventory/import_modelrender.py
  openpype/hosts/maya/plugins/load/_load_animation.py
  openpype/hosts/maya/plugins/load/actions.py
  openpype/hosts/maya/plugins/load/load_ass.py
  openpype/hosts/maya/plugins/load/load_assembly.py
  openpype/hosts/maya/plugins/load/load_audio.py
  openpype/hosts/maya/plugins/load/load_gpucache.py
  openpype/hosts/maya/plugins/load/load_image_plane.py
  openpype/hosts/maya/plugins/load/load_look.py
  openpype/hosts/maya/plugins/load/load_redshift_proxy.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/load/load_rendersetup.py
  openpype/hosts/maya/plugins/load/load_vdb_to_redshift.py
  openpype/hosts/maya/plugins/load/load_vdb_to_vray.py
  openpype/hosts/maya/plugins/load/load_vrayproxy.py
  openpype/hosts/maya/plugins/load/load_vrayscene.py
  openpype/hosts/maya/plugins/load/load_yeti_cache.py
  openpype/hosts/maya/plugins/load/load_yeti_rig.py
  openpype/hosts/maya/plugins/publish/collect_assembly.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/extract_animation.py
  openpype/hosts/maya/plugins/publish/extract_ass.py
  openpype/hosts/maya/plugins/publish/extract_assproxy.py
  openpype/hosts/maya/plugins/publish/extract_camera_alembic.py
  openpype/hosts/maya/plugins/publish/extract_camera_mayaScene.py
  openpype/hosts/maya/plugins/publish/extract_fbx.py
  openpype/hosts/maya/plugins/publish/extract_look.py
  openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
  openpype/hosts/maya/plugins/publish/extract_model.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
  openpype/hosts/maya/plugins/publish/extract_redshift_proxy.py
  openpype/hosts/maya/plugins/publish/extract_rig.py
  openpype/hosts/maya/plugins/publish/extract_vrayproxy.py
  openpype/hosts/maya/plugins/publish/extract_vrayscene.py
  openpype/hosts/maya/plugins/publish/extract_xgen_cache.py
  openpype/hosts/maya/plugins/publish/extract_yeti_rig.py
  openpype/hosts/maya/plugins/publish/validate_cycle_error.py
  openpype/hosts/maya/plugins/publish/validate_mesh_arnold_attributes.py
  openpype/hosts/maya/plugins/publish/validate_mesh_ngons.py
  openpype/hosts/maya/plugins/publish/validate_shape_zero.py
  openpype/hosts/maya/startup/userSetup.py
Labels: type: enhancement, host: Maya

#2616 Deadline: Be able to pass Mongo url to job
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/harmony/plugins/publish/collect_farm_render.py
  openpype/lib/abstract_collect_render.py
  openpype/modules/default_modules/deadline/plugins/publish/collect_default_deadline_server.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_publish_job.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: backend, module: Deadline

#2664 Fix python install in docker for centos7
  Dockerfile.centos7
Labels: backend

#2667 hiero: removing obsolete unsupported plugin
  openpype/hosts/hiero/api/startup/Python/Startup/version_everywhere.py
Labels: type: bug

#2670 Ftrack: Sync description to assets
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
Labels: type: enhancement, module: Ftrack

#2659 Launcher: Fix access to 'data' attribute on actions
  openpype/tools/launcher/models.py
  openpype/tools/launcher/widgets.py
Labels: type: bug

#2630 Global: adding studio name/code to anatomy template formatting data
  openpype/lib/__init__.py
  openpype/lib/avalon_context.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2635 General: FFmpeg conversion also check attribute string length
  openpype/lib/transcoding.py
Labels: type: enhancement

#2673 hiero: fix effect collector name and order
  openpype/hosts/hiero/plugins/publish/collect_clip_effects.py
Labels: type: bug

#2682 Ftrack: Hierarchical attributes are queried properly
  openpype/modules/default_modules/ftrack/event_handlers_server/action_push_frame_values_to_task.py
  openpype/modules/default_modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_links.py
  openpype/modules/default_modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_clean_hierarchical_attributes.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/ftrack/lib/avalon_sync.py
  openpype/modules/default_modules/ftrack/lib/custom_attributes.py
Labels: module: Ftrack, backend

#2656 General: Show applications without integration in project
  openpype/lib/applications.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_applications.py
  openpype/modules/default_modules/ftrack/lib/custom_attributes.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/system_schema/host_settings/schema_shell.json
  openpype/settings/entities/schemas/system_schema/schema_applications.json
  openpype/settings/lib.py
  openpype/tools/launcher/models.py
  openpype/tools/settings/local_settings/apps_widget.py
Labels: backend

#2570 General: Store settings by OpenPype version
  openpype/resources/__init__.py
  openpype/resources/images/warning.png
  openpype/settings/__init__.py
  openpype/settings/constants.py
  openpype/settings/entities/root_entities.py
  openpype/settings/handlers.py
  openpype/settings/lib.py
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/project_manager/project_manager/style.py
  openpype/tools/project_manager/project_manager/widgets.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/constants.py
  openpype/tools/settings/settings/widgets.py
  openpype/tools/settings/settings/window.py
  openpype/tools/tray/pype_tray.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/delegates.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/models.py
Labels: backend, type: feature

#2692 Maya Redshift fixes
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
Labels: type: bug, host: Maya, renderer:Redshift

#2680 Maya configurable unit validator
  openpype/hosts/maya/plugins/publish/validate_maya_units.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement, host: Maya

#2676 Houdini Explicitly collect correct frame name even in case of single frame render when `frameStart` is provided
  openpype/hosts/houdini/plugins/publish/collect_frames.py
Labels: type: bug, host: Houdini

#2603 Houdini: Implement Arnold .ass standin extraction from Houdini (also support .ass.gz)
  openpype/hosts/houdini/api/lib.py
  openpype/hosts/houdini/plugins/create/create_arnold_ass.py
  openpype/hosts/houdini/plugins/publish/collect_frames.py
  openpype/hosts/houdini/plugins/publish/extract_ass.py
  openpype/settings/defaults/project_settings/houdini.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_houdini_create.json
Labels: type: enhancement, host: Houdini, renderer:Arnold

#2642 Maya: cleanup duplicate rendersetup code
  openpype/hosts/maya/api/attributes.py
  openpype/hosts/maya/api/lib_rendersetup.py
  openpype/hosts/maya/plugins/publish/collect_renderable_camera.py
Labels: host: Maya

#2606 Houdini: Load Arnold .ass procedurals into Houdini
  openpype/hosts/houdini/plugins/load/load_ass.py
Labels: type: enhancement, host: Houdini, renderer:Arnold

#2701 LookAssigner: Fix imports after moving code to OpenPype repository
  openpype/tools/mayalookassigner/models.py
  openpype/tools/mayalookassigner/vray_proxies.py
  openpype/tools/mayalookassigner/widgets.py
Labels: type: bug, host: Maya

#2693 Multiple hosts: unify menu style across hosts
  openpype/hosts/blender/api/ops.py
  openpype/hosts/flame/api/menu.py
  openpype/hosts/fusion/api/menu.py
  openpype/hosts/hiero/api/menu.py
  openpype/hosts/houdini/startup/MainMenuCommon.xml
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/resolve/api/menu.py
Labels: type: bug

#2691 Nuke: prerender with review knob
  openpype/hosts/nuke/plugins/create/create_write_prerender.py
  openpype/modules/default_modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schema_project_nuke.json
Labels: type: enhancement

#2711 Settings: Studio Project anatomy is queried using right keys
  openpype/settings/handlers.py
Labels: type: bug, severity: HIGH, backend

#2710 Local Settings: Additional applications don't break UI
  openpype/tools/settings/local_settings/apps_widget.py
  openpype/tools/settings/local_settings/window.py
Labels: type: bug

#2715 General: Don't use 'objectName' from loaded references
  openpype/plugins/publish/collect_scene_loaded_versions.py
Labels: type: bug

#2725 TVPaint: Set objectName with members
  openpype/hosts/tvpaint/api/pipeline.py
Labels: type: bug, host: TV Paint

#2727 Project Manager: Disable add task, add asset and save button when not in a project
  openpype/tools/project_manager/project_manager/window.py
Labels: type: enhancement

#2706 Loader: Remove default family states for hosts from code
  openpype/hosts/flame/api/pipeline.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/resolve/api/pipeline.py
Labels: deprecated

#2704 Houdini: Fix refactor of Houdini host move for CreateArnoldAss
  openpype/hosts/houdini/plugins/create/create_arnold_ass.py
Labels: type: bug, host: Houdini

#2729 General: Fix loading of unused chars in xml format
  openpype/lib/transcoding.py
Labels: backend

#2622 Flame: loading clips to reels
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/pipeline.py
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/api/utility_scripts/openpype_flame_to_ftrack/openpype_flame_to_ftrack.py
  openpype/hosts/flame/plugins/load/load_clip.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
  openpype/tools/pyblish_pype/window.py
Labels: type: feature, host: Flame

#2731 Loader UI: Multiple asset selection and underline colors fixed
  openpype/tools/libraryloader/app.py
  openpype/tools/loader/app.py
  openpype/tools/loader/lib.py
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/assets_widget.py
Labels: type: bug

#2713 Fusion: Moved implementation into OpenPype
  openpype/hosts/fusion/api/__init__.py
  openpype/hosts/fusion/api/lib.py
  openpype/hosts/fusion/api/menu.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/fusion/api/utils.py
  openpype/hosts/fusion/api/workio.py
  openpype/hosts/fusion/hooks/pre_fusion_setup.py
  openpype/hosts/fusion/plugins/create/create_exr_saver.py
  openpype/hosts/fusion/plugins/inventory/select_containers.py
  openpype/hosts/fusion/plugins/inventory/set_tool_color.py
  openpype/hosts/fusion/plugins/load/actions.py
  openpype/hosts/fusion/plugins/load/load_sequence.py
  openpype/hosts/fusion/plugins/publish/collect_comp.py
  openpype/hosts/fusion/plugins/publish/collect_instances.py
  openpype/hosts/fusion/plugins/publish/render_local.py
  openpype/hosts/fusion/plugins/publish/submit_deadline.py
  openpype/hosts/fusion/scripts/duplicate_with_inputs.py
  openpype/hosts/fusion/scripts/fusion_switch_shot.py
  openpype/hosts/fusion/scripts/set_rendermode.py
  openpype/hosts/fusion/utility_scripts/32bit/backgrounds_selected_to32bit.py
  openpype/hosts/fusion/utility_scripts/32bit/backgrounds_to32bit.py
  openpype/hosts/fusion/utility_scripts/32bit/loaders_selected_to32bit.py
  openpype/hosts/fusion/utility_scripts/32bit/loaders_to32bit.py
  openpype/hosts/fusion/utility_scripts/__OpenPype_Menu__.py
  openpype/hosts/fusion/utility_scripts/switch_ui.py
  openpype/hosts/fusion/utility_scripts/update_loader_ranges.py
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/system_schema/host_settings/schema_fusion.json
Labels: host: Fusion

#2741 Version Up: Preserve parts of filename after version number (like subversion) on version_up
  openpype/lib/path_tools.py
Labels: type: bug

#2745 Flame: bunch of bugs
  openpype/hosts/flame/__init__.py
  openpype/hosts/flame/hooks/pre_flame_setup.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/export_preset/openpype_seg_thumbnails_jpg.xml
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/export_preset/openpype_seg_video_h264.xml
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/modules/__init__.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/modules/app_utils.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/modules/ftrack_lib.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/modules/panel_app.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/modules/uiwidgets.py
  openpype/hosts/flame/startup/openpype_flame_to_ftrack/openpype_flame_to_ftrack.py
  openpype/hosts/flame/startup/openpype_in_flame.py
  openpype/plugins/publish/validate_editorial_asset_name.py
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Labels: type: bug

#2746 Flame: adding validator source clip
  openpype/hosts/flame/plugins/publish/validate_source_clip.py
Labels: type: enhancement

#2734 Work Files: Preserve subversion comment of current filename by default
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2754 Harmony: Rendering in Deadline didn't work in other machines than submitter
  openpype/modules/default_modules/deadline/plugins/publish/submit_harmony_deadline.py
Labels: host: Harmony

#2760 Update docusaurus to latest version
  .github/workflows/documentation.yml
  website/docusaurus.config.js
  website/yarn.lock
Labels: type: documentation

#2508 Maya: Add only reference node to look family container like with other families
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/load/load_look.py
  openpype/tools/mayalookassigner/commands.py
  openpype/tools/mayalookassigner/vray_proxies.py
Labels: type: bug, host: Maya

#2757 Loader UI: Fix right click in representation widget
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
Labels: type: bug

#2748 Aftereffects 2022 and Deadline
  openpype/hosts/aftereffects/api/extension.zxp
  openpype/hosts/aftereffects/api/extension/CSXS/manifest.xml
  openpype/hosts/aftereffects/api/extension/js/main.js
  openpype/hosts/aftereffects/api/extension/jsx/hostscript.jsx
  openpype/hosts/aftereffects/api/ws_stub.py
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/modules/default_modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/settings/defaults/project_settings/aftereffects.json
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: type: bug, host: After Effects

#2605 Deadline: Simplify GlobalJobPreLoad logic
  vendor/deadline/custom/events/OpenPype/OpenPype.param
  vendor/deadline/custom/events/OpenPype/OpenPype.py
  vendor/deadline/custom/plugins/GlobalJobPreLoad.py
  vendor/deadline/readme.md
  website/docs/assets/deadline_configure_event.png
  website/docs/module_deadline.md
Labels: type: enhancement

#2768 After Effects: Fix typo in name `afftereffects` -> `aftereffects`
  openpype/hooks/pre_add_last_workfile_arg.py
  openpype/hooks/pre_copy_template_workfile.py
Labels: type: bug, host: After Effects

#2772 Documentation/link fixes
  website/docs/artist_hosts_resolve.md
Labels: type: bug, type: documentation

#2765 Avoid renaming udim indexes
  openpype/plugins/publish/integrate_new.py
Labels: type: bug

#2770 Houdini: Implement Reset Frame Range
  openpype/hosts/houdini/api/lib.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/houdini/startup/MainMenuCommon.xml
Labels: type: enhancement, host: Houdini

#2747 Houdini: Move Houdini Save Current File to beginning of ExtractorOrder
  openpype/hosts/houdini/plugins/publish/save_scene.py
  openpype/hosts/houdini/plugins/publish/save_scene_deadline.py
Labels: host: Houdini

#2775 Slack: Added regex for filtering on subset names
  openpype/modules/slack/plugins/publish/collect_slack_family.py
  openpype/settings/defaults/project_settings/slack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
  website/docs/module_slack.md
Labels: module: Slack

#2709 Maya: Remove some unused code
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/menu.json
  openpype/hosts/maya/api/menu_backup.json
  openpype/hosts/maya/api/pipeline.py
Labels: type: bug, host: Maya

#2780 Houdini: Remove duplicate ValidateOutputNode plug-in
  openpype/hosts/houdini/plugins/publish/validate_output_node.py
Labels: host: Houdini

#2791 SyncServer: Moved module one hierarchy level higher
  openpype/modules/base.py
  openpype/modules/sync_server/README.md
  openpype/modules/sync_server/__init__.py
  openpype/modules/sync_server/providers/__init__.py
  openpype/modules/sync_server/providers/abstract_provider.py
  openpype/modules/sync_server/providers/dropbox.py
  openpype/modules/sync_server/providers/gdrive.py
  openpype/modules/sync_server/providers/lib.py
  openpype/modules/sync_server/providers/local_drive.py
  openpype/modules/sync_server/providers/resources/dropbox.png
  openpype/modules/sync_server/providers/resources/folder.png
  openpype/modules/sync_server/providers/resources/gdrive.png
  openpype/modules/sync_server/providers/resources/local_drive.png
  openpype/modules/sync_server/providers/resources/sftp.png
  openpype/modules/sync_server/providers/resources/studio.png
  openpype/modules/sync_server/providers/sftp.py
  openpype/modules/sync_server/resources/paused.png
  openpype/modules/sync_server/resources/refresh.png
  openpype/modules/sync_server/resources/synced.png
  openpype/modules/sync_server/sync_server.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/sync_server/tray/app.py
  openpype/modules/sync_server/tray/delegates.py
  openpype/modules/sync_server/tray/lib.py
  openpype/modules/sync_server/tray/models.py
  openpype/modules/sync_server/tray/widgets.py
  openpype/modules/sync_server/utils.py
Labels: module: Sitesync

#2751 Flame: use Shot Name on segment for asset name
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/plugins/create/create_shot_clip.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
Labels: type: enhancement

#2783 Flame: Fix version string in default settings
  openpype/settings/defaults/system_settings/applications.json
Labels: type: bug, severity: HIGH, host: Flame

#2785 Documentation: broken link fix
  website/docs/artist_getting_started.md
Labels: type: bug, type: documentation

#2790 Royal render: Move module one hierarchy level higher
  openpype/modules/base.py
  openpype/modules/royal_render/__init__.py
  openpype/modules/royal_render/api.py
  openpype/modules/royal_render/plugins/publish/collect_default_rr_path.py
  openpype/modules/royal_render/plugins/publish/collect_rr_path_from_instance.py
  openpype/modules/royal_render/plugins/publish/collect_sequences_from_job.py
  openpype/modules/royal_render/royal_render_module.py
  openpype/modules/royal_render/rr_job.py
  openpype/modules/royal_render/rr_root/README.md
  openpype/modules/royal_render/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
Labels: module: RoyalRender

#2789 Deadline: Move module one hierarchy level higher
  openpype/modules/base.py
  openpype/modules/deadline/__init__.py
  openpype/modules/deadline/abstract_submit_deadline.py
  openpype/modules/deadline/deadline_module.py
  openpype/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py
  openpype/modules/deadline/plugins/publish/collect_default_deadline_server.py
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/deadline/plugins/publish/validate_deadline_connection.py
  openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
  openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.ico
  openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.options
  openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.param
  openpype/modules/deadline/repository/custom/plugins/HarmonyOpenPype/HarmonyOpenPype.py
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.ico
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.options
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.param
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.py
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.ico
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.options
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.param
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
  openpype/modules/deadline/repository/readme.md
  website/docs/module_deadline.md
Labels: module: Deadline

#2700 RoyalRender: Minor enhancements
  .gitmodules
  openpype/modules/base.py
  openpype/modules/royalrender/__init__.py
  openpype/modules/royalrender/api.py
  openpype/modules/royalrender/plugins/publish/collect_default_rr_path.py
  openpype/modules/royalrender/plugins/publish/collect_rr_path_from_instance.py
  openpype/modules/royalrender/plugins/publish/collect_sequences_from_job.py
  openpype/modules/royalrender/royal_render_module.py
  openpype/modules/royalrender/rr_job.py
  openpype/modules/royalrender/rr_root/README.md
  openpype/modules/royalrender/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
  openpype/settings/defaults/project_settings/royalrender.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_royalrender.json
Labels: type: enhancement, module: RoyalRender

#2799 Documentation: fixed broken links
  website/docs/module_deadline.md
Labels: type: bug, type: documentation

#2802 resolve: fixing fusion module loading
  openpype/hosts/resolve/api/utils.py
Labels: type: bug, host: Resolve

#2800 Ftrack: Unset task ids from asset versions before tasks are removed
  openpype/modules/ftrack/event_handlers_user/action_delete_asset.py
  openpype/modules/ftrack/lib/avalon_sync.py
Labels: module: Ftrack

#2803 General: Set context environments for non host applications
  openpype/hooks/pre_global_host_data.py
  openpype/lib/__init__.py
  openpype/lib/applications.py
Labels: type: enhancement, backend

#2806 Flame Babypublisher optimalization
  openpype/hosts/flame/startup/openpype_babypublisher/export_preset/openpype_seg_thumbnails_jpg.xml
  openpype/hosts/flame/startup/openpype_babypublisher/export_preset/openpype_seg_video_h264.xml
  openpype/hosts/flame/startup/openpype_babypublisher/modules/__init__.py
  openpype/hosts/flame/startup/openpype_babypublisher/modules/app_utils.py
  openpype/hosts/flame/startup/openpype_babypublisher/modules/ftrack_lib.py
  openpype/hosts/flame/startup/openpype_babypublisher/modules/panel_app.py
  openpype/hosts/flame/startup/openpype_babypublisher/modules/uiwidgets.py
  openpype/hosts/flame/startup/openpype_babypublisher/openpype_babypublisher.py
Labels: type: bug, host: Flame

#2778 Tray publisher: New Tray Publisher host (beta)
  openpype/cli.py
  openpype/hosts/testhost/api/instances.json
  openpype/hosts/testhost/api/pipeline.py
  openpype/hosts/traypublisher/api/__init__.py
  openpype/hosts/traypublisher/api/pipeline.py
  openpype/hosts/traypublisher/plugins/create/create_workfile.py
  openpype/hosts/traypublisher/plugins/publish/collect_source.py
  openpype/hosts/traypublisher/plugins/publish/collect_workfile.py
  openpype/hosts/traypublisher/plugins/publish/validate_workfile.py
  openpype/lib/__init__.py
  openpype/lib/execute.py
  openpype/modules/base.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_api.py
  openpype/modules/interfaces.py
  openpype/modules/traypublish_action.py
  openpype/pipeline/create/README.md
  openpype/pipeline/create/context.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/collect_avalon_entities.py
  openpype/plugins/publish/integrate_new.py
  openpype/plugins/publish/validate_aseset_docs.py
  openpype/pype_commands.py
  openpype/style/style.css
  openpype/tools/experimental_tools/dialog.py
  openpype/tools/experimental_tools/tools_def.py
  openpype/tools/publisher/control.py
  openpype/tools/publisher/publish_report_viewer/__init__.py
  openpype/tools/publisher/publish_report_viewer/model.py
  openpype/tools/publisher/publish_report_viewer/report_items.py
  openpype/tools/publisher/publish_report_viewer/widgets.py
  openpype/tools/publisher/publish_report_viewer/window.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/publish_widget.py
  openpype/tools/publisher/widgets/validations_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
  openpype/tools/settings/local_settings/experimental_widget.py
  openpype/tools/traypublisher/__init__.py
  openpype/tools/traypublisher/window.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/widgets.py
  openpype/widgets/attribute_defs/files_widget.py
Labels: type: enhancement

#2810 Settings UI: Search case sensitivity
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/search_dialog.py
Labels: type: bug

#2779 Houdini: Remove unused code
  openpype/hosts/houdini/api/__init__.py
  openpype/hosts/houdini/api/lib.py
Labels: host: Houdini

#2726 Various testing updates
  openpype/cli.py
  openpype/hosts/photoshop/api/launch_logic.py
  openpype/hosts/photoshop/plugins/publish/collect_color_coded_instances.py
  openpype/pype_commands.py
  tests/README.md
  tests/integration/conftest.py
  tests/integration/hosts/aftereffects/lib.py
  tests/integration/hosts/aftereffects/test_publish_in_aftereffects.py
  tests/integration/hosts/photoshop/test_publish_in_photoshop.py
  tests/lib/assert_classes.py
  tests/lib/testing_classes.py
  tests/unit/openpype/default_modules/royal_render/test_rr_job.py
  website/docs/admin_builds.md
  website/docs/admin_settings.md
  website/docs/dev_introduction.md
  website/docs/dev_testing.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: type: documentation

#2817 General: Color dialog UI fixes
  openpype/widgets/color_widgets/color_inputs.py
  openpype/widgets/color_widgets/color_triangle.py
Labels: type: enhancement, severity: LOW
