Repository ynput/OpenPype, pull requests merged in 2022-03, with the labels that each got.

#2819 Ftrack: Job killer with missing user
  openpype/modules/ftrack/event_handlers_user/action_job_killer.py
Labels: module: Ftrack

#2820 Settings UI: Fix "Apply from" action
  openpype/tools/settings/settings/base.py
Labels: type: bug

#2825 Settings: Missing document with OP versions may break start of OpenPype
  openpype/settings/handlers.py
  openpype/tools/settings/settings/base.py
Labels: type: bug, backend

#2766 General: Extract template formatting from anatomy
  openpype/lib/__init__.py
  openpype/lib/anatomy.py
  openpype/lib/applications.py
  openpype/lib/path_templates.py
  openpype/modules/ftrack/event_handlers_user/action_create_folders.py
Labels: backend

#2827 Deadline: Added missing events folder
  openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.param
  openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.py
Labels: type: bug, module: Deadline

#2828 Deadline: Remove recreated event
  openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.param
  openpype/modules/deadline/repository/custom/events/OpenPype/OpenPype.py
Labels: type: bug, module: Deadline

#2633 Maya `vrscene` loader fixes
  openpype/hosts/maya/plugins/load/load_vrayscene.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_load.json
Labels: type: bug, host: Maya

#2824 Deadline: more detailed temp file name for environment json
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: bug, module: Deadline

#2821 General: Host name was formed from obsolete code
  openpype/lib/avalon_context.py
Labels: type: bug, host: Nuke, host: Maya

#2829 Tools: Don't use avalon tools code
  openpype/hosts/blender/api/pipeline.py
  openpype/hosts/harmony/api/lib.py
  openpype/hosts/maya/api/commands.py
  openpype/hosts/maya/api/menu.py
  openpype/tools/mayalookassigner/widgets.py
  openpype/tools/sceneinventory/model.py
  openpype/tools/sceneinventory/view.py
  openpype/tools/standalonepublish/publish.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/host_tools.py
  openpype/tools/workfiles/model.py
Labels: refactor

#2818 Nuke: Use AVALON_APP to get value for "app" key
  openpype/hosts/nuke/api/lib.py
Labels: host: Nuke

#2836 Ftrack: Can sync fps as string
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/ftrack/event_handlers_user/action_create_cust_attrs.py
  openpype/modules/ftrack/lib/__init__.py
  openpype/modules/ftrack/lib/avalon_sync.py
  openpype/modules/ftrack/lib/constants.py
Labels: type: enhancement, module: Ftrack

#2811 Nuke: adding Reformat to baking mov plugin
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement, host: Nuke

#2805 Manager: Update all to latest button
  openpype/tools/sceneinventory/view.py
  openpype/tools/sceneinventory/window.py
Labels: type: enhancement

#2816 StandalonePublisher: use dynamic groups in subset names
  openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py
Labels: type: bug

#2832 Maya: Stop creation of reviews for Cryptomattes
  openpype/plugins/publish/extract_jpeg_exr.py
Labels: type: bug

#2839 General: Move change context functions
  openpype/hosts/fusion/scripts/fusion_switch_shot.py
  openpype/hosts/fusion/utility_scripts/switch_ui.py
  openpype/lib/avalon_context.py
  openpype/scripts/fusion_switch_shot.py
  openpype/tools/assetcreator/app.py
  openpype/tools/workfiles/app.py
Labels: refactor

#2845 AssetCreator: Remove the tool
  openpype/tools/assetcreator/__init__.py
  openpype/tools/assetcreator/__main__.py
  openpype/tools/assetcreator/app.py
  openpype/tools/assetcreator/model.py
  openpype/tools/assetcreator/widget.py
Labels: deprecated

#2840 Blender: Fixed parameters for FBX export of the camera
  openpype/hosts/blender/plugins/publish/extract_camera.py
Labels: type: bug, host: Blender

#2822 General: Custom function for find executable
  openpype/hosts/maya/plugins/publish/extract_look.py
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/execute.py
  openpype/lib/vendor_bin_utils.py
Labels: type: enhancement

#2851 WebPublisher: Fix wrong number of frames for video file
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/lib/vendor_bin_utils.py
  openpype/scripts/otio_burnin.py
Labels: type: bug

#2812 global: letter box calculated on output as last process
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: type: enhancement

#2852 WebPublisher: Fix username stored in DB
  openpype/modules/ftrack/plugins/publish/collect_username.py
Labels: type: bug

#2859 TrayPublisher: Choose project widget is more clear
  openpype/style/style.css
  openpype/tools/traypublisher/window.py
Labels: type: enhancement

#2857 New Publisher: Error dialog got right styles
  openpype/tools/publisher/widgets/create_dialog.py
Labels: type: bug

#2854 General: Move create logic from avalon to OpenPype
  openpype/__init__.py
  openpype/api.py
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/blender/api/pipeline.py
  openpype/hosts/blender/api/plugin.py
  openpype/hosts/blender/plugins/load/load_layout_blend.py
  openpype/hosts/blender/plugins/load/load_layout_json.py
  openpype/hosts/blender/plugins/load/load_rig.py
  openpype/hosts/flame/api/pipeline.py
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/fusion/plugins/create/create_exr_saver.py
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/harmony/api/plugin.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/hiero/api/plugin.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/houdini/api/plugin.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/create/create_vrayscene.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/photoshop/api/__init__.py
  openpype/hosts/photoshop/api/pipeline.py
  openpype/hosts/photoshop/api/plugin.py
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/resolve/api/pipeline.py
  openpype/hosts/resolve/api/plugin.py
  openpype/hosts/tvpaint/api/pipeline.py
  openpype/hosts/tvpaint/api/plugin.py
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
  openpype/hosts/tvpaint/plugins/create/create_render_pass.py
  openpype/hosts/unreal/api/pipeline.py
  openpype/hosts/unreal/api/plugin.py
  openpype/hosts/webpublisher/api/__init__.py
  openpype/lib/plugin_tools.py
  openpype/pipeline/__init__.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/legacy_create.py
  openpype/plugin.py
  openpype/tests/test_avalon_plugin_presets.py
  openpype/tools/creator/model.py
  openpype/tools/creator/window.py
  openpype/tools/standalonepublish/widgets/widget_family.py
Labels: refactor

#2855 General: Fix getattr clalback on dynamic modules
  openpype/modules/base.py
Labels: type: bug

#2863 NewPublisher: Changing task on publishing instance
  openpype/hosts/testhost/plugins/publish/collect_context.py
  openpype/hosts/testhost/plugins/publish/collect_instance_1.py
  openpype/pipeline/create/context.py
  openpype/plugins/publish/integrate_new.py
  openpype/tools/publisher/control.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/list_view_widgets.py
  openpype/tools/publisher/widgets/tasks_widget.py
  openpype/tools/publisher/widgets/widgets.py
Labels: type: enhancement

#2864 General: Fix hardlink for windows
  openpype/lib/path_tools.py
Labels: type: bug

#2866 Nuke: gizmo precollect fix
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/hosts/nuke/plugins/publish/validate_write_legacy.py
Labels: host: Nuke

#2847 Nuke: Fix family test in validate_write_legacy to work with stillImage
  openpype/hosts/nuke/plugins/publish/validate_write_legacy.py
Labels: host: Nuke

#2868 Deadline: Fix plugin name for tile assemble
  openpype/lib/transcoding.py
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: type: bug, module: Deadline

#2837 Maya: add loaded containers to published instance
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement, host: Maya

#2858 WebPublisher: Video file was published with one too many frame
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
Labels: type: bug

#2872 General: Subset name filtering in ExtractReview outpus
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: type: enhancement

#2877 General: Missing time function
  openpype/hosts/harmony/plugins/publish/collect_farm_render.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/collect_vrayscene.py
  openpype/lib/__init__.py
  openpype/lib/abstract_collect_render.py
  openpype/lib/config.py
  openpype/plugins/publish/collect_time.py
Labels: type: bug

#2876 Refactor: move webserver tool to openpype
  openpype/hosts/aftereffects/api/launch_logic.py
  openpype/hosts/aftereffects/api/ws_stub.py
  openpype/hosts/photoshop/api/launch_logic.py
  openpype/hosts/photoshop/api/ws_stub.py
  openpype/tools/adobe_webserver/app.py
  openpype/tools/adobe_webserver/readme.txt
Labels: host: After Effects, refactor

#2846 General: Basic event system
  openpype/__init__.py
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/blender/api/pipeline.py
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/hiero/api/events.py
  openpype/hosts/hiero/api/menu.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/photoshop/api/pipeline.py
  openpype/hosts/tvpaint/api/communication_server.py
  openpype/hosts/tvpaint/api/pipeline.py
  openpype/hosts/webpublisher/api/__init__.py
  openpype/lib/__init__.py
  openpype/lib/avalon_context.py
  openpype/lib/events.py
  openpype/pipeline/lib/__init__.py
  openpype/pipeline/lib/events.py
  openpype/tools/loader/app.py
  openpype/tools/workfiles/app.py
Labels: refactor

#2874 Fixes for attaching loaded containers (#2837)
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
Labels: type: bug, host: Maya

#2884 General: Avoid circular import
  openpype/__init__.py
Labels: type: bug

#2885 General: Remove forgotten use of avalon Creator
  openpype/lib/avalon_context.py
Labels: type: bug

#2889 General: Reduce style usage to OpenPype repository
  openpype/hosts/nuke/plugins/inventory/repair_old_loaders.py
  openpype/hosts/nuke/plugins/load/load_backdrop.py
  openpype/hosts/nuke/plugins/load/load_effects.py
  openpype/hosts/nuke/plugins/load/load_effects_ip.py
  openpype/hosts/nuke/plugins/load/load_gizmo.py
  openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
  openpype/hosts/nuke/plugins/load/load_script_precomp.py
  openpype/plugins/load/copy_file.py
  openpype/plugins/load/delete_old_versions.py
  openpype/resources/images/spinner-200.svg
  openpype/style/__init__.py
  openpype/style/data.json
  openpype/tools/launcher/models.py
  openpype/tools/loader/model.py
  openpype/tools/mayalookassigner/__init__.py
  openpype/tools/mayalookassigner/app.py
  openpype/tools/mayalookassigner/models.py
  openpype/tools/mayalookassigner/views.py
  openpype/tools/mayalookassigner/widgets.py
  openpype/tools/project_manager/project_manager/multiselection_combobox.py
  openpype/tools/publisher/widgets/tasks_widget.py
  openpype/tools/sceneinventory/model.py
  openpype/tools/sceneinventory/view.py
  openpype/tools/standalonepublish/widgets/model_asset.py
  openpype/tools/standalonepublish/widgets/model_tasks_template.py
  openpype/tools/standalonepublish/widgets/widget_asset.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/assets_widget.py
  openpype/tools/utils/host_tools.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/tasks_widget.py
  openpype/tools/utils/views.py
  openpype/tools/workfiles/model.py
Labels: refactor

#2891 Harmony - fixed creator issue
  openpype/hosts/harmony/api/TB_sceneOpened.js
Labels: type: bug

#2894 SceneInventory: Fix import of load function
  openpype/pipeline/__init__.py
  openpype/tools/sceneinventory/window.py
Labels: type: bug

#2879 Nuke: ExtractReviewSlate can handle more codes and profiles
  openpype/hosts/standalonepublisher/plugins/publish/extract_trim_video_audio.py
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/lib/__init__.py
  openpype/lib/transcoding.py
  openpype/lib/vendor_bin_utils.py
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/extract_review_slate.py
  openpype/scripts/otio_burnin.py
  openpype/tests/test_lib_restructuralization.py
Labels: type: enhancement

#2826 Maya: Deformer node ids validation plugin
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/publish/validate_animation_out_set_related_node_ids.py
  openpype/hosts/maya/plugins/publish/validate_node_ids_deformed_shapes.py
  openpype/hosts/maya/plugins/publish/validate_rig_out_set_node_ids.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: bug, host: Maya

#2902 Fixing gap detection in extract review
  openpype/plugins/publish/extract_review.py
Labels: type: bug

#2892 Flame: support for comment with xml attribute overrides
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
Labels: type: feature, host: Flame

#2897 nuke: imageio adding ocio config version 1.2
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Labels: type: enhancement, host: Nuke

#2907 General: Change how OPENPYPE_DEBUG value is handled
  openpype/cli.py
  openpype/lib/log.py
Labels: type: enhancement

#2901 Settings UI: Add simple tooltips for settings entities
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/schemas/README.md
  openpype/tools/settings/settings/base.py
Labels: type: enhancement

#2875 AfterEffects: Fix rendering for single frame in DL
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/lib/delivery.py
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  tests/README.md
  tests/unit/openpype/lib/test_delivery.py
Labels: type: bug, host: After Effects

#2906 Ftrack: Fill workfile in custom attribute
  openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  openpype/tools/workfiles/app.py
Labels: type: enhancement, module: Ftrack

#2916 Deadline: Add headless argument
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: enhancement, module: Deadline

#2919 CI: change the version bump logic
  tools/ci_tools.py
Labels: type: enhancement

#2914 General: Move formatting and workfile functions
  openpype/hosts/standalonepublisher/plugins/publish/collect_texture.py
  openpype/hosts/tvpaint/plugins/load/load_workfile.py
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/lib/delivery.py
  openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
  openpype/pipeline/load/utils.py
  openpype/plugins/publish/integrate_new.py
  openpype/tools/workfiles/app.py
Labels: refactor

#2924 Hiero: Fix import of 'register_event_callback'
  openpype/hosts/hiero/api/events.py
Labels: type: bug, host: Hiero

#2926 General: Don't print log record on OSError
  openpype/lib/log.py
Labels: type: bug, module: Ftrack

#2931 General: Move Attribute Definitions from pipeline
  openpype/hosts/testhost/plugins/create/auto_creator.py
  openpype/hosts/testhost/plugins/create/test_creator_1.py
  openpype/hosts/testhost/plugins/create/test_creator_2.py
  openpype/hosts/testhost/plugins/publish/collect_instance_1.py
  openpype/lib/__init__.py
  openpype/lib/attribute_definitions.py
  openpype/pipeline/__init__.py
  openpype/pipeline/create/context.py
  openpype/pipeline/lib/__init__.py
  openpype/widgets/attribute_defs/widgets.py
Labels: refactor

#2925 Workfiles: Open published workfiles
  openpype/tools/utils/delegates.py
  openpype/tools/workfiles/__init__.py
  openpype/tools/workfiles/app.py
  openpype/tools/workfiles/files_widget.py
  openpype/tools/workfiles/lib.py
  openpype/tools/workfiles/model.py
  openpype/tools/workfiles/save_as_dialog.py
  openpype/tools/workfiles/view.py
  openpype/tools/workfiles/window.py
Labels: type: enhancement

#2934 Settings UI: Collapsed of collapsible wrapper works as expected
  openpype/tools/settings/settings/wrapper_widgets.py
Labels: type: bug

#2941 Slack: add generic exception
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
Labels: type: bug, client

#2944 SceneInventory: Fix imports in UI
  openpype/pipeline/actions.py
  openpype/tools/sceneinventory/switch_dialog.py
Labels: type: bug

#2903 Nuke: improving readability
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
Labels: type: enhancement, host: Nuke

#2949 LogViewer: Don't refresh on initialization
  openpype/modules/log_viewer/tray/app.py
  openpype/modules/log_viewer/tray/widgets.py
Labels: type: bug

#2945 Slack: Added configurable maximum file size of review upload to Slack
  openpype/modules/slack/plugins/publish/collect_slack_family.py
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
  openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
Labels: type: enhancement, client

#2911 Nuke: Add no-audio Tag
  openpype/settings/entities/schemas/projects_schema/schemas/schema_representation_tags.json
Labels: type: enhancement

#2947 General: anatomy data with correct task short key
  openpype/lib/avalon_context.py
Labels: type: bug

#2951 Docs: Added MongoDB requirements
  website/docs/dev_requirements.md
Labels: type: documentation

#2932 Maya: Do not pass `set` to maya commands (fixes support for older maya versions)
  openpype/hosts/maya/api/lib.py
Labels: host: Maya

#2936 General: More fail safe delete old versions
  openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
  openpype/plugins/load/delete_old_versions.py
Labels: type: bug

#2939 General: Python specific vendor paths on env injection
  openpype/hooks/pre_python_2_prelaunch.py
  openpype/lib/applications.py
Labels: type: bug

#2943 NewPublisher: Prepared implementation of optional pyblish plugin
  openpype/pipeline/__init__.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/publish_plugins.py
Labels: type: enhancement

#2952 Maya - added transparency into review creator
  openpype/hosts/maya/plugins/create/create_review.py
  openpype/hosts/maya/plugins/publish/extract_playblast.py
Labels: host: Maya, client

#2956 Settings: Conditional dictionary avoid invalid logs
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/dict_conditional.py
  openpype/settings/entities/dict_immutable_keys_entity.py
  openpype/settings/entities/dict_mutable_keys_entity.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/item_entities.py
  openpype/settings/entities/list_entity.py
Labels: type: bug

#2923 General: Default modules loaded dynamically
  openpype/modules/base.py
Labels: type: enhancement

#2948 nuke: python3 compatibility issue with `iteritems`
  openpype/hosts/nuke/plugins/load/load_effects.py
  openpype/hosts/nuke/plugins/load/load_effects_ip.py
  openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
  openpype/hosts/nuke/plugins/publish/validate_write_deadline_tab.py
Labels: type: bug

#2965 Slack: Added default for review_upload_limit for Slack
  openpype/settings/defaults/project_settings/slack.json
Labels: type: bug

#2908 Multiverse: First PR
  openpype/hosts/maya/plugins/create/create_multiverse_usd.py
  openpype/hosts/maya/plugins/create/create_multiverse_usd_comp.py
  openpype/hosts/maya/plugins/create/create_multiverse_usd_over.py
  openpype/hosts/maya/plugins/load/load_multiverse_usd.py
  openpype/hosts/maya/plugins/publish/extract_multiverse_usd.py
  openpype/hosts/maya/plugins/publish/extract_multiverse_usd_comp.py
  openpype/hosts/maya/plugins/publish/extract_multiverse_usd_over.py
  openpype/plugins/publish/integrate_new.py
Labels: type: feature

#2922 Flame: centos related debugging
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/scripts/wiretap_com.py
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/collect_timeline_otio.py
Labels: type: bug, host: Flame

#2980 General: `METADATA_KEYS` constant as `frozenset` for optimal immutable lookup
  openpype/settings/constants.py
Labels: type: enhancement

#2950 General: Smaller fixes and typos
  openpype/hosts/traypublisher/plugins/create/create_workfile.py
  openpype/hosts/traypublisher/plugins/publish/validate_workfile.py
  openpype/modules/ftrack/lib/avalon_sync.py
  openpype/modules/log_viewer/tray/app.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/utils/lib.py
  openpype/widgets/attribute_defs/files_widget.py
Labels: type: bug

#2958 General: OIIO conversion for ffmeg can handle sequences
  openpype/lib/transcoding.py
Labels: type: bug

#2975 General: Tools with host filters
  openpype/lib/applications.py
  openpype/settings/defaults/system_settings/tools.json
  openpype/settings/entities/schemas/system_schema/schema_tools.json
  openpype/settings/lib.py
Labels: type: enhancement

#2967 Hero versions: Use custom templates
  openpype/plugins/publish/integrate_hero_version.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  openpype/settings/entities/schemas/projects_schema/schemas/template_color.json
Labels: type: enhancement

#2989 AEL: fix opening existing workfile if no scene opened
  openpype/hosts/aftereffects/api/workio.py
Labels: type: bug, host: After Effects

#2985 Nuke: ReviewDataMov Read RAW attribute
  openpype/hosts/nuke/api/plugin.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement

#2981 Settings UI: Fix version completer on linux
  openpype/tools/settings/settings/widgets.py
Labels: type: bug

#2935 General: Move plugins register and discover
  openpype/__init__.py
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/blender/api/pipeline.py
  openpype/hosts/flame/api/pipeline.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/fusion/plugins/create/create_exr_saver.py
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/plugins/publish/validate_write_legacy.py
  openpype/hosts/photoshop/api/pipeline.py
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/resolve/api/pipeline.py
  openpype/hosts/tvpaint/api/pipeline.py
  openpype/hosts/unreal/api/pipeline.py
  openpype/lib/avalon_context.py
  openpype/lib/python_module_tools.py
  openpype/pipeline/__init__.py
  openpype/pipeline/actions.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/load/plugins.py
  openpype/pipeline/plugin_discover.py
  openpype/pipeline/thumbnail.py
  openpype/tests/test_avalon_plugin_presets.py
  openpype/tools/creator/model.py
Labels: refactor

#2990 Fix: Disable setuptools auto discovery
  setup.py
  tools/build.ps1
  tools/build.sh
Labels: type: bug

#2991 PS: fix renaming subset incorrectly in PS
  openpype/hosts/photoshop/plugins/publish/validate_naming.py
  openpype/settings/defaults/project_settings/photoshop.json
Labels: type: bug, host: Photoshop
