Repository ynput/OpenPype, pull requests merged in 2022-01, with the labels that each got.

#2462 General: Workdir extra folders
  openpype/hooks/pre_create_extra_workdir_folders.py
  openpype/lib/__init__.py
  openpype/lib/path_tools.py
  openpype/modules/default_modules/ftrack/event_handlers_user/action_create_folders.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
  openpype/tools/workfiles/app.py
Labels: type: enhancement

#2408 General: Run applications as separate processes under linux
  app_launcher.py
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/execute.py
  setup.py
Labels: type: enhancement, backend

#2471 TVPaint: Create render layer dialog is in front
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
Labels: type: bug, host: TV Paint

#2475 Tools: Be able to change models of tasks and assets widgets
  openpype/tools/utils/assets_widget.py
  openpype/tools/utils/tasks_widget.py
Labels: type: enhancement

#2464 Publish pype: Reduce publish process defering
  openpype/tools/publisher/control.py
  openpype/tools/pyblish_pype/control.py
  openpype/tools/pyblish_pype/window.py
Labels: type: enhancement

#2460 Maya: Improve speed of Collect History logic
  openpype/hosts/maya/plugins/publish/collect_history.py
Labels: type: enhancement, host: Maya

#2459 Maya: Validate Rig Controllers - fix Error: in script editor
  openpype/hosts/maya/plugins/publish/validate_rig_controllers.py
Labels: type: enhancement, host: Maya

#2398 Flame: OpenTimelineIO Export Modul
  openpype/hosts/flame/__init__.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/menu.py
  openpype/hosts/flame/otio/__init__.py
  openpype/hosts/flame/otio/flame_export.py
  openpype/hosts/flame/otio/utils.py
  openpype/hosts/flame/plugins/publish/collect_test_selection.py
Labels: type: feature, host: Flame

#2383 Maya : add option to not group reference in ReferenceLoader
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/load/load_reference.py
Labels: type: enhancement, host: Maya

#2480 Loader: Remove always on top flag in tray
  openpype/modules/avalon_apps/avalon_app.py
  openpype/plugins/load/delivery.py
Labels: type: bug

#2457 Maya: Optimize Validate Locked Normals speed for dense polymeshes
  openpype/hosts/maya/plugins/publish/validate_mesh_normals_unlocked.py
Labels: type: enhancement, host: Maya

#2483 General: Custom template paths filter fix
  openpype/lib/avalon_context.py
Labels: type: bug

#2363 Version handling
  igniter/__init__.py
  igniter/bootstrap_repos.py
  igniter/install_dialog.py
  igniter/message_dialog.py
  igniter/tools.py
  openpype/lib/openpype_version.py
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/__init__.py
  openpype/settings/entities/base_entity.py
  openpype/settings/entities/color_entity.py
  openpype/settings/entities/exceptions.py
  openpype/settings/entities/input_entities.py
  openpype/settings/entities/op_version_entity.py
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/settings/handlers.py
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/settings/settings/base.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/item_widgets.py
  openpype/tools/settings/settings/widgets.py
  start.py
  tests/unit/igniter/test_bootstrap_repos.py
Labels: backend

#2458 Maya: Validate NGONs re-use polyConstraint code from openpype.host.maya.api.lib
  openpype/hosts/maya/plugins/publish/validate_mesh_ngons.py
Labels: host: Maya

#2488 Workfiles tool: Files widget show files on first show
  openpype/tools/workfiles/app.py
Labels: type: bug

#2465 General: Anatomy does not return root envs as unicode
  openpype/lib/anatomy.py
Labels: type: bug, backend

#2489 Tools: Fix style and modality of errors in loader and creator
  openpype/style/__init__.py
  openpype/tools/creator/widgets.py
  openpype/tools/creator/window.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/error_dialog.py
  openpype/tools/utils/widgets.py
Labels: type: enhancement

#2492 General: Modules import function output fix
  openpype/lib/python_module_tools.py
Labels: backend

#2494 General: Settings work if OpenPypeVersion is available
  openpype/settings/entities/op_version_entity.py
Labels: type: bug, backend

#2491 AE: fix hiding of alert window below Publish
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/aftereffects/plugins/load/load_background.py
Labels: host: After Effects

#2496 Ftrack: Event handlers settings
  openpype/modules/default_modules/ftrack/ftrack_module.py
  openpype/modules/default_modules/ftrack/ftrack_server/ftrack_server.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
Labels: type: enhancement, module: Ftrack

#2435 TVPaint: Use new publisher exceptions in validators
  openpype/hosts/tvpaint/plugins/publish/help/validate_asset_name.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_duplicated_layer_names.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_layers_visibility.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_marks.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_missing_layer_names.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_render_pass_group.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_scene_settings.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_start_frame.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_workfile_metadata.xml
  openpype/hosts/tvpaint/plugins/publish/help/validate_workfile_project_name.xml
  openpype/hosts/tvpaint/plugins/publish/validate_asset_name.py
  openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
  openpype/hosts/tvpaint/plugins/publish/validate_layers_visibility.py
  openpype/hosts/tvpaint/plugins/publish/validate_marks.py
  openpype/hosts/tvpaint/plugins/publish/validate_missing_layer_names.py
  openpype/hosts/tvpaint/plugins/publish/validate_project_settings.py
  openpype/hosts/tvpaint/plugins/publish/validate_render_pass_group.py
  openpype/hosts/tvpaint/plugins/publish/validate_scene_settings.py
  openpype/hosts/tvpaint/plugins/publish/validate_start_frame.py
  openpype/hosts/tvpaint/plugins/publish/validate_workfile_metadata.py
  openpype/hosts/tvpaint/plugins/publish/validate_workfile_project_name.py
Labels: type: enhancement

#2482 Project Manager: Remove project button cleanup
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/project_manager/project_manager/images/warning.png
  openpype/tools/project_manager/project_manager/style.py
  openpype/tools/project_manager/project_manager/widgets.py
  openpype/tools/project_manager/project_manager/window.py
Labels: type: enhancement

#2501 TimersManager: Move module one hierarchy higher
  openpype/modules/base.py
  openpype/modules/timers_manager/__init__.py
  openpype/modules/timers_manager/exceptions.py
  openpype/modules/timers_manager/idle_threads.py
  openpype/modules/timers_manager/launch_hooks/post_start_timer.py
  openpype/modules/timers_manager/rest_api.py
  openpype/modules/timers_manager/timers_manager.py
  openpype/modules/timers_manager/widget_user_idle.py
Labels: type: enhancement

#2493 General: PYTHONPATH may break OpenPype dependencies
  openpype/hooks/pre_non_python_host_launch.py
  openpype/hosts/tvpaint/hooks/pre_launch_args.py
  openpype/lib/__init__.py
  openpype/lib/execute.py
  openpype/lib/pype_info.py
  openpype/modules/default_modules/ftrack/ftrack_server/event_server_cli.py
  openpype/modules/default_modules/ftrack/ftrack_server/socket_thread.py
  openpype/modules/standalonepublish_action.py
  openpype/plugins/publish/extract_burnin.py
  openpype/tools/standalonepublish/widgets/widget_components.py
  openpype/tools/tray/pype_tray.py
Labels: type: bug, severity: HIGH, backend

#2447 Improve lib.polyConstraint performance when Select tool is not the active tool context
  openpype/hosts/maya/api/lib.py
Labels: type: enhancement

#2450 Houdini: Remove broken unique name counter
  openpype/hosts/houdini/plugins/load/load_alembic.py
  openpype/hosts/houdini/plugins/load/load_camera.py
Labels: type: enhancement

#2455 Fix #2453 Refactor missing _get_reference_node method
  openpype/hosts/maya/plugins/load/load_look.py
Labels: type: enhancement

#2510 Photoshop: Move implementation to OpenPype
  openpype/hosts/photoshop/api/README.md
  openpype/hosts/photoshop/api/__init__.py
  openpype/hosts/photoshop/api/extension.zxp
  openpype/hosts/photoshop/api/extension/.debug
  openpype/hosts/photoshop/api/extension/CSXS/manifest.xml
  openpype/hosts/photoshop/api/extension/client/CSInterface.js
  openpype/hosts/photoshop/api/extension/client/client.js
  openpype/hosts/photoshop/api/extension/client/loglevel.min.js
  openpype/hosts/photoshop/api/extension/client/wsrpc.js
  openpype/hosts/photoshop/api/extension/client/wsrpc.min.js
  openpype/hosts/photoshop/api/extension/host/JSX.js
  openpype/hosts/photoshop/api/extension/host/index.jsx
  openpype/hosts/photoshop/api/extension/host/json.js
  openpype/hosts/photoshop/api/extension/icons/avalon-logo-48.png
  openpype/hosts/photoshop/api/extension/index.html
  openpype/hosts/photoshop/api/launch_logic.py
  openpype/hosts/photoshop/api/lib.py
  openpype/hosts/photoshop/api/panel.PNG
  openpype/hosts/photoshop/api/panel_failure.PNG
  openpype/hosts/photoshop/api/pipeline.py
  openpype/hosts/photoshop/api/plugin.py
  openpype/hosts/photoshop/api/workio.py
  openpype/hosts/photoshop/api/ws_stub.py
  openpype/hosts/photoshop/hooks/__init__.py
  openpype/hosts/photoshop/plugins/__init__.py
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/photoshop/plugins/lib.py
  openpype/hosts/photoshop/plugins/load/load_image.py
  openpype/hosts/photoshop/plugins/load/load_image_from_sequence.py
  openpype/hosts/photoshop/plugins/load/load_reference.py
  openpype/hosts/photoshop/plugins/publish/closePS.py
  openpype/hosts/photoshop/plugins/publish/collect_current_file.py
  openpype/hosts/photoshop/plugins/publish/collect_extension_version.py
  openpype/hosts/photoshop/plugins/publish/collect_instances.py
  openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py
  openpype/hosts/photoshop/plugins/publish/collect_workfile.py
  openpype/hosts/photoshop/plugins/publish/extract_image.py
  openpype/hosts/photoshop/plugins/publish/extract_review.py
  openpype/hosts/photoshop/plugins/publish/extract_save_scene.py
  openpype/hosts/photoshop/plugins/publish/increment_workfile.py
  openpype/hosts/photoshop/plugins/publish/validate_instance_asset.py
  openpype/hosts/photoshop/plugins/publish/validate_naming.py
  openpype/scripts/non_python_host_launch.py
Labels: type: enhancement, host: Photoshop

#2513 Fix published frame content for sequence starting with 0
  openpype/plugins/publish/integrate_new.py
Labels: type: bug, host: After Effects

#2495 Flame - create publishable clips
  openpype/hosts/flame/__init__.py
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/constants.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/menu.py
  openpype/hosts/flame/api/pipeline.py
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/api/scripts/wiretap_com.py
  openpype/hosts/flame/api/utility_scripts/openpype_in_flame.py
  openpype/hosts/flame/api/utils.py
  openpype/hosts/flame/api/workio.py
  openpype/hosts/flame/hooks/pre_flame_setup.py
  openpype/hosts/flame/plugins/create/create_shot_clip.py
  openpype/hosts/flame/plugins/publish/collect_test_selection.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/defaults/system_settings/applications.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
Labels: type: enhancement

#2521 Expose toggle publish plug-in settings for Maya Look Shading Engine Naming
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement

#2506 Fix #2497: reset empty string attributes correctly to "" instead of "None"
  openpype/hosts/maya/api/lib.py
Labels: type: bug, host: Maya

#2522 Fix create zip tool - path argument
  igniter/bootstrap_repos.py
  tools/create_zip.py
Labels: backend

#2498 Slack: Add review to notification message
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
  openpype/settings/entities/schemas/projects_schema/schema_project_slack.json
  website/docs/module_slack.md
Labels: type: enhancement, client, type: documentation, module: Slack

#2456 Maya: Validate Shape Zero do not keep fixed geometry vertices selected/active after repair
  openpype/hosts/maya/plugins/publish/validate_shape_zero.py
Labels: type: bug

#2425 General: Validate third party before build
  setup.py
Labels: type: enhancement, backend

#2543 AfterEffects: Move implementation to OpenPype
  openpype/hosts/aftereffects/api/README.md
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/api/extension.zxp
  openpype/hosts/aftereffects/api/extension/.debug
  openpype/hosts/aftereffects/api/extension/CSXS/manifest.xml
  openpype/hosts/aftereffects/api/extension/css/boilerplate.css
  openpype/hosts/aftereffects/api/extension/css/styles.css
  openpype/hosts/aftereffects/api/extension/css/topcoat-desktop-dark.min.css
  openpype/hosts/aftereffects/api/extension/icons/iconDarkNormal.png
  openpype/hosts/aftereffects/api/extension/icons/iconDarkRollover.png
  openpype/hosts/aftereffects/api/extension/icons/iconDisabled.png
  openpype/hosts/aftereffects/api/extension/icons/iconNormal.png
  openpype/hosts/aftereffects/api/extension/icons/iconRollover.png
  openpype/hosts/aftereffects/api/extension/index.html
  openpype/hosts/aftereffects/api/extension/js/libs/CSInterface.js
  openpype/hosts/aftereffects/api/extension/js/libs/jquery-2.0.2.min.js
  openpype/hosts/aftereffects/api/extension/js/libs/json.js
  openpype/hosts/aftereffects/api/extension/js/libs/loglevel.min.js
  openpype/hosts/aftereffects/api/extension/js/libs/wsrpc.js
  openpype/hosts/aftereffects/api/extension/js/libs/wsrpc.min.js
  openpype/hosts/aftereffects/api/extension/js/main.js
  openpype/hosts/aftereffects/api/extension/js/themeManager.js
  openpype/hosts/aftereffects/api/extension/jsx/hostscript.jsx
  openpype/hosts/aftereffects/api/launch_logic.py
  openpype/hosts/aftereffects/api/lib.py
  openpype/hosts/aftereffects/api/panel.PNG
  openpype/hosts/aftereffects/api/panel_failure.PNG
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/aftereffects/api/plugin.py
  openpype/hosts/aftereffects/api/workio.py
  openpype/hosts/aftereffects/api/ws_stub.py
  openpype/hosts/aftereffects/plugins/create/create_local_render.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/aftereffects/plugins/load/load_background.py
  openpype/hosts/aftereffects/plugins/load/load_file.py
  openpype/hosts/aftereffects/plugins/publish/add_publish_highlight.py
  openpype/hosts/aftereffects/plugins/publish/closeAE.py
  openpype/hosts/aftereffects/plugins/publish/collect_audio.py
  openpype/hosts/aftereffects/plugins/publish/collect_current_file.py
  openpype/hosts/aftereffects/plugins/publish/collect_extension_version.py
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/aftereffects/plugins/publish/extract_local_render.py
  openpype/hosts/aftereffects/plugins/publish/extract_save_scene.py
  openpype/hosts/aftereffects/plugins/publish/increment_workfile.py
  openpype/hosts/aftereffects/plugins/publish/remove_publish_highlight.py
  openpype/hosts/aftereffects/plugins/publish/validate_instance_asset.py
  openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
  openpype/scripts/non_python_host_launch.py
Labels: host: After Effects

#2546 Renamed to proper name
  website/docs/module_slack.md
Labels: type: documentation

#2529 General: Validate if current process OpenPype version is requested version
  openpype/lib/__init__.py
  openpype/lib/openpype_version.py
  openpype/lib/pype_info.py
  openpype/modules/default_modules/ftrack/scripts/sub_event_status.py
  openpype/resources/__init__.py
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/tray/images/gifts.png
  openpype/tools/tray/pype_tray.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2549 General: Fix install thread in igniter
  igniter/bootstrap_repos.py
  igniter/install_thread.py
Labels: severity: HIGH, backend

#2550 Settings: PathInput strip passed string
  openpype/settings/entities/input_entities.py
Labels: type: enhancement

#2548 Global: Exctract Review anatomy fill data with output name
  openpype/plugins/publish/extract_otio_review.py
  openpype/plugins/publish/extract_review.py
Labels: type: enhancement

#2514 Nuke: Merge avalon's implementation into OpenPype
  openpype/hosts/nuke/__init__.py
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/actions.py
  openpype/hosts/nuke/api/command.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/menu.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/api/utils.py
  openpype/hosts/nuke/api/workio.py
  openpype/hosts/nuke/plugins/create/create_backdrop.py
  openpype/hosts/nuke/plugins/create/create_camera.py
  openpype/hosts/nuke/plugins/create/create_gizmo.py
  openpype/hosts/nuke/plugins/create/create_model.py
  openpype/hosts/nuke/plugins/create/create_read.py
  openpype/hosts/nuke/plugins/create/create_write_prerender.py
  openpype/hosts/nuke/plugins/create/create_write_render.py
  openpype/hosts/nuke/plugins/create/create_write_still.py
  openpype/hosts/nuke/plugins/inventory/repair_old_loaders.py
  openpype/hosts/nuke/plugins/inventory/select_containers.py
  openpype/hosts/nuke/plugins/load/load_backdrop.py
  openpype/hosts/nuke/plugins/load/load_camera_abc.py
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/hosts/nuke/plugins/load/load_effects.py
  openpype/hosts/nuke/plugins/load/load_effects_ip.py
  openpype/hosts/nuke/plugins/load/load_gizmo.py
  openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
  openpype/hosts/nuke/plugins/load/load_image.py
  openpype/hosts/nuke/plugins/load/load_model.py
  openpype/hosts/nuke/plugins/load/load_script_precomp.py
  openpype/hosts/nuke/plugins/publish/extract_backdrop.py
  openpype/hosts/nuke/plugins/publish/extract_camera.py
  openpype/hosts/nuke/plugins/publish/extract_gizmo.py
  openpype/hosts/nuke/plugins/publish/extract_model.py
  openpype/hosts/nuke/plugins/publish/extract_ouput_node.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_lut.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
  openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
  openpype/hosts/nuke/plugins/publish/extract_thumbnail.py
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/hosts/nuke/plugins/publish/precollect_workfile.py
  openpype/hosts/nuke/plugins/publish/validate_backdrop.py
  openpype/hosts/nuke/plugins/publish/validate_gizmo.py
  openpype/hosts/nuke/plugins/publish/validate_instance_in_context.py
  openpype/hosts/nuke/plugins/publish/validate_write_legacy.py
  openpype/hosts/nuke/plugins/publish/validate_write_nodes.py
  openpype/hosts/nuke/startup/init.py
  openpype/hosts/nuke/startup/menu.py
Labels: host: Nuke

#2558 Ftrack: Use ApplicationManager to get DJV path
  openpype/modules/default_modules/ftrack/event_handlers_user/action_djvview.py
Labels: type: enhancement

#2557 General: Do not validate version if build does not support it
  .github/workflows/test_build.yml
  openpype/lib/__init__.py
  openpype/tools/tray/pype_tray.py
Labels: type: bug, severity: HIGH, backend

#447 Deadline Maya Alembic caching
  pype/hosts/maya/__init__.py
  pype/hosts/maya/lib.py
  pype/plugins/ftrack/publish/integrate_ftrack_instances.py
  pype/plugins/global/publish/integrate_new.py
  pype/plugins/maya/create/create_animation.py
  pype/plugins/maya/create/create_pointcache.py
  pype/plugins/maya/publish/collect_animation.py
  pype/plugins/maya/publish/collect_pointcache.py
  pype/plugins/maya/publish/extract_animation.py
  pype/plugins/maya/publish/extract_pointcache.py
  pype/plugins/maya/publish/save_scene.py
  pype/plugins/maya/publish/submit_maya_deadline.py
  pype/plugins/maya/publish/validate_animation_content.py
  pype/plugins/maya/publish/validate_unreal_up_axis.py
  pype/scripts/export_maya_alembic_job.py
Labels: type: enhancement, host: Maya, 2x-dev, convert to 3.0

#2505 Improve FusionPreLaunch hook errors
  openpype/hosts/fusion/hooks/pre_fusion_setup.py
Labels: type: bug

#2563 Ftrack: Delete action revision
  openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_asset.py
Labels: type: bug, module: Ftrack

#2519 Flame: collecting publishable instances
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/otio/flame_export.py
  openpype/hosts/flame/otio/utils.py
  openpype/hosts/flame/plugins/publish/collect_test_selection.py
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/collect_timeline_otio.py
  openpype/hosts/flame/plugins/publish/extract_otio_file.py
  openpype/modules/default_modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  openpype/plugins/publish/collect_hierarchy.py
  openpype/plugins/publish/collect_otio_frame_ranges.py
  openpype/plugins/publish/collect_otio_review.py
  openpype/plugins/publish/collect_otio_subset_resources.py
Labels: type: feature, host: Flame

#2547 Flame: extracting segments with trans-coding
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/render_utils.py
  openpype/hosts/flame/api/utils.py
  openpype/hosts/flame/otio/flame_export.py
  openpype/hosts/flame/otio/utils.py
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/plugins/publish/collect_hierarchy.py
  openpype/plugins/publish/collect_otio_frame_ranges.py
  openpype/plugins/publish/collect_otio_review.py
  openpype/plugins/publish/collect_otio_subset_resources.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_otio_audio_tracks.py
  openpype/plugins/publish/extract_otio_review.py
  openpype/plugins/publish/extract_otio_trimming_video.py
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
  openpype/tools/pyblish_pype/window.py
Labels: type: enhancement

#2559 Webpublisher: Moved error at the beginning of the log
  openpype/lib/remote_publish.py
Labels: type: enhancement

#2560 Webpublisher: ftrack shows incorrect user names
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/modules/default_modules/ftrack/plugins/publish/collect_username.py
  openpype/pype_commands.py
Labels: type: bug

#2555 Webpublisher: Added endpoint to reprocess batch through UI
  openpype/hosts/webpublisher/plugins/publish/collect_batch_data.py
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver_cli.py
  openpype/lib/remote_publish.py
  openpype/pype_commands.py
Labels: type: enhancement

#2551 Fix Maya AssProxyLoader version switch
  openpype/hosts/maya/plugins/load/load_ass.py
Labels: type: bug, host: Maya

#2540 Maya: Remove Maya Look Assigner check on startup
  openpype/hosts/maya/api/customize.py
Labels: host: Maya

#2532 Maya: ReferenceLoader fix not unique group name error for attach to root
  openpype/hosts/maya/plugins/load/load_reference.py
Labels: host: Maya

#2531 Maya: namespaced context go back to original namespace when started from inside a namespace
  openpype/hosts/maya/api/lib.py
Labels: host: Maya

#2518 Maya: Fix Extract Look with space in names
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: type: bug, host: Maya

#2535 Houdini: vdbcache family preserve frame numbers on publish integration + enable validate version for Houdini
  openpype/hosts/houdini/plugins/publish/collect_instances.py
  openpype/hosts/houdini/plugins/publish/extract_vdb_cache.py
  openpype/plugins/publish/validate_version.py
Labels: type: bug, host: Houdini

#2533 Maya: Fix Load VDB to V-Ray
  openpype/hosts/maya/plugins/load/load_vdb_to_vray.py
Labels: type: bug, host: Maya

#2392 Maya: Vray fix proxies look assignment
  openpype/tools/mayalookassigner/app.py
  openpype/tools/mayalookassigner/commands.py
  openpype/tools/mayalookassigner/vray_proxies.py
  openpype/tools/mayalookassigner/widgets.py
Labels: host: Maya, renderer:Vray

#2486 Maya: Collect 'fps' animation data only for "review" instances
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/create/create_review.py
Labels: type: enhancement

#2537 Maya to Unreal: Extended static mesh workflow
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/create/create_unreal_staticmesh.py
  openpype/hosts/maya/plugins/publish/clean_nodes.py
  openpype/hosts/maya/plugins/publish/collect_unreal_staticmesh.py
  openpype/hosts/maya/plugins/publish/extract_fbx.py
  openpype/hosts/maya/plugins/publish/extract_unreal_staticmesh.py
  openpype/hosts/maya/plugins/publish/validate_assembly_name.py
  openpype/hosts/maya/plugins/publish/validate_unreal_staticmesh_naming.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_anatomy/templates.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_templates.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: host: Maya, host: UE, type: feature

#2575 General: OpenPype version updates
  openpype/lib/__init__.py
  openpype/lib/openpype_version.py
  openpype/lib/pype_info.py
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/tools/settings/settings/wrapper_widgets.py
  openpype/tools/tray/pype_info_widget.py
  openpype/tools/tray/pype_tray.py
  website/docs/admin_settings_system.md
  website/docs/assets/settings/settings_system_general.png
  website/docs/assets/settings/settings_system_version_downgrade.png
  website/docs/assets/settings/settings_system_version_update.png
Labels: type: bug, severity: HIGH, backend

#2541 Loader: Allow to toggle default family filters between "include" or "exclude" filtering
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_tools.json
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2568 global: track name was failing if duplicated root word in name
  openpype/plugins/publish/collect_otio_review.py
Labels: type: bug

#2580 `vrscene` creator Deadline webservice URL handling
  openpype/hosts/maya/plugins/create/create_vrayscene.py
  openpype/hosts/maya/plugins/publish/collect_vrayscene.py
Labels: type: bug, host: Maya, renderer:Vray, module: Deadline

#2586 Webpublisher: Fix - subset names from processed .psd used wrong value for task
  openpype/hosts/photoshop/plugins/publish/collect_remote_instances.py
Labels: type: bug, client, host: Photoshop

#2589 Fix poetry index and speedcopy update
  poetry.lock
  pyproject.toml
Labels: type: bug, backend

#2594 switch distutils to sysconfig for `get_platform()`
  tools/build_dependencies.py
Labels: type: bug, backend

#2484 Validate Maya Rig produces no cycle errors
  openpype/hosts/maya/plugins/publish/validate_cycle_error.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: bug

#2048 TVPaint: EXR Extractor
  pype/plugins/tvpaint/publish/extract_sequence_exr.py
Labels: 2x-dev, host: TV Paint, convert to 3.0, type: feature

#2066 Unreal: JSON Layout Loading support
  openpype/hosts/blender/api/plugin.py
  openpype/hosts/blender/plugins/load/load_layout_blend.py
  openpype/hosts/blender/plugins/load/load_layout_json.py
  openpype/hosts/blender/plugins/load/load_model.py
  openpype/hosts/blender/plugins/load/load_rig.py
  openpype/hosts/blender/plugins/publish/extract_blend_animation.py
  openpype/hosts/blender/plugins/publish/extract_fbx.py
  openpype/hosts/blender/plugins/publish/extract_fbx_animation.py
  openpype/hosts/blender/plugins/publish/extract_layout.py
  openpype/hosts/blender/plugins/publish/increment_workfile_version.py
  openpype/hosts/blender/plugins/publish/validate_object_mode.py
  openpype/hosts/unreal/plugins/load/load_animation.py
  openpype/hosts/unreal/plugins/load/load_layout.py
  openpype/hosts/unreal/plugins/load/load_rig.py
  openpype/hosts/unreal/plugins/load/load_staticmeshfbx.py
Labels: type: enhancement, host: UE, host: Blender

#2591 Webpublisher: Skip version collect
  openpype/plugins/publish/collect_scene_version.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  tests/integration/README.md
Labels: client, host: Photoshop

#2615 Settings: Enum does not store empty string if has single item to select
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/enum_entity.py
Labels: type: bug, backend

#2536 Launcher: Added context menu to to skip opening last workfile
  openpype/hooks/pre_add_last_workfile_arg.py
  openpype/hooks/pre_global_host_data.py
  openpype/hooks/pre_non_python_host_launch.py
  openpype/lib/applications.py
  openpype/tools/launcher/actions.py
  openpype/tools/launcher/constants.py
  openpype/tools/launcher/delegates.py
  openpype/tools/launcher/models.py
  openpype/tools/launcher/widgets.py
Labels: type: enhancement
