Repository ynput/OpenPype, pull requests merged in 2022-07, with the labels that each got.

#3436 General: Use Anatomy after move to pipeline
  openpype/hooks/pre_global_host_data.py
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/houdini/vendor/husdoutputprocessors/avalon_uri_processor.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/tvpaint/plugins/load/load_workfile.py
  openpype/hosts/unreal/api/rendering.py
  openpype/hosts/unreal/plugins/publish/collect_render_instances.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/lib/path_tools.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/ftrack/event_handlers_server/event_user_assigment.py
  openpype/modules/ftrack/event_handlers_user/action_create_folders.py
  openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
  openpype/modules/ftrack/event_handlers_user/action_delivery.py
  openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
  openpype/modules/ftrack/event_handlers_user/action_rv.py
  openpype/modules/ftrack/event_handlers_user/action_store_thumbnails_to_avalon.py
  openpype/modules/sync_server/providers/local_drive.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/load/utils.py
  openpype/plugins/load/delete_old_versions.py
  openpype/plugins/load/delivery.py
  openpype/plugins/publish/collect_anatomy_object.py
  openpype/tools/loader/widgets.py
  openpype/tools/texture_copy/app.py
  openpype/tools/workfiles/files_widget.py
Labels: refactor

#3457 General: Use query functions in rest api calls
  openpype/modules/avalon_apps/rest_api.py
Labels: refactor

#3100 Maya: Implement `iter_visible_nodes_in_range` for extracting Alembics
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/publish/extract_animation.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
  openpype/hosts/maya/plugins/publish/validate_visible_only.py
Labels: type: enhancement, host: Maya

#3197 Maya: Redshift Volume Loader Implement update, remove, switch + fix vdb sequence support
  openpype/hosts/maya/plugins/load/load_vdb_to_redshift.py
Labels: type: enhancement, host: Maya

#3380 Fusion: Use client query functions
  openpype/hosts/fusion/api/lib.py
  openpype/hosts/fusion/plugins/load/load_sequence.py
  openpype/hosts/fusion/scripts/fusion_switch_shot.py
  openpype/hosts/fusion/utility_scripts/switch_ui.py
Labels: host: Fusion, refactor

#3379 Resolve: Use client query functions
  openpype/hosts/fusion/plugins/load/load_sequence.py
  openpype/hosts/resolve/plugins/load/load_clip.py
Labels: host: Resolve, refactor

#3452 Harmony: add loader settings
  openpype/settings/defaults/project_settings/harmony.json
  openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
Labels: type: enhancement

#3446 General: Use query functions in load utils
  openpype/client/entities.py
  openpype/hosts/maya/api/setdress.py
  openpype/pipeline/load/utils.py
Labels: refactor

#3360 OP-3088: Ability to set resolution for playblasts from asset, and override through review instance.
  openpype/hosts/maya/plugins/create/create_review.py
  openpype/hosts/maya/plugins/publish/collect_review.py
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: type: enhancement, host: Maya

#3337 General: Host implementation defined with class
  openpype/host/__init__.py
  openpype/host/host.py
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/maya/startup/userSetup.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/create/context.py
  openpype/pipeline/legacy_io.py
  openpype/tools/sceneinventory/model.py
  openpype/tools/utils/host_tools.py
  openpype/tools/workfiles/__init__.py
  openpype/tools/workfiles/app.py
  openpype/tools/workfiles/files_widget.py
  website/docs/dev_host_implementation.md
  website/sidebars.js
Labels: refactor

#3370 Maya: Handle excluding `model` family from frame range validator.
  openpype/hosts/maya/plugins/publish/validate_frame_range.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: bug, host: Maya

#3460 Maya: Re-use `maintained_time` from lib
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: refactor

#3461 Maya: Merge animation + pointcache extractor logic
  openpype/hosts/maya/plugins/publish/extract_animation.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
Labels: refactor

#3462 General: Delete old versions is safer when ftrack is disabled
  openpype/plugins/load/delete_old_versions.py
Labels: type: bug

#3474 General: thumbnail extractor fix
  openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
  openpype/plugins/publish/extract_thumbnail.py
Labels: type: bug

#3459 General: Use query functions in global plugins
  openpype/client/__init__.py
  openpype/client/entities.py
  openpype/plugins/load/delete_old_versions.py
  openpype/plugins/load/delivery.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/collect_avalon_entities.py
  openpype/plugins/publish/collect_scene_loaded_versions.py
  openpype/plugins/publish/extract_hierarchy_avalon.py
  openpype/plugins/publish/integrate_hero_version.py
  openpype/plugins/publish/integrate_new.py
  openpype/plugins/publish/integrate_thumbnail.py
  openpype/plugins/publish/validate_editorial_asset_name.py
Labels: refactor

#3475 General: Better arguments order in creator init
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
Labels: type: enhancement

#3425 Hiero: Add custom scripts menu
  openpype/hosts/hiero/api/launchforhiero.py
  openpype/hosts/hiero/api/menu.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/settings/defaults/project_settings/hiero.json
  openpype/settings/entities/schemas/projects_schema/schema_project_hiero.json
  website/docs/admin_hosts_hiero.md
  website/docs/assets/hiero-admin_scriptsmenu.png
  website/sidebars.js
Labels: type: enhancement, host: Hiero

#3464 Resolve: removed few bugs
  openpype/hosts/resolve/api/lib.py
  openpype/hosts/resolve/api/plugin.py
  openpype/hosts/resolve/plugins/create/create_shot_clip.py
  openpype/hosts/resolve/plugins/load/load_clip.py
  openpype/hosts/resolve/plugins/publish/precollect_workfile.py
Labels: type: bug, host: Resolve

#3473 Kitsu: bugfix with sync-service ans publish plugins
  openpype/modules/kitsu/plugins/publish/collect_kitsu_entities.py
  openpype/modules/kitsu/utils/sync_service.py
  openpype/modules/kitsu/utils/update_op_with_zou.py
Labels: type: bug

#3476 General: Creator Plugins have access to project
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
Labels: type: enhancement

#3478 New Publisher: Disabled context change allows creation
  openpype/tools/publisher/widgets/create_dialog.py
Labels: type: bug

#3454 General: Use query functions in openpype lib functions
  openpype/api.py
  openpype/client/__init__.py
  openpype/client/entities.py
  openpype/lib/__init__.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/lib/plugin_tools.py
  openpype/lib/project_backpack.py
  openpype/lib/usdlib.py
  openpype/tests/test_lib_restructuralization.py
  openpype/tools/workfiles/window.py
Labels: refactor

#3484 NewPublisher: Added ability to use label of instance
  openpype/pipeline/create/context.py
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/list_view_widgets.py
Labels: type: enhancement

#3487 NewPublisher: Align creator attributes from top to bottom
  openpype/tools/publisher/widgets/widgets.py
Labels: type: enhancement

#3442 General: Move publish plugin and publish render abstractions
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/harmony/plugins/publish/collect_farm_render.py
  openpype/lib/abstract_collect_render.py
  openpype/lib/abstract_expected_files.py
  openpype/lib/abstract_metaplugins.py
  openpype/modules/deadline/abstract_submit_deadline.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/abstract_collect_render.py
  openpype/pipeline/publish/abstract_expected_files.py
  openpype/pipeline/publish/publish_plugins.py
Labels: refactor

#3491 General: Extract review use first frame of input sequence
  openpype/plugins/publish/extract_review.py
Labels: type: bug

#3494 TrayPublisher: Added more options for grouping of instances
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/list_view_widgets.py
Labels: type: enhancement

#3485 General: Fix Plist loading for application launch
  openpype/lib/applications.py
Labels: type: bug

#3384 Maya: Add additional playblast options to review Extractor.
  openpype/hosts/maya/api/lib.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
  openpype/vendor/python/common/capture.py
Labels: type: enhancement, host: Maya

#3469 Migrate basic families to the new Tray Publisher
  openpype/settings/defaults/project_settings/traypublisher.json
Labels: type: enhancement

#3506 Ftrack: Trigger custom ftrack topic of project structure creation
  openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py
Labels: type: enhancement

#3495 TimersManager: Use query functions
  openpype/modules/timers_manager/timers_manager.py
Labels: refactor

#3505 Settings UI: Add extract to file action on project view
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/widgets.py
Labels: type: enhancement

#2898 Refactor Integrate Asset
  openpype/lib/file_transaction.py
  openpype/plugins/publish/collect_subset_group.py
  openpype/plugins/publish/integrate.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: refactor

#3504 TrayPublisher: Make sure host name is filled
  openpype/hosts/traypublisher/api/__init__.py
  openpype/hosts/traypublisher/api/pipeline.py
  openpype/hosts/traypublisher/api/plugin.py
  openpype/pipeline/create/creator_plugins.py
  openpype/tools/traypublisher/window.py
Labels: type: bug, host: TrayPublisher

#3498 NewPublisher: Keep plugins with mismatch target in report
  openpype/pipeline/create/context.py
  openpype/tools/publisher/control.py
  openpype/tools/publisher/publish_report_viewer/report_items.py
Labels: type: enhancement

#3497 Nuke: load clip with options from settings
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_load.json
Labels: type: enhancement, host: Nuke

#3513 TrayPublisher: Simple creation enhancements and fixes
  openpype/hosts/traypublisher/api/plugin.py
  openpype/hosts/traypublisher/plugins/publish/collect_review_family.py
  openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py
  openpype/hosts/traypublisher/plugins/publish/validate_filepaths.py
  openpype/lib/attribute_definitions.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/collect_cleanup_keys.py
  openpype/settings/defaults/project_settings/traypublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
  openpype/tools/publisher/control.py
  openpype/tools/publisher/publish_report_viewer/widgets.py
  openpype/widgets/attribute_defs/files_widget.py
  openpype/widgets/attribute_defs/widgets.py
Labels: type: bug

#3519 General: Fix hash of centos oiio archive
  pyproject.toml
Labels: type: bug

#3516 Ftrack: Automatic daily review session creation can define trigger hour
  openpype/modules/ftrack/event_handlers_server/action_create_review_session.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3523 Maya: Added wrapper around cmds.setAttr
  openpype/vendor/python/common/capture.py
Labels: type: bug, host: Maya, client

#3526 General: Interactive console in cli
  openpype/cli.py
  openpype/pype_commands.py
  website/docs/admin_openpype_commands.md
Labels: type: enhancement

#3502 Add pack and unpack convenience scripts
  openpype/lib/project_backpack.py
  tools/pack_project.ps1
  tools/unpack_project.ps1
Labels: type: enhancement

#3486 TrayPublisher: implemented render_mov_batch
  openpype/hosts/traypublisher/plugins/create/create_movie_batch.py
  openpype/hosts/traypublisher/plugins/publish/collect_movie_batch.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/traypublisher.json
  openpype/settings/entities/enum_entity.py
  openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
  openpype/tools/publisher/publish_report_viewer/model.py
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/list_view_widgets.py
Labels: type: enhancement

#3514 Maya: Renderman display output fix
  openpype/hosts/maya/api/lib_renderproducts.py
Labels: type: bug, host: Maya

#3466 Deadline: Use query functions
  openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: module: Deadline, refactor

#3539 Workfiles tool: Show of tool and it's flags
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/tools/utils/host_tools.py
  openpype/tools/workfiles/window.py
Labels: type: bug

#3496 Kitsu: Use query function from client
  openpype/modules/kitsu/utils/sync_service.py
  openpype/modules/kitsu/utils/update_op_with_zou.py
  openpype/modules/kitsu/utils/update_zou_with_op.py
Labels: module: Kitsu, refactor

#3547 Module interfaces: Fix import error
  openpype/modules/base.py
Labels: type: bug

#3550 Settings: Clean default values of environments
  openpype/settings/defaults/system_settings/general.json
Labels: type: bug

#3540 Maya: add additional validators to Settings
  openpype/hosts/maya/plugins/publish/validate_review_subset_uniqueness.py
  openpype/hosts/maya/plugins/publish/validate_setdress_root.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement, host: Maya

#3554 Update website with more studios
  website/src/css/custom.css
  website/src/pages/index.js
  website/static/img/NoGhost_Logo_black.svg
  website/static/img/agora_studio.png
  website/static/img/ellipse_animation.svg
  website/static/img/igg-logo.png
  website/static/img/logo_normaal.png
  website/static/img/lucan_Logo_On_White-HR.png
  website/static/img/methodmadness.png
  website/static/img/noghost.png
  website/static/img/staticvfx.png
Labels: type: documentation

#3530 Refactor Integrate Asset
  openpype/lib/file_transaction.py
  openpype/plugins/publish/integrate.py
  openpype/plugins/publish/integrate_legacy.py
  openpype/plugins/publish/integrate_subset_group.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: refactor

#3522 General: Get current context document functions
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/harmony/plugins/publish/validate_scene_settings.py
  openpype/hosts/hiero/api/plugin.py
  openpype/hosts/houdini/api/lib.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/validate_maya_units.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/publish/validate_script.py
  openpype/hosts/resolve/api/plugin.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
  openpype/hosts/standalonepublisher/plugins/publish/validate_frame_ranges.py
  openpype/hosts/unreal/plugins/load/load_animation.py
  openpype/hosts/unreal/plugins/load/load_layout.py
  openpype/lib/avalon_context.py
  openpype/pipeline/context_tools.py
Labels: refactor

#3556 General: Remove hosts filter on integrator plugins
  openpype/plugins/publish/integrate.py
  openpype/plugins/publish/integrate_legacy.py
Labels: type: bug

#3527 General: Move load related functions into pipeline
  openpype/client/__init__.py
  openpype/client/entities.py
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/harmony/plugins/load/load_background.py
  openpype/hosts/harmony/plugins/load/load_imagesequence.py
  openpype/hosts/harmony/plugins/load/load_template.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/photoshop/api/pipeline.py
  openpype/lib/avalon_context.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/load/__init__.py
  openpype/pipeline/load/utils.py
  openpype/plugins/publish/validate_containers.py
  openpype/tests/test_lib_restructuralization.py
Labels: refactor

#3566 Maya: fix active pane loss
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: host: Maya

#3562 Maya: Fix animated attributes (ie. overscan) on loaded cameras breaking review publishing.
  openpype/vendor/python/common/capture.py
Labels: type: bug, host: Maya

#3569 Maya: fix Review image plane attribute
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: type: bug

#3559 NewPublisher: Python 2 compatible html escape
  openpype/tools/publisher/publish_report_viewer/model.py
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/list_view_widgets.py
  openpype/tools/utils/lib.py
Labels: type: bug

#3531 General: Mongo core connection moved to client
  openpype/client/__init__.py
  openpype/client/entities.py
  openpype/client/mongo.py
  openpype/hosts/maya/api/shader_definition_editor.py
  openpype/hosts/maya/plugins/publish/validate_model_name.py
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver_cli.py
  openpype/lib/local_settings.py
  openpype/lib/log.py
  openpype/lib/mongo.py
  openpype/lib/remote_publish.py
  openpype/modules/ftrack/ftrack_server/event_server_cli.py
  openpype/modules/ftrack/ftrack_server/lib.py
  openpype/modules/ftrack/scripts/sub_event_storer.py
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
  openpype/pipeline/mongodb.py
  openpype/settings/handlers.py
Labels: refactor

#3561 General: Global thumbnail extractor is ready for more cases
  openpype/plugins/publish/extract_thumbnail.py
Labels: type: enhancement

#3563 General: Use query functions in integrator
  openpype/plugins/publish/integrate.py
Labels: refactor

#3571 General: Lib cleanup
  openpype/api.py
  openpype/lib/__init__.py
  openpype/lib/config.py
  openpype/lib/dateutils.py
  openpype/lib/git_progress.py
  openpype/lib/log.py
  openpype/modules/ftrack/event_handlers_user/action_delivery.py
  openpype/plugins/load/delivery.py
  openpype/plugins/publish/collect_datetime_data.py
Labels: refactor

#3579 General: Update imports in start script
  openpype/settings/defaults/system_settings/modules.json
  start.py
Labels: type: bug

#3555 Nuke: publish existing frames with slate with correct range
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/plugins/publish/collect_slate_node.py
  openpype/hosts/nuke/plugins/publish/extract_render_local.py
  openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
  openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: bug, host: Nuke

#3576 Nuke: render family integration consistency
  openpype/hosts/nuke/plugins/publish/extract_render_local.py
  openpype/hosts/nuke/plugins/publish/precollect_instances.py
  openpype/hosts/nuke/plugins/publish/precollect_writes.py
Labels: type: bug, host: Nuke

#3570 Ftrack: Handle missing published path in integrator
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
Labels: type: bug, module: Ftrack

#3574 General: Separate extraction of template data into more functions
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/tvpaint/plugins/load/load_workfile.py
  openpype/hosts/unreal/hooks/pre_workfile_preparation.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/template_data.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/tools/workfiles/save_as_dialog.py
Labels: refactor

#3583 General: New Integrator small fixes
  openpype/plugins/publish/integrate.py
Labels: type: enhancement

#3588 Ftrack: Update ftrack api to 2.3.3
  openpype/modules/ftrack/ftrack_server/lib.py
  poetry.lock
  pyproject.toml
Labels: type: enhancement, module: Ftrack, Bump Minor

#3580 Editorial publishing workflow improvements
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/hiero/plugins/publish/precollect_instances.py
  openpype/hosts/resolve/plugins/publish/precollect_instances.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_editorial_instances.py
  openpype/plugins/publish/extract_hierarchy_avalon.py
  openpype/plugins/publish/integrate.py
  openpype/plugins/publish/validate_asset_docs.py
Labels: type: bug, host: Resolve, host: Standalone, host: Hiero, host: Flame

#3492 Traypublisher: simple editorial publishing
  openpype/hosts/traypublisher/api/editorial.py
  openpype/hosts/traypublisher/api/plugin.py
  openpype/hosts/traypublisher/plugins/create/create_editorial.py
  openpype/hosts/traypublisher/plugins/create/create_from_settings.py
  openpype/hosts/traypublisher/plugins/publish/collect_clip_instances.py
  openpype/hosts/traypublisher/plugins/publish/collect_editorial_instances.py
  openpype/hosts/traypublisher/plugins/publish/collect_editorial_reviewable.py
  openpype/hosts/traypublisher/plugins/publish/collect_shot_instances.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_component_overwrite.py
  openpype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/creator_plugins.py
  openpype/plugins/publish/collect_from_create_context.py
  openpype/plugins/publish/collect_otio_frame_ranges.py
  openpype/plugins/publish/collect_otio_subset_resources.py
  openpype/plugins/publish/extract_otio_file.py
  openpype/plugins/publish/extract_thumbnail.py
  openpype/plugins/publish/extract_trim_video_audio.py
  openpype/plugins/publish/validate_editorial_asset_name.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/traypublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
Labels: type: feature

#3589 General: Python module appdirs from git
  poetry.lock
  pyproject.toml
Labels: type: enhancement, Bump Minor

#3593 Kitsu: Shot&Sequence name with prefix over appends
  openpype/modules/kitsu/utils/update_op_with_zou.py
Labels: type: enhancement, module: Kitsu

#3587 Fix general settings environment variables resolution
  start.py
Labels: type: bug, Bump Minor
