Repository ynput/OpenPype, pull requests merged in 2022-11, with the labels that each got.

#4053 Loader: Fix comparison of repre name
  openpype/tools/loader/widgets.py
Labels: type: bug

#4048 Publisher: Better reset defer
  openpype/tools/publisher/window.py
Labels: type: enhancement

#4050 Deadline: Extract environment subprocess failure
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: bug, module: Deadline

#4042 Publisher: Add thumbnail sources
  openpype/hosts/traypublisher/api/plugin.py
  openpype/hosts/traypublisher/plugins/publish/collect_movie_batch.py
  openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py
  openpype/lib/transcoding.py
  openpype/pipeline/__init__.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/constants.py
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/workfile/lock_workfile.py
  openpype/plugins/publish/collect_from_create_context.py
  openpype/plugins/publish/extract_thumbnail_from_source.py
  openpype/plugins/publish/integrate_thumbnail.py
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/publisher/constants.py
  openpype/tools/publisher/control.py
  openpype/tools/publisher/control_qt.py
  openpype/tools/publisher/widgets/create_widget.py
  openpype/tools/publisher/widgets/images/clear_thumbnail.png
  openpype/tools/publisher/widgets/thumbnail_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/widgets.py
Labels: type: enhancement

#4066 Settings UI: Locked setting can't bypass lock
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/widgets.py
Labels: type: bug

#4063 Publisher: Prepared common function for instance data cache
  openpype/hosts/traypublisher/api/plugin.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/creator_plugins.py
Labels: type: enhancement

#4065 General: Direct interfaces import
  openpype/hosts/aftereffects/addon.py
  openpype/hosts/blender/addon.py
  openpype/hosts/flame/addon.py
  openpype/hosts/fusion/addon.py
  openpype/hosts/harmony/addon.py
  openpype/hosts/hiero/addon.py
  openpype/hosts/houdini/addon.py
  openpype/hosts/maya/addon.py
  openpype/hosts/nuke/addon.py
  openpype/hosts/photoshop/addon.py
  openpype/hosts/resolve/addon.py
  openpype/hosts/standalonepublisher/addon.py
  openpype/hosts/traypublisher/addon.py
  openpype/hosts/tvpaint/addon.py
  openpype/hosts/unreal/addon.py
  openpype/hosts/webpublisher/addon.py
  openpype/modules/__init__.py
  openpype/modules/avalon_apps/avalon_app.py
  openpype/modules/base.py
  openpype/modules/clockify/clockify_module.py
  openpype/modules/deadline/deadline_module.py
  openpype/modules/example_addons/example_addon/addon.py
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/kitsu/kitsu_module.py
  openpype/modules/launcher_action.py
  openpype/modules/log_viewer/log_view_module.py
  openpype/modules/muster/muster.py
  openpype/modules/project_manager_action.py
  openpype/modules/python_console_interpreter/module.py
  openpype/modules/royalrender/royal_render_module.py
  openpype/modules/settings_action.py
  openpype/modules/shotgrid/shotgrid_module.py
  openpype/modules/slack/slack_module.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/timers_manager/timers_manager.py
  openpype/modules/webserver/host_console_listener.py
  openpype/modules/webserver/webserver_module.py
  openpype/settings/lib.py
  openpype/tools/tray/pype_tray.py
Labels: refactor

#4056 AfterEffects: make new publisher default
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/api/extension.zxp
  openpype/hosts/aftereffects/api/extension/CSXS/manifest.xml
  openpype/hosts/aftereffects/api/extension/index.html
  openpype/hosts/aftereffects/api/launch_logic.py
  openpype/hosts/aftereffects/api/lib.py
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/aftereffects/api/workio.py
  openpype/hosts/aftereffects/plugins/create/create_legacy_local_render.py
  openpype/hosts/aftereffects/plugins/create/create_legacy_render.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/aftereffects/plugins/create/workfile_creator.py
  openpype/hosts/aftereffects/plugins/publish/help/validate_instance_asset.xml
  openpype/hosts/traypublisher/api/plugin.py
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/creator_plugins.py
  openpype/tools/loader/widgets.py
  openpype/tools/publisher/window.py
  openpype/version.py
  website/docs/artist_hosts_aftereffects.md
  website/docs/assets/aftereffects_publish_failed.png
  website/docs/assets/aftereffects_publish_instance.png
  website/docs/assets/aftereffects_render_instance.png
Labels: type: enhancement

#4067 Webpublisher: cleanup wp extract thumbnail
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/hosts/webpublisher/plugins/publish/extract_thumbnail.py
  openpype/plugins/publish/preintegrate_thumbnail_representation.py
Labels: type: bug

#4052 General/TVPaint: Attribute defs dialog
  openpype/hosts/tvpaint/plugins/load/load_image.py
  openpype/hosts/tvpaint/plugins/load/load_reference_image.py
  openpype/lib/attribute_definitions.py
  openpype/tools/attribute_defs/__init__.py
  openpype/tools/attribute_defs/dialog.py
  openpype/tools/attribute_defs/files_widget.py
  openpype/tools/attribute_defs/widgets.py
  openpype/tools/loader/lib.py
  openpype/tools/publisher/widgets/precreate_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/utils/widgets.py
  openpype/tools/workfile_template_build/window.py
Labels: type: enhancement, host: TV Paint

#4070 Publisher: Fix cache of asset docs
  openpype/tools/publisher/control.py
Labels: type: bug

#4064 General: Extract review single frame output
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  website/docs/project_settings/settings_project_global.md
Labels: type: enhancement

#4059 remove underscore from subset name
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: host: Maya

#4077 hiero: creator from settings with set maximum
  openpype/hosts/hiero/api/plugin.py
Labels: type: bug, host: Hiero

#4080 Flame/Flare: Loading to multiple batches
  openpype/hosts/flame/api/menu.py
  openpype/hosts/flame/plugins/load/load_clip_batch.py
  openpype/settings/defaults/project_settings/flame.json
Labels: type: bug, host: Flame

#4074 Nuke: resolve hashes in file name only for frame token
  openpype/hosts/nuke/plugins/load/load_clip.py
Labels: type: bug, host: Nuke

#4086 Publish Report Viewer: Fix small bugs
  openpype/tools/publisher/publish_report_viewer/widgets.py
  openpype/tools/publisher/publish_report_viewer/window.py
Labels: type: bug

#4090 Publisher: Ignore escape button
  openpype/tools/publisher/window.py
Labels: type: enhancement

#3667 TrayPublisher: Removed from experimental tools
  openpype/hosts/standalonepublisher/addon.py
  openpype/hosts/traypublisher/addon.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/tools/experimental_tools/tools_def.py
Labels: type: enhancement

#4085 Igniter: fix regex to match semver better
  igniter/bootstrap_repos.py
Labels: type: bug

#3979 Remove staging logic set by OpenPype version
  igniter/bootstrap_repos.py
  igniter/tools.py
  openpype/cli.py
  openpype/lib/applications.py
  openpype/lib/openpype_version.py
  openpype/resources/__init__.py
  openpype/settings/__init__.py
  openpype/settings/entities/__init__.py
  openpype/settings/entities/op_version_entity.py
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/settings/handlers.py
  openpype/settings/lib.py
  openpype/tools/tray/pype_tray.py
  start.py
  tests/unit/igniter/test_bootstrap_repos.py
  website/docs/admin_distribute.md
  website/docs/admin_openpype_commands.md
  website/docs/admin_use.md
Labels: type: enhancement, type: documentation, Bump Minor, refactor

#4089 General: Collect entities plugin minor changes
  openpype/hosts/tvpaint/plugins/publish/collect_instance_frames.py
  openpype/hosts/tvpaint/plugins/publish/validate_marks.py
  openpype/hosts/webpublisher/plugins/publish/validate_tvpaint_workfile_data.py
  openpype/plugins/publish/collect_anatomy_context_data.py
  openpype/plugins/publish/collect_context_entities.py
Labels: refactor

#4096 Files Widget: Ignore case sensitivity of extensions
  openpype/lib/attribute_definitions.py
  openpype/tools/attribute_defs/files_widget.py
Labels: type: bug

#3841 Maya + Yeti: Fix yeti cache load using wrong name in edge case
  openpype/hosts/maya/plugins/load/load_yeti_cache.py
Labels: host: Maya

#4047 Alembic Loader as Arnold Standin
  openpype/hosts/maya/plugins/load/load_abc_to_standin.py
Labels: host: Maya

#4101 General: Allow higher numbers in frames and clips
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_attributes.json
  openpype/tools/project_manager/project_manager/view.py
  openpype/tools/settings/settings/constants.py
Labels: type: enhancement

#4079 Flame: Loading clip with native colorspace resolved from mapping
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/plugins/load/load_clip.py
  openpype/hosts/flame/plugins/load/load_clip_batch.py
Labels: type: enhancement, host: Flame

#4095 Webpublisher: extension is lowercased in Setting and in uploaded files
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/plugins/publish/extract_review.py
Labels: type: bug, client

#4112 Ftrack: Event server status give more information about version locations
  openpype/modules/ftrack/scripts/sub_event_status.py
Labels: type: enhancement, module: Ftrack

#4093 Online family for Tray Publisher
  openpype/client/entities.py
  openpype/hosts/traypublisher/plugins/create/create_online.py
  openpype/hosts/traypublisher/plugins/publish/collect_online_file.py
  openpype/hosts/traypublisher/plugins/publish/validate_online_file.py
  openpype/pipeline/create/creator_plugins.py
  openpype/plugins/publish/integrate.py
  openpype/settings/defaults/project_anatomy/templates.json
  openpype/settings/defaults/project_settings/global.json
Labels: client, host: TrayPublisher

#4114 Nuke: loaded nodes set to first tab
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/plugins/load/load_camera_abc.py
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/hosts/nuke/plugins/load/load_effects.py
  openpype/hosts/nuke/plugins/load/load_effects_ip.py
  openpype/hosts/nuke/plugins/load/load_image.py
  openpype/hosts/nuke/plugins/load/load_model.py
  openpype/hosts/nuke/plugins/load/load_script_precomp.py
Labels: type: bug, host: Nuke

#4113 Nuke: load image first frame
  openpype/hosts/nuke/plugins/load/load_image.py
Labels: type: bug, host: Nuke

#4058 Publisher: Easy access to publish page from create page
  openpype/style/style.css
  openpype/tools/publisher/widgets/__init__.py
  openpype/tools/publisher/widgets/overview_widget.py
  openpype/tools/publisher/widgets/validations_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
Labels: type: enhancement

#4083 Maya: aov filtering
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: bug, host: Maya

#4119 General: Move default settings for template name
  openpype/settings/defaults/project_settings/global.json
Labels: type: bug

#4118 Slack: notification fail in new tray publisher
  openpype/modules/slack/plugins/publish/collect_slack_family.py
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
Labels: type: bug

#4116 Publisher: Hide unknown publish values
  openpype/lib/attribute_definitions.py
  openpype/tools/attribute_defs/widgets.py
  openpype/tools/publisher/widgets/widgets.py
Labels: type: enhancement

#4120 Publisher: Open on specific tab
  openpype/tools/publisher/widgets/card_view_widgets.py
  openpype/tools/publisher/widgets/list_view_widgets.py
  openpype/tools/publisher/widgets/overview_widget.py
  openpype/tools/publisher/widgets/tabs_widget.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/publisher/window.py
  openpype/tools/utils/host_tools.py
Labels: type: enhancement

#4121 Photoshop: bug with pop-up window on Instance Creator
  openpype/hosts/photoshop/plugins/create/create_legacy_image.py
Labels: type: enhancement, host: Photoshop

#4117 General: Fix variable check in collect anatomy instance data
  openpype/plugins/publish/collect_anatomy_instance_data.py
Labels: type: bug

#4115 Deadline: Build version resolving
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: enhancement, module: Deadline

#4136 General: Maketx executable issue
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: type: bug, host: Maya

#4135 Maya: Looks - add all connections
  openpype/hosts/maya/plugins/publish/collect_look.py
Labels: type: bug, host: Maya

#4137 General: Find executable enhancement
  openpype/lib/vendor_bin_utils.py
Labels: type: enhancement
