Repository ynput/OpenPype, pull requests merged in 2022-08, with the labels that each got.

#3582 Enable write color sets on animation publish automatically
  openpype/hosts/maya/plugins/create/create_animation.py
  openpype/hosts/maya/plugins/create/create_pointcache.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
Labels: host: Maya

#3591 Photoshop: implemented {layer} placeholder in subset template
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/photoshop/plugins/create/create_legacy_image.py
  openpype/hosts/photoshop/plugins/publish/validate_naming.py
Labels: type: enhancement, client

#3596 General: Use query functions in general code
  openpype/hooks/pre_global_host_data.py
  openpype/hosts/fusion/scripts/fusion_switch_shot.py
  openpype/hosts/testhost/api/pipeline.py
  openpype/hosts/testhost/plugins/create/auto_creator.py
  openpype/pipeline/create/context.py
  openpype/pipeline/thumbnail.py
  openpype/scripts/fusion_switch_shot.py
Labels: refactor

#3600 TrayPublisher: Fix wrong conflict merge
  openpype/hosts/traypublisher/api/plugin.py
  openpype/hosts/traypublisher/plugins/create/create_editorial.py
Labels: type: bug, host: TrayPublisher

#3611 Integrator: Don't force to have dot before frame
  openpype/plugins/publish/integrate.py
Labels: type: bug

#3612 Ftrack: Add more metadata to ftrack components
  openpype/lib/__init__.py
  openpype/lib/transcoding.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/plugins/publish/extract_review.py
Labels: type: enhancement

#3610 AfterEffects: refactored integrate doesnt work formulti frame publishes
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/pipeline/publish/abstract_collect_render.py
  tests/integration/hosts/aftereffects/test_publish_in_aftereffects_multiframe.py
  tests/lib/testing_classes.py
Labels: type: bug, host: After Effects

#3614 Core: translated validate_containers.py into New publisher style
  openpype/plugins/publish/help/validate_containers.xml
  openpype/plugins/publish/validate_containers.py
Labels: host: After Effects

#3607 Maya look data contents fails with custom attribute on group
  openpype/hosts/maya/plugins/publish/collect_look.py
  openpype/hosts/maya/plugins/publish/validate_look_contents.py
Labels: type: bug

#3615 Ftrack: Comment template can contain optional keys
  openpype/lib/path_templates.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
  openpype/settings/defaults/system_settings/modules.json
  openpype/settings/entities/schemas/system_schema/module_settings/schema_ftrack.json
  openpype/tools/pyblish_pype/model.py
  openpype/tools/pyblish_pype/window.py
Labels: type: enhancement, module: Ftrack

#3594 General: Add context to pyblish context
  openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
  openpype/plugins/publish/collect_anatomy_object.py
  openpype/plugins/publish/collect_avalon_entities.py
  openpype/plugins/publish/collect_current_context.py
  openpype/plugins/publish/collect_datetime_data.py
  openpype/plugins/publish/collect_from_create_context.py
  openpype/plugins/publish/collect_hierarchy.py
  openpype/plugins/publish/collect_machine_name.py
  openpype/plugins/publish/collect_rendered_files.py
  openpype/plugins/publish/collect_resources_path.py
  openpype/plugins/publish/integrate_hero_version.py
  openpype/plugins/publish/integrate_thumbnail.py
Labels: type: enhancement

#3605 Support for mutliple installed versions - 3.13
  igniter/bootstrap_repos.py
  igniter/tools.py
  openpype/cli.py
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.param
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.py
  setup.py
  start.py
  tools/build.sh
  tools/create_zip.py
Labels: Bump Minor, type: feature

#3619 Webpublisher: timeout for PS studio processing
  openpype/lib/remote_publish.py
  openpype/pype_commands.py
  openpype/settings/defaults/project_settings/webpublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json
Labels: host: Photoshop

#3617 Maya: Fix types of default settings
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/traypublisher.json
Labels: type: bug

#3622 Fix for multi-version build on Mac
  tools/build_dependencies.py
Labels: type: bug

#3620 General: Extract review aspect ratio scale is calculated by ffmpeg
  openpype/plugins/publish/extract_review.py
Labels: type: bug

#3621 Ftrack: Sync hierarchical attributes can handle new created entities
  openpype/modules/ftrack/event_handlers_server/event_push_frame_values_to_task.py
Labels: type: bug, module: Ftrack

#3623 General: Plugin settings handled by plugins
  openpype/lib/plugin_tools.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/create/legacy_create.py
  openpype/pipeline/load/plugins.py
  openpype/pipeline/publish/lib.py
  openpype/tools/loader/widgets.py
Labels: refactor

#3625 Maya: fix aov separator in Redshift
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: type: bug, host: Maya

#3630 Editorial: Mix audio use side file for ffmpeg filters
  openpype/plugins/publish/extract_otio_audio_tracks.py
Labels: type: enhancement

#3636 Kitsu|Fix: Movie project type fails & first loop children names
  openpype/modules/kitsu/utils/update_op_with_zou.py
Labels: module: Kitsu

#3631 Maya: FBX support for update in reference loader
  openpype/hosts/maya/api/plugin.py
Labels: type: bug, host: Maya

#3639 TimersManager: Plugins are in timers manager module
  openpype/lib/avalon_context.py
  openpype/modules/timers_manager/plugins/publish/start_timer.py
  openpype/modules/timers_manager/plugins/publish/stop_timer.py
  openpype/modules/timers_manager/timers_manager.py
  openpype/plugins/publish/collect_modules.py
  openpype/plugins/publish/start_timer.py
  openpype/plugins/publish/stop_timer.py
Labels: refactor

#3638 General: Hero version representations have full context
  openpype/plugins/publish/integrate_hero_version.py
Labels: type: bug

#3637 General: Move workfiles functions into pipeline
  openpype/client/operations.py
  openpype/hooks/pre_copy_template_workfile.py
  openpype/hosts/flame/plugins/publish/integrate_batch_group.py
  openpype/hosts/fusion/scripts/fusion_switch_shot.py
  openpype/hosts/fusion/utility_scripts/switch_ui.py
  openpype/hosts/maya/api/menu.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/tvpaint/plugins/load/load_workfile.py
  openpype/lib/applications.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/event_handlers_user/action_fill_workfile_attr.py
  openpype/pipeline/context_tools.py
  openpype/pipeline/workfile/__init__.py
  openpype/pipeline/workfile/build_workfile.py
  openpype/pipeline/workfile/path_resolving.py
  openpype/scripts/fusion_switch_shot.py
  openpype/tools/workfiles/files_widget.py
  openpype/tools/workfiles/save_as_dialog.py
  openpype/tools/workfiles/window.py
Labels: refactor

#3598 General: Workfiles builder using query functions
  openpype/client/entities.py
  openpype/hosts/maya/api/lib_template_builder.py
  openpype/hosts/maya/api/template_loader.py
  openpype/pipeline/workfile/abstract_template_loader.py
  openpype/pipeline/workfile/build_template.py
  openpype/settings/defaults/project_settings/maya.json
Labels: host: Maya, refactor

#3632 Nuke: color settings for render write node is working now
  openpype/hosts/nuke/api/lib.py
Labels: type: bug

#3628 fix the bug of failing to extract look when UDIMs format used in AiImage
  openpype/hosts/maya/plugins/publish/extract_look.py
Labels: host: Maya

#3644 General: Extract Review can scale with pixel aspect ratio
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
Labels: type: bug

#3666 Deadline: Global job pre load is not Pype 2 compatible
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: module: Deadline

#3643 Maya: Refactor moved usage of CreateRender settings
  openpype/hosts/maya/api/lib_rendersettings.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/validate_render_image_rule.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/project_settings/maya.json
Labels: type: bug, host: Maya

#3353 Maya: Implementation of JSON layout for Unreal workflow
  openpype/hosts/blender/plugins/publish/extract_layout.py
  openpype/hosts/maya/plugins/publish/extract_layout.py
  openpype/hosts/unreal/plugins/load/load_alembic_skeletalmesh.py
  openpype/hosts/unreal/plugins/load/load_alembic_staticmesh.py
  openpype/hosts/unreal/plugins/load/load_layout.py
  openpype/settings/defaults/project_settings/unreal.json
  openpype/settings/entities/schemas/projects_schema/schema_project_unreal.json
  website/docs/artist_hosts_unreal.md
  website/docs/assets/unreal-avalon_tools.jpg
  website/docs/assets/unreal-container.jpg
  website/docs/assets/unreal_add_level.png
  website/docs/assets/unreal_container.jpg
  website/docs/assets/unreal_create_render.png
  website/docs/assets/unreal_layout_loading_no_sequence.png
  website/docs/assets/unreal_layout_loading_result.png
  website/docs/assets/unreal_level_list.png
  website/docs/assets/unreal_level_list_no_sequences.png
  website/docs/assets/unreal_level_streaming_method.png
  website/docs/assets/unreal_level_streaming_method_no_sequences.png
  website/docs/assets/unreal_load_layout.png
  website/docs/assets/unreal_load_layout_batch.png
  website/docs/assets/unreal_openpype_tools.png
  website/docs/assets/unreal_openpype_tools_create.png
  website/docs/assets/unreal_openpype_tools_load.png
  website/docs/assets/unreal_openpype_tools_manage.png
  website/docs/assets/unreal_openpype_tools_publish.png
  website/docs/assets/unreal_openpype_tools_render.png
  website/docs/assets/unreal_publish_render.png
  website/docs/assets/unreal_setting_level_sequence.png
Labels: host: Maya, host: UE, type: feature

#3645 Maya: Remove unused get current renderer logic
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: host: Maya

#3656 General: Fix finding of last version
  igniter/bootstrap_repos.py
  igniter/install_thread.py
  openpype/tools/tray/pype_tray.py
  openpype/version.py
  start.py
Labels: type: bug, Bump Minor

#3675 Ftrack: Set task status on task creation in integrate hierarchy
  openpype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3673 General: Use client projects getter
  openpype/modules/kitsu/utils/update_zou_with_op.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/tools/launcher/models.py
  openpype/tools/libraryloader/app.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/sceneinventory/window.py
  openpype/tools/settings/settings/widgets.py
  openpype/tools/standalonepublish/widgets/widget_asset.py
  openpype/tools/utils/lib.py
  openpype/tools/utils/models.py
Labels: refactor

#3647 Maya: Hosts as modules
  openpype/host/host.py
  openpype/hosts/maya/__init__.py
  openpype/hosts/maya/api/workio.py
  openpype/hosts/maya/module.py
  openpype/lib/applications.py
  openpype/modules/base.py
  openpype/modules/interfaces.py
Labels: refactor

#3653 Resolve: Match folder structure to other hosts
  openpype/hosts/resolve/__init__.py
  openpype/hosts/resolve/api/__init__.py
  openpype/hosts/resolve/api/action.py
  openpype/hosts/resolve/api/lib.py
  openpype/hosts/resolve/api/menu.py
  openpype/hosts/resolve/api/pipeline.py
  openpype/hosts/resolve/api/preload_console.py
  openpype/hosts/resolve/api/utils.py
  openpype/hosts/resolve/api/workio.py
  openpype/hosts/resolve/hooks/pre_resolve_setup.py
  openpype/hosts/resolve/plugins/create/create_shot_clip.py
  openpype/hosts/resolve/plugins/load/load_clip.py
  openpype/hosts/resolve/plugins/publish/extract_workfile.py
  openpype/hosts/resolve/plugins/publish/precollect_instances.py
  openpype/hosts/resolve/plugins/publish/precollect_workfile.py
  openpype/hosts/resolve/utility_scripts/OpenPype_sync_util_scripts.py
  openpype/hosts/resolve/utility_scripts/__OpenPype__Menu__.py
  openpype/hosts/resolve/utility_scripts/tests/test_otio_as_edl.py
  openpype/hosts/resolve/utility_scripts/tests/testing_create_timeline_item_from_path.py
  openpype/hosts/resolve/utility_scripts/tests/testing_load_media_pool_item.py
  openpype/hosts/resolve/utils.py
Labels: host: Resolve, refactor

#3685 Ftrack: Addiotional component metadata
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/shotgrid.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3578 Maya: Build workfile by template
  openpype/client/entities.py
  openpype/hosts/maya/api/lib_template_builder.py
  openpype/hosts/maya/api/menu.py
  openpype/hosts/maya/api/template_loader.py
  openpype/lib/avalon_context.py
  openpype/pipeline/load/__init__.py
  openpype/pipeline/load/utils.py
  openpype/pipeline/workfile/abstract_template_loader.py
  openpype/pipeline/workfile/build_template.py
  openpype/pipeline/workfile/build_template_exceptions.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schema_project_maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_templated_workfile_build.json
  website/docs/admin_hosts_maya.md
  website/docs/assets/maya-build_workfile_from_template.png
  website/docs/assets/maya-create_placeholder.png
  website/docs/assets/maya-placeholder_new.png
  website/docs/assets/maya-workfile-outliner.png
  website/docs/assets/settings/template_build_workfile.png
Labels: host: Maya, type: feature

#3691 General: Switch from hero version to versioned works
  openpype/client/entities.py
  openpype/hosts/nuke/plugins/load/load_clip.py
  openpype/pipeline/load/utils.py
  openpype/tools/loader/widgets.py
Labels: type: bug

#3661 Maya: Disable rendering of all lights for render instances submitted through Deadline.
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_render_settings.json
Labels: type: enhancement, host: Maya

#3671 Ftrack: More logs related to auto sync value change
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Labels: type: enhancement, module: Ftrack

#3695 RoyalRender: handle host name that is not set
  openpype/plugins/publish/extract_review.py
  openpype/plugins/publish/integrate_subset_group.py
Labels: type: bug, module: RoyalRender

#3694 Deadline: better logging for DL webservice failures
  openpype/modules/deadline/abstract_submit_deadline.py
Labels: client

#3676 Photoshop: resize saved images in ExtractReview for ffmpeg
  openpype/hosts/photoshop/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Labels: client, host: Photoshop

#3660 Documentation: Settings development
  website/docs/assets/settings_dev.png
  website/docs/dev_settings.md
  website/sidebars.js
Labels: type: documentation

#3700 Settings: Lock settings UI session
  openpype/settings/handlers.py
  openpype/settings/lib.py
  openpype/tools/settings/settings/categories.py
  openpype/tools/settings/settings/dialogs.py
  openpype/tools/settings/settings/window.py
Labels: type: enhancement

#3704 Workfiles tool: Fix published workfile filtering
  openpype/tools/workfiles/model.py
Labels: type: bug

#3703 PS, AE: Provide default variant value for workfile subset
  openpype/hosts/aftereffects/plugins/create/workfile_creator.py
  openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
  openpype/hosts/photoshop/plugins/create/workfile_creator.py
  openpype/hosts/photoshop/plugins/publish/collect_workfile.py
Labels: type: bug, client

#3705 TrayPublisher: Define TrayPublisher as module
  openpype/cli.py
  openpype/hosts/traypublisher/__init__.py
  openpype/hosts/traypublisher/module.py
Labels: refactor, host: TrayPublisher

#3708 Settings: Fix project overrides save
  openpype/settings/handlers.py
Labels: type: bug

#3698 Documentation: Few updates
  website/docs/admin_openpype_commands.md
  website/docs/admin_releases.md
  website/docs/artist_concepts.md
  website/docs/changelog.md
  website/docs/module_ftrack.md
  website/docs/system_introduction.md
  website/docs/upgrade_notes.md
  website/sidebars.js
Labels: type: documentation

#3706 StandalonePublisher: Define StandalonePublisher as module
  openpype/cli.py
  openpype/hosts/standalonepublisher/__init__.py
  openpype/hosts/standalonepublisher/standalonepublish_module.py
  openpype/modules/standalonepublish_action.py
  openpype/pype_commands.py
  website/docs/admin_openpype_commands.md
Labels: host: Standalone, refactor

#3707 TVPaint: Defined as module
  openpype/hosts/tvpaint/__init__.py
  openpype/hosts/tvpaint/api/__init__.py
  openpype/hosts/tvpaint/api/pipeline.py
  openpype/hosts/tvpaint/tvpaint_module.py
Labels: host: TV Paint, refactor

#3684 Flame: retime is working on clip publishing
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/otio/flame_export.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/pipeline/editorial.py
  openpype/plugins/publish/collect_otio_subset_resources.py
Labels: type: bug, host: Flame

#3710 Loader: Subset groups using client operations
  openpype/client/notes.md
  openpype/client/operations.py
  openpype/tools/loader/model.py
  openpype/tools/loader/widgets.py
  openpype/tools/utils/lib.py
Labels: refactor

#3702 General: Move context specific functions to context tools
  openpype/lib/avalon_context.py
  openpype/pipeline/context_tools.py
  openpype/tools/workfiles/files_widget.py
Labels: refactor

#3709 Maya: Use project name instead of project code
  openpype/hosts/maya/plugins/load/_load_animation.py
  openpype/hosts/maya/plugins/load/load_ass.py
  openpype/hosts/maya/plugins/load/load_look.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/load/load_yeti_rig.py
Labels: type: bug, host: Maya

#3712 General: Added helper getters to modules manager
  openpype/modules/base.py
Labels: type: enhancement

#3713 General: Move constants from lib to client
  openpype/client/operations.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
  openpype/modules/ftrack/lib/avalon_sync.py
  openpype/tools/project_manager/project_manager/model.py
  openpype/tools/project_manager/project_manager/widgets.py
Labels: refactor

#3716 Settings: Fix studio default anatomy save
  openpype/settings/handlers.py
Labels: type: bug

#3717 Hiero: Define hiero as module
  openpype/hosts/hiero/__init__.py
  openpype/hosts/hiero/api/workio.py
  openpype/hosts/hiero/module.py
  openpype/hosts/hiero/vendor/google/protobuf/__init__.py
  openpype/hosts/hiero/vendor/google/protobuf/any_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/api_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/compiler/__init__.py
  openpype/hosts/hiero/vendor/google/protobuf/compiler/plugin_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/descriptor.py
  openpype/hosts/hiero/vendor/google/protobuf/descriptor_database.py
  openpype/hosts/hiero/vendor/google/protobuf/descriptor_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/descriptor_pool.py
  openpype/hosts/hiero/vendor/google/protobuf/duration_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/empty_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/field_mask_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/__init__.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/_parameterized.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/api_implementation.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/builder.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/containers.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/decoder.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/encoder.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/enum_type_wrapper.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/extension_dict.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/message_listener.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/message_set_extensions_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/missing_enum_values_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/more_extensions_dynamic_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/more_extensions_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/more_messages_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/no_package_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/python_message.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/type_checkers.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/well_known_types.py
  openpype/hosts/hiero/vendor/google/protobuf/internal/wire_format.py
  openpype/hosts/hiero/vendor/google/protobuf/json_format.py
  openpype/hosts/hiero/vendor/google/protobuf/message.py
  openpype/hosts/hiero/vendor/google/protobuf/message_factory.py
  openpype/hosts/hiero/vendor/google/protobuf/proto_builder.py
  openpype/hosts/hiero/vendor/google/protobuf/pyext/__init__.py
  openpype/hosts/hiero/vendor/google/protobuf/pyext/cpp_message.py
  openpype/hosts/hiero/vendor/google/protobuf/pyext/python_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/reflection.py
  openpype/hosts/hiero/vendor/google/protobuf/service.py
  openpype/hosts/hiero/vendor/google/protobuf/service_reflection.py
  openpype/hosts/hiero/vendor/google/protobuf/source_context_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/struct_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/symbol_database.py
  openpype/hosts/hiero/vendor/google/protobuf/text_encoding.py
  openpype/hosts/hiero/vendor/google/protobuf/text_format.py
  openpype/hosts/hiero/vendor/google/protobuf/timestamp_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/type_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/util/__init__.py
  openpype/hosts/hiero/vendor/google/protobuf/util/json_format_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/util/json_format_proto3_pb2.py
  openpype/hosts/hiero/vendor/google/protobuf/wrappers_pb2.py
Labels: host: Hiero

#3720 Settings: Remove settings lock on tray exit
  openpype/modules/settings_action.py
  openpype/tools/settings/settings/dialogs.py
Labels: type: enhancement

#3714 General: Move creators plugin getter
  openpype/hosts/blender/plugins/load/load_layout_blend.py
  openpype/hosts/blender/plugins/load/load_layout_json.py
  openpype/hosts/blender/plugins/load/load_rig.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/lib/avalon_context.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/creator_plugins.py
Labels: refactor

#3677 Ftrack: Store ftrack entities on hierarchy integration to instances
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/modules/ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3724 Nuke: Define nuke as module
  openpype/hosts/nuke/__init__.py
  openpype/hosts/nuke/api/workio.py
  openpype/hosts/nuke/module.py
  openpype/hosts/nuke/vendor/google/protobuf/__init__.py
  openpype/hosts/nuke/vendor/google/protobuf/any_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/api_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/compiler/__init__.py
  openpype/hosts/nuke/vendor/google/protobuf/compiler/plugin_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/descriptor.py
  openpype/hosts/nuke/vendor/google/protobuf/descriptor_database.py
  openpype/hosts/nuke/vendor/google/protobuf/descriptor_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/descriptor_pool.py
  openpype/hosts/nuke/vendor/google/protobuf/duration_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/empty_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/field_mask_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/__init__.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/_parameterized.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/api_implementation.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/builder.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/containers.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/decoder.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/encoder.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/enum_type_wrapper.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/extension_dict.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/message_listener.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/message_set_extensions_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/missing_enum_values_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/more_extensions_dynamic_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/more_extensions_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/more_messages_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/no_package_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/python_message.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/type_checkers.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/well_known_types.py
  openpype/hosts/nuke/vendor/google/protobuf/internal/wire_format.py
  openpype/hosts/nuke/vendor/google/protobuf/json_format.py
  openpype/hosts/nuke/vendor/google/protobuf/message.py
  openpype/hosts/nuke/vendor/google/protobuf/message_factory.py
  openpype/hosts/nuke/vendor/google/protobuf/proto_builder.py
  openpype/hosts/nuke/vendor/google/protobuf/pyext/__init__.py
  openpype/hosts/nuke/vendor/google/protobuf/pyext/cpp_message.py
  openpype/hosts/nuke/vendor/google/protobuf/pyext/python_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/reflection.py
  openpype/hosts/nuke/vendor/google/protobuf/service.py
  openpype/hosts/nuke/vendor/google/protobuf/service_reflection.py
  openpype/hosts/nuke/vendor/google/protobuf/source_context_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/struct_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/symbol_database.py
  openpype/hosts/nuke/vendor/google/protobuf/text_encoding.py
  openpype/hosts/nuke/vendor/google/protobuf/text_format.py
  openpype/hosts/nuke/vendor/google/protobuf/timestamp_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/type_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/util/__init__.py
  openpype/hosts/nuke/vendor/google/protobuf/util/json_format_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/util/json_format_proto3_pb2.py
  openpype/hosts/nuke/vendor/google/protobuf/wrappers_pb2.py
Labels: host: Nuke, refactor

#3728 AfterEffects: Define AfterEffects as module
  openpype/hosts/aftereffects/__init__.py
  openpype/hosts/aftereffects/api/workio.py
  openpype/hosts/aftereffects/module.py
Labels: host: After Effects, refactor

#3729 Blender: Define blender as module
  openpype/hosts/blender/__init__.py
  openpype/hosts/blender/api/workio.py
  openpype/hosts/blender/module.py
Labels: host: Blender, refactor

#3567 Nuke: Validation refactory to new publisher
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/publish/help/validate_asset_name.xml
  openpype/hosts/nuke/plugins/publish/help/validate_backdrop.xml
  openpype/hosts/nuke/plugins/publish/help/validate_gizmo.xml
  openpype/hosts/nuke/plugins/publish/help/validate_knobs.xml
  openpype/hosts/nuke/plugins/publish/help/validate_output_resolution.xml
  openpype/hosts/nuke/plugins/publish/help/validate_proxy_mode.xml
  openpype/hosts/nuke/plugins/publish/help/validate_rendered_frames.xml
  openpype/hosts/nuke/plugins/publish/help/validate_script_attributes.xml
  openpype/hosts/nuke/plugins/publish/help/validate_write_nodes.xml
  openpype/hosts/nuke/plugins/publish/precollect_workfile.py
  openpype/hosts/nuke/plugins/publish/validate_asset_name.py
  openpype/hosts/nuke/plugins/publish/validate_backdrop.py
  openpype/hosts/nuke/plugins/publish/validate_gizmo.py
  openpype/hosts/nuke/plugins/publish/validate_knobs.py
  openpype/hosts/nuke/plugins/publish/validate_output_resolution.py
  openpype/hosts/nuke/plugins/publish/validate_proxy_mode.py
  openpype/hosts/nuke/plugins/publish/validate_rendered_frames.py
  openpype/hosts/nuke/plugins/publish/validate_script.py
  openpype/hosts/nuke/plugins/publish/validate_script_attributes.py
  openpype/hosts/nuke/plugins/publish/validate_write_nodes.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: host: Nuke

#3682 Webpublisher: added check for empty context
  openpype/pype_commands.py
Labels: type: bug

#3725 General: Replace PypeLogger with Logger
  openpype/client/entities.py
  openpype/hosts/celaction/api/cli.py
  openpype/hosts/fusion/api/pipeline.py
  openpype/hosts/fusion/utility_scripts/__OpenPype_Menu__.py
  openpype/hosts/hiero/api/events.py
  openpype/hosts/hiero/api/lib.py
  openpype/hosts/hiero/api/pipeline.py
  openpype/hosts/hiero/api/plugin.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/nuke/plugins/load/actions.py
  openpype/hosts/nuke/startup/clear_rendered.py
  openpype/hosts/nuke/startup/write_to_read.py
  openpype/hosts/tvpaint/worker/worker_job.py
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver_cli.py
  openpype/lib/applications.py
  openpype/lib/execute.py
  openpype/lib/log.py
  openpype/lib/path_templates.py
  openpype/lib/remote_publish.py
  openpype/modules/base.py
  openpype/modules/deadline/deadline_module.py
  openpype/modules/ftrack/ftrack_server/ftrack_server.py
  openpype/modules/ftrack/ftrack_server/socket_thread.py
  openpype/modules/ftrack/lib/ftrack_base_handler.py
  openpype/modules/ftrack/scripts/sub_event_processor.py
  openpype/modules/ftrack/scripts/sub_legacy_server.py
  openpype/modules/ftrack/scripts/sub_user_server.py
  openpype/modules/ftrack/tray/ftrack_tray.py
  openpype/modules/log_viewer/tray/models.py
  openpype/modules/royalrender/api.py
  openpype/modules/sync_server/providers/abstract_provider.py
  openpype/modules/sync_server/sync_server.py
  openpype/modules/sync_server/sync_server_module.py
  openpype/modules/sync_server/tray/app.py
  openpype/modules/sync_server/tray/delegates.py
  openpype/modules/sync_server/tray/lib.py
  openpype/modules/sync_server/tray/models.py
  openpype/modules/sync_server/tray/widgets.py
  openpype/modules/sync_server/utils.py
  openpype/modules/timers_manager/idle_threads.py
  openpype/modules/timers_manager/rest_api.py
  openpype/modules/webserver/server.py
  openpype/pipeline/anatomy.py
  openpype/pype_commands.py
  openpype/settings/entities/base_entity.py
Labels: refactor

#3736 Photoshop: Defined photoshop as addon
  openpype/hosts/photoshop/__init__.py
  openpype/hosts/photoshop/addon.py
  openpype/hosts/photoshop/api/pipeline.py
  openpype/hosts/photoshop/api/workio.py
Labels: host: Photoshop, refactor

#3734 Harmony: Defined harmony as addon
  openpype/hosts/harmony/__init__.py
  openpype/hosts/harmony/addon.py
  openpype/hosts/harmony/api/pipeline.py
  openpype/hosts/harmony/api/workio.py
Labels: host: Harmony, refactor

#3740 Webpublisher: Webpublisher is used as addon
  openpype/hosts/aftereffects/api/lib.py
  openpype/hosts/photoshop/api/lib.py
  openpype/hosts/photoshop/plugins/publish/collect_batch_data.py
  openpype/hosts/webpublisher/__init__.py
  openpype/hosts/webpublisher/addon.py
  openpype/hosts/webpublisher/api/__init__.py
  openpype/hosts/webpublisher/lib.py
  openpype/hosts/webpublisher/plugins/publish/collect_batch_data.py
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_workfile_data.py
  openpype/hosts/webpublisher/publish_functions.py
  openpype/hosts/webpublisher/webserver_service/__init__.py
  openpype/hosts/webpublisher/webserver_service/webpublish_routes.py
  openpype/hosts/webpublisher/webserver_service/webserver.py
  openpype/lib/plugin_tools.py
  openpype/pipeline/publish/lib.py
  openpype/pype_commands.py
  openpype/scripts/remote_publish.py
Labels: refactor

#3721 Nuke: color-space settings from anatomy is working
  openpype/hosts/nuke/api/lib.py
Labels: type: bug, host: Nuke

#3663 Blender: ops refresh manager after process events
  openpype/hosts/blender/api/lib.py
  openpype/hosts/blender/api/ops.py
  openpype/hosts/blender/blender_addon/startup/init.py
Labels: type: enhancement, host: Blender

#3731 General: Module interfaces cleanup
  openpype/lib/applications.py
  openpype/modules/__init__.py
  openpype/modules/base.py
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/interfaces.py
  openpype/modules/shotgrid/shotgrid_module.py
  openpype/modules/slack/slack_module.py
  openpype/modules/timers_manager/timers_manager.py
Labels: refactor

#3678 Webpublisher:change create flatten image into tri state
  openpype/hosts/photoshop/plugins/publish/collect_color_coded_instances.py
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
Labels: client, type: feature

#3741 General: Logger tweaks
  openpype/modules/sync_server/providers/abstract_provider.py
  openpype/modules/sync_server/providers/dropbox.py
  openpype/modules/sync_server/providers/gdrive.py
  openpype/modules/sync_server/providers/sftp.py
  openpype/modules/timers_manager/rest_api.py
  openpype/modules/webserver/webserver_module.py
Labels: type: bug

#3730 AfterEffects: Move AE functions from general lib
  openpype/hosts/aftereffects/api/lib.py
  openpype/hosts/aftereffects/plugins/load/load_background.py
  openpype/hosts/aftereffects/plugins/load/load_file.py
  openpype/lib/__init__.py
  openpype/lib/plugin_tools.py
Labels: host: After Effects, refactor

#3723 Genetal: Move subset name functionality
  openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
  openpype/hosts/flame/plugins/publish/collect_timeline_otio.py
  openpype/hosts/harmony/plugins/publish/collect_workfile.py
  openpype/hosts/photoshop/plugins/publish/collect_review.py
  openpype/hosts/photoshop/plugins/publish/collect_workfile.py
  openpype/hosts/standalonepublisher/plugins/publish/collect_bulk_mov_instances.py
  openpype/hosts/traypublisher/plugins/create/create_movie_batch.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_scene_render.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile.py
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
  openpype/hosts/webpublisher/plugins/publish/collect_tvpaint_instances.py
  openpype/lib/plugin_tools.py
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/constants.py
  openpype/pipeline/create/subset_name.py
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/widgets.py
  openpype/tools/standalonepublish/widgets/widget_family.py
Labels: refactor

#3686 General: Benevolent context label collector
  openpype/plugins/publish/collect_context_label.py
  openpype/tools/publisher/publish_report_viewer/report_items.py
  openpype/tools/publisher/widgets/publish_widget.py
  openpype/tools/pyblish_pype/control.py
  openpype/tools/pyblish_pype/model.py
Labels: type: enhancement

#3744 General: Host addons cleanup
  openpype/hosts/aftereffects/__init__.py
  openpype/hosts/aftereffects/addon.py
  openpype/hosts/blender/__init__.py
  openpype/hosts/blender/addon.py
  openpype/hosts/harmony/addon.py
  openpype/hosts/hiero/__init__.py
  openpype/hosts/hiero/addon.py
  openpype/hosts/maya/__init__.py
  openpype/hosts/maya/addon.py
  openpype/hosts/nuke/__init__.py
  openpype/hosts/nuke/addon.py
  openpype/hosts/photoshop/addon.py
  openpype/hosts/standalonepublisher/__init__.py
  openpype/hosts/standalonepublisher/addon.py
  openpype/hosts/traypublisher/__init__.py
  openpype/hosts/traypublisher/addon.py
  openpype/hosts/tvpaint/__init__.py
  openpype/hosts/tvpaint/addon.py
  openpype/hosts/unreal/__init__.py
  openpype/hosts/unreal/addon.py
  openpype/hosts/unreal/lib.py
  openpype/hosts/webpublisher/addon.py
  openpype/lib/applications.py
  openpype/modules/base.py
  openpype/modules/interfaces.py
  openpype/tools/standalonepublish/app.py
  tests/lib/testing_classes.py
Labels: refactor

#3737 Nuke: missing job dependency if multiple bake streams
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: bug, host: Nuke

#3748 General: Smaller fixes of imports
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
  openpype/pipeline/create/creator_plugins.py
Labels: type: bug

#3751 General: Move delivery logic to pipeline
  openpype/lib/__init__.py
  openpype/lib/delivery.py
  openpype/lib/path_tools.py
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
  openpype/modules/ftrack/event_handlers_user/action_delete_old_versions.py
  openpype/modules/ftrack/event_handlers_user/action_delivery.py
  openpype/pipeline/delivery.py
  openpype/pipeline/load/__init__.py
  openpype/pipeline/load/utils.py
  openpype/pipeline/template_data.py
  openpype/plugins/load/delete_old_versions.py
  openpype/plugins/load/delivery.py
Labels: refactor

#3750 General: Thumbnail can use project roots
  openpype/client/operations.py
  openpype/pipeline/thumbnail.py
  openpype/plugins/publish/integrate_thumbnail.py
Labels: type: enhancement

#3753 Maya: Fix typo in getPanel argument `with_focus` -> `withFocus`
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: type: bug, host: Maya

#3662 Blender: validators code correction with settings and defaults
  openpype/hosts/blender/plugins/publish/validate_camera_zero_keyframe.py
  openpype/hosts/blender/plugins/publish/validate_mesh_has_uv.py
  openpype/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py
  openpype/hosts/blender/plugins/publish/validate_no_colons_in_name.py
  openpype/hosts/blender/plugins/publish/validate_object_mode.py
  openpype/hosts/blender/plugins/publish/validate_transform_zero.py
  openpype/settings/defaults/project_settings/blender.json
  openpype/settings/entities/schemas/projects_schema/schema_project_blender.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_blender_publish.json
Labels: host: Blender, type: feature

#3697 Houdini: Publishing workfiles
  openpype/hosts/houdini/plugins/publish/collect_current_file.py
  openpype/hosts/houdini/plugins/publish/validate_workfile_paths.py
  openpype/hosts/houdini/startup/python3.9libs/pythonrc.py
  openpype/settings/defaults/project_settings/houdini.json
  openpype/settings/entities/schemas/projects_schema/schema_project_houdini.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_houdini_publish.json
Labels: host: Houdini, type: feature

#3749 General: Move hostdirname functionality into host
  openpype/host/__init__.py
  openpype/host/dirmap.py
  openpype/host/host.py
  openpype/host/interfaces.py
  openpype/hosts/maya/__init__.py
  openpype/hosts/maya/api/pipeline.py
  openpype/hosts/nuke/api/lib.py
  openpype/lib/path_tools.py
Labels: refactor

#3735 Houdini: Define houdini as addon
  openpype/hosts/houdini/__init__.py
  openpype/hosts/houdini/addon.py
  openpype/hosts/houdini/api/pipeline.py
  openpype/hosts/houdini/api/workio.py
  openpype/hosts/houdini/hooks/set_paths.py
Labels: host: Houdini, refactor

#3732 Flame: Defined flame as addon
  openpype/hosts/flame/__init__.py
  openpype/hosts/flame/addon.py
Labels: host: Flame, refactor

#3761 Ftrack status fix typo prgoress -> progress
  openpype/settings/defaults/project_settings/ftrack.json
Labels: type: bug

#3765 SyncServer: Added cli commands for sync server
  openpype/modules/sync_server/sync_server_module.py
  openpype/pype_commands.py
Labels: type: enhancement, module: Sitesync

#3766 General: Create project function moved to client code
  openpype/client/__init__.py
  openpype/client/operations.py
  openpype/lib/avalon_context.py
  openpype/modules/ftrack/event_handlers_server/action_prepare_project.py
  openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
  openpype/modules/kitsu/utils/update_op_with_zou.py
  openpype/tools/project_manager/project_manager/widgets.py
Labels: refactor

#3727 Resolve: Define resolve as addon
  openpype/hosts/resolve/__init__.py
  openpype/hosts/resolve/addon.py
Labels: host: Resolve, refactor
