Repository ynput/OpenPype, pull requests merged in 2022-04, with the labels that each got.

#2969 Photoshop: Fix creation of subset names in PS review and workfile
  openpype/hosts/photoshop/plugins/publish/collect_review.py
  openpype/hosts/photoshop/plugins/publish/collect_workfile.py
Labels: type: bug, host: Photoshop

#2942 TVPaint: Extractor to convert PNG into EXR
  openpype/hosts/tvpaint/plugins/publish/extract_convert_to_exr.py
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
  openpype/plugins/publish/collect_cleanup_keys.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
Labels: type: enhancement, host: TV Paint

#2896 Documentation: New publisher develop docs
  openpype/hosts/testhost/plugins/create/auto_creator.py
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  website/docs/assets/publisher_card_view.png
  website/docs/assets/publisher_create_dialog.png
  website/docs/assets/publisher_list_view.png
  website/docs/dev_publishing.md
  website/sidebars.js
Labels: type: documentation

#2998 Fix - remove doubled dot in workfile created from template
  openpype/lib/avalon_context.py
Labels: type: bug

#2999 Documentation: Added mention of adding My Drive as a root
  website/docs/module_site_sync.md
Labels: type: documentation

#3001 Photoshop: create image without instance
  openpype/hosts/photoshop/plugins/publish/collect_instances.py
  openpype/hosts/photoshop/plugins/publish/extract_image.py
  openpype/hosts/photoshop/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
  website/docs/artist_hosts_photoshop.md
Labels: type: enhancement, client, host: Photoshop

#2992 nuke: bypass baking
  openpype/hosts/nuke/plugins/publish/extract_review_data.py
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: host: Nuke, type: feature

#3004 Hosts: Remove path existence checks in 'add_implementation_envs'
  openpype/hosts/blender/__init__.py
  openpype/hosts/hiero/__init__.py
  openpype/hosts/houdini/__init__.py
  openpype/hosts/maya/__init__.py
  openpype/hosts/nuke/__init__.py
Labels: type: bug, host: Maya, host: Houdini, host: Blender, host: Hiero

#2994 General: adding limitations for pyright
  pyproject.toml
Labels: python

#3002 Nuke: fixing unicode type detection in effect loaders
  openpype/hosts/nuke/plugins/load/load_effects.py
  openpype/hosts/nuke/plugins/load/load_effects_ip.py
  openpype/hosts/nuke/plugins/load/load_gizmo_ip.py
Labels: type: bug

#2996 Nuke: removing redundant Ftrack asset when farm publishing
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: bug, host: Nuke, module: Ftrack

#2937 Workfiles tool: Save as published workfiles
  openpype/style/style.css
  openpype/tools/workfiles/files_widget.py
  openpype/tools/workfiles/lib.py
  openpype/tools/workfiles/save_as_dialog.py
  openpype/tools/workfiles/window.py
Labels: type: enhancement

#3005 Nuke: add concurrency attr to deadline job
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/publish/precollect_writes.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: type: enhancement, host: Nuke

#2978 Maya to Unreal > Static and Skeletal Meshes
  openpype/hosts/maya/api/fbx.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/create/create_unreal_skeletalmesh.py
  openpype/hosts/maya/plugins/create/create_unreal_staticmesh.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/publish/clean_nodes.py
  openpype/hosts/maya/plugins/publish/collect_unreal_skeletalmesh.py
  openpype/hosts/maya/plugins/publish/collect_unreal_staticmesh.py
  openpype/hosts/maya/plugins/publish/extract_fbx.py
  openpype/hosts/maya/plugins/publish/extract_unreal_skeletalmesh.py
  openpype/hosts/maya/plugins/publish/extract_unreal_staticmesh.py
  openpype/hosts/maya/plugins/publish/help/validate_skeletalmesh_hierarchy.xml
  openpype/hosts/maya/plugins/publish/validate_skeletalmesh_hierarchy.py
  openpype/hosts/maya/plugins/publish/validate_unreal_mesh_triangulated.py
  openpype/hosts/maya/plugins/publish/validate_unreal_staticmesh_naming.py
  openpype/hosts/maya/plugins/publish/validate_unreal_up_axis.py
  openpype/plugins/publish/collect_resources_path.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_anatomy/templates.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_create.json
Labels: host: Maya, host: UE, type: feature

#3012 Ftrack: multiple reviewable componets
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
Labels: type: bug

#3010 Tray publisher: Fixes after code movement
  openpype/hosts/traypublisher/api/pipeline.py
  openpype/hosts/traypublisher/plugins/publish/validate_workfile.py
Labels: type: bug

#2988 Publishing textures for Unreal
  openpype/hosts/standalonepublisher/plugins/publish/collect_original_basename.py
  openpype/hosts/standalonepublisher/plugins/publish/help/validate_simple_texture_naming.xml
  openpype/hosts/standalonepublisher/plugins/publish/validate_simple_unreal_texture_naming.py
  openpype/plugins/publish/integrate_hero_version.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_anatomy/templates.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/standalonepublisher.json
Labels: client, host: UE, host: Standalone, type: feature

#3017 Maya: Remove missing import
  openpype/hosts/maya/api/pipeline.py
Labels: type: bug, host: Maya

#3016 Console Interpreter: Changed how console splitter size are reused on show
  openpype/modules/python_console_interpreter/window/widgets.py
Labels: type: enhancement

#3022 General: Add example addons to ignored
  openpype/modules/base.py
  openpype/modules/ftrack/event_handlers_user/action_create_folders.py
Labels: type: bug

#2995 Deadline: priority configurable in Maya jobs
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: type: enhancement, host: Maya, module: Deadline

#3024 Harmony: Added creating subset name for workfile from template
  openpype/hosts/harmony/plugins/publish/collect_workfile.py
Labels: type: bug, host: Harmony

#3023 AfterEffects: Added creating subset name for workfile from template
  openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
Labels: type: bug, host: After Effects

#3030 Maya: Allow to select invalid camera contents if no cameras found
  openpype/hosts/maya/plugins/publish/validate_camera_contents.py
Labels: host: Maya

#3025 Ftrack: Add more options for note text of integrate ftrack note
  openpype/hosts/standalonepublisher/plugins/publish/collect_app_name.py
  openpype/hosts/traypublisher/plugins/publish/collect_app_name.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
  openpype/plugins/publish/collect_host_name.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3032 Settings UI: Version column can be extended so version are visible
  openpype/tools/settings/settings/categories.py
Labels: type: bug

#3027 Ftrack: Add description integrator
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: module: Ftrack, type: feature

#3033 Deadline: Fixed default value of use sequence for review
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: bug, module: Deadline

#3008 Resolve environment variable in google drive credential path
  openpype/modules/sync_server/providers/gdrive.py
Labels: type: enhancement

#3035 Documentation: Python requirements to 3.7.9
  website/docs/dev_requirements.md
Labels: type: documentation

#3040 Unreal: Creator import fixes
  openpype/hosts/unreal/api/pipeline.py
  openpype/hosts/unreal/plugins/create/create_camera.py
  openpype/hosts/unreal/plugins/create/create_layout.py
  openpype/hosts/unreal/plugins/create/create_look.py
  openpype/hosts/unreal/plugins/create/create_staticmeshfbx.py
Labels: type: bug, host: UE

#2974 Website Docs: Remove unused pages
  website/docs/api.md
  website/docs/artist_hosts.md
  website/docs/artist_hosts_nuke.md
  website/docs/artist_hosts_nuke_tut.md
  website/docs/hosts-maya.md
  website/docs/manager_naming.md
Labels: type: documentation

#3018 SiteSync: fix transitive alternate sites, fix dropdown in Local Settings
  openpype/modules/sync_server/sync_server_module.py
  openpype/plugins/publish/integrate_new.py
Labels: type: bug, module: Sitesync

#3044 Ftrack: Integrate ftrack api fix
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
Labels: type: bug, module: Ftrack

#3043 Webpublisher - removed wrong hardcoded family
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
Labels: type: bug

#2987 Houdini: Avoid ImportError on `hdefereval` when Houdini runs without UI
  openpype/hosts/houdini/api/pipeline.py
Labels: host: Houdini

#3048 Webpublisher: fix processing of workfile
  openpype/hosts/webpublisher/plugins/publish/collect_published_files.py
Labels: type: bug

#3042 LibraryLoader: Use current project for asset query in families filter
  openpype/tools/utils/lib.py
Labels: type: bug

#2928 Flame: Flare integration preparation
  openpype/hosts/flame/api/__init__.py
  openpype/hosts/flame/api/batch_utils.py
  openpype/hosts/flame/api/lib.py
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/api/scripts/wiretap_com.py
  openpype/hosts/flame/otio/flame_export.py
  openpype/hosts/flame/plugins/load/load_clip.py
  openpype/hosts/flame/plugins/load/load_clip_batch.py
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/hosts/flame/plugins/publish/integrate_batch_group.py
  openpype/hosts/flame/plugins/publish/validate_source_clip.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
Labels: type: feature, host: Flame

#3045 General: Local overrides for environment variables
  openpype/lib/applications.py
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/settings/lib.py
  openpype/tools/settings/local_settings/constants.py
  openpype/tools/settings/local_settings/environments_widget.py
  openpype/tools/settings/local_settings/window.py
Labels: type: feature

#3050 General: Extract Review handle invalid characters for ffmpeg
  openpype/lib/transcoding.py
  openpype/plugins/publish/extract_review.py
Labels: type: bug

#3036 Ftrack: Custom attributes can be filled in slate values
  openpype/hosts/nuke/plugins/publish/extract_slate_frame.py
  openpype/modules/ftrack/lib/custom_attributes.py
  openpype/modules/ftrack/plugins/publish/collect_custom_attributes_data.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
  openpype/plugins/publish/extract_burnin.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/README.md
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
  openpype/tools/settings/settings/base.py
  openpype/tools/utils/lib.py
Labels: type: enhancement

#2915 Maya: invalid review flag on rendered AOVs
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/pipeline/farm/patterning.py
  openpype/settings/defaults/project_settings/deadline.json
Labels: type: bug

#3051 Deadline: reworked pools assignment
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/create/create_vrayscene.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/plugins/publish/submit_maya_muster.py
  openpype/hosts/maya/plugins/publish/validate_muster_connection.py
  openpype/lib/__init__.py
  openpype/lib/connections.py
  openpype/modules/deadline/deadline_module.py
  openpype/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py
  openpype/modules/deadline/plugins/publish/collect_default_deadline_server.py
  openpype/modules/deadline/plugins/publish/collect_pools.py
  openpype/modules/deadline/plugins/publish/help/validate_deadline_pools.xml
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/deadline/plugins/publish/validate_deadline_pools.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: module: Deadline

#3061 Nuke: Typos in imports from Nuke implementation
  openpype/hosts/nuke/plugins/inventory/select_containers.py
  openpype/hosts/nuke/plugins/load/load_backdrop.py
Labels: type: bug, host: Nuke

#3062 Documentation: more info about Tasks
  website/docs/admin_settings_project_anatomy.md
  website/docs/assets/settings/anatomy_tasks.png
Labels: type: documentation

#3064 GitHub: Updated push-protected action in github workflow
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: type: bug

#3060 Nuke: Add aov matching even for remainder and prerender
  openpype/lib/profiles_filtering.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py
Labels: type: bug

#3055 Update collect_render.py
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: type: enhancement, host: Maya

#3052 Nuke docs with videos
  website/docs/artist_hosts_hiero.md
  website/docs/artist_hosts_nuke_tut.md
Labels: type: documentation

#2983 SiteSync: Added compute_resource_sync_sites to sync_server_module
  openpype/modules/sync_server/sync_server_module.py
  tests/conftest.py
  tests/unit/openpype/modules/sync_server/test_module_api.py
Labels: type: enhancement, module: Sitesync

#3077 Standalone publisher: Fix plugins install
  openpype/tools/standalonepublish/publish.py
Labels: type: bug

#3076 General: Extract review sequence is not converted with same names
  openpype/hosts/webpublisher/plugins/publish/extract_thumbnail.py
  openpype/lib/__init__.py
  openpype/lib/transcoding.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_jpeg_exr.py
  openpype/plugins/publish/extract_review.py
Labels: type: bug

#3083 Project Manager: Avoid unnecessary updates of asset documents
  openpype/tools/project_manager/project_manager/model.py
Labels: type: bug

#3080 Standalone publisher: add support for bgeo and vdb
  openpype/hosts/standalonepublisher/plugins/publish/collect_context.py
  openpype/settings/defaults/project_settings/standalonepublisher.json
  openpype/tools/standalonepublish/widgets/widget_drop_frame.py
  openpype/tools/standalonepublish/widgets/widget_family_desc.py
Labels: type: enhancement, host: Standalone

#3092 Ftrack: Update Create Folders action
  openpype/modules/ftrack/event_handlers_user/action_create_folders.py
  openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py
Labels: type: bug, module: Ftrack

#3089 Ftrack: Update Create Folders action
  openpype/modules/ftrack/event_handlers_user/action_create_folders.py
  openpype/modules/ftrack/event_handlers_user/action_create_project_structure.py
Labels: type: bug, module: Ftrack

#3091 RoyalRender Control Submission - AVALON_APP_NAME default
  openpype/modules/royalrender/rr_root/plugins/control_job/perjob/m50__openpype_publish_render.py
  openpype/pype_commands.py
Labels: type: bug, module: RoyalRender

#3094 Docs: add all-contributors config and initial list
  .all-contributorsrc
  .gitignore
  README.md
Labels: type: documentation

#2838 AfterEffects: Implemented New Publisher
  openpype/hosts/aftereffects/api/__init__.py
  openpype/hosts/aftereffects/api/extension.zxp
  openpype/hosts/aftereffects/api/extension/CSXS/manifest.xml
  openpype/hosts/aftereffects/api/extension/jsx/hostscript.jsx
  openpype/hosts/aftereffects/api/pipeline.py
  openpype/hosts/aftereffects/api/workio.py
  openpype/hosts/aftereffects/api/ws_stub.py
  openpype/hosts/aftereffects/plugins/create/create_legacy_local_render.py
  openpype/hosts/aftereffects/plugins/create/create_legacy_render.py
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/aftereffects/plugins/create/workfile_creator.py
  openpype/hosts/aftereffects/plugins/load/load_background.py
  openpype/hosts/aftereffects/plugins/load/load_file.py
  openpype/hosts/aftereffects/plugins/publish/collect_audio.py
  openpype/hosts/aftereffects/plugins/publish/collect_render.py
  openpype/hosts/aftereffects/plugins/publish/collect_workfile.py
  openpype/hosts/aftereffects/plugins/publish/extract_local_render.py
  openpype/hosts/aftereffects/plugins/publish/extract_save_scene.py
  openpype/hosts/aftereffects/plugins/publish/help/validate_scene_settings.xml
  openpype/hosts/aftereffects/plugins/publish/pre_collect_render.py
  openpype/hosts/aftereffects/plugins/publish/validate_instance_asset.py
  openpype/hosts/aftereffects/plugins/publish/validate_scene_settings.py
  openpype/lib/abstract_collect_render.py
  openpype/pipeline/__init__.py
  openpype/plugins/publish/collect_from_create_context.py
  openpype/plugins/publish/integrate_new.py
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/defaults/project_settings/global.json
Labels: host: After Effects, type: feature

#2856 AfterEffects: Allow configuration of default variant via Settings
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/settings/defaults/project_settings/aftereffects.json
  openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
Labels: host: After Effects

#3070 General: Add global log verbose arguments
  openpype/cli.py
  openpype/lib/log.py
  openpype/modules/ftrack/ftrack_server/lib.py
  openpype/pype_commands.py
  openpype/settings/defaults/system_settings/general.json
  openpype/settings/entities/schemas/system_schema/schema_general.json
  openpype/settings/handlers.py
  start.py
  website/docs/admin_openpype_commands.md
  website/docs/admin_use.md
Labels: type: enhancement, Bump Minor

#3087 General: Remove repos related logic
  igniter/bootstrap_repos.py
  setup.py
  start.py
  tests/unit/igniter/test_bootstrap_repos.py
Labels: type: enhancement

#3088 Maya: Collect Render fix any render cameras check
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: type: bug, host: Maya

#3104 Local Settings UI: Overlay messages on save and reset
  openpype/style/data.json
  openpype/style/style.css
  openpype/tools/settings/local_settings/window.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/overlay_messages.py
Labels: type: enhancement

#3006 Fix support for Renderman in Maya
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/system_settings/tools.json
Labels: type: bug, host: Maya

#3099 General: TemplateResult can be copied
  openpype/lib/path_templates.py
Labels: type: bug

#3107 renderman support for 3.9.x
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/validate_rendersettings.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/system_settings/tools.json
Labels: host: Maya

#3095 General: Collect loaded versions skips not existing representations
  openpype/plugins/publish/collect_scene_loaded_versions.py
Labels: type: bug

#3108 Ftrack: AssetVersion status on publish
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#3111 General: Python 3 compatibility in queries
  openpype/lib/avalon_context.py
Labels: type: bug

#3117 Nuke: render instance with subset name filtered overrides
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/api/plugin.py
  openpype/hosts/nuke/plugins/publish/extract_review_data_mov.py
  openpype/settings/defaults/project_anatomy/imageio.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_publish.json
Labels: type: enhancement

#3106 Hiero: Initial frame publish support
  openpype/hosts/hiero/api/tags.py
  openpype/hosts/hiero/plugins/publish/collect_frame_tag_instances.py
  openpype/hosts/hiero/plugins/publish/extract_frames.py
  openpype/hosts/hiero/plugins/publish/precollect_workfile.py
  openpype/hosts/hiero/plugins/publish_old_workflow/collect_clip_resolution.py
  openpype/hosts/hiero/plugins/publish_old_workflow/collect_host_version.py
  openpype/hosts/hiero/plugins/publish_old_workflow/collect_tag_retime.py
  openpype/hosts/hiero/plugins/publish_old_workflow/precollect_instances.py
  openpype/hosts/hiero/plugins/publish_old_workflow/precollect_workfile.py
  openpype/plugins/publish/collect_hierarchy.py
Labels: host: Hiero, type: feature

#3063 Flame: extract presets distribution
  openpype/hosts/flame/api/plugin.py
  openpype/hosts/flame/plugins/publish/collect_timeline_instances.py
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/hosts/flame/plugins/publish/validate_source_clip.py
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_anatomy_imageio.json
Labels: type: enhancement, host: Flame

#3105 Tray publisher: Simple families from settings
  openpype/hosts/traypublisher/api/plugin.py
  openpype/hosts/traypublisher/plugins/create/create_from_settings.py
  openpype/hosts/traypublisher/plugins/create/create_workfile.py
  openpype/hosts/traypublisher/plugins/publish/collect_simple_instances.py
  openpype/hosts/traypublisher/plugins/publish/collect_workfile.py
  openpype/hosts/traypublisher/plugins/publish/validate_filepaths.py
  openpype/hosts/traypublisher/plugins/publish/validate_workfile.py
  openpype/lib/__init__.py
  openpype/lib/attribute_definitions.py
  openpype/pipeline/plugin_discover.py
  openpype/plugins/publish/extract_burnin.py
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/traypublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
  openpype/style/style.css
  openpype/tools/publisher/widgets/create_dialog.py
  openpype/tools/publisher/widgets/validations_widget.py
  openpype/tools/publisher/window.py
  openpype/tools/resources/images/menu.png
  openpype/tools/traypublisher/window.py
  openpype/widgets/attribute_defs/__init__.py
  openpype/widgets/attribute_defs/files_widget.py
  openpype/widgets/attribute_defs/widgets.py
Labels: type: enhancement

#3109 TVPaint: Match renderlayer key with other hosts
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
  openpype/hosts/tvpaint/plugins/create/create_render_pass.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_scene_render.py
  openpype/settings/defaults/project_settings/global.json
Labels: type: enhancement, host: TV Paint
