Repository ynput/OpenPype, pull requests merged in 2023-01, with the labels that each got.

#4264 Slack: notification fails because of missing published path
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
Labels: type: bug

#4268 Scene Manager: Fix variable name
  openpype/widgets/message_window.py
Labels: type: bug, host: Maya

#4275 Deadline: fix default value for passing mongo url
  openpype/settings/defaults/project_settings/deadline.json
Labels: type: bug, module: Deadline

#4209 Hiero: thumbnail from multilayer exr
  openpype/hosts/hiero/plugins/publish/extract_thumbnail.py
Labels: type: bug, host: Hiero

#4278 SiteSync: sftp connection failing when shouldnt be tested
  openpype/modules/sync_server/providers/dropbox.py
  openpype/modules/sync_server/providers/gdrive.py
  openpype/modules/sync_server/sync_server.py
Labels: type: bug

#4266 Global | Nuke: Creator placeholders in workfile template builder
  openpype/hosts/maya/api/workfile_template_builder.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/api/pipeline.py
  openpype/hosts/nuke/api/workfile_template_builder.py
  openpype/hosts/nuke/plugins/load/load_backdrop.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/workfile/workfile_template_builder.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_templated_workfile_build.json
Labels: host: Nuke, host: Maya, type: feature

#4288 Ftrack: Fix receive of host ip on MacOs
  openpype/modules/ftrack/event_handlers_user/action_where_run_ask.py
  openpype/modules/ftrack/ftrack_server/event_server_cli.py
  openpype/modules/ftrack/ftrack_server/lib.py
  openpype/modules/ftrack/scripts/sub_event_status.py
Labels: type: bug, module: Ftrack

#4279 Maya: Fix validate frame range repair + fix create render with deadline disabled
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/collect_instances.py
  openpype/hosts/maya/plugins/publish/validate_frame_range.py
Labels: host: Maya

#4134 General: Legacy io not used in global plugins
  openpype/plugins/publish/cleanup_farm.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/collect_scene_loaded_versions.py
  openpype/plugins/publish/integrate.py
  openpype/plugins/publish/validate_editorial_asset_name.py
Labels: refactor

#4198 Unreal: Publishing and Loading for UAssets
  openpype/hosts/unreal/plugins/create/create_uasset.py
  openpype/hosts/unreal/plugins/load/load_uasset.py
  openpype/hosts/unreal/plugins/publish/collect_instances.py
  openpype/hosts/unreal/plugins/publish/extract_uasset.py
  openpype/hosts/unreal/plugins/publish/validate_no_dependencies.py
  openpype/plugins/publish/integrate.py
Labels: host: UE, type: feature

#4248 Traypublisher: simple editorial multiple edl
  openpype/hosts/traypublisher/api/editorial.py
  openpype/hosts/traypublisher/plugins/create/create_editorial.py
  openpype/hosts/traypublisher/plugins/publish/collect_shot_instances.py
Labels: type: enhancement

#4254 Resolve: Use qtpy in Resolve
  openpype/hosts/resolve/api/menu.py
  openpype/hosts/resolve/api/plugin.py
Labels: host: Resolve, refactor

#4300 Unreal: fix missing `maintained_selection` call
  openpype/hosts/unreal/api/__init__.py
  openpype/hosts/unreal/api/pipeline.py
Labels: type: bug

#4298 General: Added install method with docstring to HostBase
  openpype/host/host.py
Labels: type: enhancement

#4301 Documentation: Fix harmony docs
  website/docs/artist_hosts_harmony.md
  website/docs/assets/harmony_publish.png
  website/docs/assets/harmony_publish_actions.png
  website/docs/assets/harmony_publish_expand.png
  website/docs/assets/harmony_publish_inspect.png
  website/docs/assets/harmony_publish_repair.gif
Labels: type: bug, type: documentation

#4289 Git: add pre-commit hooks
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tools/create_env.ps1
  tools/create_env.sh
Labels: type: enhancement

#4306 General: Unbind poetry version
  tools/create_env.ps1
  tools/create_env.sh
Labels: type: enhancement

#4303 General: missing comment on standalone and tray publisher
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py
  openpype/plugins/publish/collect_comment.py
Labels: type: bug, client

#4296 AfterEffects: Fix for audio from mp4 layer
  openpype/plugins/publish/extract_review.py
Labels: type: bug, client

#4263 Tray Publisher: Improve Online family functionality
  openpype/hosts/traypublisher/plugins/create/create_online.py
  openpype/hosts/traypublisher/plugins/publish/collect_online_file.py
  openpype/hosts/traypublisher/plugins/publish/validate_online_file.py
  openpype/plugins/publish/extract_thumbnail.py
Labels: type: enhancement, host: TrayPublisher

#4315 Maya: Bug - Multiverse extractor executed on plain animation family
  openpype/hosts/maya/plugins/publish/extract_multiverse_usd.py
Labels: type: bug, host: Maya

#4312 Fix run_documentation.ps1
  tools/run_documentation.ps1
Labels: type: bug

#3437 Maya: Collect instances preserve handles even if frameStart + frameEnd matches context
  openpype/hosts/maya/plugins/publish/collect_instances.py
Labels: host: Maya

#4320 General: Python 2 compatibility of instance collector
  openpype/plugins/publish/collect_from_create_context.py
Labels: type: bug

#4322 Ftrack: fix typos causing bugs in sync
  openpype/modules/ftrack/event_handlers_server/event_sync_to_avalon.py
Labels: type: bug, module: Ftrack

#4318 Slack: user groups speedup
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
Labels: type: bug

#4310 General: Loader and Creator plugins can be disabled
  openpype/pipeline/create/legacy_create.py
  openpype/pipeline/load/plugins.py
  openpype/pipeline/workfile/build_workfile.py
  openpype/pipeline/workfile/workfile_template_builder.py
  openpype/tools/creator/model.py
  openpype/tools/loader/widgets.py
Labels: type: enhancement

#4325 Exctract OTIO review has improved quality
  openpype/plugins/publish/extract_otio_review.py
Labels: type: bug, host: Hiero

#4295 General: Enhanced enum def items
  openpype/hosts/traypublisher/plugins/create/create_editorial.py
  openpype/lib/attribute_definitions.py
  openpype/pipeline/workfile/workfile_template_builder.py
  openpype/tools/attribute_defs/widgets.py
Labels: type: enhancement

#4284 General: Push to studio library
  openpype/pipeline/create/__init__.py
  openpype/pipeline/create/subset_name.py
  openpype/pipeline/load/__init__.py
  openpype/pipeline/load/utils.py
  openpype/plugins/load/push_to_library.py
  openpype/style/style.css
  openpype/tools/loader/widgets.py
  openpype/tools/push_to_project/__init__.py
  openpype/tools/push_to_project/app.py
  openpype/tools/push_to_project/control_context.py
  openpype/tools/push_to_project/control_integrate.py
  openpype/tools/push_to_project/window.py
  openpype/tools/utils/__init__.py
  openpype/tools/utils/lib.py
Labels: type: feature

#4332 General: Use class constants of QMessageBox
  openpype/hosts/maya/plugins/publish/validate_assembly_transforms.py
  openpype/tools/project_manager/project_manager/window.py
  openpype/tools/workfiles/files_widget.py
Labels: type: bug

#4341 Nuke Input process node sourcing improvements
  openpype/hosts/nuke/api/lib.py
Labels: type: bug, host: Nuke

#4347 Fix photoshop workfile save-as
  openpype/hosts/photoshop/api/workio.py
Labels: type: bug

#4342 documentation: Split tools into separate entries
  website/docs/artist_hosts_aftereffects.md
  website/docs/artist_hosts_blender.md
  website/docs/artist_hosts_harmony.md
  website/docs/artist_hosts_hiero.md
  website/docs/artist_hosts_houdini.md
  website/docs/artist_hosts_maya.md
  website/docs/artist_hosts_nuke_tut.md
  website/docs/artist_hosts_photoshop.md
  website/docs/artist_hosts_resolve.md
  website/docs/artist_hosts_tvpaint.md
  website/docs/artist_hosts_unreal.md
  website/docs/artist_tools.md
  website/docs/artist_tools_context_manager.md
  website/docs/artist_tools_creator.md
  website/docs/artist_tools_inventory.md
  website/docs/artist_tools_library_loader.md
  website/docs/artist_tools_loader.md
  website/docs/artist_tools_look_assigner.md
  website/docs/artist_tools_publisher.md
  website/docs/artist_tools_subset_manager.md
  website/docs/artist_tools_sync_queu.md
  website/docs/artist_tools_workfiles.md
  website/docs/project_settings/settings_project_global.md
  website/sidebars.js
  website/src/pages/features.js
Labels: type: documentation

#4339 New publisher: Some validation plugin tweaks
  openpype/hosts/houdini/plugins/publish/collect_inputs.py
  openpype/hosts/houdini/plugins/publish/validate_alembic_input_node.py
  openpype/plugins/publish/cleanup_explicit.py
  openpype/plugins/publish/collect_anatomy_instance_data.py
  openpype/plugins/publish/integrate_hero_version.py
  openpype/plugins/publish/validate_containers.py
  openpype/plugins/publish/validate_version.py
  openpype/settings/lib.py
  openpype/tools/publisher/widgets/assets_widget.py
Labels: type: bug

#4346 Sort families by alphabetical order in the Create plugin
  openpype/tools/creator/model.py
Labels: community contribution

#4354 change 3.7 to 3.9 in folder name
  tools/docker_build.sh
Labels: type: bug

#4195 Colorspace Management and Distribution
  common/openpype_common/distribution/file_handler.py
  openpype/hosts/nuke/api/lib.py
  openpype/hosts/nuke/plugins/publish/extract_render_local.py
  openpype/pipeline/colorspace.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/publish_plugins.py
  openpype/plugins/publish/extract_colorspace_data.py
  openpype/plugins/publish/integrate.py
  openpype/scripts/ocio_wrapper.py
  openpype/settings/defaults/project_anatomy/attributes.json
  openpype/settings/defaults/project_settings/aftereffects.json
  openpype/settings/defaults/project_settings/blender.json
  openpype/settings/defaults/project_settings/celaction.json
  openpype/settings/defaults/project_settings/flame.json
  openpype/settings/defaults/project_settings/fusion.json
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/defaults/project_settings/harmony.json
  openpype/settings/defaults/project_settings/hiero.json
  openpype/settings/defaults/project_settings/houdini.json
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/defaults/project_settings/nuke.json
  openpype/settings/defaults/project_settings/photoshop.json
  openpype/settings/defaults/project_settings/resolve.json
  openpype/settings/defaults/project_settings/traypublisher.json
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/defaults/project_settings/unreal.json
  openpype/settings/defaults/project_settings/webpublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_aftereffects.json
  openpype/settings/entities/schemas/projects_schema/schema_project_blender.json
  openpype/settings/entities/schemas/projects_schema/schema_project_celaction.json
  openpype/settings/entities/schemas/projects_schema/schema_project_flame.json
  openpype/settings/entities/schemas/projects_schema/schema_project_fusion.json
  openpype/settings/entities/schemas/projects_schema/schema_project_global.json
  openpype/settings/entities/schemas/projects_schema/schema_project_harmony.json
  openpype/settings/entities/schemas/projects_schema/schema_project_hiero.json
  openpype/settings/entities/schemas/projects_schema/schema_project_houdini.json
  openpype/settings/entities/schemas/projects_schema/schema_project_maya.json
  openpype/settings/entities/schemas/projects_schema/schema_project_photoshop.json
  openpype/settings/entities/schemas/projects_schema/schema_project_resolve.json
  openpype/settings/entities/schemas/projects_schema/schema_project_traypublisher.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_unreal.json
  openpype/settings/entities/schemas/projects_schema/schema_project_webpublisher.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_imageio_config.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_imageio_file_rules.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_imageio.json
  poetry.lock
  pyproject.toml
  tests/lib/testing_classes.py
  tests/unit/openpype/pipeline/lib.py
  tests/unit/openpype/pipeline/publish/test_publish_plugins.py
  tests/unit/openpype/pipeline/test_colorspace.py
  website/docs/dev_colorspace.md
  website/docs/project_settings/settings_project_global.md
  website/sidebars.js
Labels: type: feature

#4350 PushToProject: Fix hierarchy of project change
  openpype/pipeline/anatomy.py
  openpype/tools/push_to_project/control_integrate.py
  openpype/tools/push_to_project/window.py
Labels: type: bug

#4356 Unreal: Don't use mongo queries in 'ExistingLayoutLoader'
  openpype/hosts/unreal/plugins/load/load_layout_existing.py
Labels: type: enhancement

#4333 Global: fixing in-place source publishing for editorial
  openpype/plugins/publish/collect_otio_subset_resources.py
  openpype/plugins/publish/integrate.py
Labels: type: bug, host: Resolve, host: Hiero

#4349 General: Simplified addon distribution
  common/openpype_common/distribution/addon_distribution.py
  common/openpype_common/distribution/addon_info.py
  common/openpype_common/distribution/file_handler.py
  openpype/modules/base.py
  start.py
Labels: type: enhancement

#4336 Global: Validate unique subsets
  openpype/hosts/fusion/plugins/publish/validate_unique_subsets.py
  openpype/hosts/maya/plugins/publish/help/validate_review_subset_uniqueness.xml
  openpype/hosts/maya/plugins/publish/validate_review_subset_uniqueness.py
  openpype/hosts/photoshop/plugins/publish/validate_unique_subsets.py
  openpype/plugins/publish/help/validate_unique_subsets.xml
  openpype/plugins/publish/validate_unique_subsets.py
Labels: community contribution

#4149 Blender: added project settings for validator no colons in name
  openpype/settings/defaults/project_settings/blender.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_blender_publish.json
Labels: type: enhancement, host: Blender, community contribution

#4293 Remove redundant export_alembic method.
  openpype/hosts/maya/api/__init__.py
  openpype/hosts/maya/api/lib.py
Labels: host: Maya, refactor

#4271 Adding path validator for non-maya nodes
  openpype/hosts/maya/plugins/publish/validate_plugin_path_attributes.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: type: enhancement, host: Maya

#4381 Remove OIIO build for macos
  pyproject.toml
  tools/fetch_thirdparty_libs.py
Labels: type: bug

#4380 CelAction: Collector CLI is now working as it should
  openpype/hosts/celaction/plugins/publish/collect_celaction_cli_kwargs.py
Labels: type: bug

#4362 Nuke: update rendered frames in latest version
  openpype/hosts/aftereffects/plugins/publish/pre_collect_render.py
  openpype/hosts/nuke/plugins/publish/extract_render_local.py
  openpype/lib/file_transaction.py
  openpype/plugins/publish/collect_frames_fix.py
  openpype/plugins/publish/integrate.py
Labels: host: Nuke, client

#4374 Houdini: New publisher code tweak
  openpype/hosts/houdini/api/plugin.py
Labels: type: enhancement, host: Houdini

#4382 Houdini: Do not visualize the hidden OpenPypeContext node
  openpype/hosts/houdini/api/pipeline.py
Labels: type: enhancement, host: Houdini

#4390 Global: extract colorspace is not failing
  openpype/pipeline/colorspace.py
  openpype/pipeline/publish/publish_plugins.py
Labels: type: bug

#4003 Renderman support for sample and display filters
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/api/lib_rendersettings.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_render_settings.json
Labels: host: Maya

#4387 3dsmax: enhance alembic loader update function
  openpype/hosts/max/api/menu.py
  openpype/hosts/max/api/pipeline.py
  openpype/hosts/max/plugins/load/load_pointcache.py
Labels: type: enhancement, host: 3dsmax

#4376 Data exchange cameras for 3d Studio Max
  openpype/hosts/max/plugins/create/create_camera.py
  openpype/hosts/max/plugins/load/load_camera_fbx.py
  openpype/hosts/max/plugins/load/load_max_scene.py
  openpype/hosts/max/plugins/load/load_pointcache.py
  openpype/hosts/max/plugins/publish/extract_camera_abc.py
  openpype/hosts/max/plugins/publish/extract_camera_fbx.py
  openpype/hosts/max/plugins/publish/extract_max_scene_raw.py
  openpype/hosts/max/plugins/publish/extract_pointcache.py
  openpype/hosts/max/plugins/publish/validate_camera_contents.py
Labels: type: feature, host: 3dsmax

#4363 AYON: Distribution with progress
  ayon_start.py
  common/ayon_common/distribution/addon_distribution.py
  common/ayon_common/distribution/addon_info.py
  common/ayon_common/distribution/tests/test_addon_distributtion.py
Labels: type: enhancement
