Repository ynput/OpenPype, pull requests merged in 2023-02, with the labels that each got.

#4401 Maya: Fix Validate Attributes plugin
  openpype/hosts/maya/plugins/publish/validate_attributes.py
Labels: type: bug, host: Maya

#4402 Maya + Blender: Pyblish plugins removed unused `version` and `category` attributes
  openpype/hosts/blender/plugins/publish/validate_camera_zero_keyframe.py
  openpype/hosts/blender/plugins/publish/validate_mesh_has_uv.py
  openpype/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py
  openpype/hosts/blender/plugins/publish/validate_no_colons_in_name.py
  openpype/hosts/blender/plugins/publish/validate_transform_zero.py
  openpype/hosts/maya/plugins/publish/collect_maya_workspace.py
  openpype/hosts/maya/plugins/publish/validate_color_sets.py
  openpype/hosts/maya/plugins/publish/validate_mesh_arnold_attributes.py
  openpype/hosts/maya/plugins/publish/validate_mesh_has_uv.py
  openpype/hosts/maya/plugins/publish/validate_mesh_lamina_faces.py
  openpype/hosts/maya/plugins/publish/validate_mesh_non_zero_edge.py
  openpype/hosts/maya/plugins/publish/validate_mesh_normals_unlocked.py
  openpype/hosts/maya/plugins/publish/validate_mesh_overlapping_uvs.py
  openpype/hosts/maya/plugins/publish/validate_mesh_single_uv_set.py
  openpype/hosts/maya/plugins/publish/validate_mesh_vertices_have_edges.py
  openpype/hosts/maya/plugins/publish/validate_no_default_camera.py
  openpype/hosts/maya/plugins/publish/validate_no_namespace.py
  openpype/hosts/maya/plugins/publish/validate_no_null_transforms.py
  openpype/hosts/maya/plugins/publish/validate_rig_joints_hidden.py
  openpype/hosts/maya/plugins/publish/validate_scene_set_workspace.py
  openpype/hosts/maya/plugins/publish/validate_shape_default_names.py
  openpype/hosts/maya/plugins/publish/validate_transform_naming_suffix.py
  openpype/hosts/maya/plugins/publish/validate_transform_zero.py
  openpype/hosts/maya/plugins/publish/validate_unreal_mesh_triangulated.py
Labels: type: enhancement

#4324 General: Functions for current context
  openpype/host/host.py
  openpype/pipeline/__init__.py
  openpype/pipeline/context_tools.py
Labels: type: enhancement

#4400 Global: colorspace host settings are now optional
  openpype/pipeline/colorspace.py
Labels: type: bug

#4391 Houdini: hotfix condition
  openpype/hosts/houdini/api/plugin.py
Labels: type: bug, host: Houdini

#4414 Maya: Ignore workfile lock in Untitled scene
  openpype/hosts/maya/api/pipeline.py
Labels: type: bug, host: Maya

#4412 3dsmax: startup fixes
  openpype/hosts/max/addon.py
  openpype/hosts/max/startup/startup.py
Labels: type: bug, host: 3dsmax

#4417 General: Use right environment variable for current task name
  openpype/host/host.py
Labels: type: bug

#4411 Ftrack: Don't force ftrackapp endpoint
  openpype/modules/ftrack/ftrack_module.py
  openpype/modules/ftrack/tray/login_dialog.py
Labels: type: bug, module: Ftrack

#4365 docs-user-Getting Started adjustments
  website/docs/artist_getting_started.md
Labels: type: documentation

#4256 Maya: Xgen
  openpype/hooks/pre_add_last_workfile_arg.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/plugin.py
  openpype/hosts/maya/plugins/create/create_xgen.py
  openpype/hosts/maya/plugins/inventory/connect_geometry.py
  openpype/hosts/maya/plugins/inventory/connect_xgen.py
  openpype/hosts/maya/plugins/load/actions.py
  openpype/hosts/maya/plugins/load/load_reference.py
  openpype/hosts/maya/plugins/load/load_xgen.py
  openpype/hosts/maya/plugins/publish/collect_xgen.py
  openpype/hosts/maya/plugins/publish/extract_maya_scene_raw.py
  openpype/hosts/maya/plugins/publish/extract_workfile_xgen.py
  openpype/hosts/maya/plugins/publish/extract_xgen.py
  openpype/hosts/maya/plugins/publish/extract_xgen_cache.py
  openpype/hosts/maya/plugins/publish/reset_xgen_attributes.py
  openpype/hosts/maya/plugins/publish/validate_xgen.py
  openpype/hosts/maya/startup/userSetup.py
  openpype/plugins/publish/collect_resources_path.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schema_project_maya.json
  website/docs/artist_hosts_maya.md
  website/docs/artist_hosts_maya_xgen.md
Labels: host: Maya, type: feature

#4422 Maya: V-Ray Proxy - Update to latest fails - OP-2008
  openpype/hosts/maya/plugins/load/load_vrayproxy.py
  openpype/hosts/maya/plugins/publish/validate_vray.py
Labels: type: bug

#4428 Houdini: Houdini shelf tools fixes
  openpype/hosts/houdini/api/shelves.py
Labels: type: bug, host: Houdini

#4435 Slack: added missed scopes for Slack bot
  openpype/modules/slack/manifest.yml
Labels: type: bug

#4375 Create: Enhance instance & context changes
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/houdini/api/plugin.py
  openpype/hosts/max/api/plugin.py
  openpype/hosts/traypublisher/api/pipeline.py
  openpype/pipeline/create/context.py
Labels: type: bug, host: Houdini, host: After Effects, host: 3dsmax

#4438 Ftrack: Fix methods called on thread objects
  openpype/modules/ftrack/ftrack_server/event_server_cli.py
  openpype/modules/ftrack/tray/login_dialog.py
Labels: type: bug, module: Ftrack

#4420 Deadline: Allow disabling strict error check in Maya submissions
  openpype/hosts/maya/plugins/create/create_render.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
Labels: type: enhancement, host: Maya, module: Deadline

#4436 SiteSync: fix dirmap
  openpype/host/dirmap.py
Labels: type: bug

#4432 Photoshop: make usage of layer name in subset name more controllable
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/photoshop/plugins/create/create_image.py
Labels: type: bug

#4360 General: Loader plugin define its own compatibility
  openpype/pipeline/load/plugins.py
  openpype/pipeline/load/utils.py
Labels: type: enhancement

#4413 General: Remove 'openpype.api'
  openpype/api.py
  openpype/hosts/nuke/plugins/publish/collect_context_data.py
Labels: type: refactor

#4418 Fix: DL on MacOS
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
  openpype/modules/deadline/repository/custom/plugins/OpenPype/OpenPype.py
Labels: type: bug

#4280 Fix features for gizmo menu
  openpype/hosts/nuke/api/gizmo_menu.py
  openpype/settings/entities/schemas/projects_schema/schemas/schema_nuke_scriptsgizmo.json
Labels: host: Nuke, community contribution

#4448 Maya: Create Arnold options on repair.
  openpype/hosts/maya/plugins/publish/validate_ass_relative_paths.py
Labels: host: Maya

#4446 General: Ignore decode error of stdout/stderr in run_subprocess
  openpype/hosts/harmony/plugins/publish/extract_render.py
  openpype/lib/execute.py
  openpype/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py
  openpype/scripts/otio_burnin.py
Labels: type: bug

#4359 Fix - addSite loader handles hero version
  openpype/client/entity_links.py
  openpype/plugins/load/add_site.py
  openpype/plugins/load/remove_site.py
  openpype/tools/loader/widgets.py
Labels: type: bug, module: Sitesync

#4452 General: Fix original basename frame issues
  openpype/plugins/publish/integrate.py
Labels: type: enhancement

#4405 Blender: fix import workfile all families
  openpype/hosts/blender/plugins/load/import_workfile.py
Labels: host: Blender

#4343 Feature: Keep synced hero representations up-to-date.
  openpype/plugins/publish/integrate_hero_version.py
Labels: community contribution

#4398 Global: supporting `OPENPYPE_TMPDIR` in staging dir maker
  openpype/hosts/flame/plugins/publish/extract_subset_resources.py
  openpype/pipeline/publish/lib.py
  openpype/pipeline/tempdir.py
  website/docs/admin_environment.md
  website/docs/admin_settings_system.md
  website/sidebars.js
Labels: type: enhancement, host: Hiero

#4457 Strict Error Checking Default
  openpype/hosts/maya/plugins/publish/collect_render.py
Labels: type: bug, host: Maya

#4449 Maya: Arnold Scene Source overhaul - OP-4865
  openpype/hosts/maya/plugins/create/create_arnold_scene_source.py
  openpype/hosts/maya/plugins/create/create_pointcache.py
  openpype/hosts/maya/plugins/load/load_abc_to_standin.py
  openpype/hosts/maya/plugins/load/load_arnold_standin.py
  openpype/hosts/maya/plugins/load/load_ass.py
  openpype/hosts/maya/plugins/publish/collect_arnold_scene_source.py
  openpype/hosts/maya/plugins/publish/collect_pointcache.py
  openpype/hosts/maya/plugins/publish/extract_arnold_scene_source.py
  openpype/hosts/maya/plugins/publish/extract_ass.py
  openpype/hosts/maya/plugins/publish/extract_assproxy.py
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
  openpype/hosts/maya/plugins/publish/validate_arnold_scene_source.py
  website/docs/artist_hosts_maya.md
  website/docs/artist_hosts_maya_arnold.md
  website/docs/assets/maya-arnold_scene_source.png
  website/docs/assets/maya-arnold_standin.png
  website/docs/assets/maya-pointcache_setup.png
  website/sidebars.js
Labels: host: Maya

#4459 General: Don't use mongo call in load utils
  openpype/pipeline/load/utils.py
Labels: type: bug

#4393 General: Simplified CreateContext api
  openpype/pipeline/create/context.py
  openpype/plugins/publish/collect_from_create_context.py
  openpype/tools/publisher/control.py
Labels: type: enhancement

#4472 Publisher: Less confusing tab changes
  openpype/tools/publisher/window.py
Labels: type: enhancement

#4467 Photoshop: fix missing legacy io for legacy instances
  openpype/hosts/aftereffects/plugins/create/create_render.py
  openpype/hosts/aftereffects/plugins/create/workfile_creator.py
  openpype/hosts/photoshop/plugins/create/create_image.py
  openpype/hosts/photoshop/plugins/create/workfile_creator.py
Labels: type: bug, host: Photoshop, host: After Effects

#4474 Publisher: Fix compatibility of QAction in Publisher
  openpype/tools/publisher/widgets/widgets.py
Labels: type: bug

#4468 Global: fixing python2 incompatibility
  openpype/pipeline/tempdir.py
Labels: type: bug

#4454 General: Removed deprecated functions from lib
  openpype/lib/__init__.py
  openpype/lib/anatomy.py
  openpype/lib/avalon_context.py
  openpype/lib/plugin_tools.py
  openpype/tests/test_lib_restructuralization.py
  openpype/tests/test_pyblish_filter.py
Labels: type: refactor

#4463 Publisher: Fix reopen bug
  openpype/tools/publisher/window.py
Labels: type: bug

#4441 Shotgrid: Fix how representation paths are received during publishing
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/modules/shotgrid/plugins/publish/integrate_shotgrid_publish.py
  openpype/modules/shotgrid/plugins/publish/integrate_shotgrid_version.py
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/lib.py
Labels: community contribution

#4473 Publisher: Report also crashed creators and convertors
  openpype/pipeline/create/context.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/plugin_discover.py
  openpype/pipeline/publish/__init__.py
  openpype/pipeline/publish/lib.py
  openpype/tools/publisher/control.py
  openpype/tools/publisher/widgets/create_widget.py
Labels: type: enhancement

#4470 Update Asset field of creator Instances in Maya Template Builder
  openpype/hosts/maya/api/workfile_template_builder.py
Labels: host: Maya, community contribution

#4478 Start script: Fix possible issues with destination drive path
  start.py
Labels: Bump Minor

#4482 Workfiles tool: Add PySide 6 support
  openpype/tools/workfiles/files_widget.py
Labels: type: bug

#4424 Maya: fps rounding - OP-2549
  openpype/hosts/maya/api/commands.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/plugins/publish/validate_maya_units.py
Labels: type: bug, host: Maya

#4483 Ftrack: Upload reviewables with original name
  openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py
  openpype/settings/defaults/project_settings/ftrack.json
  openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json
Labels: type: enhancement, module: Ftrack

#4421 Maya: extract Thumbnail "No active model panel found" - OP-3849
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/hosts/maya/plugins/publish/extract_thumbnail.py
Labels: type: bug, host: Maya

#4458 Default Ftrack Family on RenderLayer
  openpype/settings/defaults/project_settings/ftrack.json
Labels: type: enhancement, host: Maya, module: Ftrack

#4491 Maya: Fix changed location of reset_frame_range
  openpype/hosts/maya/api/commands.py
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/lib_rendersettings.py
  openpype/hosts/maya/api/menu.py
Labels: type: bug, host: Maya

#4489 Deadline: Only submit version when running from build.
  openpype/modules/deadline/plugins/publish/submit_aftereffects_deadline.py
  openpype/modules/deadline/plugins/publish/submit_harmony_deadline.py
  openpype/modules/deadline/plugins/publish/submit_houdini_remote_publish.py
  openpype/modules/deadline/plugins/publish/submit_houdini_render_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_deadline.py
  openpype/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py
  openpype/modules/deadline/plugins/publish/submit_nuke_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
Labels: type: enhancement, module: Deadline

#4485 Harmony: missing set of frame range when opening scene
  openpype/hosts/harmony/api/pipeline.py
Labels: type: bug, client, host: Harmony

#4487 Maya: Maya Playblast Options - OP-3783
  openpype/hosts/maya/plugins/publish/extract_playblast.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_capture.json
Labels: type: enhancement, host: Maya

#4495 TVPaint: Update artist documentation for Publisher
  website/docs/artist_hosts_tvpaint.md
  website/docs/assets/tvp_create_layer.png
  website/docs/assets/tvp_create_pass.png
  website/docs/assets/tvp_openpype_menu.png
  website/docs/assets/tvp_publisher.png
Labels: type: documentation, host: TV Paint

#4439 Deadline for 3dsMax
  openpype/hosts/max/api/lib.py
  openpype/hosts/max/api/lib_renderproducts.py
  openpype/hosts/max/api/lib_rendersettings.py
  openpype/hosts/max/plugins/create/create_render.py
  openpype/hosts/max/plugins/publish/collect_render.py
  openpype/modules/deadline/plugins/publish/submit_max_deadline.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/settings/defaults/project_settings/deadline.json
  openpype/settings/defaults/project_settings/max.json
  openpype/settings/entities/schemas/projects_schema/schema_main.json
  openpype/settings/entities/schemas/projects_schema/schema_project_deadline.json
  openpype/settings/entities/schemas/projects_schema/schema_project_max.json
Labels: module: Deadline, type: feature, host: 3dsmax

#4471 TVPaint: Use Publisher tool
  openpype/hosts/tvpaint/api/communication_server.py
  openpype/hosts/tvpaint/api/lib.py
  openpype/hosts/tvpaint/api/pipeline.py
  openpype/hosts/tvpaint/api/plugin.py
  openpype/hosts/tvpaint/plugins/create/convert_legacy.py
  openpype/hosts/tvpaint/plugins/create/create_render.py
  openpype/hosts/tvpaint/plugins/create/create_render_layer.py
  openpype/hosts/tvpaint/plugins/create/create_render_pass.py
  openpype/hosts/tvpaint/plugins/create/create_review.py
  openpype/hosts/tvpaint/plugins/create/create_workfile.py
  openpype/hosts/tvpaint/plugins/publish/collect_instance_frames.py
  openpype/hosts/tvpaint/plugins/publish/collect_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_render_instances.py
  openpype/hosts/tvpaint/plugins/publish/collect_scene_render.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile.py
  openpype/hosts/tvpaint/plugins/publish/collect_workfile_data.py
  openpype/hosts/tvpaint/plugins/publish/extract_sequence.py
  openpype/hosts/tvpaint/plugins/publish/help/validate_render_layer_group.xml
  openpype/hosts/tvpaint/plugins/publish/validate_duplicated_layer_names.py
  openpype/hosts/tvpaint/plugins/publish/validate_layers_visibility.py
  openpype/hosts/tvpaint/plugins/publish/validate_render_layer_group.py
  openpype/hosts/tvpaint/plugins/publish/validate_render_pass_group.py
  openpype/hosts/tvpaint/plugins/publish/validate_scene_settings.py
  openpype/hosts/tvpaint/plugins/publish/validate_workfile_metadata.py
  openpype/hosts/tvpaint/plugins/publish/validate_workfile_project_name.py
  openpype/pipeline/create/creator_plugins.py
  openpype/pipeline/create/subset_name.py
  openpype/settings/defaults/project_settings/tvpaint.json
  openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
  openpype/tools/publisher/widgets/card_view_widgets.py
  website/docs/artist_hosts_tvpaint.md
  website/docs/assets/tvp_create_layer.png
  website/docs/assets/tvp_create_pass.png
  website/docs/assets/tvp_openpype_menu.png
  website/docs/assets/tvp_publisher.png
Labels: type: enhancement, host: TV Paint

#4500 General: Ignore disabled creators in create context
  openpype/pipeline/create/context.py
Labels: type: bug

#4513 Slack: check existence only if not None
  openpype/modules/slack/plugins/publish/integrate_slack_api.py
Labels: type: bug

#4399 Batch script for running Openpype on Deadline.
  tools/openpype_console.bat
Labels: type: enhancement

#4512 Nuke: Fix workfile template placeholder creation
  openpype/hosts/nuke/api/__init__.py
  openpype/hosts/nuke/api/pipeline.py
Labels: type: bug, host: Nuke, community contribution

#4515 Start script: Change returncode on validate or list versions
  start.py
Labels: type: bug, Bump Minor

#4261 maya gltf texture convertor and validator
  openpype/hosts/maya/plugins/publish/extract_gltf.py
  openpype/hosts/maya/plugins/publish/validate_glsl_material.py
  openpype/hosts/maya/plugins/publish/validate_glsl_plugin.py
  openpype/settings/defaults/project_settings/maya.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Labels: host: Maya, type: feature

#4291 Global: color v3 global oiio transcoder plugin
  openpype/lib/transcoding.py
  openpype/modules/slack/manifest.yml
  openpype/plugins/publish/extract_color_transcode.py
  openpype/plugins/publish/extract_review.py
  openpype/settings/defaults/project_settings/global.json
  openpype/settings/entities/schemas/projects_schema/schemas/schema_global_publish.json
  website/docs/project_settings/assets/global_oiio_transcode.png
  website/docs/project_settings/assets/global_oiio_transcode2.png
  website/docs/project_settings/settings_project_global.md
Labels: type: enhancement, type: documentation

#4340 Maya: OP-2630 acescg maya
  openpype/hosts/maya/api/lib.py
  openpype/hosts/maya/api/lib_renderproducts.py
  openpype/hosts/maya/api/lib_rendersettings.py
  openpype/hosts/maya/plugins/publish/collect_render.py
  openpype/hosts/maya/startup/userSetup.py
  openpype/modules/deadline/plugins/publish/submit_publish_job.py
  openpype/pipeline/colorspace.py
  openpype/scripts/ocio_wrapper.py
Labels: type: enhancement, host: Maya

#4529 Maya: Fix broken lib.
  openpype/hosts/maya/api/lib.py
Labels: type: bug, host: Maya

#4503 global: source template fixed frame duplication
  openpype/settings/defaults/project_anatomy/templates.json
Labels: type: bug

#4461 Maya: Simplify pointcache proxy integration
  openpype/hosts/maya/plugins/publish/extract_pointcache.py
Labels: type: enhancement, host: Maya

#4534 Publisher: Fix Attr UI definitions for publish plugins
  openpype/tools/publisher/control.py
  openpype/tools/publisher/widgets/widgets.py
Labels: type: bug

#4518 Deadline: Hint to use Python 3
  openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Labels: type: bug, module: Deadline

#4528 Publisher: Prevent access to create tab after publish start
  openpype/tools/publisher/widgets/overview_widget.py
  openpype/tools/publisher/window.py
Labels: type: bug

#4536 Unreal: fix loaders because of missing AssetContainer
  openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Private/AssetContainer.cpp
  openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Private/AssetContainerFactory.cpp
  openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Public/AssetContainer.h
  openpype/hosts/unreal/integration/UE_5.0/OpenPype/Source/OpenPype/Public/AssetContainerFactory.h
Labels: type: bug, host: UE

#4546 General: hardcode Poetry to 1.3.2 temporarily
  tools/create_env.ps1
  tools/create_env.sh
Labels: type: bug, dependencies

#4544 Color Transcoding: store target_colorspace as new colorspace
  openpype/plugins/publish/extract_color_transcode.py
Labels: type: bug
